libs/openFrameworks/graphics/ofGraphics.h
libs/openFrameworks/graphics/ofImage.h
libs/openFrameworks/graphics/ofPath.h

Fixing the merging problems on the multi window PR from arturoc #3384 
I've stepped through the changes in the multi window branch, and replayed those (very few) changes manually to the documentations made.

Documentation graphics fix

---

addons/ofxAndroid/src/ofxAndroidSoundStream.h

fixing ofxAndroidSoundStream

---

examples/gl/vboMeshDrawInstancedExample/src/main.cpp
examples/gl/vboMeshDrawInstancedExample/src/ofApp.cpp
examples/gl/vboMeshDrawInstancedExample/src/ofApp.h

+ adapt to new syntax for selecting GL version
+ use shared_ptr in favour of deprecated ofPtr

modernize vboMeshDrawInstancedExample

---

libs/openFrameworks/gl/ofBufferObject.cpp

fixes #3523
* uses `glCreateBuffers` instead of `glGenBuffers` if direct state access (OpenGL 4.5+) is available.
glGenBuffers does not actually create a buffer, it just returns the next available name, and only a subsequent
call to bind() will actualy initialize the buffer in memory.
This is why, for direct state access, we need to call glCreateBuffers(), so that the buffer is initialized when we pin data to it using setData()
Before this change, OpenGL 4.5 enabled cards would not draw any VBO based graphics.
This might also be related to #3514
See also: https://www.opengl.org/registry/specs/ARB/direct_state_access.txt

Fix for Direct State Access on Windows

---

libs/openFrameworks/gl/ofFbo.cpp
libs/openFrameworks/gl/ofFbo.h

A different approach to issue #3051

Deprecate ofFbo::destroy() in favor of clear()

---

libs/openFrameworks/3d/of3dPrimitives.h
libs/openFrameworks/3d/of3dUtils.h
libs/openFrameworks/3d/ofCamera.h
libs/openFrameworks/3d/ofEasyCam.h
libs/openFrameworks/3d/ofMesh.h
libs/openFrameworks/3d/ofNode.h

Minor fixes to mrbichel's 3d doc #3546

Documentation 3d

---

scripts/apothecary/formulas/openssl.sh

Updated to OpenSSL L update released Jan 15th 2015

Apothecary - OpenSSL Formula - L update

---

scripts/apothecary/formulas/FreeImage/FreeImage.sh

- Fixes not copying the include (if only building iOS)

Apothecary - FreeImage Formula Only - Fix

---

addons/ofxAssimpModelLoader/scripts/formulas/assimp.sh
scripts/apothecary/formulas/FreeImage/FreeImage.sh
scripts/apothecary/formulas/freetype.sh
scripts/apothecary/formulas/openssl.sh
scripts/apothecary/formulas/poco/poco.sh
scripts/apothecary/formulas/tess2/tess2.sh

This is a Apothecary Script only patch
- Fixes Assimp for iOS
- Adds Tail to redirected log output (so will always show last bit of
the log if error)
- Script fixes
| Lib                             | osx |  ios | 
|---------------------------------|-----|-------|
| FreeImage                       |[![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=freeimage-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=freeimage-osx) | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=freeimage-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=freeimage-ios) |
| FreeType                        |[![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=freetype-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=freetype- …

Apothecary Script updates

---

libs/openFrameworks/communication/ofArduino.h
libs/openFrameworks/communication/ofSerial.h

Documentation of communication folder

Serial and arduino doxygen documentation from ofSite

---

scripts/apothecary/formulas/tess2/tess2.patch
scripts/apothecary/formulas/tess2/tess2.sh

Relevant Former PR: https://github.com/openframeworks/openFrameworks/pull/3613
Build Status: [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=tess2-ios)](https://travis-ci.org/danoli3/apothecary-den/builds/49404443)

Apothecary Formula - Tess2 fixes

---

libs/openFrameworks/3d/ofEasyCam.cpp

Mostly fixing a compiler warning fix but may also cause a one frame
glitch with the zrot being wrong.  Cleaned up some white space inconsistency.

zRot not flipped properly

---

addons/ofxAndroid/src/ofxAndroidUtils.cpp
addons/ofxAndroid/src/ofxAndroidUtils.h

Just some more helper methods like the ones from the last PR that is already merged.
Previous PR: https://github.com/openframeworks/openFrameworks/pull/3397
Nothing too interesting. Sorry for leaving those out.

ofxAndroidUtils - Some more jni helper method.

---

libs/openFrameworksCompiled/project/linuxarmv7l/config.linuxarmv7l.rpi2.mk

Added fixed make file as described in this issue
https://github.com/openframeworks/openFrameworks/issues/3620

Added fixed make file for RPi2

---

addons/ofxOpenCv/scripts/formulas/OpenCV.sh

This is a just the apothecary formula for OpenCv. 
Windows isn't currently working all other platforms should be good. 
This is pulled from #3137 and should be good to merge without breaking the current master by updating the libs. 
@danoli3 @bakercp - if this looks good I'll merge it in. 
@elliotwoods once this is in master it should be pretty easy to try it out on Windows.

apothecary formula for opencv

---

scripts/apothecary/formulas/glfw.sh

Use @arturoc patch of glfw to support unicode #3621

Apo glfw arturoc patch

---

scripts/linux/debian/install_dependencies.sh

Hi peoples,
I added installation dependencies to satisfy 'egl', 'glesv1_cm' and 'glesv2' on Debian for ARMv7. It is tested on a Allwinner A10 SoC.
Cheers,
tpltnt

installation dependency fix for Debian

---

libs/openFrameworks/utils/ofXml.cpp

Fix for https://github.com/openframeworks/openFrameworks/issues/3643

removeContents works again

---

CHANGELOG.md
addons/ofxKinect/src/ofxKinect.cpp
addons/ofxKinect/src/ofxKinect.h

bugfix for kinect devices not being sorted correctly. closes #2527

---

libs/openFrameworks/graphics/ofPixels.cpp

forward pixels by amount of channels

---

scripts/apothecary/PROGRESS.md

squash non-unicode ✗

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidSoundPlayer.java
addons/ofxAndroid/src/ofxAndroidSoundStream.cpp
examples/gl/geometryShaderExample/src/ofApp.cpp
examples/gl/glInfoExample/src/glewOutput.cpp
examples/gl/glInfoExample/src/ofApp.cpp
examples/graphics/blendingExample/src/ofApp.cpp
examples/graphics/blendingExample/src/ofApp.h
examples/ios/MapKitExample/src/ofApp.mm
examples/ios/audioInputExample/src/ofApp.mm
examples/ios/audioOutputExample/src/ofApp.mm
examples/ios/eventsExample/src/ofApp.h
examples/ios/eventsExample/src/ofApp.mm
examples/ios/iPhoneGuiExample/src/gui/MyGuiView.mm
examples/ios/iosES2ShaderExample/src/ofApp.mm
examples/ios/iosNativeExample/src/Apps/CircleApp.mm
examples/ios/iosNativeExample/src/Apps/ImageApp.mm
examples/ios/iosNativeExample/src/Apps/SquareApp.mm
examples/ios/iosNativeExample/src/Apps/TriangleApp.mm
examples/ios/iosStoryboardExample/src/Apps/CircleApp.mm
examples/ios/iosStoryboardExample/src/Apps/ImageApp.mm
examples/ios/iosStoryboardExample/src/Apps/SquareApp.mm
examples/ios/iosStoryboardExample/src/Apps/TriangleApp.mm
examples/ios/ofxGuiExample/src/ofApp.mm
examples/ios/opencvExample/src/ofApp.mm
examples/ios/soundPlayerExample/src/ofApp.mm
examples/ios/xmlSettingsExample/src/ofApp.mm
libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofAppRunner.h
libs/openFrameworks/video/ofGstUtils.cpp
libs/openFrameworks/video/ofGstVideoPlayer.cpp

replaced sprintf, printf
and for the ios examples replaced the deprecated loadImage, loadFont and loadSound with load
issue #3301

Review of current examples for deprecated API usage

---

addons/ofxGui/src/ofxSlider.cpp

Fix scroll up issue on ofxIntSlider

---

libs/openFrameworks/math/ofMath.cpp

Removes unnecessary variables and variable assignment in ofRandom(), ofRandomf() and ofRandomuf().

ofMath: variable clean-up

---

scripts/apothecary/formulas/openssl.sh

OpenSSL 1.0.2a updated Mar 19 13:53:47 2015

Apothecary Formula - OpenSSL updated to 1.0.2a

---

CONTRIBUTING.md

Update CONTRIBUTING.md (typo)

---

libs/openFrameworks/utils/ofThread.cpp

removed verbose logging in lock, unlock, waitForThread

---

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.h

Changed method name setScaleNomalization to setScaleNormalization.

Fixed spelling

---

libs/openFrameworks/math/ofMatrix4x4.cpp

Bugfix make look at

---

scripts/linux/fedora/install_dependencies.sh

Fix dependencies for fedora, switch gstreamer-*-devel to gstreamer1-*-devel. Closes #3205

Fix dependencies for fedora. Closes #3205

---

libs/openFrameworks/utils/ofConstants.h
libs/openFrameworks/utils/ofUtils.cpp
libs/openFrameworks/utils/ofUtils.h

Reference https://github.com/openframeworks/openFrameworks/issues/3796

Add version tag support and increment version.

---

libs/openFrameworks/types/ofParameterGroup.h

correct parents of all parameters while copying a ofParameterGroup
thx: @patrickFuerst

fix parent while copying

---

scripts/apothecary/apothecary

- Fixes issues for addon formula directories contain more than one file (say a patch file or something else).

Apothecary Core Formula Fix for Addons

---

scripts/apothecary/formulas/freetype.sh

FreeType updated to 2.5.5 (Which fixes FreeType bugs and security vulnerabilities).

Apothecary Formula - FreeType 2.5.5

---

examples/ios/iosCustomSizeExample/src/UI/MyAppViewController.mm
examples/ios/iosCustomSizeExample/src/main.mm
examples/ios/iosNativeExample/src/UI/MyAppViewController.mm

- Fixes incorrect call to unknown type in ofRunApp
- Fixes assigning a UITextAlignmenCenter to a NSTextAlignment parameter (SDK) - Now assigns correct type;

Fix for iOSCustomSizeExample

---

scripts/linux/ubuntu/install_dependencies.sh

PR to fix install dependencies.sh problem described in this thread : http://forum.openframeworks.cc/t/install-dependencies-issues-with-current-github-master-and-ubunut-14-04/19620
tested only on two laptops!

Fix ubuntu install deps

---

libs/FreeImage/include/FreeImage.h

Based on the changes made in https://github.com/openframeworks/openFrameworks/pull/3845
To fix issues related to Assertions in FreeImage related to type sizes.
> Git Master, not able to load TIF files. #3832

Apothecary - FreeImage 3.16.0 Update - No assertions static libs (OS X and iOS).

---

addons/ofxOsc/src/ofxOscArg.h
addons/ofxOsc/src/ofxOscMessage.cpp
addons/ofxOsc/src/ofxOscMessage.h
addons/ofxOsc/src/ofxOscReceiver.cpp
addons/ofxOsc/src/ofxOscSender.cpp

as @ofTheo advise me, this is the pull-request based on the master branch.
This bugfixes #3537 which is about OSC 1.1 specifications.

Fix #3537 , PR within master

---

libs/openFrameworks/sound/ofSoundBuffer.cpp

Warnings showing up during linux compile.

Small fixes

---

libs/openFrameworks/video/ofQTKitGrabber.mm

and remove unuse tmpSession object.
so, `deviceInputWithDevice` is convenience initializer that is already autoreleased.
and `self.videoDeviceInput` do retain that.

fix replace retained and unrelease object to autoreleased object

---

libs/openFrameworks/utils/ofSystemUtils.cpp

fix potential of memory leak on ofSystemUtils

---

scripts/apothecary/formulas/boost/boost.sh
scripts/apothecary/formulas/boost/project-config-ios.jam

The iOS Formula for Boost 1.58.0 for Apothecary
Last remaining script for https://github.com/openframeworks/openFrameworks/issues/3926

Apothecary - Boost 1.58.0 iOS Formula for FileSystem/System

---

apps/devApps/projectGenerator/projectGenerator.vcxproj
apps/devApps/projectGenerator/src/projects/baseProject.cpp
libs/openFrameworks/utils/ofFileUtils.cpp
scripts/vs/template/emptyExample.vcxproj

This pr includes a list of changes necessary to get the project generator running again in vs 2015 / windows. 
Fixes #3928
Commit messages have more detailed info of what needed updating / fixing.

Fix pg vs2015

---

scripts/apothecary/formulas/uri/uri.sh

- Also a fix for OS X defining it as libc++ (was failing on Apothecary-den due to this).

Apothecary - URI Formula for iOS.

---

scripts/apothecary/formulas/uri/uri.sh

Minor fix to the script to add applying the Xcode patch for iOS

Apothecary - Formula for URI Xcode Patch for iOS

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

Fixes custom ofIcons with alpha channels.

Loading ofIcon properly

---

libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofAppRunner.h

I presumed this feature must already been in there, but I couldn't see it so here it is
let me know if it's already catered for elsewhere.
big fan of ofMainLoop. I was in the middle of making a feature request for `ofSession` today until i realized that the 0.9.0 had ofMainLoop
Elliot

Feature : ofSetMainLoop

---

examples/graphics/imageLoaderExample/src/ofApp.cpp

fixed imageLoaderExample

---

libs/openFrameworks/math/ofMatrix4x4.h

Hi all,
Partly as a learning exercise, partly as an effort to add some more thorough documentation, I went through ofMatrix4x4 and added some comments explaining the uses of each function. I'm sure most of it is obvious to people who know what they're looking at when inspecting a matrix class, but documentation is for those of us who don't always know! I also added some text pointing out OF's use of row-vector left-to-right style to the top.
Split up into multiple commits so each section can be examined independently.

Documentation matrix4x4

---

examples/sound/soundBufferExample/src/ofApp.cpp
examples/sound/soundBufferExample/src/ofApp.h

yet another letfover from #3855.
Cheers
tpltnt

fixed 'deprecated-declarations' warnings in soundBufferExample

---

libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj

Bugfix - Visual Studio intermediate paths

---

.travis.yml
scripts/dev/documentation.sh
scripts/ios/testTemplate.sh
scripts/osx/testTemplate.sh

Original Discussion here from 2012: ```Continuous integration/testing``` https://github.com/openframeworks/openFrameworks/issues/1068
Previous PR here: https://github.com/openframeworks/openFrameworks/pull/4008
Builds using Travis's Build Matrix System:
The current automated scripts to test are:
- iOS Empty Example + openFrameworks Core iOS Build Testing with Xcode
- OSX Empty Example + openFrameworks Core OSX Build Testing with Xcode
- Documentation Automation -  included @HalfdanJ 's changes for building the docs, however split into a seperate script. (Does the same functionality as current) This will only run a docs build for the master branch and not for PR's. (normally will just return success for this matrix).
This will add a success tick or cross to every PR for fail or success …

Travis Automated Testing of the Core - 2

---

libs/openFrameworks/types/ofTypes.h

Running this through tests now.  Feel free to test it!
Fixes #4048

Addition of std::make_unique for unsupported platforms.

---

examples/graphics/imageSequenceExample/src/ofApp.cpp
libs/openFrameworks/app/ofAppRunner.h
libs/openFrameworks/events/ofEvents.cpp
libs/openFrameworks/utils/ofFpsCounter.cpp
libs/openFrameworks/utils/ofFpsCounter.h
libs/openFrameworks/utils/ofUtils.h

New PR to eliminate extra commits.

Fixes #1930.  Replaces #4062. (unsigned long long -> uint64_t)

---

examples/gl/gpuParticleSystemExample/bin/data/shaders_gl3/passthru.vert
examples/gl/gpuParticleSystemExample/bin/data/shaders_gl3/posUpdate.frag
examples/gl/gpuParticleSystemExample/bin/data/shaders_gl3/render.frag
examples/gl/gpuParticleSystemExample/bin/data/shaders_gl3/render.geom
examples/gl/gpuParticleSystemExample/bin/data/shaders_gl3/render.vert
examples/gl/gpuParticleSystemExample/bin/data/shaders_gl3/velUpdate.frag
examples/gl/gpuParticleSystemExample/src/main.cpp
examples/gl/gpuParticleSystemExample/src/ofApp.cpp

Added shaders and code for programmable version of GPU particles example

---

libs/openFrameworks/3d/ofNode.cpp

fix #3722. Maintain global transform fixed when setting parent.

---

libs/openFrameworks/video/ofDirectShowPlayer.cpp

Fixes compile time errors on MinGW.

Fixing header names for case-sensitive MinGW

---

libs/openFrameworks/types/ofParameter.cpp
libs/openFrameworks/types/ofParameter.h
libs/openFrameworks/types/ofParameterGroup.cpp

Finished making const corrections for ofParameter and associated types.

Const corrections for ofParameter.

---

CHANGELOG.md
libs/openFrameworks/types/ofRectangle.cpp
libs/openFrameworks/types/ofRectangle.h

operator + exists.  So, adding operator -.

Added operator - to ofRectangle.

---

addons/ofxOsc/src/ofxOscMessage.cpp

Resolves issues with Visual Studio 2015 and ofxOsc addon

Resolve logical 'or' error with ofxOsc in VS 2015

---

libs/openFrameworks/3d/ofEasyCam.cpp

Hi,
i fixed a missing initialization in the ofEasyCam class.
Cheers,
tpltnt

explicit initialization in ofEasyCam

---

libs/openFrameworks/3d/ofMesh.cpp

Hi,
i fixed some missing initializations in the ofMesh class.
Cheers,
tpltnt

Bugfix ofMesh constructor

---

libs/openFrameworks/events/ofEvents.cpp
libs/openFrameworks/events/ofEvents.h

Type consistency for getFrameNum.

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofFileUtils.h

Some fixes to go along with the fancy new boost filesystem (and remove warnings).

Const corrections, data-type corrections, deprecations.

---

libs/openFrameworks/app/ofAppEGLWindow.cpp
libs/openFrameworks/app/ofAppEGLWindow.h

Hi,
i fixed some missing initializations (+ some documentation) to the ofAppEGLWindow class.
Cheers,
tpltnt

adding missing initializations to ofAppEGLWindow

---

libs/openFrameworks/communication/ofSerial.cpp
libs/openFrameworks/communication/ofSerial.h

Hi,
i went through ofSerial, fixed some style issues, added documentation and fixed minor code issues.
Cheers,
tpltnt

ofSerial cleanup

---

libs/openFrameworks/events/ofEvent.h

Hi,
i fixed some style issues, added documentation and fixed a missing assignment in ofEvent.h
Cheers,
tpltnt

ofEvent cleanup

---

libs/openFrameworks/3d/ofMesh.cpp
libs/openFrameworks/3d/ofMesh.h

Hi,
this fixes some style issues introduced with #4115 and duly pointed out by @armadillu. These are only aesthetic changes like converting spaces to tabs and general whitespace scrubbing.
Cheers,
tpltnt

fixing #4115

---

libs/openFrameworks/utils/ofXml.cpp

Hi,
this pull request fixes issue #3760. It has been checked and tested by @turowskipaul.
Cheers,
tpltnt

bugfix issue 3760

---

libs/openFrameworks/communication/ofSerial.cpp
libs/openFrameworks/utils/ofSystemUtils.cpp
libs/openFrameworks/utils/ofUtils.cpp

See #4103
Requires `UNICODE` and `_UNICODE` flags in Code::Blocks projects!

Unicode support for MinGW

---

libs/openFrameworks/utils/ofXml.cpp
libs/openFrameworks/utils/ofXml.h

Fixes iterator types ofXml.

---

libs/openFrameworksCompiled/project/win_cb/openFrameworksLib.cbp
scripts/win_cb/template/emptyExample.cbp

Unicode flags for Code::Blocks projects

---

libs/openFrameworks/3d/ofMesh.h
libs/openFrameworks/communication/ofSerial.h
libs/openFrameworks/gl/ofTexture.h
libs/openFrameworks/graphics/of3dGraphics.h
libs/openFrameworks/graphics/ofImage.h
libs/openFrameworks/graphics/ofTrueTypeFont.h
libs/openFrameworks/math/ofMatrix3x3.h
libs/openFrameworks/math/ofMatrix4x4.h
libs/openFrameworks/math/ofQuaternion.h
libs/openFrameworks/math/ofVec2f.h
libs/openFrameworks/types/ofBaseTypes.h
libs/openFrameworks/types/ofColor.h
libs/openFrameworks/types/ofParameter.h
libs/openFrameworks/types/ofRectangle.h
libs/openFrameworks/utils/ofLog.h
libs/openFrameworks/utils/ofUtils.h

Typos, missing items, warnings, etc.

Documentation fixes. 

---

scripts/dev/create_package.sh

recursively copy config.make and Makefile into examples for mingw

recursively copy config.make and Makefile into examples for mingw

---

libs/openFrameworks/utils/ofThreadChannel.h

Fixes #4225
@kylemcdonald as one recently using ofThreadChannel, would you mind giving this a proof-read?

ofThreadChannel documentation.

---

libs/openFrameworks/utils/ofThreadChannel.h

A single commit that I didn't push on thread channel docs.

Spaces to tab.

---

examples/addons/oscSenderExample/src/ofApp.cpp

Hi,
I fixed parts of #3129. The signal detection for "mouse up" and "mouse down" is still untouched.
Cheers,
tpltnt

partial fix issue 3129

---

scripts/linux/archlinux/install_dependencies.sh

Just a small notice with some instructions

added rtaudio notice for arch linux

---

libs/openFrameworks/utils/ofFileUtils.cpp

this fixes an annoying warning on OSX where this call: 
std::filesystem::create_directories(dirPath);
return false when *any* of the folders in the path already exist.  this means that although the folder is created, we get a warning that it wasn't created. 
the solution is to search for the directories existence before attempting to create it and using that to drive the warning. 
I am cleaning up the text based output from the project generator and this will go along way to making it much cleaner.

fix for spurious warning

---

addons/ofxProjectGenerator/src/projects/baseProject.cpp
addons/ofxProjectGenerator/src/projects/baseProject.h
addons/ofxProjectGenerator/src/projects/visualStudioProject.cpp
addons/ofxProjectGenerator/src/projects/visualStudioProject.h
addons/ofxProjectGenerator/src/projects/xcodeProject.cpp
addons/ofxProjectGenerator/src/projects/xcodeProject.h
libs/openFrameworks/utils/ofFileUtils.cpp

this PR corresponds to this PR on the project generator branch: 
https://github.com/openframeworks/projectGenerator/pull/15
I am cleaning up the text based feedback from the command line project generator so it has clear logs and easy to follow help screens, etc.

Better command line feedback

---

addons/ofxiOS/src/core/ofxiOSEAGLView.mm
addons/ofxiOS/src/core/ofxiOSViewController.mm

fixes ios fbo issue #4199

---

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp
examples/ios/MapKitExample/src/ofApp.mm
examples/ios/TouchAndAccelExample/src/Ball.h
examples/ios/TouchAndAccelExample/src/ofApp.mm
examples/ios/advancedGraphics/src/ofApp.mm
examples/ios/dirListExample/src/ofApp.mm
examples/ios/graphicsExample/src/ofApp.mm
examples/ios/imageLoaderExample/src/ofApp.mm
examples/ios/iosCustomSizeExample/src/main.mm
examples/ios/iosNativeExample/src/Apps/CircleApp.mm
examples/ios/iosNativeExample/src/Apps/ImageApp.mm
examples/ios/iosNativeExample/src/Apps/SquareApp.mm
examples/ios/iosNativeExample/src/Apps/TriangleApp.mm
examples/ios/iosStoryboardExample/src/Apps/CircleApp.mm
examples/ios/iosStoryboardExample/src/Apps/ImageApp.mm
examples/ios/iosStoryboardExample/src/Apps/SquareApp.mm
examples/ios/iosStoryboardExample/src/Apps/TriangleApp.mm
examples/ios/ofxGuiExample/src/ofApp.mm
examples/ios/opencvExample/src/ofApp.mm
examples/ios/oscReceiverExample/src/ofApp.mm
examples/ios/polygonExample/src/ofApp.mm

ios example fixes

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.cpp
libs/openFrameworks/graphics/ofCairoRenderer.cpp

fix popStyle applying the wrong style in all renderers

---

.travis.yml
scripts/ci/no-op/build.sh

Better workaround for a Travis bug.

Exclude the default build to work around a travis bug.

---

libs/openFrameworks/math/ofMath.cpp
libs/openFrameworks/math/ofMath.h

Removes warning for ofMap and adds documentation about default safety behavior.

Fixes #4217

---

examples/gl/shaderExample/src/main.cpp

removing ofSetCurrentRenderer(ofGLProgrammableRenderer::TYPE);

Modernize for 09

---

libs/openFrameworks/math/ofMath.cpp
libs/openFrameworks/math/ofMath.h

Reverts openframeworks/openFrameworks#4262

Revert "Of random updates"

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

bugfix for AVFoundation player issue for 10.8. closes #4356

---

libs/openFrameworks/math/ofVec2f.h
scripts/linux/compileOF.sh

Reverts openframeworks/openFrameworks#4043

Revert "leave one core for OS during compilation, see #3970"

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

ofAVFoundationPlayer release used resources on dealloc

---

addons/ofxiOS/src/sound/AVSoundPlayer.m

iOS Fixes Bug with AVSoundPlayer 

---

libs/openFrameworks/gl/ofTexture.h
libs/openFrameworks/math/ofVec2f.h

Removing declarations without definition

---

addons/ofxOpenCv/addon_config.mk

#4290
openframeworks/projectGenerator#58

Fix for iOS OpenCV missing AssetsLibrary*

---

libs/openFrameworks/gl/ofShader.cpp

Changes in rev. b2a33da2d prevented shader source code to be
quoted when GLSL compilation was not successful.
Control would return false before the shader source code was
cached internally. This gave `checkShaderInfoLog()` no
source file to compare the error log line numbers to.
This also fixes two other issues:
+ makes sure to retain the shader GPU id if a shader program
object was allocated successfully, before returning control
+ fixes an offset-by-one issue with the reported GLSL shader
compilation error line number

Fix an issue with ofShader compilation error reports

---

libs/openFrameworksCompiled/project/makefileCommon/config.project.mk

added .m and .mm files to project source discovery makefile

---

libs/openFrameworks/utils/ofSystemUtils.cpp

fixing part 2 of https://github.com/openframeworks/openFrameworks/issues/4464

Win File Name Fix

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroid.java

Fix for compilation error caused by my previous pull request. Sorry!

compilation error fix

---

docs/linux.md
docs/projectgenerator.md

this is just some updated PG info for the docs...

added new info about the new PG

---

libs/openFrameworks/video/ofAVFoundationPlayer.h
libs/openFrameworks/video/ofAVFoundationPlayer.mm
libs/openFrameworks/video/ofAVFoundationVideoPlayer.h
libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

fixes:
https://github.com/openframeworks/openFrameworks/issues/4485
in general stableizes the player

OFAVFoundationPlayer fastloading fixes

---

addons/ofxAndroid/ofAndroidLib/project.properties
addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidVideoGrabber.java
addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp

fixes closing the Android Video Grabber

fixing closing and restarting ofxAndroidVideoGrabber

---

docs/PLATFORMS.md
docs/table_of_contents.md

Hi,
another attempt at addressing #3506.
Cheers,
tpltnt

platform list

---

CHANGELOG.md

Hi oF people,
I went for 10 general items and adjusted the others according to the comments in the other (now closed) PR.
Cheers,
tpltnt

changelog for 0.9.0

---

scripts/android/buildAllExamples.sh
scripts/android/runAllExamples.sh

I've created two scripts that will build and run all android examples (on mac os at least)
It requires some enviroment variables set (see top of the scripts)

Android script for building and running all android examples

---

libs/openFrameworks/graphics/ofGraphics.h

Just some tiny fixes I stumbled upon. 
PS, should I commit directly with these kinds of changes, or PR them?

graphics minor documentation fixes

---

addons/ofxOpenCv/scripts/formulas/opencv.sh

Apothecary - Fix opencv build on osx: set `-DWITH_OPENEXR=OFF`

---

scripts/apothecary/formulas/poco/poco.sh

Fixes: https://github.com/openframeworks/openFrameworks/issues/4601

Apothecary - Poco Formula fix for Linux Formula Types

---

addons/ofxOpenCv/scripts/formulas/opencv.sh

Fixes merge issues / reverts of #4577 and https://github.com/openframeworks/openFrameworks/pull/4579/

Apothecary - OpenCV formula Fix.

---

addons/ofxOpenCv/scripts/formulas/opencv.sh

Apothecary: add -DWITH_EIGEN=OFF to opencv formula for osx

---

scripts/linux/ubuntu/install_dependencies.sh

Installs dependencies 1 by 1 and checks possible conflicts to try to avoid problems with some packages not being installed unless it's done manually.
Fixes #4550 
Fixes #4546 
Fixes #4543 
Fixes #3687
Fixes #1902

fixes for ubuntu's install dependencies

---

libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/utils/ofUtils.cpp
libs/openFrameworks/utils/ofUtils.h

Haven't tested thread safety but according to @ofTheo it should be ok

ofutils: get the clock instance on init instead of everytime.

---

scripts/templates/gitignore/.gitignore
scripts/templates/gitignore/template.config

ping @arturoc 
In the template.config, I also added linuxarm entries, but did not find any android or ios entries already existing, so I guess those aren't affected yet? This template is in principle useful for all our platforms/OSes.

Add .gitignore template for project generator. Closes #2791

---

libs/openFrameworks/video/ofQuickTimePlayer.cpp

changed createMovoeFromPath to createMovieFromPath

Fixed spelling in error message

---

examples/3d/ofNodeExample/src/Car.cpp
examples/3d/ofNodeExample/src/Car.h
examples/3d/ofNodeExample/src/main.cpp
examples/3d/ofNodeExample/src/ofApp.cpp
examples/3d/ofNodeExample/src/ofApp.h

Note:
This example is actually not working properly due to a bug in the 0.9 version. When the bug will be fixed, the light of the car will move with the car @arturoc.

Add ofNode example

---

addons/ofxOsc/src/ofxOscArg.h
addons/ofxOsc/src/ofxOscMessage.cpp
addons/ofxOsc/src/ofxOscMessage.h
addons/ofxOsc/src/ofxOscParameterSync.cpp
addons/ofxOsc/src/ofxOscParameterSync.h
addons/ofxOsc/src/ofxOscReceiver.cpp
addons/ofxOsc/src/ofxOscSender.cpp
addons/ofxOsc/src/ofxOscSender.h

* add `std::`
* arguments change from copy to const reference if that was forgiven.

ofxOsc tidying up

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

a redo of #3803 for #3763 due to changes in ofAVFoundationVideoPlayer

ofAVFoundationVideoPlayer: simplified setVolume

---

addons/ofxiOS/src/video/AVFoundationVideoPlayer.m

same as:
https://github.com/openframeworks/openFrameworks/pull/4669/files
but for iOS

simplified setVolume

---

scripts/dev/create_package.sh

Needed for PR https://github.com/openframeworks/projectGenerator/pull/106 on the pg repo

Update create_package.sh for pg electron folder name change

---

libs/openFrameworks/types/ofParameter.h
libs/openFrameworks/types/ofParameterGroup.cpp

Const correction for ofParameterGroup::contains

---

libs/openFrameworks/sound/ofSoundBuffer.cpp

There were some bugs that I fixed for the ofSoundBuffer:: getChannel method.

Hotfix ofSoundBuffer::getChannel

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

should fix: https://github.com/openframeworks/openFrameworks/issues/4689

set volume even if we are not ready

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

fixes issue where the window size is half as big on retina machines only on the initial setup.

---

libs/openFrameworks/app/ofAppGLFWWindow.h
libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofAppRunner.h

bugfix for being able to set the multidisplay fullscreen with the legacy window approach. 

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h

and small bugfix for window shrinking on hidpi screens. 
closes #4696 closes #4682
Needs testing on Windows. 
Will merge once confirmed fix on Windows.

bugfix for 90 degree orientation not working for fullscreen

---

libs/openFrameworks/math/ofQuaternion.cpp
libs/openFrameworks/math/ofQuaternion.h

about https://github.com/openframeworks/openFrameworks/pull/3976

fix problem about #3976

---

libs/openFrameworks/graphics/ofBitmapFont.cpp
libs/openFrameworks/graphics/ofTrueTypeFont.cpp

return correct bounding boxes for empty strings

---

libs/openFrameworks/gl/ofTexture.cpp
libs/openFrameworks/gl/ofTexture.h

ofTexture hasMipmap() - fixes #4732

---

libs/openFrameworks/math/ofVec2f.h

Hi,
I added some safeguards to ofVec2f::average , see #1555
Cheers,
tpltnt

catching invalid arguments to of ofVec2f::average

---

addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp
libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLProgrammableRenderer.h

I've got videograbber on android to work with programmable renderer. I'm not sure if this is the right way to implement it, since i pollute the core with android specific code. But i'm not sure where it otherwise should be done. 
Fixes #3000

Android: Support GL_TEXTURE_EXTERNAL_OES

---

addons/ofxUnitTests/src/ofxUnitTests.h
libs/openFrameworks/utils/ofURLFileLoader.cpp
libs/openFrameworks/utils/ofURLFileLoader.h

shows tests reports in appveyor's tests section

appveyor test reports

---

libs/openFrameworks/utils/ofURLFileLoader.cpp
libs/openFrameworks/utils/ofURLFileLoader.h

needed for windows tests reporting

ofURLFileLoader: add basic post support

---

libs/openFrameworks/3d/ofMesh.cpp

ofMesh has the ability to store and retrieve meshes as text files, using the fairly common ply format. Although it is almost ubiquitous, the format is not all too well documented, and many exporters from 3D modelling software do order (and name) attributes in slightly different ways than oF does.
This fix makes it possible to parse attributes based on the order of how these are defined in the file header (as the file format suggests), and cleans up the code slightly.
It also allows parsing of texture coordinates should they be named 's/t', as some 3d export plugins prefer over openFrameworks' export naming: 'u/v'.

implement more robust loading of ply meshes

---

libs/openFrameworks/graphics/ofGraphics.cpp
libs/openFrameworks/graphics/ofGraphics.h

Hi there,
I made a thing to fix #4668.
Cheers,
tpltnt

implemented universal scaling for ofScale()

---

libs/openFrameworks/3d/ofEasyCam.cpp
libs/openFrameworks/3d/ofEasyCam.h

I've added more sensitivity control and setters. The default values have been normalized but remain consistent.

ofEasyCam: Add rotation and translation sensitivity setters

---

libs/openFrameworks/app/ofAppEGLWindow.cpp

Let us enjoy dev-ing with vnc instead of hardware screens
More descriptions in the commit messages

Raspberrypi uinput fallback

---

libs/openFrameworks/communication/ofSerial.cpp
libs/openFrameworks/communication/ofSerial.h

substitutes https://github.com/openframeworks/openFrameworks/pull/3101

ofSerial: fixes for firmata servos in linux + better type handling

---

libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk

Msys2 makefile

---

libs/openFrameworks/utils/ofLog.cpp
libs/openFrameworks/utils/ofLog.h

I want to ofGetLogLevel method for specific module.

add ofGetLogLevel for specific module

---

examples/3d/advanced3dExample/src/Swarm.cpp
examples/gl/billboardExample/src/ofApp.cpp
examples/gl/computeShaderParticlesExample/src/ofApp.cpp
libs/openFrameworks/app/ofAppRunner.h
libs/openFrameworks/events/ofEvents.cpp

Hey,
i renamed ofGetLastFrameTime() to ofGetTimeSinceLastFrame() as suggested in #4600.
Cheers.
tpltnt

Feature issue 4600

---

examples/3d/advanced3dExample/src/Swarm.cpp
examples/gl/billboardExample/src/ofApp.cpp
examples/gl/computeShaderParticlesExample/src/ofApp.cpp
libs/openFrameworks/app/ofAppRunner.h
libs/openFrameworks/events/ofEvents.cpp

Reverts openframeworks/openFrameworks#4646

Revert "Feature issue 4600"

---

libs/openFrameworks/sound/ofRtAudioSoundStream.cpp

Fix ofSoundDevice created from nullptr

---

examples/utils/threadExample/src/main.cpp
examples/utils/threadExample/src/ofApp.cpp
examples/utils/threadExample/src/ofApp.h
examples/utils/threadExample/src/threadedObject.h

threadExample: use locks and shared memory in a way that shows the effects of not doing so

---

apps/devApps/explicitRendererExample/src/main.cpp

I just came across this one. 
Compiles now.

fixed explicitRendererExample

---

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

Fixes: https://github.com/openframeworks/openFrameworks/issues/4825

Project Fix for OSX

---

CONTRIBUTING.md

Found a small spelling mistake. "confirms" should be "conforms".

Fix spelling error in CONTRIBUTING.md

---

examples/utils/systemSpeakExample/src/ofApp.cpp

adds support for linux by using this [espeak](https://en.wikipedia.org/wiki/ESpeak):
echo "some words"|espeak
and converts some spaces into tabs.

systemSpeakExample: linux support, converting spaces into tabs

---

.gitignore

@arturoc @grayfuse Reverts this.

Revert fa3d31b84a3a5bde90e9f99ce5d0e10d1d63242b

---

scripts/ci/linux/build.sh
scripts/ci/linuxarmv6/build.sh
scripts/ci/osx/build.sh

This should fix https://github.com/openframeworks/openFrameworks/issues/4923.

fixes #4923 allAddonsExample path in test

---

libs/openFrameworks/utils/ofConstants.h
libs/openFrameworks/utils/ofThread.cpp

Here's another commented header file from the Denver OF Docs conf.  @bakercp, can you review?

docs_low_level: ofConstants.h

---

libs/openFrameworks/utils/ofFileUtils.h

added ofBuffer & ofFilePath doxy comments

docs_low_level: ofFileUtils.h (part 1, take 2)

---

examples/graphics/graphicsExample/src/main.cpp
examples/graphics/graphicsExample/src/ofApp.cpp
examples/graphics/graphicsExample/src/ofApp.h

Example of adding in README stub in comments of example, to use as guide for future examples.

Graphics example comments

---

libs/openFrameworks/gl/ofMaterial.h
libs/openFrameworks/types/ofBaseTypes.h
libs/openFrameworks/utils/ofSystemUtils.h
libs/openFrameworks/utils/ofURLFileLoader.h

doxygen comment additions for ofSystemUtils, ofURLFileLoader, ofBaseTypes
Also changed ofMaterial header doxygen commenting to regular `//` comments since it's not really documentation but reference links etc that should be moved to markdown.

docs_low_level: ofMaterial.h, ofBaseTypes.h, ofURLFileLoader.h, ofSystemUtils.h 

---

libs/openFrameworks/3d/ofNode.h

docs_low_level: ofNode.h

---

libs/openFrameworks/math/ofMath.h

Add ofIsFloatEqual function.  Replaces #4888

---

libs/openFrameworks/video/ofAVFoundationPlayer.mm

Bugfix AVF not allocating pixels after bad load.  closes #4967

---

libs/openFrameworks/app/ofAppBaseWindow.h
libs/openFrameworks/app/ofAppEGLWindow.cpp
libs/openFrameworks/app/ofAppEGLWindow.h
libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h
libs/openFrameworks/app/ofAppGlutWindow.cpp
libs/openFrameworks/app/ofAppGlutWindow.h
libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofAppRunner.h

- ofGetCurrentWindow: returns a shared_ptr to the current window
- ofBaseAppWindow: ::startRender ::finishRender and ::swapBuffers

adds some facilities to create new windows when the app is running

---

libs/openFrameworks/types/ofParameter.h
libs/openFrameworks/types/ofParameterGroup.cpp

ofParmater(Group): delete internal object on clear and remove invalid parents

---

libs/openFrameworks/graphics/ofImage.h

A small contribution to the doxygen documentation effort for ofImage.h

Documenting ofImage's ofImageQualityType enum

---

addons/ofxNetwork/src/ofxTCPClient.cpp
addons/ofxNetwork/src/ofxTCPClient.h
addons/ofxNetwork/src/ofxTCPServer.cpp
addons/ofxNetwork/src/ofxTCPServer.h
addons/ofxNetwork/src/ofxTCPSettings.h
addons/ofxNetwork/src/ofxUDPManager.cpp
addons/ofxNetwork/src/ofxUDPManager.h
addons/ofxNetwork/src/ofxUDPSettings.h
examples/communication/networkTcpClientExample/src/ofApp.cpp
examples/communication/networkTcpServerExample/src/ofApp.cpp
examples/communication/networkUdpReceiverExample/src/ofApp.cpp
examples/communication/networkUdpSenderExample/src/ofApp.cpp

Dealing with transition to ofx[TCP/UDP]Settings as proposed by @arturoc at #5011.
I suspect this would require a lot of back and forth, so am using a separate branch/PR.

Add ofxTCPSettings and ofxUDPSettings structs to ofxNetwork.

---

scripts/apothecary/README.md

It's `openFrameworks` and not `OpenFrameworks`.

Minor typo

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h
libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofMainLoop.cpp
libs/openFrameworks/app/ofMainLoop.h

Trying to fix GLFW slowness on some linux: #5009
Fixes window size values in some cases
Fixes main loop not finishing last window which in turned caused
game mode to let the screen in a wrong resolution when the app finished

several fixes for glfw and main loop

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

Fixes missing return introduced by d751a54e75f48556c56d90fa68d0f845b5bde2fd

Fix missing return.

---

libs/openFrameworks/gl/ofGLUtils.cpp
libs/openFrameworks/gl/ofShader.cpp
libs/openFrameworks/gl/ofShader.h

Uniform buffer object support added to ofShader

Feature uniformblock

---

libs/openFrameworks/graphics/ofGraphics.h

I took this from the OF forum where @arturoc  explained each mode.
https://forum.openframeworks.cc/t/what-is-the-bitmap-drawing-mode-in-openframeworks/22923

added explanation for ofSetDrawBitmapMode options

---

libs/openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj/project.pbxproj

- Fixes https://github.com/openframeworks/openFrameworks/issues/5115

Fix Xcode IEEE Fast Math Release Fast Math Error.

---

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp
addons/ofxEmscripten/src/ofxAppEmscriptenWindow.h
libs/openFrameworks/events/ofEvents.cpp
libs/openFrameworks/events/ofEvents.h

- Adds Touch Events to Emscripten
- Also added wrapper functions to ofCoreEvents for touch to follow suite with mouse/keyboard.

Emscripten - Touch events

---

libs/openFrameworks/3d/ofEasyCam.cpp
libs/openFrameworks/3d/ofEasyCam.h

See the commit comment for more details and see how to reproduce.

Fix mouseScrolled()'s initial inertia behavior

---

libs/openFrameworks/math/ofVectorMath.h

Fixes https://github.com/openframeworks/openFrameworks/issues/5171

Put the glm stream operators in the glm namespace.

---

libs/openFrameworks/types/ofColor.cpp
libs/openFrameworks/types/ofColor.h

* change argument like `const float&` to `float`
* add left side scalar operator. (i.e. allow `2.0f * color;`)

ofColor tidying up

---

libs/openFrameworks/gl/ofTexture.h
libs/openFrameworks/utils/ofUtils.h

just like #4955 changed sections syntax.

Doxygen sections ofTexture & ofUtils

---

libs/openFrameworks/3d/ofEasyCam.cpp
libs/openFrameworks/3d/ofEasyCam.h

cherry picked from @prisonerjohn 
fixes https://github.com/openframeworks/openFrameworks/issues/4846

ofEasyCam: Added custom control area. Defaults to viewport if not set.

---

libs/openFrameworks/types/ofRectangle.cpp

Updates for float equality checks in ofRectangle.

ofIsFloatEquals updates for ofRectangle.

---

libs/openFrameworks/gl/ofMaterial.cpp
libs/openFrameworks/gl/ofMaterial.h
libs/openFrameworks/gl/shaders/phong.frag
libs/openFrameworks/gl/shaders/phong.vert
libs/openFrameworksCompiled/project/qtcreator/modules/of/helpers.js

This allows to add a function that will get executed in the fragment shader after all the light and material calculations allowing to modify the final color.
For example:
```cpp
auto postFragment = R"(
vec4 postFragment(vec4 color){
float distanceToCamera = length(v_eyePosition);
float maxDistance = 1000;
float attenuation = clamp(maxDistance / distanceToCamera, 0, 1);
return color * attenuation;
}
)";
material.setPostFragment(postFragment);
```

ofMaterial: Add postFragment function. Move shaders to their own files

---

libs/openFrameworks/math/ofMatrix3x3.cpp
libs/openFrameworks/math/ofVectorMath.h

I also think there was a bug in ofMatrix3x3...

glm::mat3 and glm::mat4 stream operators

---

.gitignore
.gitmodules
scripts/linux/archlinux/install_dependencies.sh
scripts/linux/debian/install_dependencies.sh
scripts/linux/fedora/install_dependencies.sh
scripts/linux/ubuntu/install_dependencies.sh

put apothecary in git submodule and update path in scripts

---

libs/openFrameworks/utils/ofThread.cpp

bugfix for ofThread::waitForThread crash. Closes #4828

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/helpers.js

I forgot to load the Textfile extension...

also load TextFile extension in qbs helper

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofFileUtils.h
tests/utils/buffer/src/main.cpp

Allows to traverse a text line by line backwards

ofBuffer: add getReversedLines

---

libs/openFrameworks/utils/ofConstants.h
libs/openFrameworks/video/ofAVFoundationGrabber.h
libs/openFrameworks/video/ofAVFoundationGrabber.mm
libs/openFrameworks/video/ofQTKitGrabber.h
libs/openFrameworks/video/ofQTKitGrabber.mm
libs/openFrameworks/video/ofQTKitMovieRenderer.h
libs/openFrameworks/video/ofQTKitMovieRenderer.m
libs/openFrameworks/video/ofQTKitPlayer.h
libs/openFrameworks/video/ofQTKitPlayer.mm
libs/openFrameworks/video/ofQtUtils.cpp
libs/openFrameworks/video/ofQtUtils.h
libs/openFrameworks/video/ofQuickTimeGrabber.cpp
libs/openFrameworks/video/ofQuickTimeGrabber.h
libs/openFrameworks/video/ofQuickTimePlayer.cpp
libs/openFrameworks/video/ofQuickTimePlayer.h
libs/openFrameworks/video/ofVideoGrabber.h
libs/openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj/project.pbxproj

Don't merge just yet. 
Running some checks on 10.11 / Xcode 8
Should address the issue in #5264

preprocessor fixes for OS X 10.12 for QTKit and QuickTime

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/helpers.js
libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs
libs/openFrameworksCompiled/project/qtcreator/ofApp.qbs
scripts/qtcreator/install_template.sh

Add some checks on PATH when using QTCreator with MSYS2.

QtCreator fixes for MSYS2

---

examples/windowing/noWindowExample/README.md
examples/windowing/noWindowExample/src/main.cpp
examples/windowing/noWindowExample/src/ofApp.cpp
examples/windowing/noWindowExample/src/ofApp.h

maybe some more explanation about 
things that will not happen in headless mode?
keystrokes? events? sound? rendering?

noWindowExample. needs input, please review

---

.appveyor.yml
scripts/ci/msys2/build.sh
scripts/ci/msys2/install.sh
scripts/ci/msys2/run_tests.sh
scripts/msys2/compileOF.sh
scripts/msys2/install_dependencies.sh
tests/addons/ofxGui/src/main.cpp
tests/utils/strings/src/main.cpp

fixing a previous PR from oxillo

Msys2 appveyor

---

scripts/msys2/install_dependencies.sh

installation of libusb package in MSYS2 (required for Kinect example)
fixes #5290

MSYS2 : Add libusb in dependencies install

---

CHANGELOG.md

ascii art in changelog

---

examples/3d/cameraLensOffsetExample/src/ofApp.cpp

There are a number of examples that do not build cleanly. This is the first in a series of PRs to fix the examples.

simple fix to get inverse

---

examples/3d/normalsExample/src/ofApp.cpp

More cleanup in the examples directory.

use auto type to get vectors

---

examples/gl/shaderExample/bin/data/shaders_gl3/noise.frag
examples/gl/shaderExample/bin/data/shaders_gl3/noise.vert

Added the copy from vert to frag for clarification of use in the example

Missing texCoordVarying in vert shader example

---

examples/android/androidAccelerometerExample/Makefile
examples/android/androidAdvanced3DExample/Makefile
examples/android/androidAssimpExample/Makefile
examples/android/androidAudioExample/Makefile
examples/android/androidCameraExample/Makefile
examples/android/androidEmptyExample/Makefile
examples/android/androidFontExample/Makefile
examples/android/androidGuiExample/Makefile
examples/android/androidImageExample/Makefile
examples/android/androidJavaOnlyActivityExample/Makefile
examples/android/androidMultiOFActivitiesExample/Makefile
examples/android/androidOpenCVExample/Makefile
examples/android/androidOpenCVFaceExample/Makefile
examples/android/androidPolygonExample/Makefile
examples/android/androidShaderExample/Makefile
examples/android/androidSoundPlayerExample/Makefile
examples/android/androidSwipeExample/Makefile
examples/android/androidTouchExample/Makefile
examples/android/androidVBOExample/Makefile
examples/android/androidVibratorExample/Makefile
examples/android/androidVideoExample/Makefile
scripts/qtcreator/templates/wizards/openFrameworks/Makefile
scripts/qtcreator/templates/wizards/openFrameworksUpdate/Makefile
scripts/templates/android/Makefile
scripts/templates/linux/Makefile
scripts/templates/linux64/Makefile
scripts/templates/linuxarmv6l/Makefile
scripts/templates/linuxarmv7l/Makefile
scripts/templates/msys2/Makefile
scripts/templates/osx/Makefile

A line in the Makefiles was indented with spaces when tabs should be used

Substitute some spaces with tabs across all the Makefiles

---

scripts/vs/download_libs.ps1

+ source directory for decompression was not correct

vs download libs : fix powershell script

---

examples/gl/billboardExample/src/ofApp.cpp

Open to comment on the type that I ended up using for the templated vector type. Is there an of* type that will yield the same result?

initilize verticies without using set()

---

addons/ofxGui/src/ofxBaseGui.cpp
libs/openFrameworks/utils/ofJson.h
libs/openFrameworks/utils/ofXml.cpp
libs/openFrameworks/utils/ofXml.h

-Added ofSerialize and ofDeserialize methods to ofXml, using the new ofXml api.
-Fixed ofDeserialize in ofJson, as it was not reading the nested groups.

Fixed ofxGui save and load.

---

apps/devApps/explicitRendererExample/Makefile
apps/devApps/raspberrypi_hello_world/Makefile
apps/devApps/raspberrypi_hello_world_gles2/Makefile
libs/openFrameworksCompiled/project/android/config.android.default.mk
libs/openFrameworksCompiled/project/makefileCommon/Makefile.examples
libs/openFrameworksCompiled/project/makefileCommon/compile.core.mk
libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk
libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk
libs/openFrameworksCompiled/project/makefileCommon/config.project.mk
libs/openFrameworksCompiled/project/makefileCommon/config.shared.mk
libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk

I missed a good number of spaces when I did #5362 so here they are

Substitute remaining spaces in Makefiles with tabs

---

addons/ofxGPS/src/iOS/ofxGPSImpliOS.h
addons/ofxGPS/src/iOS/ofxGPSImpliOS.mm

Hi,
A while back I did a pull request for a massive android change that included a cross platform iOS+Android gps addon that was decided to be included in the core add ons. By @arturoc ’s request, I omited the iOS part of the addon so that it can be reviewed by @openframeworks/ios  separately.
This addon is actively developed by me and used in production scenarios (tens of thousands of users). It is based on work by Zach Gage, with a uniform interface common with an Android addon I found (work by @arturoc  if I’m not mistaken). 
I plan to continue improving it, and making it more configurable (enable/disable background locations, add tolerances, and more).

ofxGPS - iOS implementation

---

addons/ofxiOS/src/sound/AVSoundPlayer.m

Fix for tvOS Sound on Device Reported and Fixed by @andreasmuller 
https://github.com/danoli3/openFrameworks/pull/5

Fix for tvOS Sound Default Setting for Device

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidLifeCycle.java

Cleanup of old stack management code. Not needed now that we have reference count for gl activities.

Android - OFAndroidLifeCycle - cleanup

---

libs/openFrameworks/app/ofAppEGLWindow.cpp

Typo introduced in 6b593ee3ae272dbbd377d1100d1802994bd60c10
Fixes #5487

Fixed opening of mouse and keyboard on RPi

---

libs/openFrameworks/utils/ofJson.h

Fix JSON loading path types, add documentation.

---

libs/openFrameworks/math/ofVec2f.h

Similar to documentation fixes made for ofVec3f in #5448, forgot to see if I should also update ofVec2f.

 Fix descriptions for ofVec2f

---

addons/ofxOsc/src/ofxOscBundle.cpp
addons/ofxOsc/src/ofxOscBundle.h
addons/ofxOsc/src/ofxOscMessage.cpp
addons/ofxOsc/src/ofxOscMessage.h

A few of the review items slipped through on #5476.  Here are the fixes.

Type fixes for OSC, additional documentation.

---

INSTALL_FROM_GITHUB.md

After some discussion in the forum (https://forum.openframeworks.cc/t/compile-of-locally/26248 , https://forum.openframeworks.cc/t/how-do-i-build-from-source/24569/2, https://forum.openframeworks.cc/t/how-to-build-project-generator-from-of-git-repo/26232 and many others), I've written this.
I've followed this procedure, and now in my OF folder i've two changed files:
```bash
M apps/projectGenerator
M scripts/apothecary
```
Because I've run previously `git submodule update`. This is the output of git diff
```
diff --git a/apps/projectGenerator b/apps/projectGenerator
index 2b24ac0..2a1cb6a 160000
--- a/apps/projectGenerator
+++ b/apps/projectGenerator
@@ -1 +1 @@
-Subproject commit 2b24ac02060254855bc3a7560aed64d1c97a4ba9
+Subproject commit 2a1cb6af9c6a957b84d645136c996990a3c02726
diff …
```

add instruction about how to install OF from github

---

libs/openFrameworks/sound/ofSoundPlayer.cpp

same sentence exists [line1](https://github.com/openframeworks/openFrameworks/blob/19ec2688df9eecd818e333bef4753c302058de17/libs/openFrameworks/sound/ofSoundPlayer.cpp#L1)

Delete duplicated sentence

---

libs/openFrameworks/types/ofColor.cpp
libs/openFrameworks/types/ofColor.h

ofColor: fix extern template warnings for static constants. 

---

INSTALL_FROM_GITHUB.md

And some wording, typos and sections

Instructions if user cloned OF repo without fork

---

addons/ofxGui/src/ofxInputField.cpp
addons/ofxGui/src/ofxInputField.h

+ add check not to move cursor if invalid input
+ rename substr -> visibleInput
+ add visual separators
+ extend visibleInput when character entered inside text
+ disable cursor blink when cursor in motion

sundry text input snags and fixes

---

addons/ofxGui/src/ofxColorPicker.cpp
addons/ofxGui/src/ofxColorPicker.h

-Now the color point is set correctly on setup.
-update color point on mouse pressed and mouse released.
Issue:
https://github.com/openframeworks/openFrameworks/issues/5589

ofxColorPicker fixes.

---

addons/ofxGui/src/ofxBaseGui.cpp

Making sure json file exists before reading from it

---

libs/openFrameworks/communication/ofSerial.cpp

isDeviceArduino() is only used on TARGET_OSX

Fix warning about unused function.

---

libs/openFrameworks/app/ofAppEGLWindow.cpp

Fixes #5305

---

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

Fixes https://github.com/openframeworks/projectGenerator/issues/111
Fixes #4728
Should merge with https://github.com/openframeworks/projectGenerator/pull/161

Fixes #4728 (XCode template Default Western Encoding -> UFT8)

---

INSTALL_FROM_GITHUB.md

Minor tweaks, added an example of how to use the CLI PG to generate example makefiles.

Update install-from-github guide

---

libs/openFrameworks/video/ofVideoGrabber.cpp

These warnings are seen in linux in particular.

Fix unsigned / signed comparison warnings in ofVideoPlayer.

---

scripts/dev/download_libs.sh

Fix MSYS2 downloading wrong lib package

---

scripts/linux/fedora/install_dependencies.sh

And moved from `yum` package manager to `dnf` package manager,
which is supposed to replace it.

Fixes "libglfw3-devel not found" on Fedora.

---

docs/android_studio.md
libs/openFrameworksCompiled/project/android/ndk-verify.gradle
scripts/templates/android/build.gradle

Added a script that is verifying the NDK version, and giving better errors when wrong version is installed. Making it more user friendly.

Add script verifying NDK install

---

libs/openFrameworksCompiled/project/vs/openFrameworksDebug.props
libs/openFrameworksCompiled/project/vs/openFrameworksRelease.props

otherwise would get an error if the OF path has spaces in it.

Added quotes around paths in post-build script

---

libs/openFrameworks/gl/ofFbo.h

Fix typo on deprecation warning

---

examples/android/androidGuiExample/src/ofApp.cpp

Without this change the program fails to compile on master

Fix ofVec2f to glm::vec2 conversion issue

---

.travis.yml
libs/openFrameworks/utils/ofLog.cpp
libs/openFrameworksCompiled/project/android/ndk-verify.gradle

For some reason 12b is giving some undefined references since some days ago and everything seems to be working fine with 15c

android ndk 15c

---

libs/openFrameworks/utils/ofURLFileLoader.cpp

test with e.g.:
```
ofHttpResponse resp = ofLoadURL("http://foo.bar");
ofLog() << "code: " << resp.status;
ofLog() << "error: " << resp.error;
```

use CURLcode, get error description from curl

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs
libs/openFrameworksCompiled/project/qtcreator/ofApp.qbs
libs/openFrameworksCompiled/project/qtcreator/openFrameworks.qbs
scripts/qtcreator/templates/wizards/openFrameworks/qtcreator.qbs
scripts/qtcreator/templates/wizards/openFrameworksUpdate/qtcreator_update.qbs
scripts/qtcreator/templates/wizards/openFrameworksUpdate/qtcreator_update_no_addons.qbs

i could not test the changes on other systems.
think the changes deal with newer version of qbs, so i guess it is fine on linux/win as well
but would be good if this would be checked on linux/win before merging...

Qbs fixes qtcreator 441 osx

---

libs/openFrameworks/3d/ofEasyCam.cpp

fix for 
https://github.com/openframeworks/openFrameworks/issues/5774

Fix of easy cam drift

---

scripts/linux/compilePG.sh

Script Resolver Revision based on #5691
Includes cherry pick of @baydam original solution
Fixes #5691 / updates it.

OF Root Linux Resolver Update

---

libs/openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj/project.pbxproj

As discussed in these comments, https://github.com/openframeworks/openFrameworks/commit/dcdc4f4a2cc8d0523998db438b2a3fa33f4fc86a#diff-3370fe6b5470b2a40b86861e869911b3L1 add ofBaseApp.cpp to the OF XcodeProject so that it can be compiled.

add missing ofBaseApp.cpp file into xcode prj

---

libs/openFrameworks/3d/ofCamera.cpp

+ fixes bug when drawing ofCamera Frustum which appeared recently.
+ simplifies code drastically
+ adds comments focusing on the "how" rather the "what".

fix ofCamera-drawFrustum

---

libs/openFrameworks/utils/ofURLFileLoader.cpp

ofLoadURL couldn't resolve SSL on android.

Fix for SSL certificate issue when load a URL

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

ofAppGLFWWindow: the size reported on setup was wrong.

---

addons/ofxiOS/src/utils/ofxiOSKeyboard.mm

Fixes https://github.com/openframeworks/openFrameworks/issues/2449
Tested

Fixes #2449 ofxiOSKeyboard position

---

libs/openFrameworks/graphics/ofTessellator.h

Minimalism is cool, but 1D is going too far :P

Fix typo: 1D is actually 2D

---

scripts/linux/fedora/install_codecs.sh

... as per the instructions on https://rpmfusion.org/Configuration

add release number to pkg names, so correct version will be picked up

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs

Without adding these qbs is not able to build the project

More fixes for QtCreator 4.6.0

---

addons/ofxiOS/src/core/ofxiOSViewController.mm

bugfix ios viewport issue closes #5627

bugfix ios viewport issue closes #5627

---

libs/openFrameworks/types/ofParameter.cpp

ofParameter working with ofxImgui

ofParameter: escape # to _

---

libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk
scripts/msys2/install_dependencies.sh

should fix #5923 and should adapt to projects using other dlls in mingw32

MSYS2 : dynamic build list of dlls to be copied

---

examples/shader/09_gaussianBlurFilter/bin/data/shadersES2/shaderBlurX.frag
examples/shader/09_gaussianBlurFilter/bin/data/shadersES2/shaderBlurY.frag
examples/shader/09_gaussianBlurFilter/bin/data/shadersGL2/shaderBlurX.frag
examples/shader/09_gaussianBlurFilter/bin/data/shadersGL2/shaderBlurY.frag
examples/shader/09_gaussianBlurFilter/bin/data/shadersGL3/shaderBlurX.frag
examples/shader/09_gaussianBlurFilter/bin/data/shadersGL3/shaderBlurY.frag

Bugfix shader macos. Closes #5954 

---

.appveyor.yml
libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj
scripts/ci/vs/install.sh
scripts/dev/nightlybuilds.sh
scripts/dev/release.sh
scripts/templates/vs/emptyExample.vcxproj
scripts/vs/download_libs.sh
tests/addons/networkTcp/networkTcp.vcxproj
tests/addons/networkUdp/networkUdp.vcxproj
tests/events/events/events.vcxproj
tests/graphics/pixels/pixels.vcxproj
tests/io/loadImage/loadImage.vcxproj
tests/math/ofNodeRegressionTests/ofNodeRegressionTests.vcxproj
tests/math/quaternionTests/quaternionTests.vcxproj
tests/utils/buffer/buffer.vcxproj
tests/utils/fileUtils/fileUtils.vcxproj
tests/utils/strings/strings.vcxproj

don't create vs2015 packages and update ci tests to vs2017

Remove vs2015

---

addons/ofxAndroid/src/ofxAndroidUtils.h

add ofxAndroidPauseApp()

---

libs/openFrameworks/3d/ofNode.h
libs/openFrameworks/graphics/ofCairoRenderer.cpp
libs/openFrameworks/graphics/ofPath.cpp
libs/openFrameworks/graphics/ofPath.h
libs/openFrameworks/graphics/ofPolyline.h
libs/openFrameworks/graphics/ofPolyline.inl
libs/openFrameworks/sound/ofSoundBaseTypes.cpp

Other small fixes, whitespace etc.

ofPath / ofPolyline still used rotate(az ...). Convert to rotateDeg/rotateRad.

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroid.java

https://forum.openframeworks.cc/t/0-10-0-release-candidate-3/29348/45?u=kashim

fix context WifiManager in ofAndroidLib

---

addons/ofxGui/src/ofxColorPicker.cpp
libs/openFrameworks/3d/ofCamera.cpp
libs/openFrameworks/3d/ofEasyCam.cpp
libs/openFrameworks/3d/ofNode.cpp
libs/openFrameworks/app/ofAppEGLWindow.cpp
libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.cpp
libs/openFrameworks/gl/ofLight.cpp
libs/openFrameworks/gl/ofMaterial.cpp
libs/openFrameworks/graphics/ofCairoRenderer.cpp
libs/openFrameworks/types/ofRectangle.cpp
libs/openFrameworks/utils/ofConstants.h

Seems they make things really slow. Mostly debugging on xcode and probably other platforms.
Closes #5812

Remove glm swizzles

---

libs/openFrameworksCompiled/project/linux64/config.linux64.default.mk
libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk
libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs

makes link times much faster on big projects

use gold linker in linux

---

addons/ofxGui/src/ofxSliderGroup.cpp

Fixes https://github.com/openframeworks/openFrameworks/issues/6031

Bugfix ofxSliderGroup division by zero

---

libs/openFrameworks/3d/of3dPrimitives.h

`ofEnabledDepthTesting()` to `ofEnableDepthTest()`

fix document on ofSpherePrimitive

---

libs/openFrameworks/3d/ofNode.cpp
tests/math/ofNodeRegressionTests/src/main.cpp

The 1st one in https://github.com/openframeworks/openFrameworks/issues/6025.

Bugfix ofnode orientation with scale

---

libs/openFrameworks/utils/ofJson.h

maybe this fix doesn't break compatibility.

fix `ofSerialize` constness in ofJson.h

---

examples/gui/parameterGroupExample/src/ofApp.cpp

it was there but never got connected, so that was a little confusing

binding the listener method to the vSync param

---

scripts/templates/vs/emptyExample.vcxproj

add a missing commit
https://github.com/openframeworks/openFrameworks/pull/6122#issuecomment-419633186

Bugfix vs project template (pt.2)

---

examples/gles/customEGLWindowSettingsExample/src/main.cpp

example was no longer working. These changes worked for me but unsure if this is the proper way

Update customEGLWindowSettingsExample main.cpp

---

libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig

In association with #6131 .
remove 2 lines.

remove i386 architecture

---

addons/ofxGui/src/ofxBaseGui.cpp
addons/ofxGui/src/ofxBaseGui.h
addons/ofxGui/src/ofxGui.h
addons/ofxGui/src/ofxGuiGroup.cpp
addons/ofxGui/src/ofxGuiGroup.h
addons/ofxGui/src/ofxInputField.cpp
addons/ofxGui/src/ofxLabel.cpp
addons/ofxGui/src/ofxPanel.cpp
addons/ofxGui/src/ofxPanel.h
addons/ofxGui/src/ofxSlider.cpp
addons/ofxGui/src/ofxToggle.cpp

I've added a feature to ofxGuiGroup to disable its header. I've found this feature quite useful to unclog the gui and for making dropdowns.
This feature does not alter the normal functioning of ofxGui, just adds a harmless new feature.
Hope this can get merged right away.
cheers

ofxGui scaled for retina displays + group header enable/disable feature 

---

libs/openFrameworksCompiled/project/makefileCommon/compile.core.mk
libs/openFrameworksCompiled/project/makefileCommon/config.shared.mk

replace erroneous tabs in makefiles

---

addons/ofxiOS/src/core/ofxiOSGLKViewController.mm

In the current version of the addon does not work fbo on ios. Here is the issue:
https://forum.openframeworks.cc/t/fbo-doesnt-work-on-ios/31174

ofxiOS: fix FBO for GLK view

---

libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk

remove #else comment

---

addons/ofxOpenCv/src/ofxCvImage.cpp

Fix https://github.com/openframeworks/openFrameworks/issues/6115

Check for !bAllocated on assignment of ofxCvImage (fixes #6115)

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

fix setSpaceSize to be independent of setLetterSpacing and work regardless of whether setLetterSpacing is at default value. More details on the forum: https://forum.openframeworks.cc/t/oftruetypefont-setletterspacing-setspacesize-problem/32327

fix setSpaceSize

---

libs/openFrameworks/3d/ofEasyCam.cpp

ofEasyCam stopped working for translate with mouse buttons - this fixes and makes sure left / middle / right and key modifiers all work for ofEasyCam

Bugfix ofEasyCam

---

libs/openFrameworksCompiled/project/android/build.gradle
libs/openFrameworksCompiled/project/android/common-functions.gradle
scripts/dev/download_libs.sh
scripts/templates/android/build.gradle

Update the Android SDK version to 23.

Update the android sdk version to 23.

---

libs/openFrameworks/graphics/ofPath.cpp
libs/openFrameworks/graphics/ofPath.h

Fix missing const in ofPath

---

libs/openFrameworks/3d/ofNode.cpp
libs/openFrameworks/types/ofRectangle.h

Small fixes to enable move to glm branch 0.9.9.
MSYS2 not building due to current CI problem

small glm fixes - glm 0.9.9 compatibility

---

libs/openFrameworks/graphics/ofGraphicsBaseTypes.h

related to what i brought up in issues #6320
tested & working. though double check if needed

making the default background color 60

---

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

bugfix AppStore configuration for osx - strips 32bit from dylibs and frameworks

---

scripts/templates/emscripten/template.config
scripts/templates/gitignore/template.config
scripts/templates/tvOS/template.config

Update template.config in order to support Template dropdown in PG frontend.
- /gitignore
- /tvOS
- /emscripten
need more?
See details about frontendPG update here.
https://github.com/openframeworks/projectGenerator/pull/206

update template.config files

---

scripts/dev/download_libs.sh

add double quotes to allow for folder names with spaces

---

examples/3d/3DPrimitivesExample/src/ofApp.h

fix: Fix the indent

---

libs/openFrameworks/graphics/of3dGraphics.h

Replaces and fixes
https://github.com/openframeworks/openFrameworks/pull/5006
circa 2016

Docs of3d graphics

---

libs/openFrameworks/gl/ofGLBaseTypes.h

Merges @brannondorsey 
https://github.com/openframeworks/openFrameworks/pull/5004
Circa 2016

Docs ofBaseGLRenderer

---

libs/openFrameworks/3d/ofNode.h

Replaces #4991
@digitalcoleman

Docs ofNode 

---

apps/devApps/explicitRendererExample/src/main.cpp
examples/3d/3DPrimitivesExample/src/ofApp.h
libs/openFrameworks/graphics/of3dGraphics.h
libs/openFrameworks/utils/ofUtils.h

More documentation for ofUtils

Docs of ofUtil

---

libs/openFrameworks/3d/ofCamera.cpp
libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.cpp
libs/openFrameworks/graphics/of3dGraphics.cpp
libs/openFrameworks/graphics/ofCairoRenderer.cpp
libs/openFrameworks/graphics/ofPolyline.inl

as we discussed in https://github.com/openframeworks/apothecary/pull/136

fixes ofPolyline to prepare oF for glm 0.9.9.5

---

addons/ofxiOS/src/core/ofxiOSAppDelegate.mm
addons/ofxiOS/src/events/ofxiOSAccelerometer.mm

* make fullscreen on external display.
* add including ofLog.h on ofxiOSAccelerometer.mm

[fix] ofxiOS: make fullscreen on external display.

---

libs/openFrameworks/graphics/ofPixels.cpp
libs/openFrameworks/graphics/ofPixels.h

fix ofPixels.h/cpp warnings

---

addons/ofxGui/src/ofxColorPicker.cpp

fixes https://github.com/openframeworks/openFrameworks/issues/6419
@arturoc

fixed ofxColorPicker glitch

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/helpers.js

Fix #6333 
Better detection of MSYS2 installation directory (including MINGW64)

QTCreator : improved msys2 install detection

---

CHANGELOG.md
libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk

Fix #4720 
Copy Dlls in Debug and Release
Also in MINGW64

MSYS2 : Copy dlls

---

examples/3d/assimpExample/src/ofApp.cpp
examples/input_output/imageLoaderWebExample/src/main.cpp
examples/input_output/imageLoaderWebExample/src/ofApp.cpp
examples/input_output/imageSequenceExample/src/ofApp.cpp
examples/input_output/systemSpeakExample/src/ofApp.cpp
examples/math/particlesExample/src/demoParticle.cpp

Example fixes

---

addons/ofxGui/src/ofxSliderGroup.cpp

Update to #6381 #6423 to update text colour based on the brightness of the background colour.

update text color to changing bg colour to ofxGui as well

---

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

bugfix. adds 32bit stripping to AppStore configuration for libfmodex.dylib. 

---

libs/openFrameworks/utils/ofJson.h

[Small fix] fix error log about ofJson

---

libs/openFrameworks/types/ofParameter.cpp

Implements what is discussed in: #6467

ofParameter<void>::trigger() notifies parents

---

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp

Ensures depth buffer for ofxAppEmscriptenWindow. Closes #6484

---

libs/openFrameworks/gl/ofShader.cpp

Fix for transform feedback on macOS

---

libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp

changed glGetError() to alGetError()

---

addons/ofxGui/src/ofxBaseGui.cpp
addons/ofxGui/src/ofxBaseGui.h

ofxGui: Updating events to allow multiwindow functioning

---

addons/ofxGui/src/ofxBaseGui.cpp
addons/ofxGui/src/ofxBaseGui.h
addons/ofxGui/src/ofxGuiGroup.cpp
addons/ofxGui/src/ofxGuiGroup.h
addons/ofxGui/src/ofxPanel.cpp

I've made several improvements to ofxGuiGroup and ofxPanel, which address https://github.com/openframeworks/openFrameworks/issues/6470 and https://github.com/openframeworks/openFrameworks/issues/6145.
I removed a lot of redundant code for setting the position of the gui elements, and replaced for a single function, this way the behavior is easier to understand, less bug prone and looks better as well. :)

Fix ofxPanel disable header

---

addons/ofxGui/src/ofxBaseGui.cpp
addons/ofxGui/src/ofxBaseGui.h

Reverts openframeworks/openFrameworks#6539

Revert "ofxGui: Updating events to allow multiwindow functioning"

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

bugfix fixes incorrect pixelScreenCoordScale calc in ofAppGLFWWindow::setup

---

README.md
libs/openFrameworks/3d/ofMesh.inl

Keeping master in sync with patch-release would help clarify branch differences between:
stable (i.e. release) -> patch-release (i.e. bugfix / default) -> master (i.e. dev)

Merge patch-release to master to avoid divergent dev branches

---

.appveyor.yml
addons/ofxGui/src/ofxInputField.cpp
addons/ofxGui/src/ofxSlider.cpp

Fix #6605
fix MSYS2 failing in Debug mode due to strange templates
fix VS failing due to outdated MSYS2 install on appveyor

Issue6605 msys2 ci fails

---

addons/ofxSvg/src/ofxSvg.cpp

Fixes  #6644 
replace PR #6656

switch to C locale to parse SVG in svgtiny

---

scripts/ci/linux64/build.sh
scripts/ci/linux64/install.sh
scripts/ci/upload_of_lib.sh

this produces working lib for the OF server to run nightly builds. 
nightly builds tested and working again.

Build gcc6

---

scripts/linux/archlinux/install_dependencies.sh
scripts/linux/archlinux_armv7/install_dependencies.sh
scripts/linux/chip/install_dependencies.sh
scripts/linux/el6/install_dependencies.sh

fix linux install_dependencies.sh missing ROOT variable
#6542

set ROOT environment variable

---

scripts/dev/create_package.sh

also wrong path for ios pg. 
this was breaking the nightly build.

bugfix for downloader script not being loaded for create package. 

---

libs/openFrameworks/3d/ofNode.cpp

bugfix ofNode::setOrientation euler angles. 

---

THANKS.md

I have made a gender transition, so I would appreciate that my deadname be replaced by my actual first name
here's a pull request for that

deadname removal

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidSoundPlayer.java

Fixes: Bug on Music Player (streaming / looped) audio from ofSoundPlayer in Android Sound Wrapper.
Problem occurs when setting music / checking if playing / seekTo on track that is not yet seen as "isPlaying" by the underlying system and then creates a MediaPlayer exception / bugs out. Android 9/11 tested. 
Fix guards the player a bit more with bool. Force release on Destructor to and I think android needs it
Added Attributes and new Build Constructor for MediaPlayer / Pool (required api change / future )
Fixes: SoundPool for Sound Effects played through ofSoundPlayer (no stream / no loop / multiplay) 
Corruption occurring when loading many sounds to pool, each one would corrupt the pool. Fixed with Build constructor and attributes and guards

Android fix Music Player and SoundEffects

---

libs/openFrameworks/video/ofGstVideoGrabber.cpp

Same request as https://github.com/openframeworks/openFrameworks/pull/6686 but rebased to the _patch-release_ branch as ofTheo requested.

bugfix: segfault on metadata devices - rebased

---

scripts/dev/create_package.sh

this is the second part of addressing this issue:
https://github.com/openframeworks/projectGenerator/issues/262 
Tested on the CI server.

added msys2 projectGenerator packaging.

---

libs/openFrameworks/gl/ofFbo.cpp

Based on this forum post: https://forum.openframeworks.cc/t/emscripten-with-fbo/21780/6
Closes #5663

Fix for emscripten and ofFbo

---

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.h

loadModel now calls load function and shows deprecated message.
I've tested using loadModel and load here, it is OK in my side.
I've seen ident was mixed between tabs and spaces and changed to tabs. 
Let me know if it is not the OF style.
Thanks

loadModel deprecated, using load instead

---

libs/openFrameworks/video/ofVideoPlayer.cpp

so it doesn't increment and decrement use_count.

ofVideoPlayer setPlayer std::move shared_ptr

---

libs/openFrameworks/video/ofVideoGrabber.cpp

Does the same as this other PR, but now for ofVideoGrabber
https://github.com/openframeworks/openFrameworks/pull/6821

ofVideoGrabber setGrabber std::move shared_ptr

---

libs/openFrameworks/graphics/ofGraphics.cpp
libs/openFrameworks/graphics/ofGraphics.h

this PR fixed argument name of ofRotate*Rad from degrees and radians and example code in comment.

Fixed argument and document about ofRotateRad

---

libs/openFrameworks/video/ofAVFoundationPlayer.mm

ofAVFoundationPlayer - redundant code removal

---

libs/openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj/project.pbxproj

this PR fixes compiler warning.

fixed duplicate ofBaseApp.cpp in openFramworksLib.xcodeproj

---

addons/ofxiOS/src/tvOS/ofxtvOSGLKViewController.h
addons/ofxiOS/src/utils/ofxiOSExtras.mm

this PR fixes wrong include guard (maybe come from copy/paste?) and about unknown property `glViewController`.

Fix bugs on tvos

---

libs/openFrameworks/sound/ofSoundPlayer.cpp

so it doesn't increment and decrement use_count.
Tested and everything ok here
same idea of this merged PR https://github.com/openframeworks/openFrameworks/pull/6821

std::move in ofSoundPlayer::setPlayer

---

addons/ofxiOS/src/sound/AVSoundPlayer.m
addons/ofxiOS/src/sound/ofxiOSSoundStream.mm

Here's a pull request to allow your iOS app to use a bluetooth headphone.

ios sound player to allow bluetooth audio

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp

same as https://github.com/openframeworks/openFrameworks/pull/6849

ofGLProgrammableRenderer - remove duplicate include ofMesh.h

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

changed to auto to follow the coding style here

ofAppGLFWWindow.cpp - ofVec3f removal

---

libs/openFrameworks/video/ofAVFoundationGrabber.mm

remove ofVec2f

---

scripts/ci/linuxarmv7l/install.sh

fix secure git url

---

libs/openFrameworks/utils/ofURLFileLoader.cpp

This pull request addresses the issue raised in the below report:
https://www.huntr.dev/bounties/42325662-6329-4e04-875a-49e2f5d69f78/

Enabled SSL verification

---

libs/openFrameworks/utils/ofUtils.cpp

Reverts openframeworks/openFrameworks#6891

Revert "ofUtils.cpp warning  [-Wmisleading-indentation]"

---

addons/ofxOsc/src/ofxOscSender.h

Switch default value of wrapInBundle from true to false.

---

.github/workflows/build-msys2.yml
.github/workflows/build-vs.yml

msys2 needs a different fix - so leaving for now. this updates windows CI to 2019

Fix windows ( VS ) ci

---

libs/openFrameworks/utils/ofSystemUtils.cpp

Replacing deprecated NSFileHandlingPanelOKButton

---

addons/ofxXmlSettings/src/ofxXmlSettings.cpp
addons/ofxXmlSettings/src/ofxXmlSettings.h

use load / save instead
related to https://github.com/openframeworks/openFrameworks/issues/6942

ofxXmlSettings loadFile / saveFile deprecation message

---

libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj

same as 
- https://github.com/openframeworks/openFrameworks/pull/6927/ 
but now for ios

IOS+OFLib - Enable Testability on Debug

---

addons/ofxiOS/src/app/ofAppiOSWindow.h
libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj
scripts/templates/ios/emptyExample.xcodeproj/project.pbxproj

Same as this already merged PR, but now for ios
- https://github.com/openframeworks/openFrameworks/pull/6921

XCode project ios : remove outdated localization settings

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofFileUtils.h

Reverts openframeworks/openFrameworks#6945

Revert "Refactoring ofBuffer::Lines/RLines"

---

libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig

now it can be set by project if needed by this PR
- https://github.com/openframeworks/openFrameworks/pull/6969

CoreOF.xcconfig boostless

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp
libs/openFrameworks/graphics/ofTrueTypeFont.h

Added more utility to ofTrueType. 
Can overload ranges so font loading can be more optimised 
Going to start chipping some of the Android changing into core before that merge can happen

Unicode changes ofTrueTypeFont - Optimised 

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

In this PR I've addressed this warning
```
block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
```
by adding self-> to the variables. I've tested and it is working ok here, but it would be great to have some second opinion from @danoli3 or @2bbb to see if it is OK.

ofAVFoundationMediaPlayer - fix 'self' warning

---

.github/workflows/build-ios-tvos.yml
.github/workflows/build-macos.yml
libs/openFrameworksCompiled/project/tvOS/CoreOF.xcconfig
scripts/ci/tvos/build.sh

update macos to 12.0 in CI closes #7036

---

.github/workflows/build-android.yml
.github/workflows/build-emscripten.yml
.github/workflows/build-ios-tvos.yml
.github/workflows/build-linux.yml
.github/workflows/build-macos.yml
.github/workflows/build-msys2.yml
.github/workflows/build-vs.yml

this is so changes to examples don't trigger the CI ( as they CI doesn't try and compile the examples )

ignore example folders in CI

---

examples/3d/meshFromCameraExample/src/ofApp.cpp

Changed so the camera does not spin too fast.

Map degrees to radians for glm conversion

---

examples/gl/transformFeedbackExample/bin/data/pointSprite.frag
examples/gl/transformFeedbackExample/bin/data/pointSprite.vert
examples/gl/transformFeedbackExample/bin/data/vert.glsl
examples/gl/transformFeedbackExample/src/ofApp.cpp
examples/gl/transformFeedbackExample/src/ofApp.h

Point sprite render shader

---

libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp

fix algeterror

---

examples/computer_vision/opencvPeopleDetection/addons.make
examples/computer_vision/opencvPeopleDetection/src/main.cpp
examples/computer_vision/opencvPeopleDetection/src/ofApp.cpp
examples/computer_vision/opencvPeopleDetection/src/ofApp.h
examples/computer_vision/opencvPeopleDetection/src/peopleDetector.h

Examples: opencv people detection example

---

.gitmodules

this way we install the latest from git with the latest versions of apothecary and projectGenerator

Submodules to latest

---

examples/computer_vision/opencvImageClassification/addons.make
examples/computer_vision/opencvImageClassification/bin/data/classes.txt
examples/computer_vision/opencvImageClassification/src/main.cpp
examples/computer_vision/opencvImageClassification/src/ofApp.cpp
examples/computer_vision/opencvImageClassification/src/ofApp.h
examples/computer_vision/opencvImageClassification/src/yolo5ImageClassify.h

This requires OpenCV 4.6. 
Will do a separate PR to apothecary to update OF to 4.6.

Examples: OpenCV image classification example using Yolo5

---

scripts/dev/download_libs.sh

worked ok here locally let's see how it works on actions

download_libs.sh from apothecary nightly

---

examples/shader/07_fboAlphaMask/src/main.cpp

Just got the new nightly and couldn't compile this. Simple fix!

Add missing semicolon.

---

libs/openFrameworks/types/ofBaseTypes.cpp

This fixes an shadows not working on Windows.

Set shadow matrix on shader.

---

libs/openFrameworks/app/ofMainLoop.cpp

fixes a crash on windows when you close the window

swapping around closing the window before you delete it

---

scripts/dev/create_package.sh

vscode templates includes for all platforms that can use them

---

addons/ofxGui/src/ofxInputField.cpp
addons/ofxGui/src/ofxSlider.cpp

This pull request fixes the ofxGUI examples (when used with Emscripten).

Emscripten ofxgui fix

---

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp

See 3DPrimitivesExample (f key).

fix emscripten fullscreen called from of

---

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp

This fixes special keys in Emscripten. Maybe I missed some special Keys, but most of them are working now. And maybe there is a better way to implement it (send the id directly to OF?).

Emscripten special keys fix

---

examples/gl/slowFastRenderingExample/src/ofApp.cpp
libs/openFrameworks/utils/ofConstants.h

Emscripten slowFastRenderingExample fix

---

examples/3d/modelNoiseExample/src/ofApp.cpp

Fixes the desktop version for me, too.

modelNoiseExample fix

---

addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.cpp

Adds the textures needed to ofMaterial for the built in PBR renderer to be enabled. 
Thanks to @NickHardeman for the changes

allow PBR renderer for models that have it

---

libs/openFrameworks/gl/ofCubeMap.cpp
libs/openFrameworks/gl/ofCubeMap.h

Should fix issues related to this pull request #7222

Convenience functions for cube maps

---

libs/openFrameworks/communication/ofArduino.cpp

remove deprecated sprintf

---

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp
addons/ofxEmscripten/src/ofxAppEmscriptenWindow.h

Not really sure, how to implement this right (but it outputs the y wheel value - not sure what the x wheel and z wheel value is). So this is more a suggestion than a pr...  y wheel value is -53/53 with chrome and -103/103 with firefox, so something with the scaling is not correct yet ( x wheel is -0/-0, z wheel 0/0).
Here is some information about the wheel event: https://emscripten.org/docs/api_reference/html5.h.html

Emscripten wheel event

---

scripts/templates/ios/emptyExample.xcodeproj/project.pbxproj

With a new PR on projectGenerator it will address the issue mentioned in the forum here
https://forum.openframeworks.cc/t/ofxpoco-not-working-with-nightly-builds/40916
to be merged together with this
https://github.com/openframeworks/projectGenerator/pull/315

iOS template fix

---

examples/ios/audioOutputExample/src/ofApp.h
examples/ios/audioOutputExample/src/ofApp.mm
examples/ios/soundPlayerExample/src/ofApp.mm

now it uses:
ofSoundStream object
ofSoundStreamSettings
audioOut(ofSoundBuffer & buffer)

audioOutputExample changes

---

libs/openFrameworks/gl/ofGLUtils.cpp

This makes float textures work with Emscripten.

Emscripten float textures

---

libs/openFrameworks/gl/ofGLUtils.cpp
libs/openFrameworks/gl/ofGLUtils.h
libs/openFrameworks/gl/ofMaterial.cpp
libs/openFrameworks/gl/ofMaterial.h
libs/openFrameworks/gl/ofShadow.cpp
libs/openFrameworks/gl/ofShadow.h
libs/openFrameworks/gl/shaders/shadow.glsl

Will submit a separate PR for the shadow example with a few minor updates.

Shadow support for emscripten

---

examples/gl/shadowsExample/src/main.cpp
examples/gl/shadowsExample/src/ofApp.cpp

A few small updates to account for emscripten support.

Update to shadows example

---

examples/gl/pointsAsTexturesExample/bin/data/shaders_gles/shader.frag
examples/gl/pointsAsTexturesExample/bin/data/shaders_gles/shader.vert
examples/gl/pointsAsTexturesExample/src/ofApp.cpp
libs/openFrameworks/gl/ofGLUtils.cpp

This PR enables point sprites and gl_PointSize (but only in the shader). The example works well now.

Emscripten pointsAsTexturesExample 2

---

addons/ofxAssimpModelLoader/src/ofxAssimpAnimation.cpp
addons/ofxAssimpModelLoader/src/ofxAssimpAnimation.h
addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.cpp
addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.h
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.h
addons/ofxAssimpModelLoader/src/ofxAssimpTexture.cpp
addons/ofxAssimpModelLoader/src/ofxAssimpTexture.h
addons/ofxAssimpModelLoader/src/ofxAssimpUtils.h

space to tabs
trim trailing whitespace

ofxAssimpModelLoader - spaces to tabs

---

examples/gl/materialPBR/src/ofApp.cpp

Update materialPBR example and cube map image

---

examples/gl/multiTexture3dExample/bin/data/shaders/material.frag
examples/gl/multiTexture3dExample/bin/data/shaders/material.vert
examples/gl/multiTexture3dExample/src/ofApp.cpp
examples/gl/multiTexture3dExample/src/ofApp.h

Should also work with Emscripten.

Added support for ofMaterial shader

---

addons/ofxOpenCv/src/ofxCvConstants.h

Closes https://github.com/openframeworks/openFrameworks/issues/7305

ofxOpenCv - undef NO

---

addons/ofxiOS/src/utils/ofxiOSCoreHaptics.h
addons/ofxiOS/src/utils/ofxiOSCoreHaptics.mm
examples/ios/CoreHapticsExample/src/main.mm
examples/ios/CoreHapticsExample/src/ofApp.h
examples/ios/CoreHapticsExample/src/ofApp.mm
libs/openFrameworksCompiled/project/ios/CoreOF.xcconfig
libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj

Basic implementation with example to control frequency and amplitude of iOS devices haptic generator.
#changelog #iOS

ofxiOSCoreHaptics

---

addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.cpp
libs/openFrameworks/sound/ofSoundBaseTypes.h

let's see if it compiles well in all platforms.

ofSoundBaseTypes unneeded include

---

scripts/templates/ios/src/ofApp.h
scripts/templates/ios/src/ofApp.mm
scripts/templates/osx/src/ofApp.cpp
scripts/templates/osx/src/ofApp.h

note that this covers only macOS and iOS -- I presume the ofApp.h and ofApp.c could be propagated to all others but Android?

Project template: adds missing inherited boilerplate (and override)

---

tests/math/ofNodeRegressionTests/src/main.cpp

tests/math/ofNodeRegressionTests -> orbit to orbitDeg

---

libs/openFrameworks/gl/ofCubeMap.cpp

ofCubeMap.cpp - remove unused bAllPixelsCreated

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofFileUtils.h

meant to complete a missing change from this PR - https://github.com/openframeworks/openFrameworks/pull/7110
And help this transition: https://github.com/openframeworks/projectGenerator/pull/318

listDir fix of::filesystem::path

---

libs/openFrameworks/app/ofMainLoop.cpp
libs/openFrameworks/app/ofMainLoop.h
libs/openFrameworks/app/ofWindowSettings.h

removing ofConstants.h, moving to cpp file
moving logic to cpp file
removing ofConstants.h from ofWindowSettings.h, not needed there but needed here.
Untangling includes
some minor format fixes.

ofMainloop cleanup

---

addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.h
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.h
libs/openFrameworks/gl/ofMaterial.h
libs/openFrameworks/types/ofColor.h
libs/openFrameworks/utils/ofConstants.h
libs/openFrameworks/utils/ofFileUtils.h

closes https://github.com/openframeworks/openFrameworks/issues/7376

Assimp fix model scale issue - GLM_FORCE_CTOR_INIT

---

examples/gl/multiTexture3dExample/bin/data/shaders/material.frag
examples/gl/multiTexture3dExample/bin/data/shaders/shader.frag
examples/gl/multiTexture3dExample/src/ofApp.cpp
examples/gl/multiTexture3dExample/src/ofApp.h

Fix for mouse position in the multiTexture3dExample

---

libs/openFrameworksCompiled/project/osx/config.osx.default.mk

closes https://github.com/openframeworks/openFrameworks/issues/7384#issuecomment-1470418045

osx make c++17

---

examples/gl/multiTextureShaderExample/src/main.cpp
examples/gl/multiTextureShaderExample/src/ofApp.cpp

Updates multiTextureShaderExample.

Fixes for programmable renderer and open gl es

---

libs/openFrameworks/utils/ofUtils.h

closes https://github.com/openframeworks/openFrameworks/issues/7390

ofUtils - remove pragma clang diagnostic

---

libs/openFrameworks/3d/of3dUtils.h
libs/openFrameworks/3d/ofEasyCam.h
libs/openFrameworks/app/ofWindowSettings.h
libs/openFrameworks/graphics/ofGraphics.h
libs/openFrameworks/graphics/ofGraphicsBaseTypes.cpp
libs/openFrameworks/graphics/ofPixels.cpp
libs/openFrameworks/math/ofMatrix4x4.h
libs/openFrameworks/math/ofQuaternion.cpp
libs/openFrameworks/math/ofVec4f.cpp
libs/openFrameworks/math/ofVectorMath.h
libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp
libs/openFrameworks/sound/ofSoundBuffer.cpp
libs/openFrameworks/sound/ofSoundPlayer.cpp

meant to fix some issues introduced by this PR
https://github.com/openframeworks/openFrameworks/pull/7403
will be merge as soon as the tests finish and pass

glm - fix CTOR

---

libs/openFrameworks/gl/ofGLBaseTypes.h
libs/openFrameworks/graphics/ofGraphicsBaseTypes.h
libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk

I wonder why the fixed destructors relate specifically to the c++20 standard, they seem wrong in general to me

maintained C++20 compatibility for Linux (#7268)

---

libs/openFrameworks/app/ofMainLoop.cpp
libs/openFrameworks/app/ofMainLoop.h

related - https://github.com/openframeworks/openFrameworks/commit/0c02995693c44439a635d085fd87f155f82bd832

revert addWindow functionality to be in .h file

---

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp

I've updated the code to fit the other ifs style.

ofxAssimpModelLoader - unused col warning fix

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

the feature was added in 3.1 but the conditional is wrong
https://www.glfw.org/docs/3.1/group__input.html#ga41291bf15dd3ff564b3143aa6dc74a4b

fix conditional for GL drop

---

libs/openFrameworks/types/ofColor.cpp
libs/openFrameworks/types/ofColor.h

been bothering me fo a while...

darkOrange typo

---

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

so we don't need to edit the template if we add / remove files from the core.
other advantage is the template folder gets a little bit lighter if we have to edit it

XCode - openFrameworks files by reference (blue folder)

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs

now defaults to C++17 (supersedes #7453)

update qtcreator to C++17

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs

exclude fmod from linux qbs

---

libs/openFrameworks/gl/ofGLUtils.cpp

Please see the issue #7466 prior to merging!

Fix defines in ofGLUtils #7466

---

libs/openFrameworks/communication/ofArduino.cpp
libs/openFrameworks/gl/ofMaterial.cpp
libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofSystemUtils.cpp
libs/openFrameworks/utils/ofURLFileLoader.cpp
libs/openFrameworks/video/ofDirectShowGrabber.cpp
libs/openFrameworks/video/ofDirectShowPlayer.cpp

fix various MSYS2 warnings reported in #6929

Msys2 fix warnings

---

libs/openFrameworks/sound/ofAVEngineSoundPlayer.mm

fix warning with replacing instance variable to @property

---

libs/openFrameworks/sound/ofSoundStream.cpp

See issue #7377 
And forum post: https://forum.openframeworks.cc/t/emscripten-no-videoplayer-linux-mint-manjaro/41710/5 
Not a great solution so should be fixed for 0.12.0

temp fix for broken emscripten window

---

libs/openFrameworks/graphics/ofCairoRenderer.cpp
libs/openFrameworks/graphics/ofCairoRenderer.h

good to go. updated with @artificiel regards to comparing extension to fs::path in another PR

Cairo update to Filesystem

---

libs/openFrameworks/utils/ofConstants.h
libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj
scripts/templates/vs/emptyExample.vcxproj

Add mediafoundation to OF VS project and switch to 142 ( VS 2019 ) 

---

.github/workflows/build-emscripten.yml
.github/workflows/build-ios-tvos.yml
.github/workflows/build-linux.yml
.github/workflows/build-macos.yml
.github/workflows/build-msys2.yml
.github/workflows/build-vs.yml

Avoids actions running twice when part of a PR. 
Closes #7491

Github Actions only runs on forked repo if it is not a pull request

---

libs/openFrameworks/utils/ofConstants.h

Just adding OF_OS_WINDOWS to ofConstants. so things can be incrementally updated in other ongoing PRs

OF_OS_WINDOWS

---

libs/openFrameworks/video/ofMediaFoundationPlayer.cpp
libs/openFrameworks/video/ofMediaFoundationPlayer.h

Fix to correctly set the pixels to the requested OF pixel format.

Media Foundation Video Player fix pixels

---

scripts/ci/vs/install.sh
scripts/dev/create_package.sh

Once this is merged this should fix missing addons in the CI testing.

Bugfix vs pg

---

scripts/linux/ubuntu/install_dependencies.sh

add missing gstreamer packages for Ubuntu 22.04 and newer closes #7516

add missing gstreamer packages for Ubuntu 22.04 and newer closes #7516

---

libs/openFrameworksCompiled/project/linux64/config.linux64.default.mk

so it runs ok with c++17 and filesystem in Ubuntu 16.04

Update linux64 - filesystem to run ok with Ubuntu 16.04

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

more description on this issue
closes - https://github.com/openframeworks/openFrameworks/issues/6895

fix macOS issue where fullscreen activation is broken after maximizing with green button

---

addons/ofxEmscripten/libs/html5audio/include/html5audio.h
addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js
addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js
addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.cpp
addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.h
addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.cpp
addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.h

The main change is, that the audioPlayer now only creates one audio element for each player and not for each audio file that is loaded. Some other fixes and some cleanup too...

Emscripten player update

---

addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js

this changes makes frames come in for the grabber 
for 0.12.1 #7588

Bugfix emscripten webcam not working

---

scripts/dev/download_libs.sh

- Adds -b (bleeding edge) to download_libs and will download #bleeding git tag from apothecary GitHub packages

Enable / Disable Bleeding Edge Libraries in download_libs

---

scripts/templates/vscode/.vscode/c_cpp_properties.json
scripts/templates/vscode/emptyExample.code-workspace

removing addons folder from project (individual addons will be added)
c_cpp_properties.json - spaces to tabs and minor indent changes
submodules to latest

update vscode templates

---

examples/gl/materialPBRAdvanced/bin/data/shaders/main.vert
examples/gl/materialPBRAdvanced/src/ofApp.cpp
examples/gl/textureBufferInstancedExample/bin/data/vert.glsl
examples/gl/textureBufferInstancedExample/src/ofApp.cpp
examples/gl/textureBufferInstancedExample/src/ofApp.h
libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofMaterial.cpp
libs/openFrameworks/gl/ofMaterial.h
libs/openFrameworks/gl/ofMaterialBaseTypes.h
libs/openFrameworks/gl/ofShadow.cpp
libs/openFrameworks/gl/ofShadow.h

```
string vname = "shaders/main.vert";
ofBuffer vbuffer = ofBufferFromFile(vname);
string fname = "shaders/main.frag";
ofBuffer fbuffer = ofBufferFromFile(fname);
if( vbuffer.size() && fbuffer.size() ) {
matLogo.setShaderMain(vbuffer.getText(), GL_VERTEX_SHADER, "main.vert");
matLogo.setShaderMain(fbuffer.getText(), GL_FRAGMENT_SHADER, "main.frag");
// Adds a `#define OF_SHADOW_DEPTH_PASS` when setup via the shadow class
matLogo.setDepthShaderMain(vbuffer.getText(), "main.glsl");
}
```

ofMaterial with ability to set depth shader

---

libs/openFrameworks/gl/ofMaterial.cpp
libs/openFrameworks/gl/ofMaterial.h

Related to this forum post
https://forum.openframeworks.cc/t/how-to-clear-or-remove-a-specific-texture-from-an-ofmaterial-object/42595/3

Material with ability to remove textures

---

libs/openFrameworks/graphics/ofImage.cpp

Load 16 bit grayscale images downsampled to 8bit

---

libs/openFrameworks/utils/ofThread.h

this file has a very different "tone" than docs in general, and reads almost like an essay on threading...
perhaps another round of clarification is in order, but in any case, this closes #4983

slight simplification of ofThread docs — specifically removal of references to poco

---

libs/openFrameworks/video/ofMediaFoundationPlayer.cpp
libs/openFrameworks/video/ofMediaFoundationPlayer.h

Adding license from https://github.com/axjxwright/AX-MediaPlayer/

Added mit-license to ofMediaFoundationPlayer

---

libs/openFrameworks/3d/ofNode.cpp
libs/openFrameworks/3d/ofNode.h

Update ofNode function names

---

libs/openFrameworks/gl/shaders/phong.frag

Updated frag with correct argument names

Fix for phong.frag perturb normal function

---

libs/openFrameworksCompiled/project/emscripten/config.emscripten.default.mk

Emscripten: push build down in 'em' so name does not conflict with linux bin

---

scripts/templates/osx/Project.xcconfig
scripts/templates/osx/openFrameworks-Info.plist

removed the app category entry in .plist
and added in xcconfig

App Cateogory : Games

---

addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js
addons/ofxEmscripten/src/ofxEmscriptenSoundStream.h

Just a small change for making .mp3 work...

Emscripten mp3 header fix

---

libs/openFrameworks/app/ofAppRunner.h
libs/openFrameworks/events/ofEvents.cpp
libs/openFrameworks/events/ofEvents.h
libs/openFrameworks/utils/ofUtils.cpp

A couple of functions to pull info about internal state that helped diagnose #7752

ofFunctions to retrieve information about internal render state

---

.github/workflows/build-macos.yml
scripts/ci/osx/build.sh

This PR removes unused lines in caching folders
Makes a more broad criteria for cache hit in compiled sources, so the cache is used more often

Github Actions - macOS cache updates test

---

examples/gl/vboMeshDrawInstancedExample/bin/data/shaders/instanced.frag
examples/gl/vboMeshDrawInstancedExample/bin/data/shaders/instanced.vert
examples/gl/vboMeshDrawInstancedExample/src/ofApp.h

Relies on #7808 
https://nickhardeman.com/temp/OFExamples/vboMeshDrawInstancedExample/

Fix vbo instance example to run with Emscripten

---

libs/openFrameworks/utils/ofConstants.h
libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig

Bumping some specifications here, removing c++11 exclusive code

C++14 minimum

---

libs/openFrameworks/graphics/ofGraphics.cpp
libs/openFrameworks/graphics/ofGraphics.h

Explicit functions for different ofColor types.
Related to #7780

ofSetColor functions without Template

---

libs/openFrameworks/video/ofGstVideoGrabber.cpp

helpful for pulling color image from azure kinect on linux.

Add support for image/jpeg in GST Grabber.

---

.github/workflows/build-msys2.yml
scripts/msys2/install_dependencies.sh

this is a welcome one. 
msys2 builds slashed down to less than 7 min

[actions] msys2 ccache

---

scripts/dev/create_package.sh

no sed use default platform selector in PG - settings json is populated automatically or by last user choice setting after first use rather than reset each time to set type in settings.json static

fix nightly -  projectGenerator sed

---

scripts/dev/download_libs.sh

Changes to dev download scripts 
- macOS 3 bundles
- VS to 2 bundles
- other Apple targets 3 bundles

Latest Libs - applies to latest bleeding scripts

---

.github/workflows/build-ios-tvos.yml
.github/workflows/build-vs2022.yml
.github/workflows/manual-nightly.yml

iOS to macOS 13 and Xcode 15.2
and some github actions version bump

[actions] update

---

scripts/linux/ubuntu/install_dependencies.sh

Ubuntu 24.04 - remove libgconf-2-4

---

libs/openFrameworks/sound/ofAVEngineSoundPlayer.h
libs/openFrameworks/sound/ofAVEngineSoundPlayer.mm

tests won't catch anything here. I'll test locally and merge

ofAVEngineSoundPlayer fix of::fs

---

libs/openFrameworks/math/ofMath.h
tests/math/minmaxTests/addons.make
tests/math/minmaxTests/src/main.cpp

as discussed in #7940
closes #7940

ofMin / ofMax

---

scripts/ci/linux64/build.sh
scripts/ci/linux64/run_tests.sh
scripts/ci/linuxrpi/build.sh
scripts/ci/msys2/build.sh
scripts/ci/msys2/run_tests.sh
scripts/ci/osx/run_tests.sh
scripts/ci/vs/run_tests.bat

and make using 2 cores.
group / endgroup will make it easier to navigate errors there.

Github actions scripts with group / endgroup

---

.github/workflows/actions/build-emscripten.yml
.github/workflows/actions/build-linux64.yml
.github/workflows/actions/build-rpi.yml
.github/workflows/of.yml

beta released today
https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/

[actions] update ubuntu 24.04

---

.github/workflows/manual-nightly.yml
.github/workflows/nightly-linux64.yml

aptitude via apt
ubuntu 24.04
ccache

[actions] more changes nightly and manual nightly

---

addons/ofxVectorGraphics/src/ofxVectorGraphics.cpp
addons/ofxVectorGraphics/src/ofxVectorGraphics.h

changes string to std::string.

Vector graphics fix

---

scripts/templates/vscode/.vscode/tasks.json

it is already working, but obviously there is a better way of invoking the .exe file in windows.
it simplifies a little bit the template by using some repeated configurations as global.
it is possible to have settings by platform, so it was possible to incorporate some suggestions from
https://forum.openframeworks.cc/t/vs-code-setup-guide-now-up/42959/29

[WIP] VS Code, make it run by default in Windows

---

addons/ofxOsc/src/ofxOscReceiver.h
addons/ofxOsc/src/ofxOscSender.h

remove auto-setup on default constructors

ofxOsc: no setup on default

---

libs/openFrameworks/3d/ofEasyCam.h
libs/openFrameworks/events/ofEvents.h
libs/openFrameworks/gl/ofBufferObject.cpp
libs/openFrameworks/gl/ofGLProgrammableRenderer.h
libs/openFrameworks/gl/ofMaterial.cpp
libs/openFrameworks/gl/ofShader.cpp
libs/openFrameworks/graphics/ofPolyline.inl
libs/openFrameworks/math/ofVec3f.h
libs/openFrameworks/math/ofVectorMath.h
libs/openFrameworks/sound/ofAVEngineSoundPlayer.h
libs/openFrameworks/sound/ofSoundBuffer.h
libs/openFrameworks/sound/ofSoundPlayer.cpp
libs/openFrameworks/types/ofColor.h
libs/openFrameworks/utils/ofConstants.h
libs/openFrameworks/utils/ofLog.h
libs/openFrameworks/utils/ofUtils.h
libs/openFrameworks/video/ofDirectShowPlayer.h
libs/openFrameworks/video/ofMediaFoundationPlayer.h
libs/openFrameworks/video/ofVideoPlayer.h

only removing includes already commented out

.h removal cleanup

---

scripts/vs/download_latest_libs_x64.sh

Also, checked if just x64 libs work with other targets now in the project and all works

VS bash script download latest x64 only libraries 

---

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

goes together with this PG PR
https://github.com/openframeworks/projectGenerator/pull/503

update addons folder in xcode template

---

scripts/dev/download_pg.sh

Apothecary to latest
ProjectGenerator to latest

Submodules sync and pg fix paths

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

Closes 
https://github.com/openframeworks/openFrameworks/issues/7951

macOS video player thread priority fix

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp

It renders the same as openGL ES using GL_LINES and is not visually the same as polygonMode.
Fixes #7833

Fix for Emscripten not being able to render wireframe. 

---

libs/openFrameworks/video/ofMediaFoundationPlayer.cpp

Fix for set volume function in Media Foundation player.

---

.gitignore
scripts/dev/create_package.sh
scripts/osx/snapshotAllExamples.sh

- Fixes :nightly package: missing .gitignore for template 
- Fixes https://github.com/openframeworks/openFrameworks/issues/6021 project generator added elements to examples.
+ Added osx script to test all graphics projects / setup via project generator if not, build and run each example
- Fixes: https://github.com/openframeworks/projectGenerator/issues/477

Fix: nightly packages / gitignore template and fie

---

scripts/dev/download_libs.sh
scripts/dev/download_pg.sh
scripts/osx/xcode_project.sh

Fixes for permission issues / copy command line to directory

download pg libs - copy with attributes

---

.github/workflows/manual-nightly.yml
.github/workflows/of.yml
libs/openFrameworks/sound/ofRtAudioSoundStream.cpp
libs/openFrameworks/sound/ofRtAudioSoundStream.h
libs/openFrameworks/utils/ofConstants.h
scripts/ci/package_builds.sh
scripts/dev/create_package.sh
scripts/dev/nightlybuilds.sh
scripts/emscripten/download_latest_libs.sh

Also fix:
```
#define OF_NO_FMOD
#ifndef OF_NO_FMOD
#define OF_NO_FMOD
#endif
```

nightly packages - msys2 add clang64, ucrt64, add linux arm64 linuxaarch64 

---

libs/openFrameworks/utils/ofConstants.h
libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj

iOS Latest Libraries Update 

---

libs/openFrameworksCompiled/project/osx/config.osx.default.mk

closes: https://github.com/openframeworks/openFrameworks/issues/8029

Update makefiles to handle changes in info.plist file

---

addons/ofxAssimp/addon_config.mk
addons/ofxAssimpModelLoader/addon_config.mk

addons changes to:
```addons/ofxAssimp/addon_config.mk```
```addons/ofxAssimpModelLoader/addon_config.mk```

ofxAssimpModelLoader - make file fixes for macos / ios

---

addons/ofxSvg/addon_config.mk

closes https://github.com/openframeworks/openFrameworks/issues/8077

Fix ofxSvg libs for macOS

---

addons/ofxAssimpModelLoader/addon_config.mk

this fixes for me assimp path. and group two osx entries in one
closes https://github.com/openframeworks/openFrameworks/issues/8075
cc: @danoli3

fix assimp libs path

---

libs/openFrameworks/utils/ofJson.h

fix nlohmann json include path

---

scripts/dev/downloader.sh

- downloader fixes for spaces in URL passed after or before / checks fix url error issues. 
- Fix http2 -V check (cURL)
- verbose logs disabled
- fix for trailing space in con close

[script] dev downloader fixes

---

libs/openFrameworks/app/ofAppEGLWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/events/ofEvents.h

Updated PR for https://github.com/openframeworks/openFrameworks/pull/5592

Adding support for OF_KEY_SPACE - @Makio135 #5592

---

addons/ofxOsc/libs/oscpack/src/ip/win32/UdpSocket.cpp

make MAX_BUFFER_SIZE logic to same as posix on UdpSocket in ofxOsc 

---

libs/openFrameworks/types/ofParameterGroup.cpp

no code changes;
naming, format, etc.

slight cleanup of ofParameterGroup.cpp [please merge for future work]

---

libs/openFrameworks/ofMain.h
libs/openFrameworks/types/ofParameter.h
libs/openFrameworks/utils/ofRandomDistributions.h

Subsequent changes for this PR https://github.com/openframeworks/openFrameworks/pull/8153

iso646.h in windows — and / or templates fix

---

scripts/dev/download_libs.sh
scripts/dev/downloader.sh

- fix nightly / zip path for latest / etc (master branch issue)
Fix the downloader issue of reporting error with urls:
```
[openFrameworks downloader v4.3.2] ... 
[downloader] Invalid URL: [1]
```

Github Actions update - for master

---

libs/openFrameworks/utils/ofRandomDistributions.h

fixes compile issue with linux debian

#include <optional> in ofRandomDistributions.h

---

.github/workflows/of.yml
addons/ofxGui/src/ofxGuiGroup.cpp
addons/ofxGui/src/ofxGuiGroup.h
addons/ofxGui/src/ofxPanel.cpp
addons/ofxGui/src/ofxPanel.h
addons/ofxGui/src/ofxSliderGroup.cpp
libs/openFrameworks/communication/ofSerial.cpp

it can close 
- https://github.com/openframeworks/openFrameworks/issues/8220

[msys2] - ofxGui avoid fs::path / string implicit conversion. fix for __builtin_va_arg_pack issue in swprintf

---

scripts/dev/downloader.sh

- Fix sed issue on Windows ARM64 bash for downloader

downloader [ 4.3.4 ~ 4.4.0 ]

---

libs/openFrameworks/gl/ofMaterial.h

Add missing include

---

scripts/templates/ios/toJson.command
scripts/templates/macos/toJson.command
scripts/templates/osx/toJson.command

After editing one can run toJson.command inside the template folder.
.command extension can be used as a normal app in macOS (double click on finder to run)

PR to help editing XCode templates (macos, osx, ios)

---

scripts/osx/xcode_project.sh

Fixes #https://github.com/openframeworks/openFrameworks/issues/8276

macOS Code sign app

---

scripts/osx/xcode_project.sh

- fixed broken if for dylib
- archiving working not polluting target with data folder breaking plist
- bash tabs to spaces
Fixes #https://github.com/openframeworks/openFrameworks/issues/8276#issuecomment-2685493417

xcode project script fixes

---

examples/ios/CoreLocationExample/src/ofApp.mm

fix(iOS): adjustments to layout of Location example + deprecations

---

addons/ofxAssimp/addon_config.mk
addons/ofxAssimpModelLoader/addon_config.mk

Fixes for iOS assimp addon device target:
https://github.com/openframeworks/openFrameworks/issues/8316

assimp ios addon_config

---

examples/3d/assimp3DModelLoaderExample/src/ofApp.cpp

assimp3DModelLoaderExample path to string conversion on Windows fix.

---

addons/ofxPoco/addon_config.mk

remove defined locations where not needed 
- android
- osx
- tvos
- iOS

ofxPoco mk

---

libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj

There were missing files on iOS Core project. 
closes https://github.com/openframeworks/openFrameworks/issues/8315

_OBJC_CLASS_$_AVFoundationVideoPlayer fix

---

libs/openFrameworks/utils/ofFpsCounter.cpp

Fixes: https://github.com/openframeworks/openFrameworks/issues/8271

Fix ofFpsCounter value offset update(now)

---

addons/ofxOsc/src/ofxOscReceiver.cpp

tweak(ofxOscReceiver): logNotice -> Verbose

---

libs/openFrameworks/communication/ofSerial.cpp
libs/openFrameworks/communication/ofSerial.h

closes https://github.com/openframeworks/openFrameworks/issues/8408

serial error codes fix - back to public

---

examples/input_output/imageLoaderWebExample/src/ofApp.cpp
libs/openFrameworks/utils/ofURLFileLoader.cpp

fix ssl loading without generating certs

---

libs/openFrameworks/gl/ofMaterial.cpp

since light->right is already a glm::vec3

ofMaterial - unnecessary toGlm

---

examples/gl/materialPBRExample/src/ofApp.cpp

Forum post reporting the issue:
https://forum.openframeworks.cc/t/materialpbrexample/44607/2

Change material pbr example to ofCubeMapSettings.

---

addons/ofxAssimp/src/Source/ofxAssimpSrcScene.cpp

As outlined in this forum post:
https://forum.openframeworks.cc/t/problem-with-ofxassimp-fbx-models/44649

Fix import of fbx pivots, for Mixamo models.
