openframeworks/openFrameworks

libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj
libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj.filters

* adds winmm.lib as a linker dependency (needed for high precision timer)
* enables multi-core compilation
* adds `ofMainLoop` and `ofWindowSettings` to openFrameworks project file

windows specific fixes to project files

---

examples/gl/computeShaderParticlesExample/src/ofApp.cpp

* makes sure to issue the right number of workgroups + add comment outlining reasoning
* use GL_STREAM_DRAW as usage hint - although this does not make a difference on my driver implementation, but is more correct, since the particle data is constantly read and written on the GPU
* adds key toggle for fullscreen

fixes some minor issues with the compute shader particles example

---

libs/openFrameworks/gl/ofVbo.cpp

+ if the buffer does not give us a stride, we try to calculate based on the data size and the number of coordinates (we assume each coordinate has the size of a float == 4 bytes)
+ if the buffer gives us a stride we use the attribute stride to calculate the total number of vertices.

fix calculation of totalVerts for VBOs in setVertexBuffer()

---

libs/openFrameworks/app/ofAppGlutWindow.cpp

Replaces ofAppPtr by instance->events() as glfw window does it.
+ this only affects Windows builds, as it only appears within the TARGET_WIN32 #ifdef
@arturoc, I hope this is the right way to make sure the right window instance receives the drag event - I copied GLFW window behaviour.

fix TARGET_WIN32 compile error in ofAppGlutWindow

---

addons/ofxNetwork/src/ofxTCPManager.cpp
addons/ofxNetwork/src/ofxTCPManager.h

Hi, I haven't submitted a PR before- so let me know when I'm off track, and if the coding style is wrong. I opened an issue here https://github.com/openframeworks/openFrameworks/issues/2515 which describes the problem.
I have set the connect timeout to 5 seconds by default. Not sure what the preferred time should be (and whether to use a #define for this)? But having no timeout, eg. OF_TCP_DEFAULT_TIMEOUT is not recommended as this would not solve the issue (blocking for 90 seconds then crashing when connecting to invalid ip). 
I have only tested on OSX.
Thanks OF,
Trent

Feature tcpmanager connect timeout

---

libs/openFrameworks/gl/ofBufferObject.cpp

After 6370ffda1040845e102efec07ad95bf11773eb82 glew.h was included in ofBufferObject.cpp. Because of that I couldn't get OFX to compile for Android or iOS. I think the user who reported bug #3541 was affected by this as well. This macro check seems to fix it.

Don't include glew for Android or iOS (Fixes #3541)

---

scripts/dev/create_package.sh

On OS X, tar will include ._ files in the archive unless COPYFILE_DISABLE is set.

Exclude ._ files from package on OS X.

---

addons/ofxAssimpModelLoader/scripts/formulas/assimp.sh

Cherry Picked from @ofTheo 's https://github.com/openframeworks/openFrameworks/tree/apothecary-assimp without any binaries.
Pure Formula only.
iOS update: Removed ```armv7s```, switched to compiling with assimps makefile for building for iOS

Apothecary Formula - ofxAssimpModelLoader update

---

libs/openFrameworks/math/ofMath.cpp

Looks like #3544 pulled in some + chars in ofMath, breaking compilation (I guess a copy+paste from a git diff?).
`<joke>`
There's too much math in ofMath. This makes there be less math.
`</joke>`
ping @ofTheo / @manish-juneja

Remove errant + chars in ofMath

---

libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj

When compiling the ```iOS+OFLib``` the ```SDKROOT``` was not being defined so it was having all sorts of trouble with the core framework locations (which require this variable).
It was falling into the ```/System/Library/Frameworks``` which is incorrect, although it had some for OS X with the same name, always failed on iOS specific frameworks.
This fix just defines the SDKROOT and all goes back to normal iOS SDK location.

Fixes Missing SDKROOT for iOS+OFLib

---

scripts/ios/template/emptyExample.xcodeproj/project.pbxproj

See issue: #1758
This follows the same method that Xcode uses to copy files to App
packages.
- Will not copy files if already on destination (this will increase
performance).
- If file has been updated and already exists on the target app, you
will need to clean build (same workflow as Xcode native adding
resources).
- Tested working with iOS projects to simulator and device.
Currently CP copys the files to the .app folder everytime, updating the modification datetime and therefore causing the copy times to devices every single build. So say you build a project to your iPad... every single time you have to transfer all the files in your data folder to the target device, even if nothing has changed.
The new method will copy a new file once, like Xcode, to the .app and then not update it …

Fixes: #1758 iOS use "rysnc" rather than "cp" when copying "bin/data" files

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp

This fixes #3518.
---
Using the Programmable GL Renderer, `GL_POLYGON_MODE` would lead to unexpected behaviour when using the following choreography of `ofFill`, `ofMesh`, and "naked" `ofVbo`s:
ofFill();
ofPushStyle(); // 0
ofNoFill();
ofDrawRectangle(10,10,10,10); // 1, 2
ofPopStyle();  // 3
vbo.drawElements( GL_TRIANGLES, 60); // <- draws as wireframe, but should be filled!
This happens because of how `GL_POLYGON_MODE` is
0. `ofPushStyle` would push current fill state to `ofStyle` stack
1. `ofDrawRecangle() --> ofMesh` would set the correct `GL_POLYGON_MODE` to draw itself based on its internal fill state.
2. `ofMesh` would then attempt to restore `GL_POLYGON_MODE` based on current fill state style.
3. `ofPopStyle` would restore current fill state from `ofStyle` stack, but would not …

fix #3518, glPolygonMode programmableGL

---

libs/openFrameworks/sound/ofSoundStream.cpp
libs/openFrameworks/sound/ofSoundStream.h

This PR:
- Makes ofSoundDevice a class (instead of a struct), makes it conform tighter to OF style
- Fixes a warning RE: above for ofSoundDevice (forward declared as a class, but actually a struct)
- Adds doxygen comments to ofSoundDevice, fixes outdated ones in ofSoundStream
- Fixes the inconsistent whitespace in ofSoundStream.h

ofSoundDevice doxygen comments, fix warning

---

scripts/apothecary/formulas/openssl.sh

Hello.
I ran into problems when using apothecary to build openssl on OSX 10.9.5.
i don't have LANG set in my environment, so the script failed when accessing $LANG.
Surrounding it with "if test ${LANG+defined};" helps.
my LC_CTYPE is set to UTF-8. got this error:
sed: RE error: illegal byte sequence
as pointed out here
http://stackoverflow.com/questions/19242275/re-error-illegal-byte-sequence-on-mac-os-x#19770395
it can be fixed setting LC_CTPYE=C

Apothecary Formula - openssl environment fixes

---

scripts/apothecary/formulas/android_configure.sh
scripts/apothecary/formulas/freetype.sh

Formula's for:
Notes:
-------------------------------
ofTrueTypeFont path fixes for FreeType 2.5.0+ are in a separate PR Here:
Original PR:
https://github.com/openframeworks/openFrameworks/pull/3152

Apothecary - FreeType 2.5.0 Formulae  

---

scripts/apothecary/formulas/poco/poco.sh

Switched to the Release of @PocoProject ’s Poco 1.6-release tag.
- @bakercp ’s and @danoli3 ’s fixes have been merged for 1.6 release of
Poco, so shouldn’t need our fork any more for the moment.
Also passing: [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=poco-ios)](https://travis-ci.org/danoli3/apothecary-den)

Apothecary - Poco Formula Update to 1.6 Release

---

libs/openFrameworks/gl/ofGLUtils.h

Reference Pull request:  Fix compile error on Android: GL_HALF_FLOAT is only defined in GLESv3 #3409

OpenGLES - GL_HALF_FLOAT is only defined in GLESv3 - Merge Fix for #3409

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp
scripts/apothecary/formulas/android_configure.sh
scripts/apothecary/formulas/freetype.sh

Changes for updated FreeType library.
ofTrueTypeFont path fixes for FreeType 2.5.0+
-----------
FreeType changed the library file structure in 2.5.0+ so needed to fix this
Someone had this problem before http://forum.openframeworks.cc/t/missing-of-lib-include-files/14326/3
Fixed in danoli3@12ca5fb
Merge after libraries for FreeType have been built with
https://github.com/openframeworks/openFrameworks/pull/3453

Apothecary - FreeType 2.5.0 Core oF changes [Merge after library updates]

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp

because ofFbo did not restore its viewport to openGL in ofFbo::end() but only push/pop'ed the matrix stack, OpenGL and openFrameworks would get out of state sync once an fbo with different size than the screen would be unbound, leaving the viewport for the main screen at the Fbo's size.
This fixes this by using the renderer's own push/popView methods, which forward the state changes to the GPU / OpenGL upon unbind().

fix issue where ofFbo would be leaking its viewport

---

libs/openFrameworks/graphics/ofCairoRenderer.cpp

Solves issue [#3602](https://github.com/openframeworks/openFrameworks/issues/3602). It wasn't an extra line, it was circling around.

Fix for #3602: ellipse not exported correctly

---

libs/openFrameworksCompiled/project/win_cb/openFrameworksLib.cbp

This enables C++11 for code::blocks, while still maintaining support for popen / pclose.
PR sent as a result of [this discussion](http://forum.openframeworks.cc/t/build-errors-with-openframeworks-master-from-github/18376/3) on the OF forum.

Enable C++11 in win_cb

---

libs/openFrameworks/graphics/ofImage.cpp
libs/openFrameworks/graphics/ofImage.h
libs/openFrameworks/graphics/ofPixels.cpp
libs/openFrameworks/graphics/ofPixels.h

It is quite useful to be able to get access to an image through index.
It's possible to get pixel by index so there's precedent.

Allow access to pixel color through index (like setColor)

---

scripts/apothecary/formulas/glew.sh

- Fixes script to fail if target directories have been deleted.
[![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=glew-osx)](https://travis-ci.org/danoli3/apothecary-den)

Apothecary Formula - GLEW fix for copy phase

---

scripts/apothecary/formulas/cairo.sh
scripts/apothecary/formulas/freetype.sh

In the OS X recipe, freetype's pkgconfig entry did not point to the correct fat static library, and would therefore scuttle the cairo build.
This pr fixes this by copying the fat static freeimage lib to the point indicated by freeimage's pkgconfig .pc file, so that the build can proceed properly. Also enables multi-processor builds to save time drinking tea.
* 32bit libstdc++
* 64bit libc++
This should get us one step closer to tackling #2016

fix freetype apothecary script, and therefore cairo

---

scripts/apothecary/formulas/tess2/tess2.sh

+ before, only libc++ based library slices were generated for tess2 on os x 
+ this uses a more explicit build for os x, making sure we have the correct std libraries linked to the i386 and x84_64 slices.
+ also compiles libtess2 with o3 (fastest) for desktop os x
+ cleans up osx build script slightly

fix apothecary fat osx lib for tess2

---

.gitignore
addons/ofxAndroid/ofAndroidLib/AndroidManifest.xml
addons/ofxAndroid/ofAndroidLib/build.gradle
docs/android.md
examples/android/androidEmptyExample/build.gradle
libs/openFrameworksCompiled/project/android/.gitignore
libs/openFrameworksCompiled/project/android/build.gradle
libs/openFrameworksCompiled/project/android/config.android.default.mk
libs/openFrameworksCompiled/project/android/settings.gradle
scripts/dev/create_package.sh

This change incorporates all the necessary build files, packaging changes, makefile
tweaks and documentation needed to make openFrameworks work on Android Studio.
This resolves issue #3408.

Implement support for Android Studio.

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroid.java
addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFGestureListener.java
addons/ofxAndroid/src/ofAppAndroidWindow.cpp

Some phones supply major/minor axis and angle data in their touch events; this
patch simply passes that data on to openFrameworks.

Implement majoraxis, minoraxis, angle touch parameters on Android

---

addons/ofxiOS/src/core/ofxiOSEAGLView.mm
examples/ios/iosNativeExample/src/main.mm
examples/ios/iosStoryboardExample/src/main.mm
libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofMainLoop.cpp
libs/openFrameworks/app/ofMainLoop.h

this is a fix to get ofxiOS working correctly with the new multi-window feature.
@arturoc,
found one issue where after `windowLoop()` was called, `windowsApps` was being cleared.
this resulted in `ofGetAppPtr()` returning NULL when while iOS (and Android) apps are running.
to fix this ive created an `exit()` function in `ofMainLoop` which is called after the while loop is finished and the app is ready to exit. the `exit()` function is also called by ofxiOS when it needs to remove apps and remove the event listener.
let me know if you see any issue with these modifications.
be good to get this in soon as its causing crashes with some of the ios examples.

ios mainloop fixes

---

scripts/apothecary/formulas/fmodex.sh

+ this is a download + copy-only script, since fmodex appears not to be available in source.
+ downloads fat binary release of fmodex for os x (64/32bit), 
+ linking verified against libstdc++ and libc++.
The current oF:master dylib supplied for fmodex on os x is slim. 
+ downloads headers and fat binary dylib for fmodex from fmod.org. 
+ Version downloaded (42221) is the version closest to the current headers in master, since the version referenced in the current headers (42220) is not available as a download for os x.

apothecary: add osx-fat-fmodex script

---

libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk

This variable is added mainly for Xcode projects generated from the PG (see https://github.com/openframeworks/openFrameworks/issues/3430) and is added to the Makefiles for completeness. The Makefile simply appends it to PROJECT_ADDONS_CFLAGS. Tested on OS X Makefile build.

added ADDON_CPPFLAGS Makefile var so ADDON_CFLAGS can be used by PG for pure C

---

addons/ofxAssimpModelLoader/scripts/formulas/assimp.sh
scripts/apothecary/formulas/FreeImage/FreeImage.sh
scripts/apothecary/formulas/cairo.sh
scripts/apothecary/formulas/freetype.sh
scripts/apothecary/formulas/glfw.sh
scripts/apothecary/formulas/kiss.sh
scripts/apothecary/formulas/openssl.sh
scripts/apothecary/formulas/poco/poco.sh
scripts/apothecary/formulas/portaudio.sh
scripts/apothecary/formulas/rtAudio.sh
scripts/apothecary/formulas/tess2/tess2.sh
scripts/apothecary/formulas/videoInput.sh

Fixes: **Dependencies are missing their License Agreements with their Source/Headers in /libs/**
Issue Reference: https://github.com/openframeworks/openFrameworks/issues/3614
**Apothecary script formula only.**
Tested and working via apothecary-den for iOS / OS X scripts (most crossover)
Double checked all the others that I couldn't build directly.
**Fixes minor issues in:**
- scripts/apothecary/formulas/kiss.sh (broken if statement)
- scripts/apothecary/formulas/videoInput.sh (missing branch @ofTheo had merged to master)

Apothecary Formula Only - License Copy Process

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.cpp

updates `blendingMode` in renderer`.currentStyle` whenever the blendmode is set. This allows `ofPush|PopStyle()` to store + recover blend modes as expected
Since the renderer's blendmode was not updated in either programmable or fixed function renderer, push/pop style would not work as expected: `push` would not store the current blend mode, while `pop` would "restore" the blendmode to the default value of `OF_BLENDING_ALPHA(1)`

fix blendmode style tracking in fixed function + programmable renderer

---

scripts/apothecary/README.md
scripts/apothecary/apothecary
scripts/apothecary/formulas/FreeImage/FreeImage.sh
scripts/apothecary/formulas/cairo.sh
scripts/apothecary/formulas/fmodex.sh
scripts/apothecary/formulas/freetype.sh
scripts/apothecary/formulas/glew.sh
scripts/apothecary/formulas/glfw.sh
scripts/apothecary/formulas/kiss.sh
scripts/apothecary/formulas/kiss/kiss.sh
scripts/apothecary/formulas/openssl.sh
scripts/apothecary/formulas/poco/poco.sh
scripts/apothecary/formulas/portaudio.sh
scripts/apothecary/formulas/rtAudio.sh
scripts/apothecary/formulas/tess2/tess2.sh
scripts/apothecary/formulas/videoInput.sh

Some small apothecary updates:
* Don't need explict names when copying license files, related to #3623 
* Don't assume we have the android sdk installed, only set sdk vars when targeting android and exit with error if we can't find the path file. Also, this was opening a file with a relative path *before* the script actually changes dir so it would break if you we're not running apothecary from it's own dir. Apothecary is designed to be called from any location so it's easier to script.
* Updated readme with info on custom echo wrappers
* Small formula whitespace fixes
I also noted the following which I have questions about:
1. There are two kiss formulas right now, one should be deleted: `kiss/kiss.sh`& `kiss.sh`
2. There is lots of [commented stuff in …

seem small apothecary updates

---

libs/openFrameworksCompiled/project/android/.gitignore

This ignores the gradle files automatically added by Android Studio.

Add gradle/ directory and scripts to .gitignore

---

libs/openFrameworks/video/ofAVFoundationPlayer.mm

c++11 requires a static cast, since some types cannot be unambiguously inferred in the initialiser list
This fix is necessary for c++11 / 64bit compilation and #3627, and is backwards compatible with 32 bit. Tested on both.

fix c++11 av foundation player

---

scripts/linux/compileOF.sh

Hi *,
this patch removes an overly specific path to the "chown" command during the compilation of oF. At least on ARMv7 the $LIBSPATH (of compileOF.sh) conflicts/is out of sync with the $PLATFORM_LIB_SUBPATH (of config.shared.mk). The former is used for the "chown" command, the latter for the actual compilation output. The "libs/openFrameworkCompiled/lib" directory should be owned by the user anyway.
Cheers,
tpltnt

fixing compileOF.sh (for ARMv7)

---

libs/openFrameworks/3d/ofEasyCam.cpp

* since `ofEasyCam.events` will only get set upon first use (`begin`) of the camera, enabling or disabling `mouseInput` for a camera would push a nullpointer onto the `ofEvents` stack for the camera in question, with dreadful results.
This fix addresses the issue by checking `events` against null, and applying the `mouseInput` only when possible. it also makes sure to honour any settings for the camera which have been passed during `ofApp::setup`.
Also adds some inline comments to explain what's happening to facilitate code maintenance.

fix ofEasyCam segfault when en/disableMouseInput within ofApp::setup()

---

docs/android.md
libs/openFrameworksCompiled/project/android/build.gradle
libs/openFrameworksCompiled/project/android/config.android.default.mk

On Windows, we still need to depend on MinGW to provide grep and find, and maybe some other tools. This patch forces the Android Studio build system to use the MinGW make program, and also rejects spaces in NDK path names (a common pitfall, especially on Windows and OS X).

Necessary changes to support Android Studio on Windows.

---

libs/openFrameworks/app/ofMainLoop.cpp

fixes an issue where closing the main window via mouse could crash an app.
+ if a window or app was closed through system input (via a mouse clicking on tiny x'es) or Command-Q, the ofMainLoop was bound to overshoot and cause a postmortem segfault.
This is because the iterator used to loop through all open windows was invalidated after a closed window was erased. This PR proposes to set the window iterator to the return value of `erase()` should the `windowsApps` `map` get modified. 
`erase()` is guaranteed to return the next position after the deleted element, and `::end` if there is no more element, so the loop can function as expected.

fix mainloop segfault upon window close

---

libs/openFrameworks/app/ofMainLoop.cpp

* makes #3664 OS X cpp98 compatible - and un-breaks OS X builds.
* uses an explicit declaration of the iterator type in favour of c++11 'auto' (it aint pretty but it's backwards compatible and essentially the same)
* uses the idiom lined out on http://stackoverflow.com/questions/8234779/how-to-remove-from-a-map-while-iterating-it
Tested on

fixes the segfault on exit fix, sticking strictly to cpp98 conventions.

---

libs/openFrameworks/types/ofBaseTypes.cpp
libs/openFrameworks/types/ofBaseTypes.h
libs/openFrameworks/video/ofAVFoundationPlayer.h
libs/openFrameworks/video/ofAVFoundationPlayer.mm
libs/openFrameworks/video/ofAVFoundationVideoPlayer.h
libs/openFrameworks/video/ofAVFoundationVideoPlayer.m
libs/openFrameworks/video/ofVideoPlayer.cpp
libs/openFrameworks/video/ofVideoPlayer.h

As discussed here #3628, the new AVFoundation player implemented a async loader of the videoplayer. This PR implements a loadAsync call in the ofVideoPlayer that can be used for async loading of movies, currently only implemented in the ofAvFoundationPlayer. 
It's implemented by waiting for a `dispatch_semaphore_signal()` in the otherwise async loader

Async videoplayer loader, implemented for AVFoundationPlayer

---

libs/openFrameworks/3d/ofEasyCam.cpp

This restores the default behaviour of ofEasyCam, which used to have mouse input enabled by default, and addresses an issue reported by @kylemcdonald on #3661.

initially enable mouseInput for ofEasyCam

---

libs/openFrameworks/app/ofAppNoWindow.h
libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLProgrammableRenderer.h
libs/openFrameworks/gl/ofGLRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.h
libs/openFrameworks/graphics/ofCairoRenderer.cpp
libs/openFrameworks/graphics/ofCairoRenderer.h
libs/openFrameworks/graphics/ofRendererCollection.h
libs/openFrameworks/types/ofBaseTypes.h

- fixes #3667
- removes renderer.draw(mesh) without polygon mode which was behaving
different in fixed and programmable
- fixes programable::drawInstanced(mesh) which was setting the wrong
polygon mode afterwards

refactor renderers to remove some unused methods

---

libs/openFrameworks/utils/ofFileUtils.cpp

ofBuffer::allocate() didn't zero-pad the buffer, now it does. This matches behavior elsewhere so ofBuffer::size() correctly returns the allocated size. Fixes #3677.

Fix #3677 ofBuffer::allocate()

---

scripts/apothecary/formulas/freetype.sh

As @carthach pointed out in #3627, freetype might fail to work in some cases since an optional dependency to harfbuzz (a utility to parse extended OpenType features) has not been met. 
Since we haven't included & compiled harfbuzz in the past (and freetype for homebrew is fine without it) it seems a sensible choice to compile freetype without it.
If we wanted to include Harfbuzz, we'd need to add a dependency for harfbuzz 0.9.19 or newer: <http://sourceforge.net/projects/freetype/files/freetype2/2.5.3/> 
But this would create a catch22 while compiling, because harfbuzz, in turn, depends on Freetype.
We also have had a flag to exclude harfbuzz from android builds for a while. I wonder if we should exclude it from iOS builds, as well... 
ping @bakercp

apothecary: remove harfbuzz dependency from freetype

---

examples/sound/soundPlayerExample/src/ofApp.cpp
examples/sound/soundPlayerFFTExample/src/ofApp.cpp
libs/openFrameworks/sound/ofSoundPlayer.cpp

This PR:
- Returns a bool from inside loadSound
- Updates the sound player examples to use the non-deprecated "load" syntax

Fix missing return in ofSoundPlayer::loadSound, update examples

---

examples/gui/guiExample/src/ofApp.cpp
examples/gui/guiFromParametersExample/src/ofApp.cpp

Small point I found confusing in the GUI examples. bHide meant "shown" or "not hidden". Still defaults on, but uses !bHide to draw.

bHide now means 'hidden', not 'shown'

---

libs/openFrameworks/math/ofMath.cpp
libs/openFrameworks/math/ofMath.h

A few fixes for https://github.com/openframeworks/openFrameworks/pull/3699 related to const correctness + additional const corrections and a fix of an incorrect `ofNoise(const ofVec2f&)` signature.

Const and argument corrections in ofMath.h/.cpp.

---

libs/openFrameworks/video/ofAVFoundationPlayer.h
libs/openFrameworks/video/ofAVFoundationPlayer.mm
libs/openFrameworks/video/ofAVFoundationVideoPlayer.h
libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

adding garbage collection for AVFoundationVideoPlayer disposal making movie loading faster.
also fixes some memory leaks reported here:
https://github.com/openframeworks/openFrameworks/issues/3704
https://github.com/openframeworks/openFrameworks/issues/3729
https://github.com/openframeworks/openFrameworks/issues/3715
might fix this as well: https://github.com/openframeworks/openFrameworks/issues/2530 (did not test)
also includes these pullrequests: 
https://github.com/openframeworks/openFrameworks/pull/3672: using a cleanup+release method for internal cleanup. refactored `finalize` to `cleanupAndAutorelease`
https://github.com/openframeworks/openFrameworks/pull/3670: making texture objects private

oFAVFoundationPlayer gc and memory fixes

---

libs/openFrameworks/utils/ofXml.cpp

* catch SAXException for better parse error info
* check if file exists before trying to load and print error if not
Now I get:
[ error ]  ofXml: parse error: Tag mismatch in line 10 column 3
and:
[ error ] ofxXml: couldn't load, "glslColorScheme.xml" not found
instead of:
[ error ] ofXml: loadFromBuffer(): DOM ERROR

ofXml: better parse error messages & file existence check

---

libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj
scripts/vs/template/emptyExample.vcxproj

As mentioned by @LeoColomb in #2548 , this turns on multiprocessor compilation (`/MP`) for visual studio 2012. It also turns off "minimal rebuild" (`/Gm`), because that's an incompatible option.
Build times (for all of OF + empty example) :
- Current master 2:37
- With /MP 1:11
(My Windows HDD is elderly)

Turn on multiprocessor compilation for visual studio 2012

---

libs/openFrameworks/video/ofGstUtils.cpp

I've had a compatibility issue using ofGstUtils in Windows environment (with ofxGstreamer add on), with Code::Block 13.12 (gcc 4.7.1) if I enable the C++11 standard option.
In this standard the putenv function is not defined, so I substitute the function with SetEnvironmentVariableA, including winbase.h

Compatibility issue of ofGstUtils

---

examples/gl/glInfoExample/src/ofApp.cpp

A typo which causes a compile-time error on VS 2013.

Fix a typo

---

examples/gui/guiExample/src/ofApp.cpp
libs/openFrameworks/graphics/ofTrueTypeFont.h

**guiExample code consistency**: some small updates to resolve multiple coding styles and the use of multiple ifs instead of if else statements.
**OF_TTF string as static const**: this fixes a SWIG error when generating OF bindings (aka for ofxLua). Simply swapping "const static" with "static const" solves it. C++ doesn't care either way, so this change [shouldn't effect anything](http://stackoverflow.com/a/12006039/2146055). Besides, "static const" is the recommended order in C anyway.

small updates: guiExample code consistency & OF_TTF string as static const

---

libs/openFrameworks/video/ofVideoGrabber.cpp

If the ofVideoGrabber is not initialized on application start the grabber member is null, resulting in a segmentation fault, if  we try to check for the initialization of object; The performance penality of this guard are negligible.

Add guard to avoid segfault on uninitialized Video Grabber

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

* take HIDPI / LODPI into account when repositioning fullscreen window on OS X
before this, HIDPI fullscreen windows would not cover the full screen.

use backingscale to re-position window on os x

---

CHANGELOG.md
libs/openFrameworks/utils/ofXml.cpp
libs/openFrameworks/utils/ofXml.h

Reverts openframeworks/openFrameworks#3711
The way it's implemented will cause ambiguity problems. we should have a templated version instead

Revert "ofXml::setValue as int"

---

addons/ofxOpenCv/scripts/formulas/OpenCV.sh
addons/ofxOpenCv/scripts/formulas/patch.calibfilter.cpp.patch

iOS : [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=opencv-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=opencv-ios) https://travis-ci.org/danoli3/apothecary-den?branch=opencv-ios
OS X:  [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=opencv-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=opencv-osx) https://travis-ci.org/danoli3/apothecary-den?branch=opencv-osx
- Works for iOS armv7, arm64, i386, x86_64 - clang with libc++
- OS X i386 libstdc++, OS X x86_64 with libc++
Fixed symbolic error conflicts with libPNG / libJPEG.
Implemented iOS build script
Tested and working with more recent 2.4 minor OpenCV versions as well with minimal changes from this.
Includes patch file for 2.4 that is required to compile under …

Working Apothecary Formula for OpenCV 2.4 - iOS and OS X

---

libs/openFrameworks/3d/ofMesh.cpp
libs/openFrameworks/3d/ofMesh.h

These fixes make the use of index variables in ofMesh more consistent and also get rid of various type comparison warnings on linux.

ofMesh of index type fixes

---

scripts/apothecary/formulas/FreeImage/FreeImage.sh
scripts/apothecary/formulas/FreeImage/Makefile.osx.patch

Fixes: "Git Master, not able to load TIF files. #3832"
- Problem: Assertions were not being turned off for compilation of static library.
- Affected Versions: OS X x86(32 bit).
- Will PR static libs for iOS / OS X for FreeImage with this change.

Apothecary - FreeImage Formula Updated with NDEBUG (No Assertions).

---

examples/events/simpleEventsExample/src/Circle.cpp
examples/events/simpleEventsExample/src/Circle.h
examples/gl/textureBufferInstancedExample/src/ofApp.cpp

Adds missing `mouseEntered` / `mouseExited` callbacks

Fixing compile-time errors in examples

---

libs/openFrameworks/gl/ofVbo.cpp

This patch fixes ofVbo copy and assignment constructors when not using the programmable pipeline.
Without it vaoID will be garbage and 'clear' tries to release it.

fix ofVbo copy constructor

---

addons/ofxiOS/src/core/ofxiOSAppDelegate.mm
addons/ofxiOS/src/core/ofxiOSViewController.mm

This PR contains fixes for the iOS Orientation issues
- iOS 8 orientation animation; excessive rotation & incorrect rotations - Fixes https://github.com/openframeworks/openFrameworks/issues/3336
- iOS 8.3 Landscape issues - Fixes https://github.com/openframeworks/openFrameworks/issues/3824
- iOS 8 breaks OF handling of Hardware Orientation - Fixes https://github.com/openframeworks/openFrameworks/issues/3158
- iOS 8 broken orientation with ofxiOSImagePicker - Fixes https://github.com/openframeworks/openFrameworks/issues/3474
----------------------------
- Fixes iOS 7 orientation issue of getting out of sync with preferred orientation
- Fixes issues related to ```settings.enableHardwareOrientation = false``` for iOS 8
- Fixed bounds issues mentioned here …

iOS Orientation Issues Fix

---

addons/ofxOsc/libs/oscpack/src/ip/win32/UdpSocket.cpp

+ Does not affect posix systems (linux, OSX), since these compile against the `/posix` version of the affected `.cpp` file.
This adds a missing declaration and a (char *) cast to make the windows compiler happy. Otherwise apps using ofxOSC will not compile on Windows.

Fixes compiler errors for win32 version of ofxOSC.

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

Clang's Leak Sanitizer found these

Fixing Fontconfig memory leaks by destroying allocated FcPatterns

---

libs/openFrameworks/graphics/ofTessellator.cpp

Destruction of `cacheTess` is required before new initialization, otherwise `tessNewTess` will override used address and its resources will never be freed.

Closes #3883

---

addons/ofxGui/src/ofxButton.cpp

add the ability to get access to the ofxButton in the ListenerMethod . 
Tested on Windows 8.

change valueChanged so that the sender is included

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidVideoPlayer.java

…and resumed
By doing using reset() before releasing the media player we avoid the "mediaplayer went away with unhandled events" warning:
mediaPlayer.reset();
mediaPlayer.release();
Also by reseting the mediaplayer after creating it we avoid the internal/external state mismatch corrected exception when pausing resuming the app. Doing that forces us also to keep track of loop state when resuming the video.
06-02 18:05:37.195: E/MediaPlayer(30590): internal/external state mismatch corrected

Avoid Warning/Exception when Android video is playing and app is paused

---

libs/openFrameworks/math/ofMath.cpp

change from `(RAND_MAX + 1.0f)` to `(static_cast<double>(RAND_MAX) + 1.0)`.
Because, if RAND_MAX is sufficiently large as larger than float precision, then `RAND_MAX + 1.0f == RAND_MAX`.
In other words, often `rand() / (RAND_MAX + 1.0f)` returns `1.0f`
And, added `static_cast<double>` to clarify the meaning.
At the same time, replace same codes like `rand() / (RAND_MAX + 1.0f)` to `ofRandomuf()`.
Maybe this tiny code will be inline expanded automatically when compiling.
more discussion about this: please see #3762

change denominator of ofRandomuf from float to double.

---

libs/openFrameworks/types/ofColor.cpp
libs/openFrameworks/types/ofColor.h

if no `const` then we can't compare some situation.
see: #3898

add const to comparison of ofColor.

---

scripts/linux/debian_armv6l/install_dependencies.sh

Gstreamer is now included in the default Raspbian

Removed old debian gstreamer omx repo. fixes #3669

---

libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/utils/ofLog.h
libs/openFrameworks/utils/ofThread.cpp

instead catch the exceptions and log them locally on each thread.
simplifies the architecture and seems a better idea than having
some global state taking care of this.
i've just realized that ofThreadLogger and Poco's ErrorHandler is doing just this. i also wanted to make the thread detach itself if it failed which i would need to have done in ofThreadLogger.
i think this makes much more sense and simplifies things a bit but i might be missing something about what Poco's ErrorHandler is doing. ping @bakercp

remove ofThreadLogger

---

libs/openFrameworks/types/ofTypes.h

+ vs2015RC does not yet implement the [[deprecated]] attribute:
http://blogs.msdn.com/b/vcblog/archive/2014/11/17/c-11-14-17-features-in-vs-2015-preview.aspx
Since our compiler-agnostic deprecation macro OF_DEPRECATED cannot add
deprecation messages to typedefs, there appears no other option than to
omit deprecation messages for these typedefs in visual studio for now.

fix for deprecation attributes in vs2015

---

libs/openFrameworks/video/ofDirectShowGrabber.cpp

+ use pixels.getData() instead of pixels.getPixels
This brings DirectShow grabber in line with the current api and removes a
deprecation warning.

update DirectShow grabber to use new syntax

---

libs/openFrameworks/events/ofEvent.h
libs/openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj/project.pbxproj

+ header <iterator> is needed for VS2015 to find
back_inserter, possibly other comilers might need it, too.
+ also add ofEvent to openFrameworks XCode project file, so
that XCode shows the file in the project file outline

add missing include to ofEvent.h

---

libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj
libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj.filters

this is not a code change, but necessary so that the file ofEvent.h shows
up in the project files view in Visual Studio.

add ofEvent.h to visual studio project files

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.h

+ since the implementation for ofGLProgrammableRenderer::setCurrentFBO has
been removed in 94cb65672e92dc33dc67733f4397699f15a41399 the signature for
the method should probably go away, too.
setCurrentFBO is not used anywhere within oF core, which is why probably
nobody noticed the missing implementation.
Addresses #2738

remove method signature for setCurrentFBO

---

scripts/apothecary/formulas/openSSL/opensslconf.h

- Minor fix to the formula header re-includer for OpenSSL.
- Now using the same format as the file in the include directory.

Apothecary - OpenSSL formula file include

---

libs/openFrameworksCompiled/project/ios/CoreOF.xcconfig

Changes applied to ios/CoreOF.xcconfig
- Adds the new libraries (boost, uri)
- Adds the new source headers (boost, uri, utf8)

iOS Core Config update for new libraries

---

libs/openFrameworks/utils/ofUtils.cpp
libs/openFrameworks/utils/ofUtils.h

* on windows, `strftime` called with an invalid formatting
string will lead to an app crash.
* since `ofGetTimestampString()`, when called without
parameters, uses the parameters `%Y-%m-%d-%H-%M-%S-%i`,
this would lead to a crash upon the first call of
`ofGetTimeStampString` because of the non-standard `%i`
formatter.
https://msdn.microsoft.com/en-us/library/fe06s4ak(v=vs.140).aspx
Since the `%i` parameter is non-standard over probably all
implementations of `strftime`, and we manually replace it
anyways, i've re-arranged the replacement to happen before
the call to `strftime`.
This is not super optimised (and I believe this method
could be), but it doesn't crash anymore.

fix getTimestampString app crash on windows

---

libs/openFrameworks/types/ofParameter.h

* removes an extra template<> line which was causing
compiler errors since then the template could not be
specialised.
To specialise a template which is already templated, the
template typename has to be specified, as it is in the
next line.

fix ofParameter - extra template<>

---

scripts/vs/template/emptyExample.vcxproj

* xcopy overwrites all .dlls in the bin/ folder
every time an app gets rebuilt. This leads to
longer compile times, since about 20MB need to be
overwritten in the bin/ folder everytime an app is
built.
* robocopy is similar to rsync and will only copy or
overwrite a file if either a change was detected
(i.e. the build target was changed from 32bit to
64 bit) - or the directory is missing a file.
Files which are already present and of the same
size will not be copied.
This speeds up app compile time. (And may also
help towards longer SSD lifetime)
~~xcopy~~ robocopy is a default system tool, and available
since Windows 7 onwards.
https://technet.microsoft.com/en-GB/library/cc733145.aspx

use robocopy instead of xcopy in post-build step

---

addons/ofxAndroid/src/ofxAndroidSoundPlayer.cpp

getVolume was using an incorrect jni method signature. It was using "(V)F", when it should actually be "()F". getVolume was triggering a crash on Android devices.

Fix ofxAndroidSoundPlayer getVolume

---

libs/openFrameworksCompiled/project/vs/openFrameworksDebug.props
libs/openFrameworksCompiled/project/vs/openFrameworksRelease.props
scripts/vs/template/emptyExample.vcxproj

* when building an app in debug mode, visual studio tries to
find linker symbol (*.pdb) files for libraries that ship
with openframeworks.
Since these libraries are shipped without debug symbol files
(these files are huge) a warning is issued for almost
every library that ships with openFrameworks whenever an
app is built, or re-built. For oF, this meant scores of
warnings on debug builds.
In the past, it has been impossible to ignore this linker
warning message, but it had been so nagging to not being
able to ignore it that some people even had tutorials for
binary patching the visual studio linker executable to be
able to get rid of it.
It seems that with Visual Studio2015 it is finally
officially possible to ignore this (utterly useless in our
case) warning.
Let's.

ignore linker warning 4099 for visual studio debug

---

libs/openFrameworks/gl/ofFbo.cpp

This problem occurs when reallocating ofFbo that is used on MRT. 
(such as resizing)
The fbo that attached to 1 or later , is always black.
This is probably because activeDrawBuffers has not been cleared.
When fbo is not the MRT, the attach_point is always 0.
So, it looks like there is no problem. But activeDrawBuffers will be incremented.

Reallocating ofFbo on MRT, drawBuffers unable to attach.

---

libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig

Fixes missing xconfig include for OpenSSL headers.

Missing OpenSSL include OSX xconfig

---

addons/ofx3DModelLoader/src/3DS/texture3DS.cpp

proposed fix for: https://github.com/openframeworks/openFrameworks/issues/3987 issue #3987

fixed ofx3DModelLoaders texture3DS class to properly access ofImage's Protected Members

---

scripts/osx/template/emptyExample.xcodeproj/project.pbxproj

Fix pthread issues from Xcode OSX template.
As referenced: 
https://github.com/openframeworks/openFrameworks/issues/3980

OSX -pthread template fix

---

scripts/apothecary/formulas/uri/uri.sh

- Defines BOOST paths Explicitly for iOS for CMAKE 
When checking the Cmake file it had some of the boost defines set to some at /usr/local/ boost locations from a home-brew install of boost) 
(Note: I have since built with these proposed changes and still got the iOS Simulator crash, so unrelated).
- Changes ```../../formulas/uri/``` to $FORMULA_DIR variable.

Apothecary Formula Fixes for URI 

---

examples/sound/soundPlayerExample/src/ofApp.cpp

While looking into #3855, i fixed the soundPlayerExample by changing `getIsPlaying()` to `isPlaying()`.
Cheers
tpltnt

fixed deprecation warnings for soundPlayerExample

---

addons/ofxOpenCv/src/ofxCvGrayscaleImage.cpp

Hi,
I received some error messages from ofxCvGrayscaleImage::absDiff() and could not figure out the `mom` and `dad` names from the message alone. I changed the  error messages to be more comprehensible (without needing to know the method signature).
Cheers,
tpltnt

adjusted error messages of ofxCvGrayscaleImage::absDiff()

---

scripts/ios/template/emptyExample.xcodeproj/project.pbxproj

Fix for Xcode Template to fix the potential issues with code signing for the iOS simulator. 
- If the developer does not have an active or any Apple Developer account associated with their account it has issues properly signing / deploying to Simulator
- By default deploying to the simulator does not require code signing however in the current project template setup it is attempting to code sign the simulator
- Define different targets for iPhoneSimulator and iPhoneOS for Xcode under the code signing section.
- By adding iPhoneSimulator explicitly and defining this as Do not code sign. This error is fixed.

iOS Template - Code Sign fix for simulator

---

libs/openFrameworks/gl/ofShader.cpp

std::regex uses a slightly different API as did POCO, and
regex_search has to be used instead of regex_match to find
matching tokens in a string.

fix regex matching for shader error log

---

libs/openFrameworks/gl/ofTexture.cpp

when allocating an ofTexture backed by an ofBufferObject, the glInternal format would always be hardcoded to GL_RGBA32F, regardless of the glInternalFormat parameter handed over through the method parameters.
This was probably accidentally leftover from a refactor.
ping @arturoc

fix hard-coded glInternalformat

---

addons/ofxAndroid/src/ofAppAndroidWindow.cpp
addons/ofxNetwork/src/ofxTCPServer.h
addons/ofxiOS/src/sound/ofxOpenALSoundPlayer.cpp
examples/utils/threadExample/src/threadedObject.h
libs/openFrameworks/types/ofTypes.h
libs/openFrameworks/video/ofGstUtils.cpp

Hi,
i replaced all occurences of `ofMutex` and `ofScopedLock` since they are deprecated. The documentation is also updated. This should be merged in conjunction with #4012.
Cheers
tpltnt

ofScopedLock and ofMutex deprecation

---

examples/gl/textureBufferInstancedExample/src/ofApp.cpp
libs/openFrameworks/gl/ofTexture.cpp
libs/openFrameworks/gl/ofTexture.h

When allocating a texture as a texture buffer, the texture
cannot be used as a vanilla texture anymore, but must be
used as a buffer texture.
This name change in the hope it might help disambiguation.
Addresses #4035 
+ Also updated textureBufferInstancedExample so it uses the new signature

rename ofTexture::allocate for texture buffers

---

libs/openFrameworks/utils/ofUtils.cpp
libs/openFrameworks/utils/ofUtils.h

visual studio requires a locale to be given for std::isspace.
it seems that there are two signatures for std::isspace available, one in `<string>` and one in `<locale>`
but Visual Studio defaults to the one in `<locale>` 
http://en.cppreference.com/w/cpp/locale/isspace 
vs.
http://en.cppreference.com/w/cpp/string/byte/isspace
+ refactor getLocale to a helper method within `ofUtils.cpp` to keep things DRY
addresses #4042

add locale to trim methods

---

CHANGELOG.md
addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp
addons/ofxAndroid/src/ofxAndroidVideoPlayer.cpp
addons/ofxEmscripten/src/ofxEmscriptenVideoGrabber.cpp
addons/ofxiOS/src/video/ofxiOSVideoPlayer.mm
libs/openFrameworks/gl/ofFbo.cpp
libs/openFrameworks/gl/ofTexture.cpp
libs/openFrameworks/gl/ofTexture.h
libs/openFrameworks/graphics/ofImage.cpp
libs/openFrameworks/video/ofAVFoundationPlayer.mm
libs/openFrameworks/video/ofVideoGrabber.cpp
libs/openFrameworks/video/ofVideoPlayer.cpp

rename `ofTextureData.glTypeInternal` to `ofTextureData.glInternalFormat` for naming consistency with
the underlying OpenGL enum.
Closes #4036
+ also updates CHANGELOG to highlight the change

rename .glTypeInternal -> .glInternalFormat

---

libs/openFrameworks/math/ofMatrix4x4.cpp

Fixes a warning on OSX.  
`register` is deprecated in c++11.
https://stackoverflow.com/questions/20618008/register-keyword-c-11

Remove deprecated register keyword.

---

libs/openFrameworks/utils/ofFpsCounter.cpp
libs/openFrameworks/utils/ofFpsCounter.h

Fixing warnings.  `targetFps` is a private variable that is set but never accessed.

Fix unused variable warning "targetFps".

---

libs/openFrameworks/events/ofEvent.h

I want to conditionally create a stack of events to be notified.  
Then I want to pass events through that stack.  Since the stack is linked in a sort of chain, I only want to include events in the stack that have subscribers and are enabled.  
Thus, it is important to be able to know if an event is enabled and if the event has subscribers.  These two accessors allow me to use the existing ofEvent system without extending ofEvent and adding these accessors to my own subclass.

Add isEnabled() and size() to ofBaseEvent.

---

libs/openFrameworks/utils/ofUtils.cpp
libs/openFrameworks/utils/ofUtils.h
libs/openFrameworks/utils/ofXml.cpp
libs/openFrameworks/utils/ofXml.h

Added getter methods for type long in ofXml (as in #3081 for ofxXmlSettings). 
I used long long instead of long for maximal value range.
Tested single methods + serialize and deserialize in combination with ofParameter (Ubuntu only).

added getter for type long (ofXml & ofUtils)

---

libs/openFrameworks/utils/ofSystemUtils.cpp

Restored code from @admsyn's commit in 2013: https://github.com/admsyn/openFrameworks/commit/41048de13c8f8ae4cceb771765408f583b46ca50
@ofZach [of-dev mailing list]: «There's also some little things like on osx adding retina support __and getting focus back to the window after using a dialog prompt__, etc.»
See also http://forum.openframeworks.cc/t/using-ofsystemtextboxdialog-makes-window-lose-focus/19743
Only affects TARGET_OSX and I tested it on 10.10.2 with Xcode 6.3.1

Fix modal dialog focus problem on OSX

---

addons/ofxProjectGenerator/src/projects/xcodeProject.cpp

so comparison on next line isn't always false

ofxProjectGenerator: Fix type for return from std::string::find()

---

addons/ofxGui/src/ofxSlider.h

splitting generateDraw()/generateText() and render() is nicely done but you can't really build on it in derived classes in the ofxGui context because of the missing virtual modifier in the base class. render() and mouse...() are virtual functions already.
(example: for a simple gui extension I tried to override generateText() to draw some labels instead of the actual value)

ofxGui: improve inheritability of ofxSlider

---

libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj
libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj.filters

ofThreadChannel, new with of 0.9, was not yet part of the
tree view in the VS project template.
This adds the file to the openFrameworks project file so it
shows up in the solution explorer view.

add ofThreadChannel.h to project view in VS

---

libs/openFrameworks/gl/ofVbo.cpp

When an ofVbo is assigned a new buffer for vertex data, the
internal VAO was not flagged as dirty. This would lead to
the old buffer still being bound to the previous vertex
buffer, and the new vertex data not being displayed.
With this fix, the ofVbo's internal VAO is marked dirty
after the buffer has been assigned, and the VAO will be
re-submitted upon the next draw call, using the new buffer
for vertex data.

fix vao not updated upon vertex buffer change

---

CODE_OF_CONDUCT.md

This PR adds a CODE_OF_CONDUCT.md alongside the README.md and LICENSE.md. @ofZach mentioned this one on Twitter and I thought it was nice, so I thought I'd add it.
Probably more important than any code of conduct itself is the discussion that happens around it. I brought this up in October and some of the comments then were:
- Make the "Philosophy" section more prominent on the "About" page (it's been moved to the top).
- It'd be nice, but we already have a lot of text on the site. We should organize and consolidate the text in a smart way (@workergnome started working on this, but it's on hiatus).
- Changing the language a little bit. For example, "If you are not a part of the group, welcome!" got changed to "If you are not yet...". Changing "of-dev" to "of-contributors" could also be …

Addition of Code of Conduct

---

addons/ofxGui/src/ofxBaseGui.cpp
addons/ofxGui/src/ofxBaseGui.h
addons/ofxGui/src/ofxGuiGroup.cpp
addons/ofxGui/src/ofxGuiGroup.h

Corrected version of https://github.com/openframeworks/openFrameworks/pull/4119:
- the parent attribute is moved from ofxGuiGroup to ofxBaseGui: when a button or something else derived from ofxBaseGui changes size, the parent control should be updated, therefore ofxBaseGui needs a parent
- sizeChangedCB moved to ofxBaseGui, gets called every time an element gets resized, is public to enable calling it even if the child has a different class

Extending ofxBaseGui #2

---

libs/openFrameworks/video/ofGstUtils.h

On Yosemite 10.10.4 with Clang 6.1, projects that use GStreamer fail to compile because of this type mismatch.

Fix gst_element_query_duration argument type (int64_t to gint64).

---

libs/openFrameworksCompiled/project/makefileCommon/compile.core.mk
libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk
libs/openFrameworksCompiled/project/makefileCommon/config.project.mk

`OUPUT` is corrected to `OUTPUT` in all misspelt cases in the project make files.

Fix typo in makefiles

---

addons/ofxProjectGenerator/src/utils/Utils.cpp

For some obscure reason the VS2015 compiler seems to want to
optimise away digestString when compiling in optimised
Release mode.
This leads to a crash as reported by @DomAmato in #4155
Initialising `digestString`, then setting its value explicitly
appears to make it change its mind about the apparent
uselessness of the return value.
From the code in Utils.cpp#generateUUID I can't see an apparent reason
for the compiler to get so overzealous.

fix issue #4155

---

addons/ofxGui/src/ofxBaseGui.cpp
addons/ofxGui/src/ofxGuiGroup.cpp
addons/ofxOsc/src/ofxOscParameterSync.cpp
addons/ofxOsc/src/ofxOscParameterSync.h
libs/openFrameworks/types/ofParameter.h
libs/openFrameworks/types/ofParameterGroup.cpp

Getting rid of the "new" keyword in favor of std::make_shared when possible.
Clarify and document a complex ofParameter function that is efficient but difficult to grasp at first glance.

Const corrections and std::make_shared use.

---

libs/openFrameworks/types/ofParameter.h

Just renamed setWithoutEventNotifcations to setWithoutEventNotifications.
It was added a few days ago: #4176

Typo in ofParameter::setWithoutEventNotifcations

---

examples/sound/audioOutputExample/src/ofApp.cpp
examples/sound/soundPlayerExample/src/ofApp.cpp
libs/openFrameworks/sound/ofFmodSoundPlayer.cpp
libs/openFrameworks/sound/ofFmodSoundPlayer.h

adding `ofFmodSetBuffersize()` to set the buffersize of Fmodx before initialisation.
added `FMOD_System_SetDSPBufferSize` to `initializeFmod()`
allows to synchronize buffersizes of ofSoundStream and ofSoundPlayer.

Add of fmod set buffersize

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.h
libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

move properties into header file, avoid class extensions.
only use variables neede for videooutput if videooutput is used.

dont use class extensions in order ot make it compile for 32bit

---

scripts/ios/template/emptyExample.xcodeproj/project.pbxproj

this was tripping up the compiler for some reason and it was giving errors in xcode 6.4

removed blank lines from shellScript in ios xcode template project

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.cpp

This PR adds missing ofFbo id printings and a comment in bind() for people like me who may wonder for half an hour why their fbo isn't drawing :)

Print ofFbo id on warnings, add to bind() comments another possible warning trigger

---

libs/openFrameworks/3d/ofNode.cpp

closes https://github.com/openframeworks/openFrameworks/issues/4081

ofNode orbit fix; Now uses quaternions to avoid Gimball Lock.

---

addons/ofxProjectGenerator/src/projects/xcodeProject.cpp

this is a small fix which fixes a double parsing when find and replacing ../../.. paths inside the config file

fixes relative paths in osx templates project generation

---

.travis.yml
addons/.gitignore
addons/ofxUnitTests/src/ofxUnitTests.h
libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofUtils.cpp
scripts/ci/linux/build.sh
scripts/ci/osx/build.sh
scripts/dev/create_package.sh
tests/.gitignore
tests/utils/fileUtils/addons.make
tests/utils/fileUtils/src/main.cpp

some tests i've been using mainly for the changes in ofFileSystem + an OF addon for unit tests.
right now is pretty simple and could be integrated in the future with some already existing unit tests framework.
- The addon has a ofxUnitTestsApp that is an ofBaseApp so tests can implement it to be called with the proper OF initialization. Most tests only need to implement a `run()` method in that class
- It provides, test and test_eq methods by now that will fail if the result is not true or the passed parameters are not equal
- It also provides a colored log channel so the output from tests is easily checked
This is ready to be merged but mostly uploading it to test: #4285 which is working fine for me

unit tests

---

addons/ofxProjectGenerator/src/projects/baseProject.cpp

without this, I always end up with a line named "addons" in my addons.make

catch empty addon line in project generator

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

Warning said to use an explicit cast to remove warning.

Fix AVFoundationVideoPlayer warnings for OS X.

---

libs/openFrameworks/gl/ofGLRenderer.cpp

This seems to fix #3805. If no texture is bound just enable the appropriate client state and fill in the tex coord pointer. I hope I am not missing something.

Fix openframeworks/openFrameworks#3805

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.cpp

see the issue #4312 
@arturoc I think this should be good to merge - but maybe you could give the okay, just incase there was a reason the circle resolution wasn't being stored.

bugfix. stores circle resolution in current style. closes #4312

---

libs/openFrameworks/utils/ofUtils.h

I introduced a regression into ofToBinary when attempting to get rid of warnings.  The current version in the repo is wrong and doesn't make sense.  This is a fix that matches the old functionality.

Fix ofToBinary

---

addons/ofxNetwork/src/ofxUDPManager.cpp

The TARGET_WIN32 guard went missing in ofxUDPManager.cpp -- re-adding (otherwise compile fails in DEBUG mode). 
Tested on Android.

Re-added TARGET_WIN32 guards around logger calls.

---

addons/ofxNetwork/src/ofxUDPManager.cpp

Hi @arturoc, the log function to call is ofxNetworkCheckError() (wrapper for ofxNetworkCheckErrno()). 
Unfortunately eclipse didn't clean the project correctly and I didn't catch the error on testing. This patch should be correct however.
Thanks -- apologies about the trouble!

UDPManager updated network error log function

---

libs/openFrameworks/app/ofAppGlutWindow.cpp
libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofUtils.cpp
libs/openFrameworks/utils/ofUtils.h
tests/utils/fileUtils/src/main.cpp

In osx when OF starts it sets the current directory to the directory
where the exe is located and then uses a relative path from there to
correctly find the data folder.
This has several problems:
- The current working directory is not correct anymore, mostly for command
line applications is useful to know where the command was run from. This is
for example making the command line PG fail in osx and would require a hack
like https://github.com/openframeworks/projectGenerator/pull/22, in general
people would need to know that OF internally changes the cwd but even with
that the actual cwd is totally lost so there's no way to recover it except
by queryng $PWD which is not multiplatform
- If someone changes the current working directory using setcwd or std::current_path
the data folder won't …

Fixes osx ofToDataPath. See openframeworks/projectGenerator#22

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofFileUtils.h
libs/openFrameworks/utils/ofUtils.cpp
tests/utils/fileUtils/src/main.cpp

some fixes for https://github.com/openframeworks/openFrameworks/pull/4299 to keep returning relative paths on ofToDataPath

return relative ofToDataPath

---

examples/ios/iosCustomSizeExample/src/main.mm
examples/ios/iosNativeExample/src/main.mm
examples/ios/iosStoryboardExample/src/main.mm

making sure that a shared instance to the ofAppiOSWindow is not stored in the main.mm, since that prevents the window from being destroyed later in the app life cycle.

ios fixes for multi window examples.

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLProgrammableRenderer.h
libs/openFrameworks/gl/ofGLRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.h
libs/openFrameworks/gl/ofVbo.cpp
libs/openFrameworks/gl/ofVbo.h
libs/openFrameworks/types/ofBaseTypes.h

I have an index buffer into some particles that is sorted back to front, I'm trying to render the particles slice by slice and ran into some missing functionality, namely that there is no way to specify an offset into the index buffer that you want to use for drawing.
An example below:
```c++
#pragma once
#include "ofMain.h"
// ------------------------------------------------------------------------------------------------------------
//
class ofApp : public ofBaseApp
{
public:
// --------------------------------
void setup()
{
camera.setAutoDistance( false );
camera.setPosition( ofVec3f(0,1,8) );
camera.setNearClip( 0.01 );
camera.setFarClip( 64 );	
int numParticles = 512 * 512; 
ofVec3f size(12,3,6);
for( int i = 0; i < numParticles; i++ )
{
ofVec4f p(0,0,0,1); 
p.x = ofMap( i, 0, …
```

drawElements with an offset into the index buffer

---

libs/openFrameworks/utils/ofUtils.cpp

Fix ofJoinString and optimize it to do at most one memory allocation.

Fixes #4363  and avoids multiple memory allocations in ofJoinString

---

libs/openFrameworksCompiled/project/makefileCommon/compile.core.mk
libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk

if a cflag changes the makefile should recompile the whole project so the new flags affect all the files

makefile rule to recompile when flags change

---

libs/openFrameworksCompiled/project/android/gradle.properties

As reported in this issue https://github.com/openframeworks/ofSite/issues/315 a `gradle.properties` file is needed in the `/libs/openFrameworksCompiled/project/android` folder

Adding gradle.properties file

---

docs/android_studio.md

The old NDK info doesn't work with 0.9 and some settings need to be changed with current releases of Android Studio in order to compile.
Changed according to https://github.com/openframeworks/openFrameworks/pull/4374#issuecomment-141001075
I only mentioned that 0.9 is a minimum requirement so people don't try it right now with 0.8.4

Fixed Android Studio tutorial for 0.9

---

docs/android_studio.md

As reported in this thread http://forum.openframeworks.cc/t/error-building-the-androidemptyexample/20759/4, the old versions of the NDK are not working, the
r10e works

Correct wiki adding the working NDK version

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

Two fixes for avfoundationvideplayer:
1. memory leak: https://github.com/openframeworks/openFrameworks/issues/4401
2. texture cache freeze: https://github.com/openframeworks/openFrameworks/issues/4384

Bugfix avfvideo memleak

---

scripts/linux/archlinux/install_dependencies.sh
scripts/linux/archlinux_armv6/install_dependencies.sh
scripts/linux/debian/install_dependencies.sh
scripts/linux/fedora/install_dependencies.sh
scripts/linux/ubuntu/install_dependencies.sh

Hi,
i fixed the error #4427 in install-dependecies.sh due to the argument order for apothecary in cdee8cb. 
Cheers,
ni-cc

fixing error in install-dependencies.sh of cdee8cb

---

libs/tess2/include/tesselator.h

Fixes https://github.com/openframeworks/openFrameworks/issues/4437 (Font example renders really strange text on iOS)
Seems the Tess2 header reverted it's Apple Pre-Processor when it was recompiled.

Fix for iOS Font issues

---

addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.h
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.h

Addresses a few minor issues with the assimp loader. 
* Mainly fixes an crashing issue with animations not being counted properly
* Brings forward declarations in line with assimp library objects
* More explicit deletion of scene object, to secure assimp has freed the old scene when new scene is loaded.
More details in individual commits. 
Closes #4337

Fix assimp anim load

---

addons/ofxiOS/src/core/ofxiOSAppDelegate.mm
examples/ios/iosExternalDisplayExample/src/ofApp.mm

When using AirPlay with Mirroring on, All apps and views of the iOS device are mirrored on the external display.
Default action for an iOS Application after Mirroring is trigged is to display as normal, just also on the external screen. This still occurs with an oF iOS Application if the device starts AirPlay Mirroring and then proceeded to open an oF iOS App.
- If the user starts an iOS oF app first and then proceeds to turn on AirPlay mirror while the iOS oF application is active, the screen shows a black screen hiding the main view of the App.
This is defined by default the ofxiOSAppDelegate, which creates a Black screen to hide the iOS oF Application display in the case the user wants to hide the view (not default behaviour by iOS).
Lets lose that hide screen by default, and if …

iOS - Fix for AirPlay Mirroring BlackScreen by Default - Post App Launch

---

libs/openFrameworks/graphics/ofPixels.cpp
libs/openFrameworks/graphics/ofPixels.h
libs/openFrameworks/video/ofGstUtils.cpp

new setFromAlignedPixels gets taken when PixelFormat == OF_PIXELS_I420.

dirty fix for #3404

---

libs/openFrameworks/3d/of3dPrimitives.cpp

Correct strides for vertices and indices in the 3d primitives since the updated resolution changes.
Fixes this issue: https://github.com/openframeworks/openFrameworks/issues/4218

Bugfix of3 d primitives example

---

scripts/apothecary/apothecary

for apothecary depends when launching a new apothecary script the cwd was not being correctly set back to the apothecary directory. 
this pr fixes that issues.

bugfix for apothecary script fixes depends change directory - addresses #4481

---

libs/openFrameworks/gl/ofMaterial.cpp

Because the old implementation of `ofMaterial.cpp` mixed the `STRINGIFY`preprocessor macro with GLSL preprocessor directives, the behaviour of the c preprocessor for this file was undefined.
This lead to strange GLSL code in VS2015 builds, and `ofMaterial` may have been considered broken on this platform(s).
To close #4495, this PR suggests & implements the following:
* Using **Raw String Literals** for inline GLSL code instead of `STRINGIFY`. This allows us to
concat different cpp constants based on the cpp build environment. Raw String Literals are a C++11 feature. See: http://en.cppreference.com/w/cpp/language/string_literal
* Anything within Raw String Literals is not interpreted by the preprocessor, also escapes are not scanned. It is literally a literal.
Tested on XCode 7.1 / clang …

fix area lights for programmable renderer

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroid.java
libs/openFrameworksCompiled/project/android/config.android.default.mk

I had an issue having an android app with a app name including a space. The bin/data folder got saved into a .zip file using the name of the folder the app is in. When unzipped, it used the app name (so the label of the app), these where not the same in my case since i wanted a space in my app name. 
This PR is making a fixed name (`ofdataresources`) instead for the data zip folder. I cant think of issues having a fixed name instead of a dynamic names based on app name.

Android: use fixed data zip file name

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroid.java
libs/openFrameworksCompiled/project/android/config.android.default.mk

1. Build x86 native lib to libOFAndroidApp_x86.so (instead of libOFAndroidApp.so)
2. try to load x86, and if failed, load the arm. This resolves crashes on arm emulated asus devices that report arm instead of x86.
See discussion here: http://forum.openframeworks.cc/t/ofandroid-doesnt-work-on-x86-devices/21164/25

OFAndroid - try to load x86 lib before arm to resolve houdini crashes

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidVideoGrabber.java
addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp
addons/ofxAndroid/src/ofxAndroidVideoGrabber.h
examples/android/androidCameraExample/src/ofApp.cpp
examples/android/androidCameraExample/src/ofApp.h
scripts/ci/android/install.sh

This PR tries to improve the android camera. 
- By default it will now select the best frame rate available instead of first (that on nexus 6 is 15fps). Fixes #4502 
- ```getPixels()``` now works, and the pixel conversion and copying only happens if needed (drastically improves performance). Fixes #3752
- Running without calling ```getPixels()```allows the code to run 30fps in full HD on a Nexus 6
- Now the deviceID can be changed while the camera is running, so its now possbile to swap camera easily
- ```listDevices()``` is now implemented 
- Functions for getting the facing and orientation of cameras
- Removed legacy code regarding supporting very old API 8 that didn't support surface textures
- Updated android grabber sample to show more functionality 
There are some outstanding …

Android camera refactor

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofBaseApp.h
libs/openFrameworks/events/ofEvents.cpp
libs/openFrameworks/events/ofEvents.h

When scrolling, `ofMouseEventArgs` would report the scroll
offset in the same place where it usually would report the
current mouse coordinates: `ofMouseEventArgs.[xy]`
This meant that to find out where on screen a scroll event
occured, you had to call `ofGetMouse[XY]` when responding to a
scroll event.
All other mouse events, e.g. Press/Release pass on the
current mouse position as `ofMouseEventArgs.[xy]`.
This brings the scroll event into line, by:
+ adding `scrollX` and `scrollY` to `ofMouseEventArgs`
+ passing the current mouse position in `.x` and `.y`,
in line with other mouse event responders
I've double-checked our legacy GLUT window, and
ofAppEGLWindow if they needed updating too, but these window
classes appear not to capture scrolling events anyway.
Closes #4523

fix ofMouseEventArgs for scroll event

---

libs/openFrameworks/3d/ofEasyCam.cpp

Unfortunately #4524 introduced an issue with ofEasyCam, which was tracking the mouse argument's `.y` instead of the new `.scrollY`.
This PR fixes this.

fix ofEasyCam scroll behaviour

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

need to set internal state on load otherwise first load after close has no effect.

ofAVFoundationPlayer close-open fix

---

addons/ofxGui/src/ofxSlider.cpp

This updates `ofxSlider` to use the `.scrollY` property of `ofMouseEventArgs` instead of `.y`.
I went through all core ofAddons searching for mentions of mouse scrolls, ofxSlider was the only element that appears to need updating.
Incidentally, I found that #4524 might have fixed an issue with `ofxGuiGroup::mouseScrolled`:
Before, the following method would have returned unpredictable results, since `args.x` and `args.y` would have been referring to scroll coordinates, not mouse coordinates.
```
bool ofxGuiGroup::mouseScrolled(ofMouseEventArgs & args){
ofMouseEventArgs a = args;
for(std::size_t i = 0; i < collection.size(); i++){
if(collection[i]->mouseScrolled(a)){
return true;
}
}
if(isGuiDrawing() && b.inside(ofPoint(args.x, args.y))){
return true;
}else{
return false;
}
}
```
With …

fix scrolling behaviour for ofxSlider

---

addons/ofxiOS/src/core/ofxiOSAppDelegate.mm

Fixes: iOS #4544 "Background Apps May Not Execute Commands on the Graphics Hardware"

Fix for iOS Backgrounding Crash #4544

---

libs/openFrameworks/utils/ofConstants.h
libs/openFrameworks/utils/ofUtils.cpp

Fix for #4559 adding OF_TARGET_WINGCC to the ofTargetPlatform enum in ofConstants.h. This fixes build issues on Windows 10 when using GCC with Msys2.

Updated OF_TARGET_WINGCC changed to OF_TARGET_MINGW 

---

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp

see #4553 
added checks to avoid calling glPolygonMode too many times.

bugfix for drawing wireframe and verts on an assimp model. closes #4553

---

addons/ofxOpenCv/scripts/formulas/opencv.sh

The fixes are summarized as follows:
- add `-a` option to `tee` to append outputs to the log file
- redirect stderr to stdout and save both to log file
It could be useful for debugging.
Please see the second commit for the actual changes. First one tweaks trailing white-spaces (my editor automatically does).

Improve logging while building opencv in osx

---

addons/ofxOpenCv/scripts/formulas/opencv.sh

The cmake cache files wasn't removed correctly before, that caused annoying non-deterministic builds.

Fix non-deterministic opencv build on osx

---

addons/ofxNetwork/src/ofxNetworkUtils.h
addons/ofxNetwork/src/ofxTCPManager.cpp

This should get basic TCP communication working again for all platforms.
The macro ofxNetworkCheckError() and the function it calls ofxNetworkCheckErrno() make no attempt to convert parameters to strings avoiding calling any function that might reset the errno or (WSA)GetLastError() value.
ofxNetworkCheckErrno() will not generate a log entry if (WSA)EWOULDBLOCK is the error.
ofxTCPManager::Receive() checks the error returned from ofxNetworkCheckError() and sets the return value to 0 (instead of -1) if (WSA)EWOULDBLOCK is returned, indicating no data available and not an error.
On some OSs EAGAIN might be defined as the same or a different value from EWOULDBLOCK.

Addresses 4 issues related to #4556:

---

examples/ios/iosNativeARCExample/src/AppViewControllers/CircleAppViewController.mm
examples/ios/iosNativeARCExample/src/AppViewControllers/ImageAppViewController.mm
examples/ios/iosNativeARCExample/src/AppViewControllers/SquareAppViewController.mm
examples/ios/iosNativeARCExample/src/AppViewControllers/TriangleAppViewController.mm

- Fixes missing ofAppiOSWindow import
As reported here: http://forum.openframeworks.cc/t/member-access-into-incomplete-type-ofappioswindow/21462

iOS Example fix for iOSNativeARCExample

---

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp

fixes regressions in 0.9.0 
doesn't solve the ability to do proper wireframe outlines on ES - but that was the case for 0.8.4 as well.

better fix for drawing wireframes on non GLES addresses #4553

---

examples/events/multiWindowOneAppExample/src/main.cpp

added a commented line about sharing window contexts, which is necessary to share pixels between windows. this might be helpful to include in the example if it's not clear from the docs.

added note about sharing context between windows

---

libs/openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj/project.pbxproj
scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

Fixes a lot of the issues in: https://github.com/openframeworks/openFrameworks/issues/4619
1. Fixes FMOD using the **executable path**. Moves to the **framework directory**.
2. Adds a **new Run Script** post build to **Code sign frameworks or dylibs** found in the App Package. (Automatic Script, Only runs if code signing set and entitlements).
3. Adds **Copy Resources into App** Package (bin/data) like iOS
4. Fixes Installation Directory bug (Needed to be **/Applications**) instead of $HOME/Applications
5. The **Skip Install** flag is set to YES. (For archiving/deployment), fixes Organizer issues.

OSX AppStore Fixes

---

libs/openFrameworks/3d/ofNode.cpp
libs/openFrameworks/3d/ofNode.h

Instead of using {0,1,0} get's the vector of the camera position to
the lookAt point. then figures out the rotation that transforms {0,0,1}
into that vector and rotates {0,1,0} by that rotation to get the up vector.

ofNode: better default for up vector on lookAt. Closes #4594

---

libs/openFrameworks/utils/ofThread.cpp

Sometimes when trying to join a thread that has already been detached
poco throws an exception. This catches it so the app doesn't crash

ofThread: fix thread join

---

libs/openFrameworks/graphics/of3dGraphics.cpp

The cones used to draw arrow heads were drawing at the wrong position, offset slightly (0.5 * headSize) from where they should be. This was especially apparent when arrowheads were larger.
This commit fixes this.
Before (was): 
After this fix:

fix an issue with arrow heads not drawing centered

---

libs/openFrameworks/types/ofParameter.h

ofParameter seems to have its internal value max() set incorrectly.  Both min and max are set to `of::priv::TypeInfo<ParameterType>::min()`.  This fixes that.

Bug fix - Set max to max().

---

libs/openFrameworks/graphics/ofPixels.cpp
libs/openFrameworks/graphics/ofPixels.h

solves a problem with planes not referencing the original and instead making a copy

ofPixels: add move constructor and move return values

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofUtils.cpp
libs/openFrameworks/utils/ofUtils.h

- moveTo was trying to move with the stream opened which failed on windows
- create was loosing the binary mode when changing the mode
- getHomeFolder wash using getenv which might fail
- adds ofGetEnv for multiplatform getenv

ofFileUtils: fix several problems in windows:

---

libs/openFrameworks/utils/ofURLFileLoader.cpp
libs/openFrameworks/utils/ofURLFileLoader.h

Adds support for sending POST requests. still doesn't support sending form fields or files, only request body.
This is needed to report tests results in appveyor, the windows testing platform

ofURLFileLoader: add basic support for POST method

---

libs/openFrameworks/communication/ofSerial.cpp

ofSerial::readByte not returning OF_SERIAL_NO_DATA on Windows #4630

ofSerial::readByte not returning OF_SERIAL_NO_DATA on Windows

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h

This is a small fix for #4639 using an ofRectangle.
For some reason, there was an update to ofAppGLFWWindow.cpp line 156 that wasn't merged when I fetched for upstream, so that is reflected in the small whitespace change there.

save window position on OS X before going fullscreen

---

libs/openFrameworks/video/ofAVFoundationPlayer.h
libs/openFrameworks/video/ofAVFoundationPlayer.mm

oF requires OSX 10.7, iOS >= 5, bith do support textureCaches. No need for check.
fixes: https://github.com/openframeworks/openFrameworks/issues/4073

remove bTextureCacheSupported. fixes #4073

---

addons/ofxiOS/src/core/ofxiOSViewController.mm

Fix for Cannot find protocol declaration for 'UIViewControllerTransitionCoordinator' iOS <8 SDK
Fixes #4627
It was ```NS_AVAILABLE_IOS(8_0);```.

Fix for Cannot find protocol declaration iOS UIViewControllerTransitionCoordinator

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

`settings.monitor = 1;
settings.windowMode = OF_FULLSCREEN;`
will now work on OSX, as long as the position is not set in the settings.
Must set the window shape and then the position, as previously commented here
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L707

Bugfix glfw fullscreen multi - fix for setting monitor and fullscreen in glfw settings on OSX

---

libs/openFrameworks/graphics/ofPixels.cpp
libs/openFrameworks/video/ofDirectShowPlayer.cpp
libs/openFrameworks/video/ofDirectShowPlayer.h

This adds support for setPixelFormat() for the directshow player which allows also to play videos with widths that are not multiple of 4. there's probably someway to have the library pad the video if it's not a standard size but by now this at least allows to play those videos by adding:
```cpp
player.setPixelFormat(OF_PIXELS_BGRA);
player.load("weird_size_video.mp4")
player.play();
```
Closes: #4679

DS VideoPlayer: add support for all different RGB formats

---

libs/openFrameworks/graphics/ofPixels.cpp

Using Visual Studio, calling getNumChannels() inside the for each pixel
loop has a huge effect on performance. By simply caching this result we
can get a 20x speed up. 180 -> 9ms on an 1920x1080 RGB to grayscale.
The difference with Xcode is minimal.

optimise ofPixels::setImageType() on Windows VS

---

libs/openFrameworks/video/ofAVFoundationPlayer.h
libs/openFrameworks/video/ofAVFoundationPlayer.mm

I had to add back in the bool used to check if the player should use the cached texture. 
This should be a good fix for #4722
I tested with a 1080p video and the average fps difference between the ARB approach with texture caching and the nonARB with no caching was 150 fps vs 148 fps.

bugfix for AVF video player not drawing if ARB textures are enabled Closes #4722

---

libs/openFrameworks/math/ofQuaternion.h

i fixed them with global operator overload.
reason:
now, `operator<<` and `operator>>` in `class ofQuaternion`.
but this is not call forever.
and if we call `<<` like following:
```
ofQuaternion q;
ofLogNotice() << q;
```
this code will run.
but, in fact, this code calls `ostream &operator<<(ostream &os, const ofMatrix4x4 &mat)` with implicity conversion.

ofQuaternion operator<<, operator>> is wrong.

---

scripts/apothecary/android_configure.sh

The current build script only supports linux, this fixes this problem

Support darwin platform in apothecary android builds

---

libs/openFrameworks/gl/ofShader.cpp

ofShader's assignment constructor was retaining shader type
instead of id.
In case you ever wondered about an error message a la:
"something's wrong here, releasing unknown shader id xxx"
when quitting your app, this is because when copy-assigning
shaders, the wrong id would have been stored, thus upon
destruction of the ofShader object the mismatch appears.

fix shader assignment constructor

---

libs/openFrameworks/video/ofAVFoundationVideoPlayer.h
libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

Updated: Ok, now I think I finally fixed a real issue by https://github.com/openframeworks/openFrameworks/commit/fdea3689050d39b133ade2dac2293d2a975ce981. The reason of crashes is that AVPlayerItemVideoOutput delegate wasn't released property. See http://stackoverflow.com/questions/29103254/copy-helper-block-crash-in-avfoundation for explanation.
Also, I added a few cleanup that I noticed while debugging. 
There are two commits in this PR:
- [ofAVFoundationPlayer] Internal AVFoundationVideoPlayer will be dealloced synchronously instead of asynchronously. This ensures that dealloc runs before the ofAVFoundationPlayer's destructor finished.
- [AVFoundationVideoPlayer] Avoid unloading a video twice. This should prevent unexpected future or current bugs.
Let me illustrate the timings of the …

[AVFoundationPlayer] Fix crashes when unloading a video

---

libs/openFrameworks/video/ofAVFoundationPlayer.h
libs/openFrameworks/video/ofAVFoundationPlayer.mm
libs/openFrameworks/video/ofAVFoundationVideoPlayer.h
libs/openFrameworks/video/ofAVFoundationVideoPlayer.m
libs/openFrameworks/video/ofVideoPlayer.cpp

- Also adds a couple of extra safety checks for null ptr textures. 
- Removes unneeded error messages when texture hasn't yet been loaded. 
closes #4629
The main change here is that ofAVFoundationPlayer.mm now uses the Objective C **bLoaded** state for ofAVFoundationPlayer::isLoaded instead of the **bReady** flag. bReady isn't true immediately but only when the first frame can be delivered and that can take a few mills to happen and it doesn't seem possible or practical to block until thats true as well. 
This means in synchronous loading mode after the load function is called isLoaded will now return true. 
The player still takes time to have frames ready, but as long as you wait for the is FrameNew() you will have good pixels ( which is what you should wait for anyway ). 
For anything …

bugfix PR now correctly shows when a video is loaded for AVF based players. 

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

Its not ideal that we have to do this, but I think this is due to OS X having lower left as the origin for cocoa windows. ( http://stackoverflow.com/questions/12408334/cocoa-nsview-origin-x-at-the-bottom ) 
If we want a quick fix that works this should cover it, but it might be a good idea to file an issue with GLFW and get it fixed there.

bugfix for OS X. stops window moving on ofSetWindowShape closes #4753

---

libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk

Upgrade of MSYS2 could break copy_dlls. Try not to rely on specific version.

Improve copy dlls

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofFileUtils.h
tests/utils/buffer/addons.make
tests/utils/buffer/buffer.sln
tests/utils/buffer/buffer.vcxproj
tests/utils/buffer/buffer.vcxproj.filters
tests/utils/buffer/buffer.vcxproj.user
tests/utils/buffer/icon.rc
tests/utils/buffer/src/main.cpp

after doing some better benchmarkings it seems as fast as using memcpy once removed the extra insert for the null terminator. @elliotwoods can you test both PR's with your application? i'd prefer to merge this one by now since it's implementation is much safer by not depending on tracking the size manually

ofBuffer reserve without memcpy

---

.gitignore

From forum post https://forum.openframeworks.cc/t/branches-and-my-of-folder/22277, to allow for folders named apps* in the of directory.

add any folder with name prefix apps to gitignore

---

libs/openFrameworks/types/ofParameter.cpp
libs/openFrameworks/types/ofParameter.h

which it's pretty useless by itself but allows to add a parameter to
an `ofParameterGroup` that will end up represented as a button in an
ofxGui.
an `ofParameter<void>` can't be set or have operators... but has a
`trigger()` method that calls the corresponding event.
This still doesn't add the posibility to add an `ofParameter<void>` to
an `ofxPanel`.
ping @frauzufall

ofParameter: add ofParameter<void>

---

libs/openFrameworks/utils/ofThread.cpp
libs/openFrameworks/utils/ofThread.h
libs/openFrameworks/utils/ofURLFileLoader.cpp

Solves #3999 but introducing std::thread in ofThread this late might be problematic, i don't mind moving #3999 and this PR back to next release.
This also removes some methods in ofThread which is not possible to implement with std::thread anymore like getting the current thread as an object or checking if the calling thread is the main thread. in any case using those methods were not very good practice i think.
std thread doesn't have a numeric id so this returns now std::thread::id instead of int we could keep track of each created thread using a static variable in the class but i think is better to just expose the native id

refactor ofThread to use std::thread instead of Poco::Thread

---

libs/openFrameworks/gl/ofFbo.cpp
libs/openFrameworks/gl/ofFbo.h

In order to get better performances when copying a FBO to a PBO, I have implemented the following method:
```
void ofFbo::copyTo(ofBufferObject & buffer) const{
if(!bIsAllocated) return;
bind();
buffer.bind(GL_PIXEL_PACK_BUFFER);
glReadPixels(0, 0, settings.width, settings.height, ofGetGLFormatFromInternal(settings.internalformat), ofGetGlTypeFromInternal(settings.internalformat), NULL);
buffer.unbind(GL_PIXEL_PACK_BUFFER);
unbind();
}
```
When copying big FBOs, using ```glReadPixels()``` instead of ```glGetTexImage()``` (via the ofTexture of the ofFbo) improves the performances quite substantially. (~20ms instead of ~80ms on a Mac Book Pro w/ a NVIDIA GeForce GT 650M 1024 MB)
Here a simple test app to see the differences in performance: …

Added a method to copy a fbo to a pbo using glReadPixels.

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

since glyphPositions are `emplaced` back, visual studio (and possibly
other compilers) warn bitterly about implicit type conversion.
this pr makes the conversion explicit to end the whining.
Since we're storing the glyph position in an ofVec2f and we don't have
an integer vector type there's no way not to have a type conversion at
some point.

fix warning in ofTrueTypeFont

---

libs/openFrameworks/events/ofEvent.h
libs/openFrameworks/events/ofEventUtils.h
libs/openFrameworks/events/ofEvents.cpp
tests/events/events/addons.make
tests/events/events/events.sln
tests/events/events/events.vcxproj
tests/events/events/events.vcxproj.filters
tests/events/events/events.vcxproj.user
tests/events/events/icon.rc
tests/events/events/src/main.cpp

ofEvent now supports adding std::function as a listener, that allows among other things:
- pass a lambda function as a listener
- pass a function with a different signature as a listener.
For example to pass a lambda as a listener now you can do:
```cpp
ofEvents().mouseMoved.newListener([](ofMouseEventArgs & mouse){
cout << mouse << endl;
});
```
Since std::function doesn't have an equality operator, there's no way to
unregister an event the old way calling `ofRemoveListener(function)` since
that required to compare the passed function with every other registered in
the event and remove it if it was the same.
`ofRemoveListener`also has some other problems, for example, the typical pattern:
```cpp
class MyClass{
public:
MyClass(){ …
```

std::function listeners for ofEvent + unregister token. Replaces #4392

---

libs/openFrameworks/types/ofParameter.h

If you want to use an `ofEventListener` to respond to an `ofEvent`, you best create one using a templated factory method which is part of `ofEvent<T>`.
Since ofParameter shields users from accessing its data directly by holding it inside a private data `obj`, there is no way to call the `newListener` factory method on a parameter changed event (`changedE`) which you want to observe.
This PR proposes to add a `newListener` method to `ofParameter`, which will, based on dark templating magick, forward any of its parameters to the `ofEvent` object held by the private `ofParameter::obj`.
I wish there was a simpler way, but this seems to me the best way to observe an ofParameter and responding to any changes using a lambda.
Minimal testcase: …

add newListener() method to ofParameter

---

libs/openFrameworks/utils/ofThread.h

This seems to have regressed here 22e1b1de2ea4775761093c3a8bf39948cf1b4849.
Herb Sutter et al seem to think a mutable mutex is just fine.
http://herbsutter.com/2013/01/01/video-you-dont-know-const-and-mutable/

Revert to mutable mutex in ofThread.

---

libs/FreeImage/include/FreeImage.h

Fixes issues with OS X and BOOL issues on some compilers.
Only seems to be an issue for older compilers / systems.
Older issues that solved this: 
(2009) #76
(2013) #1889
This has cropped up again in 2015 due to updating to 3.17.0 and this no longer being an issue on Modern OS X Xcode compilers.
Previous PR:
#4833

FreeImage fix for OS X and Windows

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

Fix for #4842, #4746 & [datgui#39](https://github.com/braitsch/ofxDatGui/issues/39) where the window instance's dimensions were being multiplied by the pixelScreenCoordScale within the internal resize callback. The problem this created is that the dimensions are also multiplied by pixelScreenCoordScale within any query against the window e.g. getWidth, getHeight, getWindowSize etc so the multiplication was happening twice resulting in those calls returning a 4x value instead of a 2x value when pixelScreenCoordScale is greater than 1.

fix for #4842 removing pixelScreenCoordScale multiplier from window resize callback

---

libs/openFrameworks/types/ofBaseTypes.h

Previously stated the value was in milliseconds but it is actually representing seconds.

Fix documentation for ofBaseVideoPlayer::getDuration()

---

.gitignore

Ignoring addons.make in examples folders, so that project generator doesn't create a great deal of new untracked files to the local git projects.

ignore addons.make in examples folders

---

libs/openFrameworks/gl/ofTexture.h

Currently this is a protected member - by making it public it allows users to allocate and loadData without having to modify glUtils/ofTexture for formats such as GL_BGRA/GL_UNSIGNED_INT_8_8_8_8_REV and GL_RGB_422_APPLE/GL_UNSIGNED_SHORT_8_8_APPLE which both require a mismatch between internal type and glFormat to work correctly.

Make ofTexture::loadData with different glFormat/glType public

---

libs/openFrameworks/3d/ofMesh.cpp

When loading meshes from .ply files, color vertex attributes may be specified as `uchar`, not just float. 
The existing implementation was not allowing for this, and `uchars` were righteously (though not rightfully) interpreted as `float`s.
This PR suggests adding a flag for the vertex color type derived whilst reading the file's manifest section.
It then makes interpretation of color data type dependent on this flag, and scales `uchar` color data to normalised float range, so that both types, either `uchar` or `float` may be used to the same effect.
Fixes #4935

Fix for ply mesh data loader with uchar color type

---

addons/ofxAndroid/src/ofxAndroidVideoPlayer.cpp

The ofxAndroidVideoPlayer doesn't close properly.
I Play a video file, I stop it, I pause-resume the app and the video restarts again himself without calling him. Another issue, not closed mediaplayer causes ioConfigChanged() error on some devices when trying to start a soundplayer after the app resume.
I see that the inside of the close() method is empty. I added the necessary code lines inside this method.

update to close Android video player properly

---

tests/math/ofNodeRegressionTests/addons.make
tests/math/ofNodeRegressionTests/icon.rc
tests/math/ofNodeRegressionTests/ofNodeRegressionTests.sln
tests/math/ofNodeRegressionTests/ofNodeRegressionTests.vcxproj
tests/math/ofNodeRegressionTests/ofNodeRegressionTests.vcxproj.filters
tests/math/ofNodeRegressionTests/ofNodeRegressionTests.vcxproj.user
tests/math/ofNodeRegressionTests/src/main.cpp

+ these tests to help transition to glm by testing current ofNode
behaviour against glm calculated ofNode behaviour
+ the tests currently focus on orbit, roateAround, and some
basic parenting
+ these can in the future be extended and used to test ofNode more
thoroughly.

add ofNode regression tests

---

libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj

+ previous openframeworks project settings for 64 bit visual studio
compiles would cause "Browse Information" to be generated.
These *.BCR files are deprecated, and would emit error messages during
first compile. The next compile would fail since Visual Studio
couldn't read the file, meaning you would have to do a full rebuild
everytime you wanted to compile a 64bit app.
In 32 bit, we rightly had these BCR Files not generated. This PR
proposes to bring 64 bit in line with 32 bit, and to not create these
files and with that the compile problem in the first place.

fix issue with 64 bit visual studio recompiles

---

addons/ofxOsc/src/ofxOscReceiver.cpp
addons/ofxOsc/src/ofxOscReceiver.h

for example, we wrote like this:
```cpp
ofxOscReceiver receiver;
void setup() { receiver.setup(9005); }
```
and we do in terminal.app (or similar)
```
$ nc -4u localhost 9005
> a
```
maybe your app got crush.
so, this process is too extreme.
but, recently, some app got bad packet and crushed 10 machines at same time. (maybe bad packet is broadcasted)
i think this is very critical.
and, more critical point is "we cannot catch this exception from the outside now."
now, this PR is first aid.
(but, i hope to be accepted this PR as soon as possible.)
i think good solution is:
doing propagate exception with `std::promise`, `std::future`, or `std::async`.
or, simply, replace ofLog (is implemented now) with send error message with `ofThreadChannel` when catch exception. and notify error.
or, is …

[proposal] make ofxOsc strong

---

addons/ofxOpenCv/src/ofxCvImage.cpp

Fix for the following clang warning:
~~~
openFrameworks/addons/ofxOpenCv/src/ofxCvImage.cpp:394:5:
'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'?
~~~

ofxCvImage pts array array delete fix

---

libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofAppRunner.h
libs/openFrameworks/app/ofMainLoop.cpp
libs/openFrameworks/app/ofMainLoop.h
libs/openFrameworks/events/ofEvents.cpp

Fixes #4769 problems when trying to access events before the window is setup and #5028 problems when trying to remove events after the window is gone.

ofEvents/App: when trying to access events check that events are already initialized

---

libs/openFrameworks/app/ofAppBaseWindow.h
libs/openFrameworks/app/ofAppGlutWindow.cpp
libs/openFrameworks/utils/ofConstants.h

glx includes several X headers which defined several macros with very
common names so it's really common to have clashes with those names.
this moves that header include into the cpps that need it and uses
forward declarations in the headers that needs them

Don't include glx.h globally on linux

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h

* fixes a bug where HiDPi projects would not get the correct
ofGetWidth() and ofGetHeight() values. This bug may have
been introduced recently with some essential linux fixes.
* adds a comment to clarify meaning of currentW and windowW,
one being the current virtual (possibly scaled pixel) and
the other the physical 1:1 monitor pixel.
* tested on os x with both retina and non-retina screens,
fullscreen + fullscreen restore.
* does not query glfwWindowSize but uses cached values to
remain true to the earlier linux fix.
* Uses callback return value to retrieve new window size
when window resized.

fix some issues with HIDPI (Retina)

---

addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp

This adds support for the native pixel format NV21 of the android video grabber in the returned ofPixels. 
ofPixels does not support OF_PIXELS_NV21 very well, but it's useful for advanced pixel processing in openframeworks where you need the native pixels for better performance just using ofPixels for passing the data on.

Add support for OF_PIXELS_NV21 in android video grabber

---

addons/ofxOpenCv/addon_config.mk

the addon_config.mk reffered to armeabi libraries, but they dont exist. Instead the x86 libs should be pointed to.

Update ofxOpenCv addon_config for android

---

libs/openFrameworks/3d/ofNode.cpp
libs/openFrameworks/3d/ofNode.h

+ safer destruction of ofNode
ofNodes with parents/children would not properly destroy,
since the destructor in ofNode would stumble over an
invalidated iterator since the children's list of a node
would get altered when deleting a child's parent's
children list, which points back, don't ask a genealogist,
to the object itself.
+ clear parent in setParent if parenthood is re-assigned
when re-assigning parenthood to an object that already had
a parent, listeners assigned by the previous parenthood were
not cleared. This should be fixed  now.
+ clear up parameter ambiguity in ofNode::setParent
To increase readability, the parameter in the member
function referring to the parent to be set is renamed.

fix ofNode destructor when parented

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroid.java
addons/ofxAndroid/src/ofAppAndroidWindow.cpp
libs/openFrameworks/events/ofEvent.h
libs/openFrameworks/events/ofEventUtils.h
libs/openFrameworks/events/ofEvents.cpp
libs/openFrameworks/events/ofEvents.h
tests/events/events/src/main.cpp

Events: return true in notify if event is attended. We were using ofEventAttendedException cause it was the only way to stop the event propagation in poco but that's not necessary any more.
Also fix ambiguities on add/remove listeners for lambdas and plain functions and use all this in android

Fix events

---

libs/openFrameworks/types/ofParameter.cpp
libs/openFrameworks/types/ofParameter.h
libs/openFrameworks/types/ofParameterGroup.cpp

This adds remove functions to ofParameterGroup. I didn't really know how to handle generic parameters so right now it just compares type and name. Currently this won't work if two children have the same name but it looks like this is an issue with the parameter group anyways, so I added a warning.
I also tried to automatically remove a child from a parent when the parameter gets dereferenced. Like:
```
ofParameterGroup group;
ofParameter<int>* test = new ofParameter<int>();
group.add(test->set("test", 10));
delete test;
```
This won't work though because parameter groups store their children as shared_ptr. This makes sense if a user does not keep track of all parameters themselves. But I feel like we usually do and at least for me this resulted in some unexpected behavior where I wasn't …

Feature ofParameterGroup::remove(ofParameter)

---

addons/ofxOpenCv/src/ofxCvBlob.h

Currently, calling `ofxCvBlob.draw()` will leave the drawing color set to `0xff0099` (pink) with no fill. This PR simply adds push/pop style guards in the blobs drawing function, to prevent trampling the users styles.

push and pop styling when drawing OpenCV blobs

---

addons/ofxiOS/src/core/ofxiOSEAGLView.h
addons/ofxiOS/src/core/ofxiOSEAGLView.mm
addons/ofxiOS/src/core/ofxiOSViewController.mm

I have a hybrid c++/ObjectC app, so I have additional, non OF view controllers. I had a weird bug that if I have a finger down while going to a different view controller, that touch id is gone forever, and won’t be received again. This created issues with gesture recognition. I propose a small fix - to reset the touches dictionary in viewWIllAppear. I tested it in production scenarios and it works great. I saw no adverse affects for this. And it’s also a straight forward.

ofxiOSEAGLView - reset touches dictionary before the view appears

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

bugfix #5096. The key_cb was trying to get the window being detroyed.
Tested on MSYS2 only.

Unregister GLFW callbacks when closing GLFWAppWindow

---

libs/openFrameworks/events/ofEvents.cpp

Currently, supplying a negative framerate to `ofSetFrameRate()` will produce the following segfault:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ffacb0 in clock_gettime ()
```
This PR allows negative framerates to make time go backwards.
Just kidding.
Uses existing handler to mark the framerate as "not set".

handle negative framerate requests

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroid.java
addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidLifeCycleHelper.java
addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFOrientationListener.java
addons/ofxAndroid/src/ofAppAndroidWindow.cpp
addons/ofxAndroid/src/ofxAndroidApp.h
addons/ofxAndroid/src/ofxAndroidUtils.h
libs/openFrameworks/app/ofMainLoop.cpp

Copy of #4516  solving merge conflict after android refactor
- Implements `deviceOrientationChanged(ofOrientation newOrientation)` in ofxAndroidApp like in iOS that gets called whenever the orientation on the app is changed
- Implements support for `ofSetOrientation(OF_ORIENTATION_90_RIGHT)` and `ofSetOrientation(OF_ORIENTATION_180)` (these were implemented as their flipped versions before)
Orientation event can be tested with following gist in ofApp.h
```{.cpp}
void deviceOrientationChanged(ofOrientation newOrientation){
ofLogNotice("ANGLE")<<ofOrientationToDegrees(newOrientation);
}
```

Android orientation event

---

libs/openFrameworks/graphics/ofImage.cpp
libs/openFrameworks/graphics/ofImage.h

Currently, `ofImage`'s move constructor performs a clone, as noted in #5034. This PR uses `std::move` to move pixel and texture data from the parent image. The parent is left `clear()`ed after the move.
I tested it with this app, on Fedora with gcc:
```c++
#pragma once
#include "ofMain.h"
class ofApp : public ofBaseApp{
public:
void setup(){
a.load("of.png");
ofSetFrameRate(1);
};
void draw(){
ofBackground(0);
ofImage b = a;
ofImage c = std::move(b); // tests move constructor
//ofImage c; c = std::move(b); // tests move assignment
b.draw(0, 0); //should always draw black and print "ofGLRenderer: drawing an unallocated texture"
c.draw(256, 0); //should draw correctly
};
private:
ofImage a;
};
```

implemented move constructor for ofImage

---

libs/openFrameworks/graphics/ofGraphics.cpp
libs/openFrameworks/utils/ofThreadChannel.h

hey!
2 little fixes
1. ofBackgroundGradient currently uses ofGetWidth rather than ofGetViewportWidth, which means it doesnt' work with viewports.#5043
2. fix spurious wake in ofThreadChannel #4946

fixes to ofBackgroundGradient and ofThreadChannel

---

libs/openFrameworks/utils/ofLog.cpp
libs/openFrameworks/utils/ofLog.h

hey!
here's a small fix which makes the static padding variable dll-safe
i.e. when you're dynamically loading a library which itself links openFrameworks
elliot

fix ofLog padding so that it is correctly initialised between dynamically loaded exe's

---

addons/ofxAndroid/src/ofxAndroidSoundStream.cpp
addons/ofxAndroid/src/ofxAndroidSoundStream.h

Android signature return value was `long unsigned long`, [but should be `uint64_t`](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/sound/ofSoundStream.h#L166)

Change signature of android sound stream getTickCount

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

The problem, described in issue #5123, was caused by the copy/assignment constructors of the ofTrueTypeFont that did not copy all the members to the target.
Since my familiarity with openFrameworks and C++ knowledge are limited, please check if my additions are relevant/do not have any side effects.
The bug was apparently fixed and did not cause any visible side effects. Tested on the small sample of code I've shown in the issue and on few examples (such as graphics/fontShapesExample and graphics/fontsExample).

Bugfix of true type font copying

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

I noticed that stringWidth and stringHeight methods produce weird results when called with an empty string parameter. Simple test program:
```
ofTrueTypeFont font;
void ofApp::setup(){
font.load("sans-serif", 10);
}
void ofApp::draw(){
std::cout << font.stringWidth("text") << " " << font.stringWidth("") << " " << font.stringWidth(" ") << "       ";
std::cout << font.stringHeight("text") << " " << font.stringHeight("") << " " << font.stringHeight(" ") << std::endl;
}
```
(The result should be 27 0 0   9 0 0).
The problem was caused by the fact that an empty string produces a mesh with no vertices, so the corners of the bounding box are not changed (the defaults are limits of float). Solved by a simple check.
Also, the std::numeric_limits<float>::min() is not the minimum value that can be …

Bugfix of true type font size for empty string

---

libs/openFrameworks/video/ofVideoGrabber.cpp
libs/openFrameworks/video/ofVideoGrabber.h

Currently if one calls
```cpp
ofVideoGrabber grabber;
grabber.setUseTexture(false);
// grabber.isUsingTexture() returns false.
```
then 
```cpp
grabber.setup(640, 480);
// grabber.isUsingTexture() returns true.
```
Rather than `setup()` assuming `true`, it should use the value that was (already) set by the user.  In order to avoid breaking existing setups, the default value of bUseTexture is set to true in the constructor.
This is related to #4811

ofVideoGrabber -- fix default bUseTexture behavior.

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

Ok, so after a bit of digging I found out that:
- long time ago, the spaceSize was initialized with 1 and space was treated as a separate case when drawing a character.
- for some reasons I don't fully understand, someone decided to change that. spaceSize was now initialized with 0 and there was a check (if space size is set, draw the standard space, otherwise draw the scaled one).
- after some time, at a refactor, that case was gone.
So, I reinserted that check and initialized spaceSize with 1 (thus, there is just one case, not 2).
A bit off-topic, there was an if with some weird indentation. I assumed there should have been an else.

Bugfix of true type font set space size

---

libs/openFrameworks/graphics/ofPixels.cpp

When mirrorTo-ing ofPixels horizontally, line 1179, which was
int pixelb = i;
previously, should be 
int pixelb = j*width + (width - 1 - i);.
Otherwise, results in very irregular behaviours as below: (grayscale images that look like strips on the left are mirrored versions of top-left-most image using previous ofPixels mirrorTo horizontally)

Bug Fix for "ofPixels mirrorTo horizontal"

---

addons/ofxiOS/src/utils/ofxiOSEventAdapter.h
addons/ofxiOS/src/utils/ofxiOSEventAdapter.mm
libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj

My app is a hybrid c++/objC so I devised a way to easily register to ofEvents with an objC callback. It’s pretty much seamless for the end-user and looks like this:
```
//c++
static ofEvent<const bool> myEvent;
//ObjC
- (void)viewDidLoad {
[super viewDidLoad];
ofAddListener(myEvent, self, @selector(myCallBack:));
}
- (void) dealloc {
[super dealloc];
ofRemoveListener(myEvent, self, @selector(myCallBack:));
}
- (void) myCallBack:(const bool&) param{
}
```
Basically it creates a c++ callback internally and routes the event to the requested objC target. I use it in production scenarios all the time and it works flawlessly.

ofxiOSEventAdapter

---

libs/openFrameworks/gl/ofGLUtils.cpp
libs/openFrameworks/gl/ofGLUtils.h

Shows internal GL errors on the console. The log depends on the specific
driver but is of great help catching GL errors

ofGLUtils: ofEnable/DisableGLDebugLog: Enables OpenGL debug log

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/math/ofMatrix4x4.h

* Commenting out call to `glLineWidth()` in programmable renderer. Calling it causes a GL error, which makes it a pain to debug other GL errors.
* `isnan()` appears to be defined for Visual Studio, implementing our own causes conflicts with external libs.

Quick fixes

---

addons/ofxKinect/libs/libfreenect/platform/windows/unistd.h

As requested in #3062; I had trouble compiling ofxKinect on Windows x64 and this seems to fix.

ofxKinect ssize_t typdef should be different for x64 and x86 on windows

---

libs/openFrameworks/communication/ofSerial.h

fixes #5182. 
New functions in setupapi.h require definitions from devpropdef.h

fix OF0.9.3 compilation issue with latest MSYS2 releases

---

libs/openFrameworks/events/ofEvent.h

ofFastEvent was broken when the events system was updated. Fixes
https://github.com/openframeworks/openFrameworks/issues/5152

Fix for ofFastEvent

---

examples/shader/03_simpleShaderInteraction/src/ofApp.cpp

while reading the shader examples, I noticed this line in examples/shader/03_simpleShaderInteraction/src/ofApp.cpp:
`shader.setUniform4fv("mouseColor", &mouseColor[0]);`
`mouseColor` itself is a pointer to the beginning of the array and I since I got a bit confused about why it's there, here is a PR where i changed `&mouseColor[0]` to `mouseColor`
hope I am correct about this

cosmetic fix in simpleShaderInteraction example

---

examples/gl/transformFeedbackExample/bin/data/discard_frag.glsl
examples/gl/transformFeedbackExample/bin/data/vert.glsl
examples/gl/transformFeedbackExample/src/main.cpp
examples/gl/transformFeedbackExample/src/ofApp.cpp
examples/gl/transformFeedbackExample/src/ofApp.h
libs/openFrameworks/gl/ofShader.cpp
libs/openFrameworks/gl/ofShader.h

Adds some utility methods and subclasses to ofShader to make transform feedback easy to use. there's also an example but mainly it involves:
- setting up the shader to be use with transform feedback, using setup(TransformFeedbackSettings)
- creating a buffer object with enough capacity, 
- create one or more bindings for the transform feedback with the buffer(s) using ofShader::TransformFeedbackBinding
- begin the shader for transform feedback passing the mode and the binding(s) using beginTransformFeedback
- end the shader for transform feedback passing the binding again
This allows to capture geometry modified on a vertex shader or even generated on a geometry or tessellation shader into an ofBufferObject to be used later without having to recalculate it.

transform feedback

---

libs/openFrameworks/gl/ofFbo.cpp
libs/openFrameworks/gl/ofFbo.h
libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLProgrammableRenderer.h
libs/openFrameworks/gl/ofGLRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.h
libs/openFrameworks/types/ofBaseTypes.h
libs/openFrameworks/utils/ofMatrixStack.cpp
libs/openFrameworks/utils/ofMatrixStack.h

We've had for a while a bool flag in ofFbo::begin to not set the fbo perspective matrix. That boolean parameter is confusing and doesn't solve the most complex cases.
This adds an enum to better control how the fbo is initialized. From the comments docs:
```cpp
/// The mode parameter indicates which defaults are set when binding
/// the fbo.
///
/// The default ofFboBeginMode::Perspective | ofFboBeginMode::MatrixFlip
/// will set the screen perspective to the OF default for the fbo size, the
/// correct viewport to cover the full fbo and will flip the orientation
/// matrix in y so when drawing the fbo later or accesing it from a shader
/// it's correctly oriented
///
/// Passing ofFboBeginMode::Perspetive will only set perspective and viewport
///
/// Passing ofFboBeginMode::MatrixFlip …
```

ofFbo: Add methods to begin without matrix flip

---

libs/openFrameworksCompiled/project/android/config.android.default.mk

The ar command is apparently not configured to create compatible .a file and thus the linking fails on OSX.
I fixed the error by giving the path to ar explicitly. I hope this line is properly generalized and will work on other OSs. I only have access to OSX right now.

Android - Fix compilation error on OS X

---

libs/openFrameworks/utils/ofFileUtils.cpp

Bugfix for ofFile::create not working if file was not already opened.
Closes #5196 
before this would fail
```
ofFile tmp;
tmp.create("testCreate.txt");
cout << " does file exist? ( should be 1 ) " << ofFile::doesFileExist("testCreate.txt") << endl; ;
```
with this PR it works and still correctly sets the internal path back to the prior one if a prior path existed. 
ie: 
```
ofFile tmp;
tmp.open("false1.txt");
tmp.create("testCreate.txt");
cout << " does file exist? ( should be 1 ) " << ofFile::doesFileExist("testCreate.txt") << " my og path is  " << tmp.path() << endl; ;
```
produces:
```
does file exist? ( should be 1 ) 1 my og path is  ../../../data/false1.txt
```

bugfix for ofFile::create not working if file was not already opened Closes #5196

---

libs/openFrameworks/utils/ofLog.cpp
libs/openFrameworks/utils/ofLog.h

allows to log to visual studio console and the debug view tool in windows instead of logging to the console window that opens with the application
by default when running in visual studio windows applications will use that logger otherwise they'll use the normal console log

ofLog: add debugview log channel

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofFileUtils.h

New PR for issue #5187
Adds openFromCWD to ofFile and ofDirectory. 
Tested pretty extensively with all calls which seem to be affected by the bRelativeToData arguments.  
Couple of small things - will point out in the diff.

bugfix for static ofFile and ofDirectory calls not working if data path is set false. Closes #5187

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/helpers.js

Quick fix for qtcreator 4.1. I had to import missing modules into the  javascript helpers.
Note that I also get these deprecation warnings:
```
The item 'Transformer' is deprecated and will be removed in qbs 1.7.0.
Use the 'Rule' item instead.
```

fix for qtcreator 4.1

---

libs/openFrameworks/gl/ofMaterial.cpp
libs/openFrameworks/gl/ofMaterial.h
libs/openFrameworks/gl/shaders/phong.frag

This turns the Data object in ofMaterial into Settings for uniformity with other classes. also adds a setup method and the posibility to add a post fragment function and custom uniforms using the settings object.
The setPostFragment recently introduced is gone now and the only way to set it is by using the settings object

ofMaterial: add custom uniforms and get/setData -> setup(settings)

---

libs/openFrameworks/types/ofParameter.h
tests/addons/ofxGui/addons.make
tests/addons/ofxGui/src/main.cpp

Another shot at resolving #5248. See also #5250.
While writing the unittest I noticed that the issue doesn't occur if ofxGui isn't getting involved with the ofParameterGroup, so I guess the issue (#5248) might be inside ofxGui (I haven't been able to find the culprit yet). On the other hand, if ofParameter does all these weak_ptr validity checks, it should probably be resistant against situations where there is actually an invalid weak_ptr among the obj->parents. Hence, still the patch to ofParameter.h

cleanup ofParameter's parents before starting the notification iteration

---

libs/openFrameworks/gl/ofFbo.cpp
libs/openFrameworks/gl/ofFbo.h
libs/openFrameworks/gl/ofShader.cpp

useful when using MRT and need to clear each buffer with different colors.
also allow no color buffer without warning since it's perfectly valid to have an fbo with depth only

ofFbo: add methods to clear the different buffers + allow no color

---

addons/ofxOpenCv/scripts/formulas/opencv.sh

This will add an `ippicv` folder at the same level as the `opencv` folder. Both of these need to be copied into the `addons/ofxOpenCv/libs` folder. See #4981 and #5081 for discussion.

Added copy ippicv phase to apothecary script.

---

libs/openFrameworks/3d/ofNode.cpp
libs/openFrameworks/3d/ofNode.h
tests/math/ofNodeRegressionTests/src/main.cpp

decomposing a mat4 to it's components: position, orientation and scale
is not very reliable, mostly if it's not known if the matrix might contain
both scale and rotation since both are stored in the matrix diagonal
this removes the method that created a node from a mat4 since it would
mostly work but not always was really confusing for people using it
thinking it was completely reliable.
as a side effect setParent and clearParent with the maintain global
transform option on are now recreated from the individual components
being much more robust.

ofNode: remove node from mat4

---

libs/openFrameworks/utils/ofThread.cpp

Try-catch around ofThread deteach(), and only detach if not joinable

Fix for #5262 - Short lived threads can cause exceptions

---

libs/openFrameworks/communication/ofSerial.cpp

this makes ofArduino & ofSerial work on F24 linux. OS X doesn't appear to need this (anymore?)

on linux, set serial port to raw mode

---

.appveyor.yml
scripts/ci/msys2/install.sh
scripts/ci/msys2/run_tests.sh
scripts/msys2/compileOF.sh
scripts/msys2/install_dependencies.sh

Add MSYS2 32 and 64b bits building.
64 bits currently fails.
32 bits fails on string tests (see issue #5087)

Appveyor : add Msys2 build

---

libs/openFrameworks/graphics/ofPolyline.h
libs/openFrameworks/graphics/ofPolyline.inl

This fixes a regression where ofPolyline would return unnormalized values for tangent, rotation and normal.
The issue existed, because the glm:: implementation of glm::normalize don't operate in-place, but their return value must be used.
Addresses issue #5288
+ fixes an issue where pathological polylines would return nan vectors
Whenever a calculation is done which involves normalisation we should check for the length of the vector being normalised, or the normalization result not being NaN (which is the result of normalizing a `{0,0,0}`-vector in glm). 
oF used to return a zero vector in this case, and this implementation tries to match the output you would have received if using code from the pre-inline revision: 0361224e.
+ Address edge case: segments point against each other
When two …

fix ofPolyLine::calcData returning invalid values

---

libs/openFrameworks/graphics/ofPixels.cpp

This is a typo / bug as it ignores the requested `_pixelFormat` in the switch statement.

Use requested pixel type, not the current (allocated) member type.

---

addons/ofxPoco/addon_config.mk

In the current version, the project generator from 0.9.6 does not include search paths for openssl, leading to failures using SSL features.

Fix missing openssl includes for Poco.

---

libs/openFrameworks/graphics/ofPolyline.inl

fixes an issue where the starting point of a cubic bezier
would be doubled, while the target point would never be
fully reached.
BezierTo draws a cubic bezier to the target point using
two control points. Bezier curves are defined through four
points: p0, control0, control1, and p1.
In our implementation, p0 is taken from the last point in
the current polyline, and is therefore already a point on
the polyline.
Then the bezier curve is sampled curveResolution times.
When sampling, we want to make sure that the interpolation parameter
t goes from 0 to 1, **1 inclusive**. 1 inclusive, so that at the
end of interpolation we fully reach the target point p1.
As the bezier curve is attached to the current polyline, the
first step, where the interpolation parameter would be 0, is
already part of …

fix ofPolyline::bezierTo

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs

qt composer project file was missing Xinerama for linux compiles. Xinerama is already included in makefiles. This only affects builds through the Qt gui, which may otherwise fail linking.

include Xinerama in linux of.qbs

---

examples/3d/modelNoiseExample/src/ofApp.cpp

mesh.getVerticies() doesn't return the correct vector type. This fix takes the resulting vector and creates the correct type for the remainder of the code.

fix to get the mesh verticies

---

libs/openFrameworks/utils/ofFileUtils.cpp
libs/openFrameworks/utils/ofFileUtils.h

This function makes the app crash on win7. I put a try catch to avoid
the crash.
issue #5315

Avoid crash of doesDirectoryExists function

---

addons/ofxXmlSettings/src/ofxXmlSettings.cpp

It is parsing a double, it should convert to double, or we will lose precision

changed ofToFloat to ofToDouble in ofxXmlSettings

---

scripts/vs/download_libs.ps1

+ addons libs for win64 were not being copied to the correct directory
+ addons libs target directory were not cleaned before new libs were
copied to addons
This PR adds a method to the ps1 file which combines the actions needed
to update dependencies per addons, it also allows you to name the addon
libs in a list, to simplify future updates.
This should also address #5311

vs : fix install libs for addons libs

---

libs/openFrameworks/app/ofAppEGLWindow.cpp

This PR translates keypresses from `KEY_ENTER` and `KEY_KPENTER` properly to the right OF value.
See: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L1287-L1292
And: https://forum.openframeworks.cc/t/keyboard-layout-problem/25248

Handle return and enter key presses properly

---

libs/openFrameworks/communication/ofSerial.cpp

12mb/s (baud rate 12000000) communication it is the Teensy maximum serial speed communication(http://www.pjrc.com/teensy/benchmark_usb_serial_receive.html). I tested in linux and windows and works good.

Add 12mb/s communication over ofSerial.cpp

---

libs/openFrameworks/types/ofParameter.h

Xcode has terrible macro `check` in "AssertMacros.h".
if we include AssertMacros.h, then ofParameter got error.
and, AssertMacros.h is include too deep layer.
other way,
`#undef check`
or,
```
#define MACRO_DISABLER
template <class T> yes check MACRO_DISABLER (T const&);
no check MACRO_DISABLER (no);
...
static const bool value = sizeof(check MACRO_DISABLER (stream >> x)) == sizeof(yes);
...
static const bool value = sizeof(check MACRO_DISABLER (stream << x)) == sizeof(yes);
...
```
i think, rename is simple most better way.

rename check to check_op in ofParameter SFINAE.

---

examples/shader/08_displacementMap/src/ofApp.cpp

Closes #5337 
Fixes `getTextureReference()` deprecation warnings.
Fixes bad cast from `ofPixels&` to `unsigned char *` which caused a compiler error.
Fixes rename of `ofRotateDeg()` to `ofRotate()`.

Fix examples/shader/08_displacementMap compiler error

---

addons/ofxGui/src/ofxLabel.cpp

as the title says, it fixes the displaying of an ofxLabel when the label is too long for the ofxPanel boundaries

fixes issues #5386, ofxLabel overflowing when the string is too long

---

addons/ofxiOS/src/gl/EAGLView.m

A small bug, mostly affecting rare scenarios (like mine) with multiple view controllers drawing OF content. This one line fix draws the first frame right away, so that the previous content is not shown.

iOS EAGLView - prevent flicker by synchronously drawing the first frame when starting animation

---

libs/openFrameworks/video/ofAVFoundationGrabber.mm

`dimentions.width` and `dimentions.height` are `int32_t`-valued, so it doesn't need to be floating point values.

AVFoundationGrabber: Avoid integer and floating point comparison

---

libs/openFrameworks/math/ofVec3f.h

The current description is only correct for unit vectors. I also removed a reference to "inner product" in favor of "scalar product", which is more helpful to understanding the difference between dot and cross product.

Fix documentation in ofVec3f

---

libs/openFrameworks/communication/ofSerial.cpp

Fix ofSerial not listing any devices on OSX (and possibly Linux) as per issue/discussion https://github.com/openframeworks/openFrameworks/issues/5221

ofSerial: only check filenames, not full paths, in buildDeviceList()

---

examples/shader/07_fboAlphaMask/bin/data/shadersES2/shader.frag
examples/shader/07_fboAlphaMask/bin/data/shadersGL2/shader.frag
examples/shader/07_fboAlphaMask/bin/data/shadersGL3/shader.frag
examples/shader/07_fboAlphaMask/src/ofApp.cpp
examples/shader/07_fboAlphaMask/src/ofApp.h

-Fixed issue where blending gave darker edges.
-Moved all the masking into the shader.
-Removed one fbo so it is easier to understand.
fixes issue
https://github.com/openframeworks/openFrameworks/issues/5460

fboAlphaMask example fix.

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

+ fixes an issue where when restoring a window from
fullscreen on MacOS the window title would be lost. The
restore appears only to affect MacOS.
+ keeps glfw window title in sync with window
`settings.title`
Closes issue #5463

MacOS: restore window title when restoring window

---

scripts/linux/compileOF.sh

Very small fix. Solving errors when compiling using a different user than the one logged in.
Example, compilation would produce error in this case:
1. log into a machine using a certain user `user1`
2. use sudo powers from user1 to switch to `user2`
3. launch `./compileOF.sh` as user2
4. breaks when reaching the line `chown -R $ID:$GROUP_ID ../lib/*` because the `$ID` returned by `logname` earlier in the script is `user1` and not `user2` who is calling the script. 
Using `whoami` instead of `logname` fixes this error without breaking the script for other common cases.

Updates compileOF.sh for Linux to solve `chown` error

---

addons/ofxiOS/src/core/ofxiOSAppDelegate.mm

iOSAppDelegate is currently registering for the wrong enum for screen changes

register for correct notification on screen change

---

examples/gles/customEGLWindowSettingsExample/src/main.cpp

Old way of setting up the window caused a core dump.
This is a fix for #5483

Fix for gles/customEGLWindowSettingsExample core dump

---

libs/openFrameworks/app/ofAppEGLWindow.h

When setup(const ofWindowSettings &) was called, it was expected
that the inherited setup(const ofWindowSettings &) method would be called.
But it was not.
Instead, a temporary of type ofGLESWindowSettings was being created
and setup(const ofGLESWindowSettings &) was being called.
When the temporary was created, the EGL settings were lost.
By adding a "using" statement, the proper method is called.
This is a fix for #5485

Settings for EGLWindow were getting lost.

---

addons/ofxGui/src/ofxButton.h

This is an obvious typo.  I'm not sure if you want a bug report.
I can make one if needed.
Typo introduced in 3337737fc571f2ff86a4673b40f951201d893e3a

Fixed typo when removing listeners on buttons

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidLifeCycle.java
addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidLifeCycleHelper.java

We found an issue caused by supposedly incorrect handling of onPause/onResume.
It seems that glView.onPause/ onResume should be called synchronously and not later in another thread, and that it's important to call onPause before removing the view and call onResume only after adding the view.

ofxAndroid - bug fix in pause/resume that caused random crashes

---

addons/ofxOsc/src/ofxOsc.h
addons/ofxOsc/src/ofxOscArg.h
addons/ofxOsc/src/ofxOscBundle.cpp
addons/ofxOsc/src/ofxOscBundle.h
addons/ofxOsc/src/ofxOscMessage.cpp
addons/ofxOsc/src/ofxOscMessage.h
addons/ofxOsc/src/ofxOscParameterSync.cpp
addons/ofxOsc/src/ofxOscParameterSync.h
addons/ofxOsc/src/ofxOscReceiver.cpp
addons/ofxOsc/src/ofxOscReceiver.h
addons/ofxOsc/src/ofxOscSender.cpp
addons/ofxOsc/src/ofxOscSender.h
examples/communication/oscChatSystemExample/src/ofApp.cpp

This is a work-in-progress cleanup/bugfix PR for various things I've noticed with ofxOsc:
* ofxOscMessage: inconsistent type conversions (sometimes we do, sometime we don't arbitrarily)
* ofxOscSender & ofxOscReceiver:  no way to access current host & port info
* formatting is all over the place
As this is a WIP PR, let's discuss but please wait until I/we all agree on the changes before merging.
Details So Far
--------------
* with permission of original author, Damian Stewart, removed explicit license headers and kept simple attribution
* cleaned up and made overall formatting consistent
* added light commenting for all classes & member functions
* added support for "N" nil type as ofxOscArgNone
* only included required headers instead of ofMain.h
* removed "using namespace std" and …

ofxOsc updates

---

libs/openFrameworks/graphics/ofImage.cpp

As per discussion in https://github.com/openframeworks/openFrameworks/issues/5455, `ofImage` was failing to load when the file path has spaces. According to [the discussion here](http://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space), and probably elaborated in [RFC 3986](https://tools.ietf.org/html/rfc3986) which I haven't read in detail, spaces are not allowed and *must* be encoded to `%20` first.
This PR uses the `uriparser` library to first encode the path string, and then use that when trying to parse with `uriParseUriA` as previously implemented. The code was taken directly from the [example related to converting filenames to URIs](http://uriparser.sourceforge.net/doc/html/#filenames), and uses an `#ifdef` to check on using the platform-appropriate calls to …

ofImage: encode path to URI before parsing

---

libs/openFrameworks/gl/ofMaterial.cpp

+ materials shaders expect HAS_COLOR and HAS_TEXTURE to be
defined and to be either 0, or 1.
Closes issue #5523

set shader defines to 0 if not using tex, col

---

libs/openFrameworks/utils/ofXml.cpp
libs/openFrameworks/utils/ofXml.h

Adds the ability for ofXml to obtain the name of the current node (i.e. the name of the tag). This is exposed via ofXml::getName(), returns a String, and is implemented via pugi's xml_node::name() funcion.

ofXml: Feature - get name of node

---

libs/openFrameworks/utils/ofURLFileLoader.cpp

This is probably not covered by a test case, else it would have been found.
Basically, cpp doesn't match .h.

Fix broken function signature.

---

examples/gl/gpuParticleSystemExample/src/ofApp.h

The example crashes on my machine during startup because `posPingPong.src` and `posPingPong.dst` are null pointers at the beginning. This PR sets these pointers during allocation.
Also ofApp.h was not UTF-8 encoded (I could not edit it at first) so I changed that too. Is that the right encoding? Not sure..

Fix segfault when starting gl/gpuParticleSystemExample

---

libs/openFrameworks/gl/ofLight.cpp
libs/openFrameworks/gl/ofLight.h

Upon destruction `ofLight` called a global method to retrieve the current renderer. In most cases this is legit, but upon app teardown the renderer might have already been destroyed before to the `ofLight` object, which could lead to `BAD_ACCESS` errors when closing apps using `ofLight`. 
As this is an issue within `ofLight`, it affects the programmable as well as the fixed function renderers.
+ This PR suggests using a `weak_ptr` inside the `ofLight`'s `data` member to keep a non-owning link back from the light to the renderer.
+  This allows the light to check whether the renderer is still alive before calling methods on it.
+  This should also accelerate access to the renderer as the renderer itself doesn't need to be resolved on every call, only the `weak_ptr` locked.
Closes Issue …

fix issue with ofLight crashing during app exit

---

examples/strings/regularExpressionExample/README.md
examples/strings/regularExpressionExample/src/ofApp.cpp

.. by switching from Poco::RegularExpression to std::regex.
It is still not working because of https://github.com/openframeworks/openFrameworks/issues/5553 but the example does not crash anymore because Poco is missing. I checked the image URLs the new ode is getting, seems to be fine.

regularExpressionExample: removing Poco..

---

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

The rsync command fails if your project is not at the standard depth. (i.e. OpenFrameworks/apps/myApps")

Replace assumed OF path to a more robust one relative to $OF_PATH

---

scripts/linux/ubuntu/install_dependencies.sh

Adds support for Elementary OS in the ubuntu install scripts. Doesn't work on other derivatives yet .. :bowing_man: 
Issue Number: #5431 
Tested on: 
Ubuntu 12.04 and 16.04
Elementary 0.4

Feature ubuntu derivative support

---

addons/ofxGui/src/ofxBaseGui.h
addons/ofxGui/src/ofxColorPicker.cpp
addons/ofxGui/src/ofxColorPicker.h
addons/ofxGui/src/ofxGui.h
addons/ofxGui/src/ofxGuiGroup.cpp
addons/ofxGui/src/ofxGuiGroup.h
addons/ofxGui/src/ofxSliderGroup.cpp
addons/ofxGui/src/ofxSliderGroup.h

Based on @julapy ofxColorPicker and used whenever an ofParameter<ofColor> is added to a group.
By default colors now appear minimized since the picker takes a lot of space.

ofxGui: add color picker

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h
libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofAppRunner.h
libs/openFrameworks/events/ofEvents.cpp
libs/openFrameworks/events/ofEvents.h

char event: maps to glfw char event that allows to get proper events
for combinations of dead keys to allow to get characters like ò or
anything that needs a sequence of keys to be produced
ofKeyEventArgs modifiers: the key event arguments now has modifiers
that can be queried like:
keyArgs.hasModifier(OF_KEY_SHIFT)
ofGetClipboardString & ofSetClipboardString: which were only previously
accessible thorugh the window pointer
Adds some missing key transformations to glfw window, like the keypad numbers and operator keys

new key events:

---

libs/openFrameworks/utils/ofUtils.cpp
libs/openFrameworks/utils/ofUtils.h

Some more functions to work with UTF8 std::strings.
when using utf8 in std::string some functions like .size(), .insert()
and others, don't work properly when there's multicharacter codepoints
in the string.
This adds some functions to use instead of the corresponding string
methods:
```cpp
void ofUTF8Append(string & str, uint32_t utf8);
void ofUTF8Insert(string & str, size_t pos, uint32_t utf8);
void ofUTF8Erase(string & str, size_t start, size_t len);
std::string ofUTF8Substring(const string & str, size_t start, size_t len);
std::string ofUTF8ToString(uint32_t utf8);
size_t ofUTF8Length(const std::string & str);
```

ofUTF8 utilities:

---

libs/openFrameworks/utils/ofXml.cpp
libs/openFrameworks/utils/ofXml.h

In the old ofXml it was called `loadFromBuffer`, but I named it the same way `ofImage` does and added an `load(const ofBuffer& buffer)` function.

#5554 ofXml: adds load(const ofBuffer&)

---

libs/openFrameworks/video/ofAVFoundationPlayer.mm
libs/openFrameworks/video/ofAVFoundationVideoPlayer.h
libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

`ofBaseVideoPlayer` only offers `setPosition` which needs the duration of the media.
in case of a stream we do not have a duration, therefore setting the position (or frame) will fail.

#1741 of av foundation player adding video streaming

---

libs/openFrameworks/sound/ofRtAudioSoundStream.cpp
libs/openFrameworks/sound/ofSoundBuffer.cpp

-soundstream in and out buffer's samplerate is set at setup.
https://github.com/openframeworks/openFrameworks/issues/5588

Fix audio sample rate issue #5588

---

libs/openFrameworks/utils/ofMatrixStack.cpp
libs/openFrameworks/utils/ofMatrixStack.h

+ `ofMatrixStack` currently depends on `ofFbo`, although it really only calls methods from `ofFbo`'s base class, `ofBaseDraws` - `ofMatrixStack` exclusively queries into the RenderSurface's geometry.
The proposed changes update `ofMatrixStack` to require just an `ofBaseDraws`-compatible object to be passed as target render surface.
This allows other renderers, such as the vulkan renderer, to use this object, without having access to `ofFbo`.

remove dependency ofMatrixStack<->ofFbo

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/graphics/ofTrueTypeFont.cpp
libs/openFrameworks/video/ofAVFoundationVideoPlayer.h
libs/openFrameworks/video/ofAVFoundationVideoPlayer.m

Warning fixes for Xcode 8.
-defines, deprecations, and uninited-vars.

Fix warnings in Xcode 8.

---

libs/openFrameworks/communication/ofSerial.cpp

Closes openframeworks/openFrameworks#5465

ofSerial: fix port name vs. path parsing on Windows

---

scripts/dev/download_libs.sh

This is a problem that people working with the master branch (not the nightlies or releases) encounter when following the instructions.
Related
https://github.com/openframeworks/openFrameworks/issues/5500
https://github.com/bakercp/ofxIO/issues/22
https://forum.openframeworks.cc/t/raspberry-pi-3-arm6-or-arm7/26800/4

Download correct RPI libs when arch is not spec'd

---

scripts/templates/ios/ofxiOS-Info.plist

Fixes 
https://github.com/openframeworks/projectGenerator/issues/158
This automatically removes invalid characters (like underscores in an addon's example name).

Fixes invalid generated ios bundle identifiers

---

libs/openFrameworks/utils/ofLog.cpp
libs/openFrameworks/utils/ofLog.h

As discussed in the issue, this adds getters for the currently set logger channel. Specifically an `ofGetLoggerChannel()` function and a `ofLog::getChannel()` method. This allows channels to be swapped in and out more easily, or for custom channels to continue forwarding to whatever channel was already set.

Add logger channel getters (closes #5558)

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidVideoGrabber.java

This would be helpful if you need to re-use the camera elsewhere in your project.

Add a getCamera() method to get the camera used

---

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidVideoPlayer.java

I found that bIsLoaded was never set to true leading to `play()` method in OFAndroidVideoPlayer throwing out error after `load()` is called. This can be verified with the example androidVideoPlayer.
From Android's API reference, [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html), `prepare()` is synchronized. Hence, it is I/O blocking and `bIsLoaded` should be set to true immediately after `prepare()` is called otherwise `play()` will always throw "Movie not loaded".
Although `bIsLoaded` is set to true inside `mediaPlayer.setOnPreparedListener()`, the listener should only be called when `mediaPlayer.prepareAsync()` is used.

OFAndroidVideoPlayer doesn't set bIsLoaded to true

---

CHANGELOG.md
addons/ofxGui/src/ofxBaseGui.cpp
addons/ofxGui/src/ofxBaseGui.h
addons/ofxGui/src/ofxGui.h
libs/openFrameworks/graphics/ofTrueTypeFont.cpp
libs/openFrameworks/graphics/ofTrueTypeFont.h

+ following the same pattern we use with ofFbo and other objects
*Example:* Create a `Settings` object, and pass it to `load()` - here we are instructing an Icon font to load specific unicode ranges:
ofTrueTypeFont myFont;
ofTrueTypeFont::Settings settings("MaterialIcons-Regular.ttf", 26);
settings.antialiased = true;
settings.addRange({0xe889,0xe889}); // history
settings.addRange({0xe034,0xe039}); // play/pause buttons
myFont.load(settings);
The hope is to make the Settings object more discoverable, which should help especially with IDEs that have code completion.

refactor: move ofTtfSettings into ofTrueTypeFont

---

libs/openFrameworks/utils/ofFileUtils.h

I had made this PR before but I deleted it because I couldn't fix some git problems in it. was easier to make a whole new PR.

Fixed documentation for ofFilePath::getBasename()

---

libs/openFrameworks/graphics/ofBitmapFont.cpp
libs/openFrameworks/graphics/ofBitmapFont.h

- incorrect use of numeric_limits<float>::min() caused wrong results. Replaced for numeric_limits<float>::lowest()
- Added  ofDrawBitmapMode mode = ofGetStyle().drawBitmapMode, bool vFlipped = ofIsVFlipped() arguments to getBoundingBox. This allows to get the correct mesh and doesn't break previous way of use of this function.

Fixes for ofBitmapFont getBoundingBox();

---

libs/openFrameworks/3d/of3dPrimitives.cpp
libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppNoWindow.cpp
libs/openFrameworks/app/ofMainLoop.cpp
libs/openFrameworks/events/ofEvent.h
libs/openFrameworks/gl/ofBufferObject.cpp
libs/openFrameworks/gl/ofTexture.cpp
libs/openFrameworks/graphics/ofGraphics.cpp
libs/openFrameworks/sound/ofSoundPlayer.cpp
libs/openFrameworks/sound/ofSoundStream.cpp
libs/openFrameworks/utils/ofLog.cpp
libs/openFrameworks/video/ofVideoGrabber.cpp
libs/openFrameworks/video/ofVideoPlayer.cpp

Cleaner, more modern syntax.  Reduce the `new` keyword.  Not possible to replace shared_ptr constructors with custom deleters.

Use std::make_shared and std::make_unique where possible.

---

libs/openFrameworks/3d/ofMesh.h
libs/openFrameworks/3d/ofMesh.inl

Implement mesh.flatNormals(); to give it a flat look.
Works only when mode = OF_PRIMITIVE_TRIANGLES, same as existing smoothNormals() method.
```cpp
ofLight light;
ofMaterial material;
vector<ofMesh> meshes;
//--------------------------------------------------------------
void ofApp::setup() {
ofSetBackgroundColor(10, 10, 10);
ofEnableDepthTest();
//directional light
light.setDirectional();
light.setSpecularColor(ofColor(255));
light.setDiffuseColor(ofColor(255));
light.setAmbientColor(ofColor(100));
light.setOrientation(ofVec3f(0, 180, 0));
//material
material.setShininess(120);
material.setSpecularColor(ofColor(0));
material.setDiffuseColor(ofColor(200));
material.setAmbientColor(ofColor(0));
//mesh
meshes.push_back(ofMesh::sphere(100, 12, OF_PRIMITIVE_TRIANGLES)); …
```

Implement flatNormals() for polyhedrons and low-poly meshes

---

addons/ofxGui/src/ofxInputField.cpp

+ textinputfield would not show any text, as visibleinput would default
to empty string. this makes it default to its input.

ofxGUi: fix textinput field initial state

---

scripts/templates/vs/emptyExample.vcxproj

Fixes https://github.com/openframeworks/projectGenerator/issues/159
Fixes https://github.com/bakercp/ofxJSONRPC/issues/10
See also https://github.com/bakercp/ofxJSONRPC/issues/10

Update vs template for when multiple addons with identical class names are used.

---

scripts/vs/download_libs.ps1

+ adds vs_ver as a selectable option to the powershell download script, which allows you to select which version of the libraries to download.
+ adds a comment at top of script to explain how paramters may be specified
Default paramter value for vs_ver is 2015, which will load the libraries compiled with the visual studio 2015(== 140) toollset.
Call the script with:
powershell.exe -f download_libs.ps1 -vs_ver 2017
To download & install the libraries compiled with the visual studio 2017(== 141) toolset.
This should also fix an issue where the old download_libs.ps1 script would not work, as the libraries archives on the server now have a slightly different naming scheme.
Fixes #5695

vs: update download_libs.ps1

---

libs/openFrameworks/3d/ofEasyCam.cpp
libs/openFrameworks/3d/ofEasyCam.h

This should fix this issue #5703 
This fix is actually very simple. The setEvents(...)method was checking if the events pointer was valid as a way to determine if it was the first time setEvents(...) was being called, thus allowing the automatic events registration upon startup. The problem is that if disableMouseEvents() is called before the events registration; during setup, the events pointer will still be null thus rendering the bMouseInputEnabled flag useless during the first run of setEvents(...).
So, the idea is to forget about checking the events pointer validity, and instead have the bMouseInputEnabledbool set totrue upon construction. When setEvents(...) gets called the fissrt time it will register automatically the events. Hence if disableMouseEvents() is called during setup() …

ofEasyCam. fix disabling mouse interaction at start. 

---

libs/openFrameworks/3d/ofCamera.cpp
libs/openFrameworks/3d/ofCamera.h

+ add method to draw camera frustum into scene, so that a camera may be previewed showing its frustum. This is useful to debug camera views, and also allows you to preview near and far planes for cameras. Inline comments explain the math behind the draw operation.
Proposed method name & signature: `void ofCamera.drawFrustum()`
Minimal demo app shows how this feature may be used: https://gist.github.com/tgfrerer/28b2bf3ad689e4f8cc778644c9d6595e
Screengrabs from demo app:

feature: draw camera frustum

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h

Closes #4703
+ when moving an app from a scaled monitor to a non-scaled
monitor, pixel scale was not recalculated. Pixel scale
must be recalculated, however, as monitors with different
pixel scales differ in pixel scale, and the framebuffer
allocated to back a window will be of different size.
+ if a window was dragged onto another monitor and there is
enough space to accomodate the window without rescaling
it, the backing framebuffer might still change in pixel
scale - responding to the `framebuffer_size` callback from
GLFW fixes this.

fix dual-monitor-resolution issue and HiDpi

---

scripts/dev/download_libs.sh

There was a small syntax error in the `download_libs.sh` which is fixed in this PR.

Fixed bash syntax error in download_libs.sh

---

libs/openFrameworks/utils/ofXml.cpp

Apparently this might be a copy/paste error. 
It results in a new `<:anonymous/>` tag when trying to add attributes to the root XML node.
Discussion here: https://forum.openframeworks.cc/t/27585

Allow setting attributes on the root XML node

---

libs/openFrameworks/3d/ofCamera.cpp

This bug was introduced in the GLM implementation.
Issue: https://github.com/openframeworks/openFrameworks/issues/5751

FIX: ofCamera. Fixed wrong maths done with lens offset. 

---

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.h
addons/ofxGui/src/ofxSliderGroup.cpp
addons/ofxKinect/src/ofxKinect.cpp
addons/ofxKinect/src/ofxKinect.h
addons/ofxNetwork/src/ofxTCPClient.cpp
addons/ofxOsc/libs/oscpack/src/osc/OscReceivedElements.cpp
addons/ofxOsc/src/ofxOscSender.cpp
addons/ofxVectorGraphics/libs/CreEPS.cpp
addons/ofxXmlSettings/src/ofxXmlSettings.cpp
examples/communication/oscChatSystemExample/src/ofApp.cpp
examples/communication/oscReceiveExample/src/ofApp.cpp
examples/graphics/lutFilterExample/src/ofApp.cpp
examples/input_output/imageSequenceExample/src/ofApp.cpp
examples/input_output/systemSpeakExample/src/ofApp.cpp
examples/sound/audioInputExample/src/ofApp.cpp
examples/sound/audioOutputExample/src/ofApp.cpp
examples/video/videoGrabberExample/src/ofApp.cpp
libs/openFrameworks/sound/ofRtAudioSoundStream.cpp

Mostly type changes to make gcc6 a happy camper. CreEPS.cpp had includes in namespaces which gcc6 does not like any more. For system commands in systemSpeakExample I casted the result to (void) which is idiomatic c/c++ to subpress unused return value warnings. But gcc6 ignores it! At least one can see that everything is meant to be right when you compile the code. There seems to be a discussion in the gcc community how to handle this warning. Here is the official documentation https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html saying that it should work. And here is an old ticket which has been updated lately: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425

changes types to please gcc6.

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

ofTrueTypeFont will not load system fonts, either by explicitly passing their name or by using OF_TTF_SANS, OF_TTF_SERIF or OF_TTF_MONO
issue https://github.com/openframeworks/openFrameworks/issues/5761

Fix: ofTrueTypeFont. Was not loading system fonts.

---

libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp

Fixes ofOpenALSoundPlayer::setPositionMS(int ms) set wrong position
when streaming audio #5749

Pass correct frame number to sf_seek

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h

+ more explicit calculation of screen and framebuffer extents, clarifying what method does, and which dimensions to expect of values retrieved from GLFW
+ use float value for scalefactor, in case operating systems report non-int scaling for HiDPi.
This addresses an issue where mouse position would be reported wrongly if a window had been moved between hi- and/or lo-res monitors. 
Also annotates `windowW`, `currentW` with comment clarifying dimensions for these fields.
This should close the dracula-issue #4703 (again), if not, let's try garlic.

fix framebuffer/screen mouse mapping on HiDPi

---

libs/openFrameworksCompiled/project/qtcreator/modules/of/helpers.js
libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs

+ replaces deprecated `loadExtension` with `require` in `helpers.js`
+ hard-codes `linux` architecture to `x86_64`: this is necessary, as
the qbs build system otherwise expects the user to specify the
architecture property explicitly.
For further reference, the architecture property may be set explicitly
in Qt Creator as follows:
Under Projects -> Build Settings -> Build Steps -> Properties, set:
`qbs.architecture:x86_64`

qt creator project file fixes for QT Creator 4.4

---

libs/openFrameworks/3d/ofCamera.cpp
libs/openFrameworks/3d/ofCamera.h

Maintenance PR for feature #5712, where cameras may draw their frustum into the scene for debugging.
* `drawFrustum` would foolishly assume ofRectMode to be set to its default value, `OF_RECTMODE_CENTER` when drawing the frustum caps.  This might lead to frustum caps being drawn incorrectly when, somewhere before, rectmode had been set to something other than `OF_RECTMODE_CORNER`.  This is fixed now - style is pushed before drawing the frustum, set correctly for drawing the frustum, and restored to user specified values after drawing the frustum, using
ofPush/PopStyle.
+ also adds parameter to optionally explicitly define a viewport from which to calculate the frustum to be drawn - this brings the method more in line with other camera-specific methods, which allow optional
specification …

fix ofCamera::drawFrustum

---

libs/openFrameworks/app/ofAppEGLWindow.cpp
libs/openFrameworks/app/ofAppEGLWindow.h

The Adafruit 5" 800x480 Backpack did not give reasonable touch values and I discovered that in ofAppEGLWindow the way how relative and absolute input positions are handled is the same. The absolute values depend on the device min and max absolute x and absolute y axis settings. This fix stores the min and max values of the x and y axes, as well as sets the mouse event x and y values according to those.

Set mouseEvent.x and y values based on absolute limits of the axis

---

libs/openFrameworks/video/ofAVFoundationGrabber.mm

This should fix #5769. It seems to be an error that is only reporting on newer (10.12.6) osx versions.
After some digging, I found that _ofAVFoundationGrabber.mm_ has a call to `CVPixelBufferLockBaseAddress(imageBuffer,0); ` without a matching unlock call. By placing a call to `CVPixelBufferUnlockBaseAddress(imageBuffer, kCVPixelBufferLock_ReadOnly);` on line 323 of _ofAVFoundationGrabber.mm_  I have suppressed that same warning. I'm not sure if that is actually fixing the issue, or if it's just suppressing the warning.
I know this is a minor change, but the level of logging this error produces is very frustrating if you are streaming video like in videoGrabberExample.
Passes local builds of 64 and 32bit versions with examples.

ofAVFoundationGrabber not unlocking image buffer

---

CHANGELOG.md
scripts/linux/el6/install_codecs.sh
scripts/linux/el6/install_dependencies.sh

I have a need of ofx to be buildable on EL6 environment (primarily CentOS 6 and Scientific Linux 6).
We used to use Fedora deps for the most part, but that changed in the summer to use `dnf`, and
other things, which are not supported on EL6. So I've adapted `fedora` to `el6` dependencies
installation for the initial build. Please consider for inclusion.

Enable EL6 builds

---

libs/openFrameworks/sound/ofSoundStream.cpp
libs/openFrameworks/sound/ofSoundStream.h

Currently `ofSoundStream::getMatchingDevices()` calls `ofSoundStream::getDeviceList()` with no arguments, resulting in `ofSoundStream::getDeviceList()` defaulting to `ofSoundDevice::Api::DEFAULT` which means searches are restricted to ASIO devices on Windows.
This PR simply adds an optional `api` param to  `getMatchingDevices()` that gets passed along to `getDeviceList()` so that the search works for all APIs.

Added api parameter to ofSoundStream::getMatchingDevices()

---

libs/openFrameworks/sound/ofSoundBuffer.cpp

The interpolation algorithm was only taking the first channel as it was not using the correct index

ofSoundBuffer: fixed wrong interpolation algorithm

---

addons/ofxOpenCv/src/ofxCvBlob.h
addons/ofxOpenCv/src/ofxCvContourFinder.h
addons/ofxOpenCv/src/ofxCvHaarFinder.cpp
addons/ofxOpenCv/src/ofxCvHaarFinder.h

This addon was not compiling in certain circumstances w/ master and other addons.  Adding std:: fixes this.

Fix missing std:: namespace in ofxOpenCv.

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

This introduced a bug!
This reverts commit f285e8958231c71d5545053ffa6cb89ca4ce5149.
Discussed with @arturoc  previously in https://github.com/openframeworks/openFrameworks/pull/5762#issuecomment-333388005
The problem arises because 
[`static bool loadFontFace(const std::filesystem::path& _fontname, FT_Face & face, std::filesystem::path & filename)`](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L448)
is called like this
[`if(!loadFontFace(settings.fontName,` loadFace, `settings.fontName)){`](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L797)
So, in `loadFontFace(....)` the line
`filename = ofToDataPath(_fontname,true);`
actually modifies `settings.fontName`, …

Revert "fix-ofTrueTypeFont. avoid unnecesary filepath copy."

---

libs/openFrameworks/utils/ofConstants.h

now, we can't use like below:
```
OF_DEPRECATED_MSG("deprecated", template <typename type> typename std::enable_if<std::is_same<type, int>::value, type>::type f(type));
```
this PR makes it possible.

update: make `OF_DEPRECATED_MSG` allow complex template type.

---

libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk

add checks if this is a crosscompile build.
without it the pkg-config of the host system is queried leading to wrong assumptions for crosscompilation.

check pkg-config of crosscompile target for glfw3 and rtaudio

---

libs/openFrameworks/3d/ofCamera.cpp

ofCamera: fixed coordinate system transform functions
These functions are:
```
glm::vec3 worldToScreen(glm::vec3 WorldXYZ, ofRectangle viewport = ofRectangle()) const;
glm::vec3 screenToWorld(glm::vec3 ScreenXYZ, ofRectangle viewport = ofRectangle()) const;
glm::vec3 worldToCamera(glm::vec3 WorldXYZ, ofRectangle viewport = ofRectangle()) const;
glm::vec3 cameraToWorld(glm::vec3 CameraXYZ, ofRectangle viewport = ofRectangle()) const;
```
Now these take into account the cameras V flip.
Also removed redundant code from these.
The vFlip was not being taken into account when getting the camera's modelViewProjection matrix. I didn't add this fix directly into `ofCamera::getModelViewProjectionMatrix()` because this was being done in the ofMatrixStack and probably elsewhere. This fix would not …

ofCamera: fixed coordinate system transform functions

---

libs/openFrameworks/utils/ofUtils.cpp

Some absolute paths were returning a flipped separator on Windows at the drive level (e.g. `C:/some\\folder\\path\\`. Although this is no problem in most cases, it doesn't work with some Windows specific stuff, like setting the default path when using `ofSystemLoadDialog(...)`.
Here's a better description of a similar problem: https://stackoverflow.com/questions/27110973/boost-filesystem-canonical-path-is-not-valid-after-conversion-to-const-char

Added make_preferred() to paths where necessary.

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

This should behave well on all other platforms as well.
On Linux the cursor does not disappear in fullscreen, guessing this has to do with how GLFW_CURSOR_HIDDEN is handled internally, in window mode it work fine but in fullscreen GLFW_CURSOR_DISABLED is necessary.
This was also discussed here: https://github.com/openframeworks/openFrameworks/issues/2812

Fixing hideCursor() for Fullscreen on Linux

---

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp
libs/openFrameworks/app/ofAppEGLWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofAppGLFWWindow.h
libs/openFrameworks/app/ofAppGlutWindow.cpp
libs/openFrameworks/app/ofAppNoWindow.cpp
libs/openFrameworks/app/ofAppRunner.cpp
libs/openFrameworks/app/ofAppRunner.h
libs/openFrameworks/app/ofWindowSettings.h

Fixes #5861
Also fixes a problem where setting GAME_MODE using a window settings struct would change the screen resolution to 1024x768 when the size wasn't set.
To fix this we are making width and height in window settings protected which will break some code but the fix is pretty straightforward, just use setSize instead of directly assigning values to width and height

ofAppGLFWWindow: better handling of window mode

---

examples/graphics/fontShapesExample/src/ofApp.h
libs/openFrameworks/graphics/ofTrueTypeFont.cpp
libs/openFrameworks/graphics/ofTrueTypeFont.h

I've changed fontShapesExamples to use ofPath, can't remember of anything else that uses ofTtfCharacter but would be good to check that all examples are still compiling after this
Closes #4942

remove deprecated ofTtfCharacter and just use ofPath instead

---

libs/openFrameworks/graphics/ofTrueTypeFont.cpp

The PR changes the default font face for 10.13 to be regular - (it is currently condensed). 
See details #5865
10.12 and prior are unchanged.

fix for OS X OF_TTF_SANS default on 10.13 closes #5865

---

scripts/vs/download_libs.ps1

+ script was deleting temporary libs folder "32", "64" repeatedly meaning only the libs from the very last .zip slice of libs would survive the cull.
Since the temporary folders "32/64" get deleted automatically as they are part of the "cull list" when preparing the libs directory for upgrade this additional delete routine is not needed in the first place.
+ also added an echo to instruct users on how to install libs for visual studio 2017, instead of the default, visual studio 2015.
+ also added an echo telling users that that the script finished successfully.

fix download_libs.ps1 script

---

examples/3d/3DPrimitivesExample/src/ofApp.cpp
examples/3d/3DPrimitivesExample/src/ofApp.h
libs/openFrameworks/3d/of3dPrimitives.cpp
libs/openFrameworks/3d/of3dPrimitives.h
libs/openFrameworks/3d/ofMesh.inl

Flips texture coordinates for all oF primitives so that textures seen through a default camera (without view flipping) appear correct. 
Addresses #3139 
* updates of3DPrimitivesExample to use a default camera

Fix texcoords primitives

---

libs/openFrameworks/3d/ofCamera.cpp

+ ortho matrix must not use viewport offset for its own calculations, only viewport dimensions.
This is in line for how projection matrix is calculated for perspective matrices, where only the aspect ratio of the viewport is used.
Otherwise the centre of projection will be off (not viewport centre) when the camera view is drawn using a viewport with offset - as you could see when placing an ortho camera in main view in advanced3DExample.

fix ortho projection matrix calc

---

libs/openFrameworks/3d/ofMesh.inl

Aligns box primitive triangle winding order so that it is consistent with the winding order of other primitives. That is, when viewed through an `ofCamera`, and `GL_CULL_FACE` is `enabled` with `glFrontFace(GL_CW)` it will look correct, the front faces visible, the back faces invisible.
All other oF primitives appear to follow this convention.

fix box primitive winding order

---

examples/3d/advanced3dExample/src/ofApp.h

+ removes a leftover reference to deleted header file (oops)

advanced3DExample: remove reference to OrthoCam.h

---

libs/openFrameworks/gl/ofGLUtils.cpp
libs/openFrameworks/gl/ofTexture.cpp

I have added the implementation of the following methods (which are defined for Android in ofGLUtils) to ofTexture class to avoid missing method implementation issues on Android:
```
void ofRegenerateAllVbos() {}
void ofReloadAllImageTextures() {}
void ofReloadAllFontTextures() {}
```

Add unimplemented methods to ofTexture on Android

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp

Fixes: #4596
No performance difference noticed with this simple shader / medium to high.
However, massive quality improvements in Vertex orders and positions.

Fixes #4596 - Medium P to High P for Shader Floating Point Precision

---

addons/ofxiOS/src/core/ofxiOSEAGLView.mm

This is a strange one really, it might have been around for a while (iOS 11, maybe 10). I noticed it recently and just guarded my own code with a bool, however after running a few old examples I see it breaks those so this is a critical.
Call stack: (bottom to top)
viewDidLoad calls startAnimation which calls draw view and this is now calling a first call on Creation (something that didn't happen previously in iOS).
(First called from here)
Just added a bool to guard calling the draw function that notify's update/draw if setup hasn't been called.

iOS/tvOS - Fixes Update and Draw being called before Setup

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp
libs/openFrameworks/app/ofMainLoop.cpp

Ensures teardown order for a tuple of <app,renderer,window> is the following: 
1. app
2. renderer
3. window

Fix teardown order

---

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp

Fix Open GL ES 1.0/1.1 command being sent into Open GL ES 2/3.
According to Analyser this is a severe error and happening every frame multiple times.
Fixed by checking against major GL version.

Fix GL_INVALID_OPERATION on OpenGL ES 2.0 +

---

addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp

This fixes a bug where on some devices the camera preview wouldn’t appear correctly. In my case it had a green line a few pixels tall along the bottom edge of the preview.
Also, in my instance the texture matrix flipped the image, so I had to enable bFlipTexture. I don’t know if this is device dependent or not. I tested on two separate devices, a Saumsung Tab 2 and Nexus 5X.

Use the textureMatrix supplied from SurfaceTexture

---

libs/openFrameworks/graphics/ofPolyline.h
libs/openFrameworks/graphics/ofPolyline.inl

Based on ofPath methods.
To consider for both ofPath and ofPolyline:
* scale uses float but translate and rotate uses glm::vec
* it might nice to be able to set the origin for rotate and scale, instead of using (0,0,0)
* rotating in 2D is not convenient: you need to specify glm::vec3(0.0, 0.0, 1.0) as axis. Add `rotate(float az)` for 2D rotations?
* az == azimuth? use `deg` instead? or `rotateDeg()` + `rotateRad()`?

Add translate, rotate and scale to ofPolyline

---

addons/ofxOpenCv/src/ofxCvBlob.h

I'm assuming we're phasing out `ofPoint`...
In any case, I encountered an issue with the following code, which this change fixes:
```
ofxCvBlob blob = contourFinder.blobs[i];
ofPolyline polyline = ofPolyline(blob.pts);
```

Converted ofxCvBlob points from ofPoint to ofDefaultVec3.

---

addons/ofxiOS/src/core/ofxiOSEAGLView.mm
libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
libs/openFrameworks/gl/ofGLRenderer.cpp

Bugfix for iOS fbo call in setup killing rendering. 
Closes #5872

bugfix for iOS fbo call in setup killing rendering. Closes #5872

---

examples/windowing/multiWindowExample/src/main.cpp
examples/windowing/multiWindowOneAppExample/src/main.cpp

fixes #5958.
Replaced settings.width = w; settings.height =h by settings.setSize( w, h )

Bugfix windowing examples

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

bugfix for crashing osx apps with large windows. closes #5969

bugfix for crashing osx apps with large windows. closes #5969

---

addons/ofxGui/src/ofxGuiGroup.cpp

make the whole of a group header clickable instead of just the +/- sign

---

libs/openFrameworks/events/ofEvents.h

`0x16` is not a helpful (unique) bitmask when the others are `0x1`, `0x2`, `0x4`, etc.  It causes various other keys to be marked as triggered when the `OF_KEY_SUPER` or `OF_KEY_COMMAND` key is pressed.  Also, make the `hasModifiers` const correct for lots of reasons.

modifier key bitmask fix.

---

libs/openFrameworks/3d/ofNode.cpp

This PR is related to this issue: #6005

Fix order of quaternion multiplication in ofNode::setGlobalOrientation

---

scripts/templates/linux/qtcreator.qbs
scripts/templates/linux64/qtcreator.qbs

Removes leftover lines in qt creator project template files.
These lines would trip up QT Creator, which would refuse to open newly
created QtCreator project files.
The artifacts look like they might have been leftover when copying a
similar template used for the QtCreator Wizard plug-in.

fix linux project templates for QtCreator

---

libs/openFrameworks/app/ofAppGLFWWindow.cpp

fixes the bug described in https://github.com/openframeworks/openFrameworks/issues/6032
Although it fixes this bug, it only checks for the horizontal framebuffersize and currentW, Not sure if it should also check for vertical difference.

Fixed int division that needs to be floating point
