openframeworks/openFrameworks

libs/openFrameworks/app/ofAppGLFWWindow.cpp
This fixes the broken modifier key event behavior on macOS as detailed in #6070.
**I see this as a pretty critical bug fix.**
=> use correct macOS key event modifier masks

libs/openFrameworks/app/ofAppGLFWWindow.cpp
ofAppGLFWWindow: use ofGetWindowSize() when storing current window rect as windowW & windowH may already reflect the fullscreen size. This is a fix for #6074 on macOS. It may or may not be happening on Windows, so the same fix was applied for the Windows section as the code is the same.
=> ofAppGLFWWindow: use ofGetWindowSize() when storing current window rect

scripts/linux/archlinux/install_dependencies.sh
RtAudio can now be obtained through the official repositories and pkg-config has also been replaced with pkgconf.
=> Fix Arch Linux install_dependencies.sh

addons/ofxEmscripten/libs/html5audio/include/html5audio.h, addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js, addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js, addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.cpp
This pull contains fixes for:
`SoundPlayer.isLoaded()` was giving a wrong output on html5 audio. It returned if the loading started, not if the loading was finished. This is caused by the way the audio is fetched (asynchronous).
Video grabbing from webcam was outdated and did not work on IOS11 and Safari 11.x.
This fixes problems, updates the deprecated `navigator.getUserMedia()` to `navigator.mediaDevices.getUserMedia` and includes a fix to get webcam support on both IOS and Safari.
=> Fixes for html5 audio and video with emscripten

libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk
A simple workaround for a missing release build. Test first if release build exists otherwise use the debug build
fixes #6045
=> fix copy_dlls make target when there's only a debug build

libs/openFrameworks/3d/ofNode.cpp
The second one in https://github.com/openframeworks/openFrameworks/issues/6025.
=> More efficient way for ofNode::getGlobalOrientation (3~x faster)

.travis.yml
Keep Travis Using Latest Default Xcode (also Travis has updated most to latest Xcode).
https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce
=> Xcode 9.4 Default Travis

scripts/qtcreator/templates/wizards/openFrameworks/qtcreator.qbs, scripts/qtcreator/templates/wizards/openFrameworks/wizard.json, scripts/qtcreator/templates/wizards/openFrameworksUpdate/qtcreator_update.qbs, scripts/qtcreator/templates/wizards/openFrameworksUpdate/qtcreator_update_no_addons.qbs, scripts/qtcreator/templates/wizards/openFrameworksUpdate/wizard.json
Discussed here: https://github.com/openframeworks/openFrameworks/issues/6103
Add a new page in the QtCreator wizards (for new project and update project) with a checkbox named "Create a console window when application start"
It will add a new line in the qbs file:
```
// create a console window when the application start
consoleApplication: false
```
Tested with OF 0.10.0, msys, QtCreator 4.6.1, Windows 7
I'm not experimented with pull requests, hope this is right.
=> Add option to create console window in QtCreator wizards

libs/openFrameworks/gl/ofGLUtils.cpp, libs/openFrameworks/graphics/ofImage.cpp, libs/openFrameworks/utils/ofUtils.cpp
Currently `ofLoadImage` spends a large percentage of its time on `ofToDataPath` when loading lots of small images from disk.  These changes help speed this up when absolute paths are already known.
Before:
After:
This has only been tested a bit, so a code review thinking across platforms is probably a good idea.
=> Speed up image loading

libs/openFrameworks/graphics/ofTrueTypeFont.cpp, libs/openFrameworks/graphics/ofTrueTypeFont.h
`letterSpacing` scales the default spacing between glyphs, as such it needs to default to `1.f`.
This means, letterSpacing of 1.0 means neutral letter spacing, glyph is placed in default position, respecting the glyph's advance value.
* If letterSpacing is 0.75, this means that spacing between letters is reduced by 0.25 * the *whitespace width* of the current font.
*If letterSpacing is 1.25, this means that an additional space of 0.25 * the *whitespace width* is added between letters.
+ Since proportional fonts have per-glyph advance values, we use a constant width as *whitespace width*.
+ additionally, per spec, we scale the default *whitespace width* by the font's property `spaceSize`
Note that to calculate the default whitespace width for a font we don't use the advance value for the …
=> Fix ttf font bounding box calculations

scripts/templates/vs/emptyExample.vcxproj
Try to solve two issues.
With this PR's initial commit, Issue 1 has been solved. But Issue 2 still remains.
There are several output files should be placed inside of an intermediate file folder.
For example,
And these changes should be tested on VS2018 and VS2015.
More commits coming later.
Official documents about VS build macro
https://docs.microsoft.com/en-us/cpp/ide/common-macros-for-build-commands-and-properties?view=vs-2017
=> Bugfix VS project template

scripts/vs/setupCommandLine.cmd
Two fixes and one new feature of VS build scripts.
Fixes
- `devenv` ignores %PLATFORM% parameter. It compiles against win32 even %PLATFORM% is x64.
- `msbuild` ignores %ACTION% parameter. It can only excute "build" action even %ACTION% is clean, etc.
Feature
- Use `/maxcpucount` option to enable parallel compile.
More info
Excute `msbuild /?` command for available options.
=> Bugfix VS buildscript

libs/openFrameworks/3d/ofCamera.cpp
As is stands, setting an off-axis viewport or a lens offset on an ofCamera will only affect the projection matrix if the camera is _not_ ortho enabled.  I can't think of a case why one would want this behavior.
This PR makes a small change to ofCamera that shifts the ortho viewport by the lensOffset via matrix translation exactly how the perspective counterpart does it.
The use case I have is a multi-computer rendering of the same app in which i need a mix of perspective and orthographic views originating at the same eye point.  In perspective mode, setting the viewports with the `offAxisViewport` method is perfect, but it fails to do anything when I enable ortho.  This PR makes both modes behave in the same way.
If orthogonal and perspective matrices are to be generated by the same …
=> ofCamera with ortho enabled to respect a lensOffset

examples/gles/customEGLWindowSettingsExample/src/main.cpp
just realized that the example was using updated syntax from 59fcc11
=> Revert "Update customEGLWindowSettingsExample main.cpp"

libs/openFrameworks/graphics/of3dGraphics.cpp
+ calculation of arrow tip translation matrix was not correct,
- glm::rotation requires normalized input parameters
- application order of partial transforms was flipped (rotation must
come before translation)
fixes issue #6162
=> fix drawArrow internal matrix calculation

libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
This fixes the copy_dlls make target on msys2 (windows)
fixes #6165
=> define APPNAME earlier to fix msys2 copy dlls failing

scripts/templates/osx/openFrameworks-Info.plist
This should address the permissions issue for 10.14 users. 
Tagging #6149
=> added camera and microphone permissions for mojave

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
fix for xcode template file to allow PG to add frameworks and fix broken projects. 
closes #6172
=> fix for xcode template file to allow PG to add frameworks

.appveyor.yml, scripts/ci/msys2/run_tests.sh
fixes: #6168 
This does not update msys2 runtime and pacman which could be needed if this fails
=> fix ssl dependencies

addons/ofxGui/src/ofxInputField.cpp, addons/ofxGui/src/ofxSlider.cpp
Fix for this issue https://github.com/openframeworks/openFrameworks/issues/6133
The scrolling was still being handled when the gui was not being drawn both in ofxSlider and ofxInputField. 
Tested using the code provided in the mentioned issue.
Also, 
there is some redundant code in ofxSlider.cpp and ofxInputField.cpp. Both have a function called `toRange(...)` which is identical in both. When the scroll callback is called this function  is called. Can't we move this function to the ofxBaseGui for instance? Also, the code used in the scroll callback in both ofxSlider and ofxInputField is quite similar, maybe moving this to ofxBaseGui might be better too.
=> Fix ofx gui slider scrolling

libs/openFrameworks/sound/ofSoundBuffer.cpp
ofSoundBuffer::checkSizeAndChannelsConsistency is crashing when calling ofSoundBuffer::getChannel with channels = 1
=> ofSoundBuffer getChannel fix

libs/openFrameworks/utils/ofConstants.h
reported from here.
https://forum.openframeworks.cc/t/arch-linux-compilation-error-after-updating-the-system/31097
and solution?.
https://github.com/mupen64plus/mupen64plus-video-z64/pull/16
=> fix `conflicting declaration` OpenGL on some linux distros

scripts/templates/ios/src/main.mm
Multitouch was never broken on iOS - it had to be enabled from the main.mm file. What made it confusing was that `settings.enableMultiTouch` was not present in the template to begin with, so just added it! Makes life slightly easier :)
=> Fixes multitouch confusion on iOS

libs/openFrameworks/sound/ofSoundBuffer.cpp
write pointer is incremented twice, removed the unnecessary increment
=> fix buffer overflow in linear interpolation of audio buffer with loop

addons/ofxOpenCv/src/ofxCvConstants.h
Added openCv's C++ headers which got removed in because of some changes in opencv.
This is addressing what's discussed [here](https://forum.openframeworks.cc/t/ofx-does-not-recognize-native-opencv-functions/31609)
As noted in that thread,
> ofxOpenCv is only including the C header #include "cv.h", while ofxCv includes the C++ one #include "opencv2/opencv.hpp"
> OF 0.9.8 used opencv 2.4.8 where the cv.h file included the C++ headers, as you can see [here](https://github.com/opencv/opencv/blob/2.4.8/include/opencv/cv.h#L63-L72), while OF 0.10 uses opencv 3.1 which does not include those headers as you can see [here](https://github.com/opencv/opencv/blob/3.1.0/include/opencv/cv.h#L63-L67)
=> Fix. Added openCv C++ headers.

libs/openFrameworks/gl/shaders/phong.frag
Proposed bugfix for: #6221 phong.frag: v_transformedNormal and eye should be re-normalized
Changes to libs/openFrameworks/gl/shaders/phong.frag
line 68, function pointLight(...): vec3 eye normalized so that that eye direction is a normalized vector. This means that calculation of the halfVector (in line 82) should now be correct. Previously 'VP' was normalized but 'eye' was un-normalized, which resulted in incorrect calculation of the halfVector, and hence incorrect placement of specular highlights.
line 127, function spotLight(...): vec3 eye normalized so that that eye direction is a normalized vector. This means that calculation of the halfVector (in line 142) should now be correct. Previously 'VP' was normalized but 'eye' was un-normalized, which resulted in incorrect calculation of …
=> phong.frag: v_transformedNormal and eye should be re-normalized (#6221)

addons/ofxGui/src/ofxGuiGroup.cpp, addons/ofxGui/src/ofxPanel.cpp
fixed `ofxGuiGroup` events propagation.
When using an `ofEasyCam` and an `ofxPanel` or `ofxGuiGroup` object,if moving the camera by dragging the mouse and the mouse was released over the gui, then when trying to change something in the gui would also change the `ofEasyCam` object. 
This issue got reported [here](https://forum.openframeworks.cc/t/clicks-on-ofxgui-panel-params-pass-through-to-main-window/31368/3) 
Additionally, I changed all the instances of `ofPoint` and `ofVec*f` into glm.
=> Fix ofx gui events propagation

examples/shader/01_simpleColorQuad/src/main.cpp, examples/shader/02_simpleVertexDisplacement/src/main.cpp, examples/shader/03_simpleShaderInteraction/src/main.cpp, examples/shader/04_simpleTexturing/bin/data/shadersES2/shader.frag, examples/shader/04_simpleTexturing/bin/data/shadersES2/shader.vert, examples/shader/04_simpleTexturing/src/main.cpp, examples/shader/04_simpleTexturing/src/ofApp.cpp, examples/shader/05_alphaMasking/src/main.cpp, examples/shader/06_multiTexture/src/main.cpp, examples/shader/07_fboAlphaMask/src/main.cpp, examples/shader/08_displacementMap/src/main.cpp, examples/shader/09_gaussianBlurFilter/src/main.cpp
this PR try to fix shader examples for Raspberry Pi
fix https://github.com/openframeworks/openFrameworks/issues/5056
=> fix shaders examples for Raspberry Pi

libs/openFrameworks/video/ofAVFoundationVideoPlayer.h, libs/openFrameworks/video/ofAVFoundationVideoPlayer.m
at the moment AVFoundation player does not allow setting frame/position and speed before the player is ready. isReady is handled internally only - users do not have a way to know when the movie is ready to play.
proposing these changes so frame/position and speed can be set before the video is ready to play.
=> AVFoundationPlayer - set speed, frame/position when beeing ready to play

libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk
This adds -mwindows linker flag to release builds. The debug build still presents a console, it's a debug build after all
=> Fix console still present on msys2 builds

libs/openFrameworks/app/ofAppRunner.h, libs/openFrameworks/utils/ofLog.cpp
this PR replaces `ptr_fun` with `function<...>`.
`ptr_fun` is deprecated in C++11, and deleted in C++17.
=> prepare to c++17

libs/openFrameworks/gl/ofTexture.cpp
`ofTexture::loadData` with `int32_t*` and `uint32_t*`inputs sets the type in the call to `glTexSubImage2D` incorrectly to `GL_SHORT`, causing corruption.
=> fix data type on texture load from int32_t* and uint32_t*

libs/openFrameworks/utils/ofUtils.cpp
remove line break from ofGetVersionInfo() so I can make this kind of comparsion
```c++
if (ofGetVersionInfo() == "0.10.1-stable") {
largura += 4;
}
```
instead of
```c++
if (ofGetVersionInfo() == "0.10.1-stable\n") {
largura += 4;
}
```
=> remove line break from ofGetVersionInfo() end

libs/openFrameworks/utils/ofSystemUtils.cpp
See issue #4945.
I've made changes for macOS as suggested in the thread and adapted it for Linux and Windows.
I've only been able to test on Linux right now, I believe it should work fine on macOS, but I'm really unsure on the windows side.
I haven't looked at the parts of the code that deal with android and emscripten.
=> Make ofSystemTextBoxDialog return empty string on cancel.

scripts/linux/fedora/install_dependencies.sh
Add `jack-audio-connection-kit-dbus` as a Fedora dependency.
On a fresh system the projectGenerator reports "projectGenerator: error while loading shared libraries: libjack.so.0: cannot open shared object file: No such file or directory".
Installing `jack-audio-connection-kit-dbus` fixes this issue at least on Fedora 29.
=> Add jack-audio-connection-kit-dbus as Fedora dep

examples/README.md
I noticed the link for Input / Output on line 37 was broken. Changed '-' to '_' which should fix the problem.
=> Broken Link Fix

libs/openFrameworks/3d/ofEasyCam.cpp, libs/openFrameworks/3d/ofEasyCam.h
when calling `setPosition(..)` on an `ofEasyCam` object during setup, by default it will no go to this position as it will get over riden by the auto distance function of it. Now, once calling `setPosition(..) ` during setup, auto distance is disabled and the camera will get positioned where it needs to be.
=> Fix easy cam auto distance

CONTRIBUTING.md
Use the correct absolute path instead of a relative path in two links. The malformed path went to a 404 page instead of the issue tracker.
Existing url:
`https://github.com/openframeworks/openFrameworks/blob/master/github.com/openframeworks/openFrameworks/issues`
Fixed url:
`https://github.com/openframeworks/openFrameworks/issues`
=> Fix url for issue tracker

scripts/linux/fedora/install_dependencies.sh
The script uses ROOT when modifies the ofxOpenCv addon. Without it the script fails.
=> Added missing ROOT variable to fedora install_dependencies.sh

libs/openFrameworks/3d/ofMesh.inl
If users try to load a PLY with double precision position data instead of float data, OF will act like its floating point precision, instead of silently loading the model incorrectly.
This was discussed in my forum post [here](https://forum.openframeworks.cc/t/solved-double-precision-ply-file/32506 ) It was suggested I make a PR so here we are. :) thanks.
=> Add handling of double precision position data in PLY model loader

addons/ofxGui/src/ofxGuiUtils.h, addons/ofxGui/src/ofxSlider.cpp, addons/ofxGui/src/ofxSlider.h
Instead of calling `ofPath` tessellation on each draw call for sliders, slider knows how to generate mesh for bar rectangles itself. The mesh is cached, and updated **iff** the slider value changes.
Rect mesh caching works similarly to the slider's internal caching of text meshes.
You might notice a slight performance improvement on GUIs with multiple sliders with this PR.
As an additional check/optimisation, slider fill rectangles with either width or height < 1 pixels will also not be drawn (they would not be visible anyway).
By *not* using `ofPath` (and by implication the tessellator) to draw the slider we avoid having to ask the tessellator to tessellate extremely small paths, in which case it had a tendency to throw its hands up in
despair or disgust (hard to tell from a stack trace) …
=> update method for drawing slider bars

libs/openFrameworks/sound/ofSoundBuffer.cpp
there was a small type that was making `ofSoundBuffer::copyFrom` not to set the samplerate to the value passed as argument.
ofSoundBuffer's variable for the sample rate is called `samplerate`while the argument passed to the copyFrom function was called `sampleRate`. The function was setting the sample rate using `samplerate` thus it would never actually set it to the argument passed. This PR fixes this issue.
=> ofSoundBuffer::copy from was not being set properly

libs/openFrameworks/3d/ofMesh.inl
`ofMesh.inl` contains a comment like this:
//TODO: add index generation for other OF_PRIMITIVE cases
This PR implements one of those missing cases (`OF_PRIMITIVE_TRIANGLE_STRIP`)
=> Implement ofMesh .save() of triangle strips

addons/ofxOsc/src/ofxOscSender.cpp
as mentioned here: https://forum.openframeworks.cc/t/ofxoscsender-falls-back-on-localhost/32442/2
and discussed there: https://github.com/bltzr/openFrameworks/commit/93ccf317e4377dd754655fb91956a3efe0c43b76 with @danomatika 
when providing an unavailable host to ofxOscSender.setup() it was falling back to localhost, which prevented from knowing that the connection to the desired host failed.
those 2 commits fix that, and post an error message when the endpoint cannot be reached
=> ofxOscSender.setup() fix

libs/openFrameworks/sound/ofSoundBuffer.cpp
The tick count and device id were not being passed when copying the buffers which I think are very useful.
=> ofSoundBuffer: copying tick count and device id when calling copyTo

libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs
Currently when dealing with complex addon_config.mk files, QTCreator was failing in situations like this:
```make
ADDON_LDFLAGS  += -Wl,--start-group
ADDON_LDFLAGS  += /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.a
ADDON_LDFLAGS  += /opt/intel/mkl/lib/intel64/libmkl_sequential.a
ADDON_LDFLAGS  += /opt/intel/mkl/lib/intel64/libmkl_core.a
ADDON_LDFLAGS  += -Wl,--end-group
ADDON_LDFLAGS  += -lpthread -lm -ldl
```
While makefile works fine, QTCreator/QBS failed when linker flags were already escaped (-Wl, or -Xlinker,).
According to the documentation, linker flags should not be escaped.
https://doc.qt.io/qbs/qml-qbsmodules-cpp.html#linkerFlags-prop
So, this PR fixes that for addons.
=> Correctly parse escaped linker flags in addons for QTCreator.

addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js
The Runtime object has been removed for quite some time at this point. 
So `Runtime.dynCall` should be changed to just `dynCall` in `library_html5audio.js` file.
Before the fix, it generated the following error: (No sound)
> Uncaught TypeError: Runtime.dynCall is not a function at ScriptProcessorNode.stream.onaudioprocess
After the fix, I could properly run examples that use `ofSoundStream` on a browser through Emscripten.
Relevant issue: https://github.com/openframeworks/openFrameworks/issues/6345#issue-472141591
=> Fix Uncaught TypeError: Runtime.dynCall

.appveyor.yml, scripts/msys2/install_dependencies.sh
Fix #6330.
Version of GCC included in appveyor image is older than the one used to build openframeworks.
This results in an error when loading the Dlls at runtime.
install_dependencies.sh upgraded to use the MINGW_PACKAGE_PREFIX env variable defined by MSYS environment instead of the custom made mingw-w64-$arch. That should make install_denpendencies compatible with MINGW64 with no changes.
=> Upgrade MSYS2 packages in appveyor (including GCC)

libs/openFrameworks/graphics/ofImage.cpp, libs/openFrameworks/graphics/ofImage.h
Included missing header in ofImage.h required for instantination of ofImage_::clone().
=> Included missing header in ofImage.h required for instantination of of ofImage_::clone()

libs/openFrameworks/graphics/ofPath.cpp
Explicitly set default values for `ofPath::Command`.
Setting these makes serialization and other customization a bit easier.
=> Add default values for ofPath::Command members.

CHANGELOG.md, docs/msys2.md, scripts/msys2/install_dependencies.sh
Fix #5740 : It's better not to modify user environment without him knowing. Moreover, setting PATH is optional. So move instructions to documentation
Fix #6211 : documentation typo
=> MSYS2 : Remove setup of PATH env var in install_dependencies

scripts/templates/osx/openFrameworks-Info.plist
This should solve the permissions issues in #6193 as all apps made from OF were being treated as the same app by the system.  
This makes each App's bundle ID unique which fixed the issue of another OF app interfering with the camera permissions on 10.14.
=> bugfix for mojave permissions issues with camera. closes #6193

scripts/dev/nightlybuilds.sh
This isn't the cause of the current nightly build errors, but it hides the actual cause. 
Because lasthash.txt is written before the build is successful it means it's not trying to do the build each night even though the actual packages are older than the last commit.  
Moving it to the end of the script will mean that our log file will show the real error messages preventing the build.
=> Bugfix - last commit hash written before build successful.

scripts/dev/create_package.sh
Project generator seems to be compiling fine now after installing poco. 
This seems to be the last step to getting the nightlies to build again. 
compiling the PG with DebugNoOF produces bin/projectGenerator_debug but a few lines down the script calls bin/projectGenerator
=> bugfix changes the create_package script to call executable generated by DebugNoOF

scripts/dev/nightlybuilds.sh
Nightly script needs to cd back to the scripts/dev/ folder after successful build to write lasthash.txt to the correct location.  
Otherwise lasthash.txt in scripts/dev/ is not getting updated.
=> nightly script bug fix - needs to cd back to scripts/dev/

addons/ofxiOS/src/core/ofxiOSEAGLView.mm, addons/ofxiOS/src/core/ofxiOSGLKView.mm
=> bugfix. iOS fixes reversed touches when not using hardware orientation.

scripts/templates/vscode/Makefile, scripts/templates/vscode/config.make
To support vscode template, we need Makefile.
macOS (and Linux probably) PG copy these files by default but Windows does not.
=> feature-add-Makefile-for-vscode-template

scripts/templates/android/build.gradle
Hi
Just hit the same error as the one below, and it seems that project generator uses the template under oF directory.
I have added the line to comply with com.android.support:support-v4:25.+ and tested with 
android studio 3.5 that it builds and runs.
https://forum.openframeworks.cc/t/android-error-failed-to-resolve-com-android-support25/32436
=> [android] add maven url to comply with v4:25

addons/ofxNetwork/src/ofxTCPManager.cpp, addons/ofxNetwork/src/ofxTCPManager.h, addons/ofxNetwork/src/ofxTCPServer.cpp, addons/ofxNetwork/src/ofxTCPServer.h, addons/ofxNetwork/src/ofxTCPSettings.h, examples/communication/networkTcpServerExample/src/ofApp.cpp
When you don't close your socket cleanly (e.g. your program crashes), it can linger on your OS for quite some time before you're allowed to reuse the same port.
In this state, calls to `bind` will return `EADDRINUSE` error.
Most software deals with this by setting the `SO_REUSEADDR` socket option before calling `bind`. However, this functionality is missing from ofxTCPManager.
It looks like it confuses some people too:
https://forum.openframeworks.cc/t/tcp-server-socket-not-closing-already-in-use/22793
I'm setting it to `false` by default, to maintain old behaviour, but openFrameworks should seriously consider enabling it by default (that is, if this patch is accepted, of course).
NOTE: not tested on Windows, but should work there AFAIK.
=> Add SO_REUSEADDR option to ofxTCPManager and ofxTCPServer.

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
Tested on Xcode 9 through to Xcode 11. 
This fixes signing for all unsigned dynamic libraries.
See #6383
Would be good to merge this before doing our next release.
=> added flag to xcode template to fix code signing errors. Closes #6383

addons/ofxNetwork/src/ofxTCPManager.cpp
adds a missing explicit cast to ofxTCPManager.
=> add missing explicit cast

libs/openFrameworks/utils/ofXml.cpp
This is an error I saw in the nightly. 
Just switching the deprecated function to the replacement function name.
=> bugfix. fixes error with Xcode build due to depracted function error.

.appveyor.yml, libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk, scripts/ci/msys2/build.sh, scripts/msys2/install_dependencies.sh
Simplify MSYS2 packages installations.
Clean up package installation on appveyor.
Clean up MSYS2 makefile (and make it compatible with MINGW64)
=> MSYS2 installation and compilation enhancements

libs/openFrameworks/video/ofAVFoundationGrabber.mm
* add init for grabber was not init.
* replace substitute by nil for unused allocation.
=> [tiny fix] brush up ofAVFoundationGrabber

libs/openFrameworks/graphics/ofPolyline.inl
Added a couple of other initializations to zero. 
The rest all seem assigned safely.
=> bugfix ofPolyline::getSmoothed missing glm initialization. closes #6414

CHANGELOG.md, addons/ofxGui/src/ofxSliderGroup.cpp
Fixes #6381 
Adds a check to update header colors value when the header is minimised. Minimum viable code to test it works.
```
//in ofApp.h
ofParameter<ofColor> color;
ofxPanel gui;
//---
//.cpp
//--------------------------------------------------------------
void ofApp::setup(){
gui.setup();
gui.add(color.set(ofColor(255, 0, 0)));
}
//--------------------------------------------------------------
void ofApp::update(){    
float blue = 255 * sin(ofDegToRad(ofGetFrameNum()/1.0));
color = ofColor(color->r, color->g, abs(blue));
}
//--------------------------------------------------------------
void ofApp::draw(){
ofSetColor(color);  
ofDrawCircle(ofGetWidth()/2, ofGetHeight()/2, 100);        
gui.draw();
}
```
=> Fixes #6381 based on @LYHSH code snippet

libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs
qt creator prefixed osx frameworks with the global addons path. 
`:-1: error: framework not found /Users/thomasgeissl/libs/oF/addons/ofxMidi/CoreMIDI
`
=> not prefixing frameworks with the global addons path

addons/ofxOpenCv/src/ofxCvHaarFinder.cpp
This fixes the broken cameraLensOffsetExample listed in #6412 
Old CV Haar approach clears the blobs vector before adding to it. 
New approach forgot to clear the vector making the blobs vector increase in size continuously.
=> bugfix findHaarObjects. fixes constant push back to blobs every frame.

examples/shader/08_displacementMap/bin/data/shadersES2/shader.vert, examples/shader/08_displacementMap/src/main.cpp
OpenGL ES2 needs texture2DLod() instead of texture2D() in the vertex shader
=> Fixed OpenGL ES2 shader example 08

examples/windowing/multiWindowExample/src/ofApp.cpp, examples/windowing/multiWindowOneAppExample/src/ofApp.cpp
Had me confused for a bit when resizing the example, this way the circle stays in the centre even if the window is a non square one.
=> update multi window example to draw w/2, h/2 instead of w/2, w/2.

libs/openFrameworks/types/ofRectangle.h
If `ofRectangle`s field `position.z` was not explicitly set, this would mean that garbage memory most likely remained stored in place of the .z coordinate of a rectangle's position.
Whilst this didn't affect any 2D operations, as soon as the rectangle in question was going to be drawn, its .z position would be fed straight into an ofMesh, and then a vertex shader, and all sorts of mayhem could happen.
Test this with `guiFromParametersExample` when opening the `ofxColorPicker` GUI element after selecting a colour...
By adding a default member initialiser to `.position`, the .z coordinate will receive default 0, which is what any 2D graphical element would be expected to be initialised with.
Fixes #6419
=> add default member initialiser for position

libs/openFrameworks/app/ofAppGLFWWindow.cpp, libs/openFrameworks/app/ofAppGLFWWindow.h
this fixes #6445 
I tried a few different methods first but this is needed due to how many frames it takes the window to restore on the RPI. 
Tested toggling fullscreen from both an app started in windowed and fullscreen mode.
=> bugfix fixes fullscreen issues on RPI. closes #6445

libs/openFrameworks/graphics/ofTrueTypeFont.cpp, libs/openFrameworks/graphics/ofTrueTypeFont.h
We were calling prevC,c but should be leftC,rightC which also
changes depending on the text direction.
Fixes #6437
=> ofTruetypeFont: fix kerning calculation

libs/openFrameworks/graphics/ofPolyline.h
Wasn't as bad as it initially seemed. 
Just needed the non forward decelerations in ofPolyline. 
Closes #6463
=> bugfix. fixes errors if legacy vector math is enabled. closes #6463

INSTALL_FROM_GITHUB.md
Also minor headline formatting to make sections more obvious.
=> Include how-to-update section

scripts/linux/debian/install_dependencies.sh
This commit adds libgconf-2-4 to the `apt install` command in the
`install_dependencies.sh` script for Debian in
`scripts/linux/debian`.
Tested on Debian 10.2 (buster).
Closes #6493.
=> Add libgconf-2-4 to debian/install_dependencies.sh

libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp, libs/openFrameworks/sound/ofOpenALSoundPlayer.h
Declare statics inside cpp to avoid forward declaration
=> ofOpenALSoundPlayer: fix conflicting forward declaration in newer versions

scripts/dev/create_package.sh, scripts/dev/download_libs.sh, scripts/dev/nightlybuilds.sh, scripts/dev/release.sh, scripts/msys2/install_dependencies.sh
This should work for nightly builds and releases. 
@oxillo maybe you could test the generated package and let us know if it works okay for you?
( msys2 64bit build ) 
http://ci.openframeworks.cc/versions/v0.11.0/of_v0.11.0_msys264_release.zip
=> add msys2 64bit builds to nightly and release scripts.

libs/openFrameworks/app/ofAppGLFWWindow.h
set default AA numSamples to 0 for GLFW window for RPi. closes #6497
=> set default AA numSamples to 0 for GLFW window for RPi. closes #6497

libs/openFrameworks/events/ofEvent.h
This allows to things, checking not being out of bounds when removing a listener and checking if there are any registered listeners. 
@arturoc @bakercp
=> ofEventListeners: added size() method.

libs/openFrameworksCompiled/project/emscripten/config.emscripten.default.mk
Hi, 
I hope I did the pull request the right way...
You need to set the flag DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR to 0 to make Open Frameworks work with the latest fastcomp Emscripten (1.39.6).
I also added some additional flags but they are mainly for debugging...
https://github.com/Jonathhhan/openFrameworks/blob/patch-release/libs/openFrameworksCompiled/project/emscripten/config.emscripten.default.mk
I am not able to change the template.html so that it is possible to use the flag DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 which would be even nicer.
Here is the topic from the forum: https://forum.openframeworks.cc/t/latest-emscripten-doesnt-work-on-examples/30463/54
=> emscripten  DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR

addons/ofxGui/src/ofxBaseGui.cpp, addons/ofxGui/src/ofxBaseGui.h
So currently if you try to use an ofxGui on a multiwindow app and draw it on a window other than the main window, you need to setup the gui before the main app setup is run, which is quite cumbersome.
Besides this, if you have an app and want to open a new window and draw in it an already setup gui the mouse events will not work. You need to disable and reenable mouse events while the window on which you want to draw the gui is the currently renderer window. 
So, the fix for this is quite simple and effective. It takes the same idea from the ofEasyCam events.
It stores a pointer to the ofEvents() and it checks against it on every draw call so if it changed it will reregister the mouse events.
This allows:
*  to avoid [this nasty line …
=> ofxGui: Updating events to allow multiwindow functioning

.appveyor.yml, libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk, scripts/ci/ccache.sh, scripts/ci/msys2/build.sh, scripts/ci/msys2/run_tests.sh
- remove use of ccache in MSYS2 appveryor build (fix #6565)
- fix "missing separator" error with make 4.3 (fix #6535)
Both fix in a single PR to have build pass on Appveyor 
Replace #6564
=> Merge make43 msys2ccache

.appveyor.yml, scripts/ci/ccache.sh, scripts/ci/msys2/install.sh
Fix #6565 - use mingw(32|64) version of ccache instead of msys version.
Revert disabling of ccache in #6566 
Remove duplicate use of setting ccache (by setting CXX in ccache.sh) and by using USE_CCACHE and setting PLATFORM_CXX in msys2 makefile. makefile solution (with USE_CCACHE) has been retained.
=> MSYS2 : (re)enable ccache in appveyor

.appveyor.yml
Reorganize YAML
- setup `platform:` matrix
- use `for:` to separate build logics MSYS2/VS - avoid `if BUILDER= ... ` statements
Reduce MSYS2 installation/upgrade time using a clean MSYS2 install.
For comparison :
- baseline : upgrade current install and install OF packages : 10min or more
- remove not needed package, upgrade, install OF packages : 7-8min 
- clean install, upgrade, install OF packages : 4min  
With the additional gain of CCache, MSYS2 builds are around 15min for MINGW32 and 25min for MINGW64
=> [CI] Optimize MSYS2 on Appveyor

addons/ofxGui/src/ofxSlider.cpp
the text input field of the ofxGuiSlider not positioned correctly as a side effect of commit b9612146dcb1bb74b2cfa95613ef175632119e70  .
Please merge @ofZach @arturoc @ofTheo
=> fixed ofxGuiSlider text input positioning error

addons/ofxGui/src/ofxGuiGroup.h, addons/ofxGui/src/ofxSliderGroup.cpp
ofxGui: Fix possible memory leak, because keyword "new" was being used but not deleted. Now using only unique_ptr
Related to:
#6145
and partially addressed in commit
b961214
(It was my fault not adding this fix to that commit)
=> Fix ofxGui memory leak

libs/openFrameworks/sound/ofSoundPlayer.h
Hello oF development team. This is a small changes.
I find a typo in `unloadSound`  deprecated message, and this PR may solved it.
Thanks.
=> improve typo in unloadSound deprecated message

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m
this PR will fix ofVideoPlayer start playback after load automatically on macOS.
=> fix undesired playback after load

libs/openFrameworks/utils/ofSystemUtils.cpp
Macos only: Minor change that properly shows the title of the NSOpenPanel when calling ofSystemLoadDialog
=> Fixed title not being shown when calling ofSystemLoadDialog in macos

libs/openFrameworks/3d/ofMesh.inl
flatNormals() doesn't work because indices gets reset by clear(), after which the indices are needed.  The simple fix is to make a local copy of indices.
=> Fix flatNormals()

libs/openFrameworks/gl/ofShader.cpp
Regex did not work when #define was originally set to `0` (because of the hex format). This is now fixed.
Also made this block of code use tabs like the rest of the file.
=> Fix regex when ofShader int define is set to 0.

addons/ofxGui/src/ofxGuiGroup.cpp, addons/ofxGui/src/ofxSliderGroup.cpp, addons/ofxGui/src/ofxSliderGroup.h
ofxGui:: ofxSliderGroup: properly removing listeners which could lead to a crash when dynamically creating ofxGui objects
ofxGuiGroup: added missing creation of sliders for an ofParameter<ofRectangle> when adding an ofParameterGRoup containing it
=> Fix ofx slider group listeners removal

libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk
Similar to this: https://github.com/openframeworks/openFrameworks/issues/5445 
When your project contains .c files, the of makefile currently passes the -std=c++11 to the compiler, which throws an error.
This wasn't a problem when using GCC, but it is when trying to use on CLANG.
Using the same strategy as mentioned on the issue above fixed the problem.
=> split PLATFORM_CFLAGS into PLATFORM_CXXFLAGS to avoid compile errors on .c files

.travis.yml
Remove the "exclude gcc" section of the travis.yml file to bring back auto ci linux builds
=> update travis.yml to fix linux build

libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk, libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk
removed march and mtune flags from config.linux.common.mk and config.msys2.default.mk
related to this post
[https://forum.openframeworks.cc/t/linux-problem-please-help/36509](https://forum.openframeworks.cc/t/linux-problem-please-help/36509)
=> remove flags

libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig
Allows Xcode to build native arch - so this should make all projects compatible with both older 64bit systems and newer arm64 systems.
=> Macos xcode fixes

scripts/dev/create_package.sh
The project generator was correctly setting the OF_ROOT path for the config.make files. 
For the nightly builds though and package generation this wasn't desired. 
Closes #6650
=> fixes wrong OF_ROOT path for make files. closes #6650

libs/openFrameworks/app/ofAppGLFWWindow.cpp
single buffering currently produces a blank screen on macOS. 
this fix from #6612 makes it work again. thanks @liasomething !
=> bugfix. make non-double buffer work for macos. closes #6612

scripts/templates/vs/emptyExample.vcxproj
Currently if you have two files with the same name in a project the first one will overwrite the second one when producing the .o files causing linking errors. This changes the output location to use the relative directory in the build folder.
=> vs bugfix fixes issue where two different cpp files with same name produce same .o file

.github/workflows/build-emscripten.yml, libs/openFrameworksCompiled/project/emscripten/config.emscripten.default.mk, scripts/ci/emscripten/build.sh
I tried the newer 2.0.0 emsdk but that had a bunch of errors so going to stick with 1.40.0 which is still newer than what we had been using.
=> Fix emscripten to use non deprecated emsdk docker image

scripts/dev/downloader.sh
The nightly build script was broken by #5848 because $2 ( for silent args ) wasn't been checked if set before testings its value.
I tried a few different solutions that felt like they should of worked but didn't.
These changes fixes the downloader function.
=> fix downloader to check if $2 is set first before testing its value.

libs/openFrameworks/graphics/ofImage.cpp
closes #6528
Also address another edge case where changing the number of channels for `OF_IMAGE_COLOR` or `OF_IMAGE_COLOR_ALPHA` can assumer RGB(A) when BGR(A)
=> fixes ofImage grabScreen and resize getting swapped R and B.

libs/openFrameworks/math/ofVectorMath.h
Fix #6496 fix class-memaccess warning on unused glm types
=> core: fix GLM warnings 

addons/ofxNetwork/src/ofxNetworkUtils.cpp, addons/ofxNetwork/src/ofxNetworkUtils.h, addons/ofxNetwork/src/ofxTCPClient.cpp, addons/ofxNetwork/src/ofxTCPManager.cpp, addons/ofxNetwork/src/ofxUDPManager.cpp, tests/addons/networkTcp/src/main.cpp, tests/addons/networkUdp/src/main.cpp
As proposed in #6457 
-   Deprecate ofxNetworkCheckError()
-   Add int ofxNetworkGetLastError() to return the last error
-   Add void ofxNetworkLogError(int err, const char* file, int line) to log an error that happened on line line in file file
-   Add ofxNetworkLogLastError() that is a shortcut for ofxNetworkLogError(ofxNetworkGetLastError(), __FILE__, __LINE__)
=> Fix ofx network

libs/openFrameworksCompiled/project/osx/config.osx.default.mk, libs/openFrameworksCompiled/project/qtcreator/ofApp.qbs, scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
Removed install_name_tool fmod post build step as fmod dylib now has correct path. 
Update qbs template to look for dylibs in Contents/Frameworks/
This should allow Xcode, Makefiles and QT Creator to compile without needing install_name_tool steps
=> Remove install_name_tool steps for fmod 

libs/openFrameworks/utils/ofXml.cpp, libs/openFrameworks/utils/ofXml.h, tests/utils/xml/addons.make, tests/utils/xml/src/main.cpp
fix #6677 : pugiXML select_single_node deprecation
fix #6676 : getChildren(name) not returning only children with name
fix #6111 : Always process floats in C locale (with '.' as decimal separator) independently of current system locale (XML floats are always with '.')
Log error when something goes wrong when loading or saving a document.
=> ofXML fixes

scripts/templates/osx/emptyExample.xcodeproj/xcshareddata/xcschemes/emptyExample AppStore.xcscheme, scripts/templates/osx/emptyExample.xcodeproj/xcshareddata/xcschemes/emptyExample Debug.xcscheme, scripts/templates/osx/emptyExample.xcodeproj/xcshareddata/xcschemes/emptyExample Release.xcscheme
this prevents xcode from passing unwanted args to the app which makes some command line arg parsers crash
=> disabled debugging when browsing versions, fixes #6687

libs/openFrameworks/app/ofAppGLFWWindow.cpp
Tested on a multi monitor setup and removing these lines, doesn't seem to change anything in a variety of scenarios. 
I think GLFW fixes since we added those lines have made them unnecessary. 
Removing the lines, lets OF start in fullscreen on Arm / M1 macs without crashing. 
Closes #6685
=> bugfix macos arm fullscreen crash. closes #6685

examples/strings/regularExpressionExample/src/ofApp.cpp
hello
the regex example was crashing on osx, m1.
i removed the closing parenthesis. i guess adding an opening one would work as well. not sure this example requires a capture group.
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::regex_error: The parser did not consume the entire regular expression.
terminating with uncaught exception of type std::__1::regex_error: The parser did not consume the entire regular expression.
```
=> fix regular expression example

examples/input_output/imageLoaderWebExample/src/ofApp.cpp, examples/video/videoGrabberExample/src/ofApp.cpp
current example was broken on macOS.
=> videoGrabberExample - set the inverted pixels to actual grabber dimensions

libs/openFrameworksCompiled/project/osx/config.osx.default.mk
Updating Info.plist with retina entry, so it can run OK on Apple M1, Big Sur while using Make to build.
I've added NSCameraUsageDescription and NSMicrophoneUsageDescription that were missing too.
=> Update Info.plist with retina entry

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidWindow.java
Adding MSAA to Native Android Window System OpenGLES 2.0 Devices
Tested on a suite of 12 varying android devices from 5 to 11 with no performance impact. 
Super Low Tier Devices do not have the ability to render MSAA so falls back to configs without feature
Works by finding and choosing Android Config from the Android Graphics Chooser and defaulting to MSAA4 then MSAA 2 then No MSAA.
Also patches and fixes Config Chooser where would fail now has a few fallback passes
=> Feature: Android MSAA 

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidWindow.java
(cherry picked from commit 792c7b5992db3b8b2d02bd9b756fa4c7f79ba2c0)
Fixing to Logs rather than throwing Exceptions. Triggered on x86 Simulator
=> Fix: Android MSAA Logs / Exception

addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroid.java
Basically current KeyCode parsing in OFAndroid layer parses keys into Unicode or kills them into 0: 
Problem: Controller Keycode: 22 becomes 0 passed back to **keyPressed** - Key should be 22 here:
Source of Problem:
Fix: Exclusion for Range >0 to < 256
PS5 ranges from 20-> 106
Android Supports Game Controllers for Accessibility and Games and these fall into the < 256 int range so using an exclusion for this range in the OFAndroid Layer that was zeroing out the KeyPressed / KeyReleased events for Hardware Controllers
=> Android Fix PS4/PS5 Controller KeyCodes to oF KeyPressed/KeyReleased

libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk
This PR extends existing support for .m and .mm source files (Objective C and Objective C++) to addons built using Make.
Support already exists for these files in user projects built using Make, and the same files in user projects and addons built using Xcode.
=> add support for Objective C and Objective C++ source in addon Make builds

libs/openFrameworks/sound/ofFmodSoundPlayer.cpp, libs/openFrameworks/sound/ofFmodSoundPlayer.h
Added the fixes mentioned in #6714 #6708
Also bumped the default channels to 512 from 32 now that there is no penalty in newer fmod for reserving more.
=> bugfix fmod sound player for macos. closes #6714 #6708

libs/openFrameworks/app/ofAppGLFWWindow.cpp
If you did:
```
ofGLFWWindowSettings settings;
settings.monitor = 1;
settings.windowMode = OF_FULLSCREEN;
```
With just one monitor the app would crash as settings.monitor was being used without being clamped
=> bugfix ofAppGLFWWindow requested monitor wasn't being clamped

libs/openFrameworks/utils/ofConstants.h, libs/openFrameworks/utils/ofFileUtils.cpp
added process switching with macro about std::filesystem::permissions.
cite:
* TS/experimental API
* https://en.cppreference.com/w/cpp/experimental/fs/permissions
* https://en.cppreference.com/w/cpp/experimental/fs/perms
* c++17 API
* https://en.cppreference.com/w/cpp/filesystem/permissions
* https://en.cppreference.com/w/cpp/filesystem/perms
* https://en.cppreference.com/w/cpp/filesystem/perm_options
=> fix c++17 std::filesystem error.

libs/openFrameworks/utils/ofUtils.cpp, libs/openFrameworks/utils/ofUtils.h
when call `ofVAArgsToString("%d", 0);`, second argument `0` will be interpreted to null pointer of `va_list`.
and function overload will be resolved to `auto ofVAArgsToString(const char * format, va_list args)` and crush.
this PR will fix this problem.
=> Fixed bug: crash when call ofVAArgsToString("%d", 0);

examples/gl/computeShaderParticlesExample/src/ofApp.cpp
I was looking at an example and noticed there was an unused int i/i++, so I got rid of it.
And my vim hooks got rid of some trailing white space, so we get that for free.
=> remove unused i

libs/openFrameworks/video/ofGstUtils.cpp
GStreamer on Windows now uses either `GSTREAMER_1_0_ROOT_MINGW_X86` or `GSTREAMER_1_0_ROOT_MSVC_X86` as an environment variable. This change looks for the new path if the legacy one returns nothing.
=> Fix GST paths on Windows for newer versions of the library.

libs/openFrameworks/utils/ofUtils.cpp, libs/openFrameworks/utils/ofUtils.h
#6738 ofGetUnixTime() returns uint64_t instead of int
=> ofGetUnixTime() returns 64bit uint now #6738

libs/openFrameworks/communication/ofSerial.cpp
I believe this only affects Linux (and by extension Rasberry Pi). I'm not 100% sure how it affects Windows or Mac so this patch is Linux only.
After having trouble receiving data from an Arduino, I investigated.
Basically I was sending 30 bytes from OF to an Arduino, and then sending the same data back to check if everything was being received correctly. The Arduino seemed to be receiving the right number of bytes, but OF was dropping bytes occasionally while receiving.
I tried playing around with baud rates to no avail.
I then came across this forum post:
https://forum.openframeworks.cc/t/simple-arduino-serial-openframework-missing-bytes/30260/4
I manged to get the correct results using Processing, and after running the Processing equivalent, it somehow set the correct serial flags and …
=> Turn off software flow control in serial device [Linux]

libs/openFrameworks/app/ofAppGLFWWindow.h
Exposing setWindowIcon to public allows for Linux builds to have a custom icon
=> Allow custom icon for Linux. Fixes #6702

libs/openFrameworks/video/ofDirectShowPlayer.cpp
Newer installs of K-Lite Codec tools are defaulting to a newer Directshow rendering pipeline, breaking video playback on Windows. This approach tries both the existing and newer approaches and only fails if it can't find either.
Fixes #6765
Thanks to @nama-gatsuo for reporting and @hanasaan for the fix suggestion!
=> bugfix. fixes DirectShow renderer for newer codecs. closes #6765

libs/openFrameworks/utils/ofURLFileLoader.cpp
fixes #6776
`ofLoadURLAsync` and `ofLoadURL` are called from different threads, however from https://curl.se/libcurl/c/threadsafe.html you can read that: "You must never share the same handle in multiple threads".
So here we fix this by creating a new handle for each request. I think the overhead is acceptable; it could be noticeable when downloading many small files though.
There might be a better way using:
``` C++ 
thread_local std::unique_ptr<CURL, void(*)(CURL*)> curl 
```
but I couldn't figure how to to it properly, sorry...
=> ofURLFileLoader: don't reuse CURL* handle

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
XCode Release and Release Rosetta both generates Universal identical apps right now.
This pull request keeps Release behavior similar to Debug, compiling Apple Silicon or Intel code depending on the scheme selection.
I think the absence of this key turned the default to NO, so it was building other architectures together causing some issues on addons based in a specific architecture.
More details of this issue here:
https://github.com/openframeworks/openFrameworks/issues/6784#issuecomment-975544869
=> Fix XCode release schemes

libs/openFrameworks/graphics/ofCairoRenderer.cpp
differently from other renderers it misses
```c++
path.setUseShapeColor(false);
```
from initialization. this update closes this issue
https://github.com/openframeworks/openFrameworks/issues/6766
and I think it matches style of other renderers (setupGraphicDefaults in the end of setup)
=> fix to beginshape endshape not using actual color

libs/openFrameworks/video/ofAVFoundationPlayer.mm
comment out CVPixelBufferUnlockBaseAddress in every frame. not needed for normal video
Some minor changes to avoid allocating videoTexture every frame.
=> ofAVFoundationPlayer.mm Minor tweaks, avoid texture allocation every frame

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m
I've noticed in XCode the video player create lots of threads and release few. 
This change allows the program to release threads over time.
=> ofAVFoundationVideoPlayer - Add autorelease to dispatch_async

libs/openFrameworks/video/ofAVFoundationVideoPlayer.m
this particular call of createAssetReaderWithTimeRange is exclusive if we seek a position of the video before the actual playhead.
but it creates a strange situation where videoSampleTime is not correctly updated and we got stuck outside the "while" loop that checks the video buffer for new content.
no video is displayed until the playhead goes to the previous position again.
This fix supress this function here, but  it is going to be called anyway in updateFromAssetReader, but this time videoSampleTime is correctly updated and video is displayed correctly with good performance.
=> AVFoundationVideoPlayer fix - set video position to a previous position than the playhead

libs/openFrameworksCompiled/project/makefileCommon/config.project.mk
changes to fix https://github.com/openframeworks/openFrameworks/issues/6534
I've studied the concatenation of make file includes to understand how CXX and CC variables were not being set per project when using PROJECT_CC and PROJECT_CXX
with this two changes it arrives at the end with the right variables set.
To understand better how variables were set I've added this in the end of my test project Makefile
```make
$(info -----------------)
$(info PROJECT_CC final is $(PROJECT_CC))
$(info PROJECT_CXX final is $(PROJECT_CXX))
$(info CC final is $(CC))
$(info CXX final is $(CXX))
$(info -----------------)
```
as the changes are isolated inside the ifdef PROJECT_CC / ifdef PROJECT_CXX it should not affect anything else
=> PROJECT_CC and PROJECT_CXX fix

libs/openFrameworks/video/ofVideoBaseTypes.h
ofBaseHasPixels is already present, inherited by ofBaseVideo
doesn't make any difference and increases readability, helps visualizing the memory layout of the object
=> ofBaseHasPixels is already present

libs/openFrameworks/utils/ofFileUtils.cpp
on std::filesystem (not std::experimental::filesystem), `addTrailingSlash` is broken.
because, `std::filesystem::path("/hoge") / std::filesystem::path("/")` returns `std::filesystem::path("/")`.
so, this bug causes the wrong behavior of `ofToDataPath`.
ref: https://wandbox.org/permlink/QzINUEPwoDVOjYWr
this PR fixes it.
=> fixed addTrailingSlash on std filesystem

libs/openFrameworks/utils/ofSystemUtils.cpp
this way we can answer without using the mouse to focus the textfield.
it closes https://github.com/openframeworks/openFrameworks/issues/6814
=> ofSystemTextBoxDialog - Focus on textfield

libs/openFrameworks/graphics/ofTrueTypeFont.cpp, libs/openFrameworks/graphics/ofTrueTypeFont.h
added ranges for CJK Symbols and Punctuation.
ref: https://en.wikipedia.org/wiki/CJK_Symbols_and_Punctuation
for example "、" means like "," and "。" means like "." .
In Japanese, basically those are needed.
and I don't know Chinese and Korean enough, but maybe those are needed too.
=> added range for CJKSymbolAndPunctuation and added to CJK ranges

libs/openFrameworks/types/ofColor.cpp, libs/openFrameworks/utils/ofThreadChannel.h
Sorry this also picked up the other commit on ofThreadChannel which is in a seperate PR
=> ofColor::getLightness() - fix overflow error

libs/openFrameworks/communication/ofSerial.cpp
This fix a bug occurring if the device's friendly name contains "COM" string.
For instance, if the device's friendly name is "Virtual COM Port (COM15)", then
enumeration will return the following device path : "COM Port (COM15" instead
of "COM15"
=> Fix issue in ofSerial during Win32 enumeration

libs/openFrameworks/graphics/ofImage.cpp, libs/openFrameworks/graphics/ofImage.h, libs/openFrameworks/types/ofColor.cpp, libs/openFrameworks/utils/ofThreadChannel.h
allow the user to send their own flags to freeimage when loading an image through ofLoadImage
=> Freeimage flags

libs/openFrameworks/utils/ofSystemUtils.cpp
A really small PR.
There is conflict with windows header and the definition of byte symbol.
=> fix: ambiguous byte conflict with windows header

libs/openFrameworks/gl/ofGLRenderer.cpp
I'll make another PR to remove it from another file too.
just wondering, there is an include guard in ofMesh.h
https://github.com/openframeworks/openFrameworks/blob/7d7993550c2f9b00a985769dfaab3825abb975e5/libs/openFrameworks/3d/ofMesh.h#L1-L5
maybe it is there because of this duplication here?
=> ofGLRenderer.cpp - Removing duplicate include ofMesh.h

libs/openFrameworks/gl/ofTexture.cpp
=> fix spell from 'extention' to 'extension'

libs/openFrameworks/3d/ofMesh.h, libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp, libs/openFrameworks/gl/ofGLRenderer.cpp, libs/openFrameworks/graphics/ofPolyline.h
now, size arguments fixed to sizeof(ofVec3f) and sizeof(ofVec2f).
this PR replaces to sizeof(correct type).
=> add type alias of template arguments to ofMesh and ofPolyline for get size of type strictly

addons/ofxOsc/addon_config.mk
so the compiler doesn't search here
```
-I/Volumes/tool/ofw/addons/ofxOsc/libs/oscpack/src/ip/win32
```
=> ofxOsc - Excluding a include folder for macOs

libs/openFrameworks/graphics/ofTrueTypeFont.cpp, libs/openFrameworks/graphics/ofTrueTypeFont.h
Index property allows to use single file fonts with several styles. The index defines the "style" to be loaded. This shouldn't break anything . It is just exposing this feature
=> ofxTruetypeFont: Added index property to ofxTryutypeSettings 

libs/openFrameworks/graphics/ofCairoRenderer.h
```
/Volumes/tool/ofw/libs/openFrameworks/graphics/ofCairoRenderer.cpp:22:2: warning: field 'graphics3d' will be initialized after field 'projection' [-Wreorder-ctor]
```
=> ofCairoRenderer reordering fields to supress warning

INSTALL_FROM_GITHUB.md
pro: much quicker install
con: have to unshallow to access other branches if needed.
=> Suggestion: shallow clone

libs/openFrameworks/utils/ofURLFileLoader.cpp
Some https requests fail on mac (and perhaps other platforms) when the verify option is set to 0. Changing it to 2 seems to resolve issue.
=> changing CURLOPT_SSL_VERIFYHOST argument

libs/openFrameworks/utils/ofUtils.cpp
this PR fixes this warning and note 
```c++
/home/pi/ofw2/libs/openFrameworks/utils/ofUtils.cpp:523:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
if (makeAbsolute && path.is_absolute())
^~
/home/pi/ofw2/libs/openFrameworks/utils/ofUtils.cpp:526:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
if (!enableDataPath)
^~
```
=> ofUtils.cpp warning  [-Wmisleading-indentation]

libs/openFrameworks/app/ofAppRunner.cpp, libs/openFrameworks/utils/ofFileUtils.cpp, libs/openFrameworks/utils/ofFileUtils.h, libs/openFrameworks/utils/ofUtils.cpp, libs/openFrameworks/utils/ofUtils.h
This PR make solve little complexity about ofUtils and ofFileUtils references each other.
those functions and private variable are moved from ofUtils to ofFileUtils.
(and remove declaration of `setWorkingDirectoryToDefault` has no implementation...)
```cpp
namespace {
bool enableDataPath = true;
string defaultDataPath();
std::filesystem::path & defaultWorkingDirectory();
std::filesystem::path & dataPathRoot();
}
void ofEnableDataPath();
void ofDisableDataPath();
std::string ofToDataPath(const std::filesystem::path & path, bool absolute=false);
bool ofRestoreWorkingDirectoryToDefault();
void ofSetDataPathRoot(const std::filesystem::path& root);
```
and those line is moved from `of::priv::initutils()` to new private function `of::priv::initfileutils()`.
```cpp
defaultWorkingDirectory() = …
```
=> Move functions about data path from ofUtils to ofFileUtils.

addons/ofxNetwork/src/ofxUDPManager.cpp
variable is unused, I can see "int total" variable replaced this logic, this cleanup removes the following warning
```
ofw/addons/ofxNetwork/src/ofxUDPManager.cpp:312:6: warning: variable 'bytesleft' set but not used [-Wunused-but-set-variable]
```
=> ofxUDPManager : unused variable bytesleft removal

libs/openFrameworks/math/ofMath.h
There is currently an edge case where ofLineSegmentIntersection incorrectly returns false if the line's end points sit directly on the edges of the rectangle. This commit should fix that.
Example code to prove this : 
```
ofRectangle rect(0,0,800,800);
glm::vec2 p1(400,0);
glm::vec2 p2(400,800);
glm::vec2 p3(0,400);
glm::vec2 p4(800,400);
ofLogNotice((rect.intersects(p1, p2)) ? "TRUE" : "FALSE");
ofLogNotice((rect.intersects(p3, p4)) ? "TRUE" : "FALSE");
```
Both tests should return true, previously they returned false. 
Hope this helps!
=> Fix ofLineSegmentIntersection test between line and rectangle.

libs/openFrameworks/app/ofAppGLFWWindow.cpp
=> update deprecated cocoaWindow setStyleMask options

libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp, libs/openFrameworks/sound/ofOpenALSoundPlayer.h
Seems to be due an update in libsndfile. 
Fix for CI and core.
Still an OpenCV error for msys2 will address in another PR.
=> Bugfix OpenAL libsndfile error on linux and msys2 

libs/openFrameworks/app/ofAppGLFWWindow.cpp
Set the window properties after resizing, to fix openframeworks/openFrameworks#6719
- coming out of fullscreen, we call cocoa's setStyleMask, which triggers the glfw framebuffer_resize callback
- then we call setWindowShape()
- since the glfw resize was already triggered, the glfw internals do not get called, do not see the glfw callbacks trigger
- i assume because the window size set by the cocoa call equals the window size we want to set, glfw does not do the 2nd resize
- theres some y axis offset adjustment that is maybe getting skipped 
- https://github.com/glfw/glfw/blob/master/src/cocoa_window.m#L1038
- haven't really looked into the guts of glfw
- workaround is to call setWindowShape() first then setStyleMask
- seems to fix the issue macos 12.3/m1 and 11.6/intel
=> Update ofAppGLFWWindow.cpp for openframeworks/openFrameworks#6719

scripts/templates/osx/openFrameworks-Info.plist
this change assures the value here will be the same as the XCode project
so, one less warning here
=> info.plist - change CFBundleIdentifier to the same as XCode proj.

libs/openFrameworks/types/ofParameter.cpp
supress warnings
ofParameter.cpp:115:44: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
ofParameter.cpp:139:44: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
=> ofParameter - remove unused lambda capture this

scripts/templates/osx/Project.xcconfig, scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj, scripts/templates/osx/openFrameworks-Info.plist
this PR simplificates the app icon. all the logic is removed from pbxproj except the rsync script
and everything is now concentrated inside the readable .xcconfig
the debug icon uses the xcconfig conditional [config=Debug]
=> Icon simplification

libs/openFrameworksCompiled/project/osx/config.osx.default.mk
Change template to make missing a return a hard error instead of allowing functions not return anything.
=> Make - missing a return a hard error now

scripts/templates/osx/Project.xcconfig
I've removed Boost entries from CoreOF and added them commented out in Project.xcconfig
=> XCode Boost commented out by default with c++17

libs/openFrameworks/communication/ofArduino.cpp
ofArduino.cpp:990:7: warning: variable 'shift' set but not used [-Wunused-but-set-variable]
=> ofArduino Cleanup unused code - remove warning

libs/openFrameworks/communication/ofArduino.h
supress this warning
```
/Volumes/tool/ofw/libs/openFrameworks/communication/ofArduino.h:792:6: warning: private field '_numEncoders' is not used [-Wunused-private-field]
```
I've just commented it out, in the case somebody wants to actually implement
=> ofArduino.h remove unused numEncoders

libs/openFrameworks/utils/ofFileUtils.cpp, libs/openFrameworks/utils/ofFileUtils.h
* remove `std::iterator` with writing type alias directly
* implement `Lines::rbegin` and `Lines::rend` are not implemented (!!)
* add some `const` qualitifiers (and `cbegin`, `cend`, etc...)
* fix logic on RLine:
* first line (i.e., last line in buffer) was wrong.
* fix edge case on Line/RLine: 
* empty line was ignored when line break appears at last/first of text (e.g. `"\na\nb\n"`)
* is this not correct?
related: #6926
=> Refactoring ofBuffer::Lines/RLines

libs/openFrameworks/video/ofAVFoundationPlayer.mm, libs/openFrameworks/video/ofAVFoundationVideoPlayer.h, libs/openFrameworks/video/ofAVFoundationVideoPlayer.m
now macOS follows windows model as discussed here
https://github.com/openframeworks/openFrameworks/issues/6527
basically the only change is:
after you call video.stop() 
video.isPaused() returns false instead of true
=> ofVideoPlayer isPaused fix for macOS

libs/openFrameworks/app/ofAppGLFWWindow.h
RPI only variable, so it goes inside #ifdef macro
```
/Volumes/tool/ofw/libs/openFrameworks/app/ofAppGLFWWindow.h:222:9: warning: private field 'needsResizeCheck' is not used [-Wunused-private-field]
```
=> supress warning unused needsResizeCheck - RPI only

libs/openFrameworks/utils/ofMatrixStack.h
warning: field 'flipRenderSurfaceMatrix' will be initialized after field 'modelMatrix' [-Wreorder-ctor]
=> ofMatrixStack.h - fix [-Wreorder-ctor] warning

libs/openFrameworks/video/ofGstUtils.cpp
Changes in isPlaying() and isPaused() for uniformity in different platforms, as discussed here
- https://github.com/openframeworks/openFrameworks/issues/6527
Hey @ofTheo here is the PR for GStreamer Linux
I don't have my linux box working to test it so it would be great if somebody else could review and test the changes.
=> videoPlayer GST isPaused isPlaying fix

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
using xcodebuild each of the three scripts used to output all env variables to the terminal
this PR disables this, and marks each build phase in terminal
=> xcodebuild - less verbose

libs/openFrameworks/app/ofAppGLFWWindow.cpp, libs/openFrameworks/app/ofAppGlutWindow.cpp, libs/openFrameworks/app/ofMainLoop.cpp, libs/openFrameworks/gl/ofBufferObject.cpp, libs/openFrameworks/gl/ofMaterial.cpp, libs/openFrameworks/graphics/ofCairoRenderer.cpp, libs/openFrameworks/graphics/ofImage.cpp, libs/openFrameworks/math/ofMatrix4x4.cpp, libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp, libs/openFrameworks/types/ofColor.cpp, libs/openFrameworks/utils/ofLog.cpp, libs/openFrameworks/utils/ofMatrixStack.cpp, libs/openFrameworks/utils/ofSystemUtils.cpp, libs/openFrameworks/utils/ofURLFileLoader.cpp, libs/openFrameworks/video/ofVideoGrabber.cpp
in this PR I've removed some more unneeded.h files and removed #include "ofConstants.h" from cpp files where it was already included in .h files.
the only exceptions left are ofFbo.cpp and ofLight.cpp (file isn't included in .h) 
it passes all tests.
what is your opinion @ofTheo ?
=> removing unneeded .h

libs/openFrameworks/utils/ofUtils.h
compiler warns at this line the string format should be literal
```c++
size_t n = std::snprintf(buf, sizeof(buf), format, std::forward<Args>(args)...);
```
but it is not fixable because we are taking format variable from some parameter anyway.
https://stackoverflow.com/a/32362969/9216273
So my suggestion is just adding a pragma to silence this specific warning on this file
=> ofUtils - pragma to  ignore warning

libs/openFrameworks/video/ofGstUtils.cpp, libs/openFrameworks/video/ofGstVideoPlayer.cpp
Fixes broken video playback with GStreamer 1.20 - partially closes #6871 
Huge thanks to Nicholas Lavella ( [from the forums](https://forum.openframeworks.cc/t/ofxgstreamer-on-m1-mac/40257/14?u=theo) ) for helping narrow it down to the callback. 
Needs testing on Linux and older Gstreamer versions ( though the changes should be backwards compatible ).
=> WIP: Fixes for gstreamer 1.20 broken video playback. closes #6871

libs/openFrameworks/utils/ofMatrixStack.cpp
This is a simple PR to fix the missing space after the `tmpCounter` variable in the ofMatrixStack error message.
Before:
~~~
[warning] ofMatrixStack: clearStacks(): found 1extra view matrices on the stack, did you forget to popView() somewhere?
~~~
After:
~~~
[warning] ofMatrixStack: clearStacks(): found 1 extra view matrices on the stack, did you forget to popView() somewhere?
~~~
=> fix ofMatrixStack error message spacing

libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp
Check if OpenAL successfully loaded the file before proceeding. I forgot to install codecs and without this check it caused an app crash.
=> ofOpenALSoundPlayer load check

libs/openFrameworks/utils/ofConstants.h
this PR is meant to allow using non ARC projects so OF is compatible with addons like ofxSyphon and others.
Related: https://github.com/openframeworks/openFrameworks/pull/6889#issuecomment-1195667266
=> No ARC enforcing

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
in this template I've renamed the build phases so we know what each Run Script does.
I've also unchecked "Based on dependency analysis"
So we don't have this warning on XCode 14
```
warning build: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
```
I've edited the project using xcode itself, then converting the results back to json and ident using jq (https://stedolan.github.io/jq)
```bash
cd $ofw/scripts/templates/osx/emptyExample.xcodeproj
plutil -convert json $ofw/scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj 
jq --tab . …
```
=> macOs template update

libs/openFrameworks/app/ofAppNoWindow.cpp
XCode complains here because code is unreachable. of course, it begins with return 0;
should we comment out? remove?
https://github.com/openframeworks/openFrameworks/blob/4ccc0b20a6b138dc94bc719bc308e29d518a8e67/libs/openFrameworks/app/ofAppNoWindow.cpp#L44-L51
=> unreachable code

libs/openFrameworks/gl/ofMaterial.cpp, libs/openFrameworks/gl/ofMaterial.h
Added ability to set a custom shader for ofMaterial. If a custom shader is set on the material, then the getShader() function will return the customShader.
=> Extend of material

libs/openFrameworks/graphics/ofTrueTypeFont.cpp, libs/openFrameworks/graphics/ofTrueTypeFont.h
I'm submitting this PR to start a discussion.
stringWidth actually get width of getStringBoundingBox, which uses a mixture of glyphProperties advance and xmin+width, that are not the same thing.
this PR fixes getStringBoundingBox, makes stringWidth independent of the function, so it is less overhead.
address the issue discussed here
https://forum.openframeworks.cc/t/are-monospace-fonts-really-monospace/40358/3
=> fix ofTrueTypeFont::stringWidth

addons/ofxOpenCv/src/ofxCvColorImage.cpp, addons/ofxOpenCv/src/ofxCvFloatImage.cpp, addons/ofxOpenCv/src/ofxCvGrayscaleImage.cpp, addons/ofxOpenCv/src/ofxCvImage.cpp, addons/ofxOpenCv/src/ofxCvImage.h, addons/ofxOpenCv/src/ofxCvShortImage.cpp
Adds `cv::Mat ofxCvImage::getCvMat();` for easier usage with modern opencv. 
The main addon needs a lot more work, or a newer addon for modern opencv usage, but this function is a nice stop gap for easily using OpenCV's C++ api in the workflow.  
Also fixes incorrect ofLog notices with the wrong allocation size.
=> Feature opencv cvmat

examples/video/videoGrabberExample/src/main.cpp, examples/video/videoGrabberExample/src/ofApp.cpp
to use 640x480 because macOs nowadays doesn't allow 320x240 anymore.
=> Update camera example

libs/openFrameworks/gl/ofMaterial.cpp, libs/openFrameworks/gl/ofMaterial.h, libs/openFrameworks/gl/shaders/phong.frag
Been working on making the assimp model loader much more robust and useful. 
( will do a separate PR for that ) 
This PR adds texture support for loading: 
- emissive 
- occlusion 
- normal map / bump map 
- specular 
- ambient 
To the ofMaterial phong.frag shader. 
In the future we could add a pbr.frag shader for Physical Based Rendering but for now this adds quite a bit. 
You can see the emissive and normal map support this adds to this model: 
And some of the details you get from the normal map in this model:
=> ofMaterial set additional textures to support better model loading

scripts/dev/create_package.sh
As discussed in #7076. 
I think this is all that is needed in order to not be removed from macos download
=> Add transform feedback example to macos (osx) download

libs/openFrameworks/gl/ofShader.cpp
Adding support for both 
```glsl
#include "dependency.glsl"
```
```glsl
#pragma include "dependency.glsl"
```
to `ofShaders`
=> support for include and pragma include shader macros

scripts/linux/testAllExamples.sh
testAllExamples.sh stumbled over README.md (and eventual qtCreator build-* directories), and then failed.
fix #6742
=> Fix linux testallexamples

addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.cpp, addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.h, addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp
Visual Studio had some exceptions which as usual pointed to legitimate issues. 
1) was tex wrapping arg was meant to be an array pointer and not a single variable 
2) was to do with the mesh helper reallocation 
Going to test this on window before merging
=> fixes to windows exceptions in assimp model loader

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.h
remove the default value from the deprecated function. Reasoning is, that the deprecated function should not be the default one, and at the same time old code using the deprecated function should still work.
Fix #7165
=> ofxAssimpModelLoader - fix ambiguous load

scripts/vs/download_libs.ps1
Fix for #7169 
The download_libs.ps1 script was only copying the VS lib files of downloaded addon libs, which left out anything else, such as include directories. This fixes the script so that the complete library is copied.
It also updates the download URL to point to Github Releases.
=> Fix for Header files missing in Windows for some first-party addons (#7169)

addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js, libs/openFrameworksCompiled/project/emscripten/config.emscripten.default.mk
This fixes ofVideoPlayer with Emscripten (and also the 3DPrimitivesExample patch, because it uses the videoGrabber).
Maybe allocate can be replaced with mallloc at some point?
https://github.com/emscripten-core/emscripten/issues/11547
The `assimpExample` patch works too, just not with the first model (which is the preset yet), because there are some shader issues which crashes the patch.
This `loadModel("Astroboy/astroBoy_walk.dae");` and the old man works without issues, the other two have issues, but still load. Did not change anything regarding the assimpExamples in this pull request, just wanted to mention it.
=> Emscripten video player fix

examples/3d/pointCloudExample/src/ofApp.cpp, examples/3d/pointPickerExample/src/ofApp.cpp
Not ideal because the points are very small now, but it seems that `GL_POINT_SMOOTH` and `glPointSize()` do not exits in WebGL. https://stackoverflow.com/questions/66781512/why-doesnt-pointsize-default-to-a-standard-value-in-webgl
Same with the pointPickerExample.
=> Emscripten_pointCloudExample fix

examples/3d/meshFromCameraExample/src/ofApp.cpp
Reverts openframeworks/openFrameworks#7185
@Jonathhhan 
Think actually we can't solve it this way as other platform grabbers will sometimes not return the requested size but the closest matching.  
I think we should probably figure out a way for emscripten to return the requested size immediately instead.
=> Revert "Emscripten meshFromCameraExample fix"

examples/gl/fboHighResOutputExample/src/ofApp.cpp
Because openGL ES does not support multisampling.
`[warning] ofFbo: allocate(): multisampling not supported in OpenGL ES`
=> Emscripten fboHighResOutputExample fix

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp
the absolute path was breaking the file loading when the file didn't exist. 
this fixes it
=> fix for emscripten not loading the first model

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp, libs/openFrameworks/gl/shaders/phong.frag
models with normal maps weren't loading because `dFdx` and `dFdy` aren't defined by default in OpenGL ES. 
with this change you get much nicer rendering of the 2nd model.
=> fix models with normal maps not working in opengles

libs/openFrameworks/utils/ofConstants.h
This commit enables some GL methods for Emscripten. `glEnable(GL_POINT_SMOOTH)` for example works now (could not test if it does something, but at least the error is gone), but `glPointSize()` still not. And also the glInfoExample works now (even if not all of the given information is correct).
Just, there are some redefinition warnings now, like:
```
/home/jonathan/Desktop/openFrameworks-emscripten_ofxgui-fix/libs/openFrameworks/gl/ofGLUtils.h:147:17: warning: 'GL_DEPTH_COMPONENT32' macro redefined [-Wmacro-redefined]
#define GL_DEPTH_COMPONENT32                                            GL_DEPTH_COMPONENT32_OES
^
/home/jonathan/emsdk_3.1.26/upstream/emscripten/cache/sysroot/include/GL/glext.h:326:9: note: previous definition is here
#define GL_DEPTH_COMPONENT32              0x81A7
``` …
=> GLES includes for Emscripten

addons/ofxVectorGraphics/src/ofxVectorGraphics.cpp
Makes the vectorGraphicsExample work with Emscripten...
And I actually wonder, why some of the GL methods are not recognized by Emscripten, while their OF counterpart is (like `glBegin(GL_LINE_STRIP)` and `ofMesh.SetMode(OF_PRIMITIVE_LINE_STRIP)`. It would be much better to make them work in Emscripten too, instead of changing examples and other addons because of that.
=> Emscripten ofxVectorGraphics fix

examples/gl/multiTexture3dExample/bin/data/shadersGLES/shader.frag, examples/gl/multiTexture3dExample/bin/data/shadersGLES/shader.vert, examples/gl/multiTexture3dExample/src/ofApp.cpp, examples/gl/multiTexture3dExample/src/ofApp.h, libs/openFrameworks/utils/ofConstants.h
I added mainly the header of the shader (and some explicit float declarations).
Works not with all browsers / GPUs.
And I guess the rotation of the sphere is not totally correct, but better than before (the Y-axis was flipped).
=> Emscripten multiTexture3dExample fix

addons/ofxEmscripten/libs/html5audio/include/html5audio.h, addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js, addons/ofxEmscripten/libs/html5video/include/html5video.h, addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js, addons/ofxEmscripten/src/ofxEmscriptenSoundStream.cpp, addons/ofxEmscripten/src/ofxEmscriptenVideoGrabber.cpp
This lists the audio / video devices with ofxEmscriptenVideoGrabber::listDevices() or ofxEmscriptenSoundStream::getDeviceList().
Right now it only prints in Java Script(in the browser console), because I do not know how to return it to OF(a single string would be easy, but I guess it is kind of a list).
=> Emscripten list devices

libs/openFrameworks/gl/ofCubeMap.cpp, libs/openFrameworks/gl/ofCubeMap.h
just tiny changes:
moving include "ofShader.h" to cpp
forward declarate ofShader
remove unneeded include "ofNode.h"
Let's see if it works OK in all platforms
=> forward declaration ofShader

addons/ofxSvg/addon_config.mk
so ios doesn't try to use osx libs
=> ofxSvg addon_config, fix ios section

addons/ofxEmscripten/libs/html5audio/include/html5audio.h, addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js, addons/ofxEmscripten/libs/html5video/include/html5video.h, addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js, addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.cpp, addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.h, addons/ofxEmscripten/src/ofxEmscriptenSoundStream.cpp, addons/ofxEmscripten/src/ofxEmscriptenSoundStream.h, addons/ofxEmscripten/src/ofxEmscriptenVideoGrabber.cpp, addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.cpp, addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.h
This is basically what I changed end of last year.
I compared it with my recent changes and it seems more complete (but I changed a lot).
I can also split it up into smaller parts.
=> Emscripten audio video revision

libs/openFrameworks/sound/ofAVEngineSoundPlayer.h, libs/openFrameworks/sound/ofAVEngineSoundPlayer.m, libs/openFrameworks/sound/ofAVEngineSoundPlayer.mm
Addressing #167 
Features:
ToDo:
Questions:
- Multiplay works by creating new internal players for each play request.  ofAVEngineSoundPlayer uses an ofEvents().update listener to cleanup the extra multiplay players. This seems more reliable than using a thread ( had some unexpected crashes when using a thread ), but curious if people see any downside to an update event on the main thread, vs spawning a new thread for each player.
=> macOS / iOS sound player. AVAudioEngine - WIP

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
this removes some leftover entries, so Header search paths and other fields doesn't show it anymore.
=> osx template cleanup AppStore leftover entries

libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
Fix #7249 
Cannot create icon.rc when destination folder is not present
Force creation of destination folder
=> fix(msys2): icon compilation

libs/openFrameworks/utils/ofUtils.h
https://forum.openframeworks.cc/t/ofgetsystemtimemillis-not-working-on-macos/40875
=> docs: clarification of the meaning of System Time

examples/sound/audioInputExample/src/ofApp.cpp
inputchannels = 1 instead of 2
Apple computers stopped accepting input with two channels, so this change is needed
=> audioInputExample update 

addons/ofxiOS/src/sound/ofxiOSSoundPlayer.mm, addons/ofxiOS/src/sound/ofxiOSSoundStream.mm
fix about memory management for `void *` with `__bridge_retained`, `__bridge_transfer`
related: #7280
=> Fix ARC problem of ofSoundStream 

examples/ios/audioInputExample/src/ofApp.h, examples/ios/audioInputExample/src/ofApp.mm
There are some changes in this example. maybe more than necessary but just to open some discussion:
the modernization of ofSoundStream object and audioIn function
change of buffer memory from heap to the stack, fixed array, zero initialized instead of memset.
it seems the example was meant to have buffer changing on the fly but it doesn't, so I removed the bufferSize check in audioIn
removed the comments regarding ios simulator because it is not working actually on OF, so we don't even know if the limitations present in the comments are still valid.
=> iOS examples - audioInputExample update

addons/ofxAssimpModelLoader/src/ofxAssimpAnimation.cpp, addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.cpp, addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.h, addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp, addons/ofxAssimpModelLoader/src/ofxAssimpTexture.cpp, addons/ofxAssimpModelLoader/src/ofxAssimpTexture.h, addons/ofxAssimpModelLoader/src/ofxAssimpUtils.h
in this PR I removed using namespace std, removed unused headers from .h files
and moved some headers to cpp files, so it is a little bit cleaner for .h includes
changed from ofMatrix4x4.h to the simpler glm/mat4x4.hpp include too
and finally removed ofMain.h which includes the whole OF project + namespace std
=> ofxAssimpModelLoader rm using namespace std and other changes

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp
This PR enables mouse / touch events outside of the canvas. Maybe needs to be tested a little more, because it does not behave exactly like the desktop app. But it solves a problem that was bugging me for some time.
Maybe it would be the best solution to limit the mousePressed and mouseMoved events to the canvas?
I already tried it with an if condition:
```
int ofxAppEmscriptenWindow::mousedown_cb(int eventType, const EmscriptenMouseEvent *mouseEvent, void *userData){
float x = EM_ASM_INT(return canvas.getBoundingClientRect().left);
float y = EM_ASM_INT(return canvas.getBoundingClientRect().top);
if(mouseEvent->targetX - x >= 0 && mouseEvent->targetX - x <= EM_ASM_INT(return canvas.width) && mouseEvent->targetY - y >= 0 && mouseEvent->targetY - y <= EM_ASM_INT(return canvas.height)){ …
```
=> Emscripten mouse / touch event improvement

libs/openFrameworks/sound/ofSoundStream.cpp
=> make ofSoundStream systemSoundStream able to lazy initialize

addons/ofxAssimpModelLoader/src/ofxAssimpTexture.cpp, addons/ofxGui/src/ofxSliderGroup.cpp, addons/ofxThreadedImageLoader/src/ofxThreadedImageLoader.cpp, addons/ofxThreadedImageLoader/src/ofxThreadedImageLoader.h, addons/ofxXmlSettings/src/ofxXmlSettings.cpp
Changes in some more files 
This is meant to remove unrelated changes in this big PR - https://github.com/openframeworks/openFrameworks/pull/7110
=> General changes (namespace, deprecated loadFile function)

examples/gl/shadowsExample/src/ofApp.cpp
One exclamation point! Otherwise it displays incorrect information about shadow support.
=> Correct check for shadows support

libs/openFrameworks/gl/ofShadow.cpp
to resolve this warning
```
extra tokens at end of #ifdef directive [-Wextra-tokens]
```
cc: @NickHardeman
=> ofShadow - resolve mixed ifdef with defined warning

scripts/dev/download_libs.sh, scripts/msys2/compileOF.sh
Implements possibility to build under UCRT64 and CLANG64 environments of MSYS.
I propose to remove MINGW32 from scripts, because nightly builds from Apothecary is unavailable.
=> MSYS: Add support for UCRT64 and CLANG64

libs/openFrameworks/types/ofParameter.h
to supress the reorder compiler warning
=> ofParameter.h - update parameters order

scripts/templates/osx/Project.xcconfig, scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
Problem: moving an app between machines requires that (1) all required dylibs to be bundled within the .app and (2) their paths to be tweaked in order to be found at runtime (including paths in dylibs-depending-on-other-dylibs). It's a hairy process to do manually, and also hairy to automate in a manner that survives a PG project update (as all tweaks to the project are lost).
This leverages https://github.com/auriamg/macdylibbundler (commonly available as `brew install dylibbundler`). The script first scans the Xcode project for all referenced dylibs that would be provided by addons and passes them to dylibbundler, who will copy and work recursively from these dylibs, automating the `install_name_tool` dance (and also signs the dylibs). A Project.xcconfig flag enables the script, which …
=> Add functionality to Xcode template to bundle dylibs

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
This goes with: https://github.com/openframeworks/projectGenerator/pull/321 
Allows the PG to add dylibs to the copy build phase of Xcode ( to be added next to the main executable ). 
So any dylib that uses `@executable_path` should just work. 
Will do a sperate PR for iOS if it is needed?
=> add copy build phase for dylibs etc

libs/openFrameworks/utils/ofFileUtils.h
The missing of const broke previous functionality.
=> ofBufferToFile is missing const in first argument

.github/workflows/build-android.yml
this will fix deprecation warnings
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/cache@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> Actions - cache to v3 in android

.github/workflows/build-macos.yml
Now we are adding addons/obj files to the cache too, so addons don't need to be totally recompiled if not needed in a PR.
=> Actions - update osx, more folders added to cache

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp, libs/openFrameworks/3d/ofCamera.cpp, libs/openFrameworks/3d/ofMesh.inl, libs/openFrameworks/gl/ofCubeMap.cpp, libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp, libs/openFrameworks/gl/ofGLRenderer.cpp, libs/openFrameworks/gl/ofLight.cpp, libs/openFrameworks/graphics/of3dGraphics.cpp, libs/openFrameworks/graphics/ofCairoRenderer.cpp, libs/openFrameworks/graphics/ofGraphics.cpp, libs/openFrameworks/graphics/ofPath.cpp, libs/openFrameworks/graphics/ofPolyline.inl, libs/openFrameworks/math/ofMath.cpp, libs/openFrameworks/math/ofMath.h, libs/openFrameworks/math/ofMathConstants.h, libs/openFrameworks/math/ofMatrix4x4.cpp, libs/openFrameworks/math/ofMatrix4x4.h, libs/openFrameworks/math/ofQuaternion.cpp, libs/openFrameworks/math/ofVec2f.h, libs/openFrameworks/math/ofVec3f.h, libs/openFrameworks/math/ofVectorMath.h, libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp, libs/openFrameworks/sound/ofSoundUtils.h, libs/openFrameworks/types/ofColor.cpp, libs/openFrameworks/types/ofRectangle.cpp, libs/openFrameworksCompiled/project/osx/config.osx.default.mk
More
Substituting MIN / MAX  to std::min std::max
FLT_EPSILON to std equivalent
pi, half_pi, two_pi by glm ones
now we can remove the unused constants later on a breaking release 0.12.0
=> Substitute defines DEG_TO_RAD / RAD_TO_DEG with ofDegToRad / ofRadToDeg

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp, addons/ofxEmscripten/src/ofxAppEmscriptenWindow.h
Related to https://github.com/openframeworks/openFrameworks/issues/7350
- Added window resize events 
- Added soft fullscreen is set to OF_FULLSCREEN in main.cpp
- Touch can emulate mouse
- Set fullscreen scale strategy
- Disable default browser touch move
```
#if defined(TARGET_EMSCRIPTEN)
auto ewin =  dynamic_pointer_cast<ofxAppEmscriptenWindow>(ofGetCurrentWindow());
ewin->setTouchSimulatesMouse(true);
ewin->preventDefaultBrowserTouchMoveBehavior();
ewin->setFullscreenScaleStrategy(EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT);
#endif
```
See windowed example:
https://nickhardeman.com/temp/OFExamples/AssimpExampleWindowed/
Soft fullscreen:
https://nickhardeman.com/temp/OFExamples/AssimpExample/
=> Emscripten Soft Fullscreen

libs/openFrameworksCompiled/project/emscripten/config.emscripten.default.mk, scripts/templates/emscripten/config.make
closes #7421
closes #7412  
@Jonathhhan this code below works for me.  
Basically you just need to uncomment two lines in the project config.make - so that way you can build some projects with pthreads if needed and others without. 
Happy if there is another / better way to enable threading, but given that it errors unless you set the server up correctly feels like we should default to off for now.
=> make pthreads not on by default for emscripten. add notes in config.make

libs/openFrameworksCompiled/project/emscripten/template.html
closes #7423
It's not a perfect solution but it seems much more functional. 
We can improve the OF fullscreen as discussed here:
https://github.com/openframeworks/openFrameworks/pull/7418#issuecomment-1482087752 
but this makes the html button and checkboxes a little more useful / functional
=> soft fullscreen for iOS and option to resize via checkbox in html template

libs/openFrameworks/gl/ofTexture.cpp
unordered_map can have an improvement performane over map, with the same funcionality less the automatic reordering.
=> ofTexture map to unordered_map

addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.h, libs/openFrameworks/3d/ofMesh.inl, libs/openFrameworks/app/ofMainLoop.h, libs/openFrameworks/gl/ofFbo.cpp, libs/openFrameworks/gl/ofMaterial.cpp, libs/openFrameworks/gl/ofMaterial.h, libs/openFrameworks/gl/ofShader.cpp, libs/openFrameworks/gl/ofShader.h, libs/openFrameworks/gl/ofVbo.cpp, libs/openFrameworks/gl/ofVbo.h, libs/openFrameworks/graphics/ofTrueTypeFont.cpp
it has better performance as unordered_map doesn't need to be shuffling things around all the time when new data is inserted. 
I think this change can be significant in ofMesh and windowsApps
From everything I've read it doesn't matter anywhere if the data is sorted by key.  But it would be great if somebody else could proofread and check if I missed something important
Other files that can be changed to unordered_map in my opinion are ofShadow / ofCubeMap ones
=> std::map to unordered_map

libs/openFrameworksCompiled/project/osx/config.osx.default.mk
Fix plist issues with make on osx. Updates #7455 closes #7437 
Thanks @dannylol19 for finding the issue. 
Used your PR as the basis for this - I think this will close #7437 but also provide more options for customization. 
I slightly changed the icon logic, but you can also override the default icon by having of.icns and of_debug.icns in your project directory.
=> Fix plist issues with make on osx. Updates #7455 closes #7437 

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
now addons will show the right folder when right clicking the folder inside xcode.
the same can be done later to addon folders, but it is a PG change
=> macOS, update template, addons

libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs
prompted by @edap's question in #7461 i've added a condition to enable a project's `.qbs` to properly override the language version (as qtcreator treats `cxxLanguageVersion` a bit differently than the `std=c++17` flag). so instead of passing the conventional `std=c++??` flag (and risking conflicting flags) if you define `cxxLanguageVersion: 'c++20'` in your `.qbs` it will override the now-default C++17.
that flag is optional, and now that OF is tied to ≥ C++17, older projects will need the C++17 "silent upgrade" anyway (the goal of this cluster of commits was to enable continuity with older projects), but it might be useful to compile a given project in C++20 or 23.
=> qtcreator qbs: allow project-based override of cxxLanguageVersion

addons/ofxOsc/src/ofxOscReceiver.cpp
only a very small change to fix an issue that occurs for me when receiving a large amount of messages. 
this fixes issue #7473 by correcting the bounds check.
Tested on Linux and Window
this is my first pull request, I'm not sure if this belongs into the master or the patch-release branch.
=> bugfix ofOSC receiver segfault index out of bounds

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp, addons/ofxEmscripten/src/ofxAppEmscriptenWindow.h
and preventing default touch event listener in document.
=> Emscripten Window defaults to passing mouse events for first touch 

scripts/osx/xcode_project.sh, scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj, scripts/templates/osx/emptyExample.xcodeproj/xcshareddata/xcschemes/emptyExample Debug.xcscheme, scripts/templates/osx/emptyExample.xcodeproj/xcshareddata/xcschemes/emptyExample Release.xcscheme
Here I'm implemented the idea discussed with @artificiel of having XCode run script phases joined together in an outside .sh file.
This have some advantages:
- if the scripts are updated, modernized you dont' need to regenerate all projects using projectGenerator, they will always pick the latest from the OF.
- a little bit faster build times. XCode always write each .sh to a temporary folder anyway.
- Better editing, one can use the code editor of choice directly instead of copying pasting from xcode tiny textfields.
- not having to reconvert xcode template to json in the case the scripts need editing
=> XCode project template - run script phases outside xcode project

libs/openFrameworks/utils/ofFileUtils.cpp, libs/openFrameworks/utils/ofFileUtils.h
I didn't end up add sort() to listDir by default as I think at this point macOS users have got used to calling sort(). 
`ofDirectory::sort` defaults to natural - so there is no change in behavior but it is about 10x faster. 
`ofDirectory::sort( ofDirectory::SORT_FAST )` is a little bit faster than ofDirectory::sort( ofDirectory::SORT_NATURAL ) as it does a simple std::sort without a comparison function 
closes #6129
=> faster sort and option for natural, fast and by date

addons/ofxKinect/addon_config.mk
While testing compatibility on linuxaarch64 on raspberrypi, ofxKinect needed to have the sames conditions as other linuxarm architecture to compile without error.
=> add linuxaarch64 to ofxKinect to support kinect on raspberrypi 64 bit

libs/openFrameworks/app/ofAppGLFWWindow.cpp
Ubuntu 16.04 parked GLFW in version 3.1.2
so this PR checks if the version is exactly 3.1.2 and ignores the line causing error.
=> Fixing GLFW issue in Ubuntu 16.04 - GLFW_TRANSPARENT_FRAMEBUFFER

libs/openFrameworks/gl/ofMaterial.h
this specific one is reverted in this PR so it is compatible with older os.
=> Ubuntu 16.04 - reverting one unordered_map to map

examples/threads/threadExample/src/ofApp.cpp, examples/threads/threadExample/src/threadedObject.h, libs/openFrameworks/app/ofAppRunner.cpp, libs/openFrameworks/app/ofAppRunner.h, libs/openFrameworks/app/ofMainLoop.h
while #4040 discusses that `ofThread` should not attempt to maintain a specific relationship to main thread as part of it's design, it is nevertheless useful to be able to determine (without running in a debugger) if a piece of code is called from the main thread or not (especially for monitoring & troubleshooting events, callbacks, notifications and other async constructs)
it is trivial to do so, but requires prior knowledge of the main thread id. this PR stores `ofMainLoop::thread_id` as part of `ofMainLoop` construction, and provides a standardized `ofAppRunner` function that compares it to the current thread::id.
tested on macOS and linux — works, with the presumption that the "main thread" does not change over app lifetime. (is it even possible that something moves the execution of …
=> ofIsCurrentThreadTheMainThread

libs/openFrameworks/utils/ofUtils.cpp, libs/openFrameworks/utils/ofUtils.h
as per https://stackoverflow.com/questions/9089842/c-chrono-system-time-in-milliseconds-time-operations and evoked in https://forum.openframeworks.cc/t/ofgetsystemtimemillis-not-working-on-macos/40875
=> ofGetUnixTimeMillis()

addons/ofxOsc/src/ofxOscReceiver.cpp, addons/ofxOsc/src/ofxOscReceiver.h
for example:
let's setup 2 receiver with
```cpp
receiver1.setup(26666, "localhost"); // same to receiver1.setup(26666, "127.0.0.1");
receiver2.setup(26666, "192.168.2.105");
```
then we can receive message on same port with different receivers like:
```cpp
while(receiver1.hasWaitingMessages()) {
ofxOscMessage m;
receiver1.getNextMessage(m);
ofLogNotice("receiver1") << m;
}
while(receiver2.hasWaitingMessages()) {
ofxOscMessage m;
receiver2.getNextMessage(m);
ofLogNotice("receiver2") << m;
}
```
I think this feature is helpful to make secure on large systems and complex network structures.
and this update is compatible simple `setup` with only given port.
=> add setup argument to listen on specific ip

libs/openFrameworks/types/ofParameter.h
=> ofParameter: reinit mechanism: use setMethod() instead of set() 

libs/openFrameworks/utils/ofUtils.cpp, libs/openFrameworks/utils/ofUtils.h, tests/utils/utils/addons.make, tests/utils/utils/src/main.cpp
=> Improve ofGetEnv with default value.

libs/openFrameworks/app/ofAppGLFWWindow.cpp
Motivation. I'm using a multiwindow app with some secondary monitors fullscreen sending data to LED panels.
gui app is on main monitor and I can toggle fullscreen on and off.
When I switch to fullscreen I notice a dark gradient in the next window. Disabling cocoa window shadow on fullscreen solve the issue, and no drawbacks because nobody needs shadow bleeding to a second monitor.
Related discussion:
https://github.com/openframeworks/openFrameworks/issues/6895#issuecomment-1111554345
=> macOS GLFW - no shadow when fullscreen

libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp, libs/openFrameworks/gl/ofGLProgrammableRenderer.h, libs/openFrameworks/gl/ofShadow.cpp, libs/openFrameworks/gl/ofShadow.h, libs/openFrameworks/gl/shaders/shadowDepth.vert
This allows using custom shaders during a shadow pass. The materials do not support custom shadow passes yet. Maybe that can be addressed in the next minor release. I tested using the shadow and material examples but could probably use a bit more.
Shadow shader functions have been added, so you can setup a shader using a function within the shadow class
`shadow.setupShadowDepthShader(ofShader& ashader, const std::string aShaderMain);`
The shader function for sending to the frag shader accepts a world position
```
vec3 worldPosition = (modelMatrix * vec4(position.xyz, 1.0)).xyz;
sendShadowDepthWorldPosition(worldPosition);
```
An example vert shader based on the MaterialPBRAdvanced Example
```
#if defined(SHADOW_DEPTH_PASS)
uniform mat4 modelMatrix;
in vec4 position;
uniform float …
```
=> Custom shaders during a shadow pass.

addons/ofxEmscripten/libs/html5video/include/html5video.h, addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js, addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.cpp, addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.h
partially addresses #7627 
need to do the same for audio
=> fix video file loading from wasm packaged files

addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js, addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.cpp, addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.h
fix audio loading/playback from index.data 
we might need to add in some other audio mime-types but this seems to account for most of them. cc @Jonathhhan
=> Bugfix emscripten audio loading

examples/gl/materialPBRAdvanced/bin/data/shaders/main.vert, examples/gl/materialPBRAdvanced/src/ofApp.cpp, examples/gl/materialPBRAdvanced/src/ofApp.h
=> Custom depth shader in materialPBRAdvanced Example

.clang-format
the result of this formatting can be perused at https://github.com/openframeworks/openFrameworks/pull/7649
so the proposal is a follow: with a .clang-format at the top-level, the git command
```
git clang-format
```
applies the .clang-format to the changed stuff. this means as time goes by the files will progressively made conformant, not disrupting the history process. 
(perhaps the apps, examples, tests and templates could be done as 4 big commits as the history is less critical there. also things can be excluded with `"DisableFormat": true`, such as included libraries -- did not take care for that in #7649).
of course that does not prevent one's IDE to automatically apply the clang-format, but depending on setup doing that might modify many files, making it harder to figure out what …
=> clang format file

libs/openFrameworks/utils/ofRandomDistributions.h
note that this is taken care of in #7657 but until that's merged at least this should be
=> [critical] ofRandomDistributions: #include tweak for self-sufficiency due to clang-format reordering of #includes

libs/openFrameworks/app/ofAppGLFWWindow.cpp, libs/openFrameworks/app/ofAppGLFWWindow.h
Implementing `glfwSetWindowRefreshCallback()` has the notable effect of redrawing window contents whilst resizing. The callback is not triggered in otherwise normal conditions. Tested on macOS 13.
1 commit for the changes; 1 commit for the format.
=> GLFW refresh callback

libs/openFrameworks/app/ofAppNoWindow.cpp, libs/openFrameworks/gl/ofGLBaseTypes.h, libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp, libs/openFrameworks/gl/ofGLProgrammableRenderer.h, libs/openFrameworks/gl/ofGLRenderer.cpp, libs/openFrameworks/gl/ofGLRenderer.h, libs/openFrameworks/gl/ofLight.cpp, libs/openFrameworks/graphics/of3dGraphics.cpp, libs/openFrameworks/graphics/ofCairoRenderer.cpp, libs/openFrameworks/graphics/ofCairoRenderer.h, libs/openFrameworks/graphics/ofGraphics.cpp, libs/openFrameworks/graphics/ofGraphics.h, libs/openFrameworks/graphics/ofGraphicsBaseTypes.h, libs/openFrameworks/graphics/ofPath.cpp, libs/openFrameworks/graphics/ofPath.h, libs/openFrameworks/graphics/ofRendererCollection.cpp, libs/openFrameworks/graphics/ofRendererCollection.h
All of the renderers accept floats for color arguments in the range 0-1 and use ofFloatColor instead of ofColor. 
ofSetColor functions that receive an ofFloatColor argument:
```
void ofSetColor(const ofFloatColor & color);
void ofSetColor(const ofFloatColor & color, float _a);
```
ofSetFloatColor functions have been added to accept floats between 0-1 or ofFloatColor
```
void ofSetFloatColor(float r, float g, float b);
void ofSetFloatColor(float r, float g, float b, float a);
void ofSetFloatColor(float gray);
void ofSetFloatColor(const ofFloatColor & color);
void ofSetFloatColor(const ofFloatColor & color, float _a);
```
Similar for ofClear
`void ofClear(const ofFloatColor & c);`
```
void ofClearFloat(float r, float g, float b);
void ofClearFloat(float r, float g, float b, float a);
void …
```
=> Use floats for colors internally. 

examples/gl/materialPBR/src/main.cpp, examples/gl/materialPBR/src/ofApp.cpp, examples/gl/materialPBR/src/ofApp.h, libs/openFrameworks/gl/ofCubeMap.cpp, libs/openFrameworks/gl/ofCubeMap.h, libs/openFrameworks/gl/ofCubeMapShaders.h
Some shader optimizations, naming conventions and support for float16 textures to work properly on open gl es mobile devices. 
I have checked on iOS via Safari and DuckDuckGo.
https://nickhardeman.com/temp/OFExamples/MaterialPBR/
This is what should be output
=> Bugfix Cubemap PBR for mobile devices

libs/openFrameworks/video/ofMediaFoundationPlayer.cpp, libs/openFrameworks/video/ofMediaFoundationPlayer.h
Set width and height immediately if loading sync
=> Windows Media Foundation Video Player Width and Height

addons/ofxSvg/src/ofxSvg.cpp, addons/ofxSvg/src/ofxSvg.h
Affinity designer exports "flattened" SVG like this:
```xml
<svg width="100%" height="100%" viewBox="0 0 1920 1080" 
version="1.1" xmlns="http://www.w3.org/2000/svg" 
xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve">
```
this % approach throws of svgtiny and it generates all vertices at (0, 0).
as a reference, the tiger.svg:
```xml
<svg version="1.2" baseProfile="tiny" id="svg2" xmlns:svg="http://www.w3.org/2000/svg"
xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
x="0px" y="0px" width="900px" height="900px"
viewBox="0 0 900 900" overflow="inherit" xml:space="preserve">
```
the proposed addition "fixes" this by: (1) checking if a viewBox is defined and (2) checking if width and height are set to 100%. if so, it replaces the 100%'s with the …
=> ofxSvg::fixSvgString(): addition to xml preprocessor

libs/openFrameworks/utils/ofRandomDistributions.h
`of::random::uniform` was exercising perfect forwarding to move arguments into the actual distributions, however this created some ambiguities with zero or one parameters — technically the underlying distribution requires min and max and somehow forwarding nothing satisfied the criteria.
so reverted to explicit T min T max params, with the option of having a single (max) param, which defaults to 1.0 in the case of float — so no implicit "range" for int versions. so:
```c++
of::random::uniform(); // returns float (0,1]
of::random::uniform(5.0); // returns float (0,5]
of::random::uniform<int>(5); // returns int (0,5)
of::random::unfiorm<int>(); // does not compile
```
[edit to add: this does not affect the backward-compatibility of ofRandom() which already wraps explicit parameters]
=> RandomDistributions: explicit parameters for of::random::uniform

examples/gl/materialPBRAdvanced/bin/data/shaders/main.vert, examples/gl/materialPBRAdvanced/src/ofApp.cpp, libs/openFrameworks/gl/ofMaterial.cpp, libs/openFrameworks/gl/shaders/pbr.vert
Address #7712. When adding a displacement map to a material, the shadows are not calculated from modified vertices from the shader.
See a fixed example based on the forum [post](https://forum.openframeworks.cc/t/ofshadow-and-ofshader-issue-on-of-0-12/42600/5)
https://nickhardeman.com/temp/OFExamples/ofShaderAndShadowTest-main/
=> Material with Displacement Proper Shadows

addons/ofxSvg/src/ofxSvg.cpp, addons/ofxSvg/src/ofxSvg.h
This allows for direct initialization and file loading in the likes of ofImage.
Yes I didn't know about this ofImage until recently
```c++
ofxSvg logoSvg { "_material/logo.svg" };
ofImage logo { "_material/logo2.png" };
```
=> ofxSvg initialize with filename

libs/openFrameworks/gl/ofGLUtils.cpp
Refers to #7716. Passes a warning for one and two channel float textures on Emscripten as unsupported. Changes from 32F to 16F to also work on mobile as well as desktop.
=> Broader support for float textures in Emscripten and mobile devices.

libs/openFrameworks/3d/ofNode.cpp, libs/openFrameworks/3d/ofNode.h
The new functions will reduce the number of matrix multiplications when needing to set the position, rotation and scale. 
Previously each call to position, rotation or scale called createMatrix() internally, which resulted in 3 mat4 multiplications.
```
node.setPosition(pos);
node.setRotation(quat);
node.setScale(scale);
```
Would be 9 mat4 matrix multiplications.
With the proposed methods, 
`node.setPositionRotationScale(pos,quat,scale);`
Only performs 3 mat4 matrix multiplications.
=> ofNode with function to set position, rotation and scale

libs/openFrameworks/graphics/ofImage.cpp
as the file is now filesystem object instead of string, it is already enclosed in double quotes when printed, this PR changes this
```
[ error ] ofImage: loadImage(): couldn't load image from ""P8.png""
```
to
```
[ error ] ofImage: loadImage(): couldn't load image from "P8.png"
```
and updates PG submodule to latest
=> ofImage: loadImage error - removing double quotes

libs/openFrameworksCompiled/project/osx/config.osx.default.mk
This also fixes the need to 'allow your application to access microphone' at every compile.
=> fixed regeneration of plist and icns at compile MacOS

addons/ofxSvg/src/ofxSvg.cpp, libs/openFrameworks/3d/ofMesh.inl, libs/openFrameworks/graphics/ofCairoRenderer.cpp, libs/openFrameworks/graphics/ofImage.cpp, libs/openFrameworks/graphics/ofTrueTypeFont.cpp, libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp, libs/openFrameworks/utils/ofFileUtils.cpp
filesystem object already encloses path with double quotes, 
so I'm removing some manual double quotes from objects that were string previously.
=> filesystem path removing double quotes

libs/openFrameworks/graphics/ofImage.cpp, libs/openFrameworks/graphics/ofImage.h
Detect and load HDR and EXR to ofTexture from file paths using either ofPixels or ofFloatPixels. Will also set the pixels to 4 channels for broader OpenGL ES support. There is also an added function for adding a flip in y argument.
`bool bLoadOk = ofLoadImage(*tex, "excellentHdrImage.hdr", mirrorY );`
Previously, something like below would be necessary.
```
std::string ext = ofFilePath::getFileExt( "excellentHdrImage.hdr" );
ext = ofToLower(ext);
bool hdr = (ext == "hdr" || ext == "exr");
if( hdr ) {
ofFloatPixels fpix;
bLoadOk = ofLoadImage(fpix, apath);
if( bLoadOk) {
#if defined(TARGET_OPENGLES)
// GL_RGB32F, GL_RGBA32F and GL_RGB16F is not supported in Emscripten opengl es, so we need to set to GL_RGBA16F or GL_RGBA32F. But GL_RGBA32F is not supported via opengl es on most mobile …
```
=> ofLoadImage for ofTexture will detect HDR and EXR 

.github/workflows/build-linux-nightly.yml, .github/workflows/manual-nightly.yml
It is just a version bump so it starts using more recent github actions and avoid commands that will be disabled soon
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. 
```
For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> update Nightly (auto and manual) actions

addons/ofxEmscripten/libs/cors/coi-serviceworker.js, libs/openFrameworksCompiled/project/emscripten/config.emscripten.default.mk
This PR makes it possible to run multi thread Emscripten without configuring the server with:
```
Header set Cross-Origin-Embedder-Policy "require-corp"
Header set Cross-Origin-Opener-Policy "same-origin"
```
Now I add only:
```
RemoveType .gz
AddEncoding x-gzip .gz
AddType application/wasm .wasm
```
To my `.htaccess` file.
See the bottom of the page: https://emscripten.org/docs/compiling/WebAssembly.html
It is not necessary, but `AddType application/wasm .wasm` avoids a warning and seems to be faster.
The suggested `Options Multiviews` does not work for me, so I leave it away.
Would be nice, to set that with the script too (but my attempt did not work).
Multithreading is now set as default (maybe change the default to `USE_PTHREADS=0` like it was before?).
=> Emscripten cors

scripts/dev/download_libs.sh
Fixes addon paths when using download_libs.sh 
https://github.com/openframeworks/apothecary/issues/315
=> VS download addons fix paths

scripts/dev/download_libs.sh, scripts/dev/download_pg.sh, scripts/osx/download_latest_libs.sh, scripts/osx/download_libs.sh, scripts/osx/download_projectGenerator.sh, scripts/vs/download_latest_libs.sh, scripts/vs/download_libs.sh, scripts/vs/download_projectGenerator.sh
Download Project Generator nightly binary and installs it to oF Root 
- scripts/osx/download_projectGenerator.sh 
- scripts/vs/download_projectGenerator.sh 
Download Latest Libraries macOS - Bleeding
- scripts/osx/download_latest_libs.sh 
Download Latest Libraries vs - Bleeding
- scripts/vs/download_latest_libs.sh 
Existing download_libs.sh no longer used for targetting -b bleeding
=> Dev Scripts - Download Project Generator Latest / Download Latest Libraries macOS/vs

libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk
this PR removes the boost from compiling path, improving a little bit the compiling / linking time.
=> makefile no boost

libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk
this one reverts this PR 
- https://github.com/openframeworks/openFrameworks/pull/7842
But only a specific file, still keeping some package caching improvements
Related discussion here: 
- https://github.com/openframeworks/openFrameworks/issues/7836
=> Msys2 GLFW - reverted to previous state after 3.3.9 bugfix

libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk, scripts/ci/addons/build.cmd, scripts/ci/addons/build.sh, scripts/ci/android/install.sh, scripts/ci/emscripten/build.sh, scripts/ci/emscripten/examples_to_build.sh, scripts/ci/linux64/build.sh, scripts/ci/linux64/run_tests.sh, scripts/ci/linuxaarch64/build.sh, scripts/ci/linuxarmv6l/build.sh, scripts/ci/linuxarmv7l/build_junest.sh, scripts/ci/msys2/build.sh, scripts/ci/msys2/run_tests.sh, scripts/ci/osx/run_tests.sh, scripts/linux/buildAllExamples.sh
two changes:
internally build core using multiple cores on make (in compile.project.mk)
and change the -j2 to -j to detect automatic number of available cores
this can improve github actions, and overall performance
=> Make - using automatic number of cores

libs/openFrameworksCompiled/project/osx/config.osx.default.mk
removing more boost paths from compiling / linking with make
=> Remove boost .a from linker path

libs/openFrameworks/graphics/ofTrueTypeFont.cpp
`ofTrueTypeFont::stringWidth()` and `ofTrueTypeFont::getStringBoundingBox()` give a wrong width value because these ignore `\n`, and width value piles up, getting longer and longer if you have multiple `\n`.
- Before
- After
- After (OF_TTF_RIGHT_TO_LEFT)
- stringWidth
https://github.com/openframeworks/openFrameworks/blob/2b8cab27d5b2dfc85be6cffc5119dce3d609f79c/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L1164-L1169
- getStringBoundingBox
https://github.com/openframeworks/openFrameworks/blob/2b8cab27d5b2dfc85be6cffc5119dce3d609f79c/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L1193-L1199
- latest master
- on macOS 13.4
- OF_TTF_LEFT_TO_RIGHT
- OF_TTF_RIGHT_TO_LEFT
https://gist.github.com/hiroMTB/e5c746c6403da714f74cf4f37b711451
=> Fix ofTrueTypeFont: wrong width calc (only when string contains \n)

libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk, libs/openFrameworksCompiled/project/osx/config.osx.default.mk
On MSYS2 build, the -mwindows flag was preventing the logs from appearing in the terminal.
Also noticed that some release build were building optimizing for size instead of speed on MSYS2 and OSX.
=> Remove -mwindows linker flag for msys2 build and adjust OPT flags

tests/io/loadImage/src/main.cpp
I've noticed tests loading https image from openframeworks forums fails from time to time ~ not sure why.
But changing to a github image helps
=> [actions] tests/io/loadImage https image fix

libs/openFrameworks/types/ofParameter.h
following the discussion in https://forum.openframeworks.cc/t/can-i-tell-if-an-ofabstractparameter-is-set-to-its-default-value/ this builds on the recent 'init' mechanism of ofParameter and adds the ability to verify if the value is at it's initial value or not, without the need to "unwrap" (cast) the internal data type of the abstract parameter at the call site.
`isInit()` will also work on a concrete `ofParameter<T>`, as well as `ofParameterGroup` (recursively calling `isInit()` on itself and returning true only if all the children are true).
note that `isInit()` is not linked to activity but current instantaneous value (if true, a parameter could have changed in the past, but is by some means back to it's init value). see `didNotify()` to check for "activity" (which will return true …
=> ofParameter::isInit() implementation

addons/ofxSvg/addon_config.mk
This PR fixes the bundled ofxSvg running on 64 bit ARM linux, eg Raspberry Pi running a 64 bit OS.
I have checked other missing linuxaarch64 lemmas for other included addons, but could not find any sofar.
Contributes to https://github.com/openframeworks/openFrameworks/issues/7791
=> Fix ofxSvg on 64 bit ARM linux architecture

scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
After a lot of struggle I finally found how to define multiple GCC_PREPROCESSOR_DEFINITIONS in xcconfig files.
my usage is this:
```
USER_PREPROCESSOR_DEFINITIONS=OF_NO_FMOD=1 NANOVG_GL2_IMPLEMENTATION=1
```
and the issue was the project calling xcodebuild to build the OF Core
the solution was to enclose everything with single quotes, so now we can use multiple parameters.
=> XCode project - compiling core / escape $USER_PREPROCESSOR_DEFINITIONS

libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk
If anybody is using RPI with an old OS.
I've left the includes for userland repositories, so it is still possible to clone userland repo
https://github.com/raspberrypi/userland
in RPI_ROOT 
cc @ofTheo
=> RPI armv6l - put back /opt/vc if not cross compiling

libs/openFrameworks/graphics/ofPixels.cpp
minimal changes to make it work
so now the pixels buffer is allocated with the exact number of bytes used.
it used to work ok with char because sizeof(char) is 1
related to some part of
https://github.com/openframeworks/openFrameworks/issues/6226
addresses crash / artifacts
=> fix ofPixels <float> allocation issue

libs/openFrameworks/graphics/ofGraphics.h
makes use of the lifetime of an object to frame push and pop matrix and style.
OLD-SCHOOL FLAT
```c++
ofPushMatrix()
ofTranslate()
// (…)
ofPushMatrix()
ofTranslate();
// (…)
ofPopMatrx();
// (…)
ofPopMatrix();
// easy to lose track and get push pop errors
```
ARTISANAL BRACING — TRYING TO UNDERSTAND WHAT’S GOING ON
```c++
ofPushMatrix()
{
ofTranslate()
// (…)
ofPushMatrix()
{
ofTranslate();
// (…)
}
ofPopMatrx();
// (…)
}
ofPopMatrix();
// as good as the artisanal visual tabbing 
```
INTRODUCING SCOPED MATRIX BRACING-AWARE OBJECT
```c++
{
ofScopedMatrix _ ;
ofTranslate()
// (…)
{
ofScopedMatrix _ ;
ofTranslate();
// (…)
}
// (…)
} 
// push:pop balanced garanteed
```
~~FOR THE HARDCORE: LAMBDA IN ANONYMOUS OBJECT ENFORCES STRUCTURE~~
```c++
ofScopedMatrix{[&]{
ofTranslate();
// (…) …
```
=> ofScopedMatrix

libs/openFrameworks/utils/ofThreadChannel.h
title says it all; proves useful if unconsumed data in the channel is known to be stale
=> ofThreadChannel::clear() to clear the channel

addons/ofxOsc/src/ofxOscMessage.h
Some cases were not caught correctly with the implicit `add` argument.
=> ofxOscMessage: extra implicit adds [fixes something noted through #7938 debugging]

addons/ofxOsc/libs/oscpack/src/ip/posix/UdpSocket.cpp
In the oscpack udpSocket listener thread there is a flag named `break_` which breaks the endless loop, resolving into the thread exiting "properly". because of the threading approach of ofxOscReceiver being changed from `detach()` to` join()`, a new race condition emerges:  in the `close()` of the ofxOscSender the `asynchronousBreak()` function is called, which sets the flag to true in order to break the listener, but there are cases where the listener thread has not spun up yet, but will be forced to by the `join()`, and the first thing it does in `Run()` is to reset `break_` to false, this removing the flag and creating the hang (the `Run()` will never return).
this changes inverses the logic: the `break_` is initialized to false, and changed back to false at the end of `Run()`. this …
=> oscpack / udpSocket: invert the "break_" semaphore

addons/ofxNetwork/src/ofxTCPClient.cpp
Fix for a failure to find the TCP delimiter when the incoming stream repeats the first character of delimiter sequence. Without this fix, a stream like `...[[/TCP]...` fails because the matcher doesn't reset after the first `[` is identified.
=> Fix edge case in TCPClient findDelimiter

examples/events/notifyEventExample/src/ofApp.cpp, libs/openFrameworks/events/ofEvent.h
this limitation was introduced around the `didNotify()` feature which is based on an `std::atomic<bool>` which is not default-copy-constructible. this was not raised as a problem because the core and builtin-addons do not inherit ofEvent in a way that triggers the copy constructors. but some addons do, which makes them incompatible.
fixed by moving the `notified_` member up into ::priv, which already has custom copy constructors. this revert the copy-constructibility of ofEvent.
=> restore default-copy-constructibility of ofEvent

addons/ofxOsc/libs/oscpack/src/ip/posix/UdpSocket.cpp, addons/ofxOsc/src/ofxOscReceiver.cpp, apps/devApps/StressofxOscReceiver/src/ofApp.cpp
replaces #7978 which had a garbled commit
=> [critical bug fix] Osc scope2

addons/ofxOsc/libs/oscpack/src/ip/win32/UdpSocket.cpp
the `INSTANTLY OUT OF SCOPE` test might need this
=> ofxOscReceiver: win32 implementation: shadow posix changes

libs/openFrameworks/app/ofAppNoWindow.h
otherwise does not satisfy `_LIBCPP_INLINE_VISIBILITY` + `_LIBCPP_CONSTEXPR_SINCE_CXX23`
=> ofAppNoWindow.h: #include ofEvents to complete the ofCoreEvents type for C++23 compliance

libs/openFrameworks/graphics/ofPixels.cpp
Fixes ofPixels_<PixelType>::resizeTo for float pixels (and hopefully every type of pixels) simply replacing bytesPerPixel by channelsFromPixelFormat(pixelFormat) to find indices.
as described here https://github.com/openframeworks/openFrameworks/issues/6226#issuecomment-2099906869
=> Fix ofPixels_<float> resize

scripts/linux/ubuntu/install_dependencies.sh
I think apt update is trying to restart some services, and runner-provisioner.service maybe shouldn't be restarted
```
Restarting services...
/etc/needrestart/restart.d/systemd-manager
systemctl restart packagekit.service php8.3-fpm.service runner-provisioner.service systemd-journald.service systemd-networkd.service systemd-resolved.service systemd-udevd.service udisks2.service walinuxagent.service
```
=> [actions] fix issue with linux64

scripts/dev/downloader.sh
With further testing was able to find some more issues with cURL single file URL passed
And the detection of WGET2 / WGET / CURL code was malfunctioning, re-wrote function
=> Downloader 3.2.3 - fixes for install detection and single url for curl

scripts/dev/download_libs.sh, scripts/dev/download_pg.sh
Download ProjectGenerator 
- optimise wont re-download if in sync with GitHub release /size/time via wget2/curl 
- now outputs to libs/downloads rather than dev/scripts
Download libs 
- addon deploy modified for bleeding with alternative deploys for addons
=> download scripts - projectGenerator optimisations - location

addons/ofxOsc/addon_config.mk, scripts/ci/vs/install_bleeding.sh
Fixes download ci script to link to correct projectGenerator download (nightly)
Fixes Issue was traced to addon_config.mk in ofxOSC common excluding win32 folder... causing recent problems in builds and debugging in projectGenerator... who would have thought
=> pg use nightly vs

libs/openFrameworks/sound/ofRtAudioSoundStream.cpp
Fixes #8013 
[As of RtAudio 6.0.0][1] you cannot assume that devices will fall in the range [0, getDeviceCount() - 1]. Doing so will potentially cause errors or out of bounds array accesses depending on the platform.
I am not super familiar with this project, but as far as I can tell I couldn't find any documentation or example projects that would need to be updated as a result of this change. However, I do know of at least two projects ([audiostellar][2] and [ofxPDSP][3]) that make this assumption, so it is definitely worth noting in the change log.
[1]: http://www.music.mcgill.ca/~gary/rtaudio/classRtAudio.html#ab1b5af34ddfe84ae2043d1f09c8638d5
[2]: https://gitlab.com/ayrsd/audiostellar
[3]: https://github.com/macramole/ofxPDSP
=> Use getDeviceIds function to list audio devices instead of relying on contiguous IDs

.github/workflows/nightly-linux64.yml
Fix GitHub Action 
- Nightly upload to release
- Tested Artifact
=> Fix GitHub Action 

libs/openFrameworks/3d/ofEasyCam.cpp
This only happens with ofEasyCam's **ortho mode + custom viewport**.
Expected behavour is to zoom in/out into the mouse pointer position when user scroll mouse wheel (or R click drag). It works fine with normal viewport with 0,0 position and full window w, h. But when we use custom viewport (e.g. camera.begin(viewport); ) then it zoom in/out into wrong position.
The problem is that ofEasyCam forgots to give viewport parameter to `screenToWorld()`. `screenToWorld()` calls `ofCamera::getViewport()` internaly but ofCamera seems not storing custom viewport parameter but just get current window's viewport, which is {0,0,fullW, fullH}. Hence it gives wrong world position.
tested on
- macOS 14.5
- Xcode 15.4
- openFrameworks(latest master at the time of this writting)
ofApp.h
```
#pragma once …
```
=> ofEasyCam : fix wrong scaling center in ortho mode

.github/workflows/of.yml, scripts/ci/vs/install_bleeding.sh, scripts/dev/download_pg.sh
Did live device testing and it was fine.
Seems like the CI for addons wasn't getting linked correctly  and failing due to not updating the project with the addon path correct with the addon libs there. 
Ci fixes / bash
Added for convince the cmdline in the projectGenerator folder
=> ci fixes - projectGenerator download fix for vs 

scripts/dev/download_libs.sh
fix #8049 
libs are suffixed with MSYSTEM.
Removing invalid condition on MINGW_PACKAGE_PREFIX
=> fix msys2 libs downloading

libs/openFrameworks/graphics/ofTrueTypeFont.cpp
Fixes: https://github.com/openframeworks/openFrameworks/issues/7810
Issues with TrueType font for system level loading. 
Updated to path for return types 
Tested
=> ofTrueType Font default system font fix. Windows / VS.

libs/openFrameworks/graphics/of3dGraphics.cpp
I've noticed the default OF plane comes with 6 cols, 4 rows
this plane is used for ofLight::draw (areaLight) for example
This is a suggestion of using a 1x1 plane as a default, and increase resolution if / when needed.
=> OF default plane with less resolution (rows, cols)

addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp, addons/ofxEmscripten/src/ofxAppEmscriptenWindow.h
Not sure, if this is backward compatible, but it works wit the current Emscripten version.
Also, the apothecary libs need to be rebuild with the current Emscripten version.
=> Emscripten 3.1.65 fix

scripts/dev/downloader.sh
Noticing some issues with wget2 still on windows causing json headers in a few cases to not be extracted due to the zip file not completing, inconsistent 
- Fixed and forced remove of local download tar/zip if found (should be done automatically with clobber but to be safe
=> downloader [4.2.4 ~ 4.2.5] - windows - wget2 disabled, remove old download files if local outdated 

examples/threads/threadExample/src/threadedObject.h, examples/threads/threadedImageLoaderExample/src/ofApp.cpp, libs/openFrameworks/utils/ofThread.h
Fixes https://github.com/openframeworks/openFrameworks/issues/7912
ofThread has virtual function - threadedFunction() and no virtual destructor. 
This PR adds virtual dtor.
Also I tested the examples and fixed a crash on exit for threadedImageLoader and something was wrong with pixel[0] access on the other. 
All working now
=> Fixes ofThread non-virtual dtor and examples

libs/openFrameworks/3d/of3dPrimitives.cpp, libs/openFrameworks/3d/of3dPrimitives.h, libs/openFrameworks/graphics/ofGraphicsBaseTypes.h
I've added a struct that contains the min and max vertices of a `of3dPrimitive`.
it can be used like this. Default values are initialized to (0.0, 0.0, 0.0).
When the primitive move, the bounding box does not get updated.
``` cpp
ofBoxPrimitive geometry;
geometry.computeBoundingBox();
cout << geometry.getBoundingBox().min.x << endl;
cout << geometry.getBoundingBox().max.y << endl;
```
=> add ofBoundingBox

libs/openFrameworksCompiled/project/macos/config.macos.default.mk, libs/openFrameworksCompiled/project/osx/config.osx.default.mk, scripts/templates/macos/config.make, scripts/templates/osx/config.make
closes https://github.com/openframeworks/openFrameworks/issues/8111
=> [macOS] fix c++23 issue using make

addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.cpp, addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.h, addons/ofxiOS/src/video/ofxiOSVideoPlayer.h, addons/ofxiOS/src/video/ofxiOSVideoPlayer.mm, libs/openFrameworks/types/ofBaseTypes.cpp, libs/openFrameworks/video/ofAVFoundationPlayer.h, libs/openFrameworks/video/ofAVFoundationPlayer.mm, libs/openFrameworks/video/ofDirectShowPlayer.cpp, libs/openFrameworks/video/ofDirectShowPlayer.h, libs/openFrameworks/video/ofGstVideoPlayer.cpp, libs/openFrameworks/video/ofGstVideoPlayer.h, libs/openFrameworks/video/ofMediaFoundationPlayer.cpp, libs/openFrameworks/video/ofMediaFoundationPlayer.h, libs/openFrameworks/video/ofVideoBaseTypes.h, libs/openFrameworks/video/ofVideoPlayer.cpp, libs/openFrameworks/video/ofVideoPlayer.h
this PR intends to use fs::path internally for video player functions 
(load, loadAsync, loadMovie [[deprecated]] )
=> ofVideoPlayer using fs::path

addons/ofxGui/src/ofxButton.cpp, addons/ofxGui/src/ofxButton.h
It is a bit confusing that the visual representation of an ofxButton is the same as the ofxToggle, as it is not possible to pre-determine that the widget will behave differently without clicking it. Even once clicked, it looks like an active toggle so you only know if if it's going to "stick" or not upon release.
This changes the representation of the Button to a rounded rectangle, completely filled when clicked (much like buttons do, in most environments). it is close enough to the original square to not disturb the visual ambiance of a populated ofxPanel, but still conveys it's operational status clearly.
It does not affect usage or API, nor adds methods or memory requirements as it simply implement it's own `generateDraw` over the one inherited by ofxToggle, by copying the …
=> ofxButton: distinguish button from Toggle visually with circle vs square

libs/openFrameworks/types/ofParameter.h
this concerns the constructor of ofParameter, and attempts to sanitize the treatment of single-arg construction such as:
```
ofParameter<Type> name {some_value};
```
as described in #7671 currently the implicit conversion will convert string and char * to bool . this is error prone as:
```
ofParameter<bool> name {"activate shields"};
```
is not flagged as an error, but creates an unnamed bool param with true as the default value (`activate shields` implicitly converts to true).
this PR does 2 things:
- ensures the arg is convertible to the type (better error message, otherwise they come deeper in the template stuff)
- if the type is bool, ensure arg is also arithmetic (so implicit conversion from 0, 1, or whatever arithmetic value is allowed)
note that it still allows the exception for …
=> prevent misinterpretation ofParameter<bool> ctor when single arg is string

libs/openFrameworks/ofMain.h
to tighten ISO conformance in MSVC without `/permissive-`
https://github.com/microsoft/STL/blob/main/stl/inc/iso646.h
=> #ifdef TARGET_WIN32 #include <iso646.h> #endif

libs/openFrameworks/video/ofGstVideoPlayer.cpp
Switching of::filesystem::path to string fixes the issue in the videoPlayer example on linux for the ofGstVideoPlayer.
Is outlined in this forum post:
https://forum.openframeworks.cc/t/linux-videoplayerexample/44043
=> Fix for of::filesystem::path and string for gst video player.

libs/openFrameworks/graphics/ofImage.cpp, libs/openFrameworks/graphics/ofTrueTypeFont.cpp, libs/openFrameworks/utils/ofFileUtils.cpp, libs/openFrameworks/utils/ofFileUtils.h, libs/openFrameworks/utils/ofSystemUtils.cpp, libs/openFrameworks/utils/ofSystemUtils.h
=> No fs::path return

libs/openFrameworks/types/ofBaseTypes.cpp, libs/openFrameworks/video/ofVideoBaseTypes.h
its argument used to be a string rather than const reference string. This fixes other video players that were affected by that change.
=> ofBaseVideoPlayer load function was reverted incorrectly

addons/.gitignore, addons/ofxAssimp/addon_config.mk
ofxAssimp was missing in the addons gitignore (not really sure how it was getting into the repo).
The lib path for macos was using the "old" folder named "osx". I would guess that this addon is not tested through CI.
I think it is safe to merge this one,
=> ofxAssimp: Updated gitignore and addon_config.mk

libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk
This a adds support for ADDON_DEFINES when using make. It follows the pattern already set for the other addon_config.mk files and it was also partly implemented, so it should not break nor bother when not present.
=> Added support for ADDON_DEFINES from addon_config.mk for make files

libs/openFrameworks/3d/of3dUtils.cpp, libs/openFrameworks/3d/of3dUtils.h, libs/openFrameworks/3d/ofMesh.inl, libs/openFrameworks/3d/ofNode.cpp, libs/openFrameworks/3d/ofNode.h, libs/openFrameworks/app/ofAppEGLWindow.cpp, libs/openFrameworks/gl/ofShader.h, libs/openFrameworks/graphics/ofGraphics.h, libs/openFrameworks/graphics/ofGraphicsBaseTypes.h, libs/openFrameworks/graphics/ofPolyline.h, libs/openFrameworks/math/ofMath.h, libs/openFrameworks/math/ofMathConstants.h, libs/openFrameworks/math/ofVec4f.h, libs/openFrameworks/types/ofColor.cpp, libs/openFrameworks/types/ofColor.h, libs/openFrameworks/types/ofRectangle.cpp, libs/openFrameworks/video/ofAVFoundationGrabber.mm
Another PR to move weight from .h files to .cpp files. 
it is using forward declaration from glm objects whenever possible
=> Reducing .h includes in .h files

libs/openFrameworksCompiled/project/macos/config.macos.default.mk, libs/openFrameworksCompiled/project/osx/config.osx.default.mk
I missed this from commit https://github.com/openframeworks/openFrameworks/commit/f3b9aa6007277ee2fbb9de447250ff20b69a8262
It no longer copies libfmod.dylib when using make, nor compiling ofFmodSoundPlayer.
=> Removing fmod from macos and osx makefile configs

.github/workflows/manual-nightly.yml, .github/workflows/nightly-linux64.yml, .github/workflows/of.yml, scripts/dev/download_libs.sh
- Change for release tag default from bleeding to Latest (for apothecary). 
- Allow to download libs of --tag (or version target for libs i.e v12.1.0, v13.0.0 etc) Allowing locking off of libraries to versions
- Fix Xcode change for install Xcode 16 Nov5th change  https://github.com/actions/runner-images/issues/10703
- Nightly update release to softprops/action gh release.
- Nighty - Add determine release type.
- Nighty -Allow for future night to build for tags (more to do with local scripts for that). (So manually can tag and it will build nighty to say v13.0.0)
=> GitHub Actions update

.github/workflows/manual-nightly.yml, .github/workflows/nightly-linux64.yml
- Nightly-Manual now on Tag on main repo
- YML Formatting error for Release type determination / tag 
- Artefact enabled with past 7 days for nightly then expires.1 for tag release.
=> Actions Fix

libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj, scripts/dev/download_libs.sh, scripts/templates/vs/emptyExample.vcxproj
Fix error of download libs nightly instead of latest download
```
[downloader] [cURL] urls:[https://github.com/openframeworks/apothecary/releases/download/nightly/openFrameworksLibs_latest_macos_1.tar.bz2 -o openFrameworksLibs_latest_macos_1.tar.bz2 https://github.com/openframeworks/apothecary/releases/download/nightly/openFrameworksLibs_latest_macos_2.tar.bz2 -o openFrameworksLibs_latest_macos_2.tar.bz2 https://github.com/openframeworks/apothecary/releases/download/nightly/openFrameworksLibs_latest_macos_3.tar.bz2 -o openFrameworksLibs_latest_macos_3.tar.bz2] args:[--retry-all-errors --remove-on-error -Z  ]
```
https://github.com/openframeworks/apothecary/releases/download/**nightly**/openFrameworksLibs_**latest**_macos_...
mismatch of Tags
=> download_libs [2.6.1 ~ 2.6.2] Fix issue for latest

.github/workflows/of.yml, scripts/ci/linux64/build.sh, scripts/ci/linuxrpi/build.sh, scripts/ci/msys2/build.sh
Actions are failing, RPI install is missing glm headers, it seems apothecary libs are being installed in the wrong path.
Even failing the actions are appearing as complete with green status. 
This PR means to fix this so everybody is more alert to this kind of regression:
https://github.com/openframeworks/openFrameworks/issues/8102#issuecomment-2363954385
=> [actions] - Fix for RPI actions that should be failing 

examples/sound/audioInputExample/src/ofApp.cpp, examples/sound/audioOutputExample/src/ofApp.cpp
Examples for RTAudio minor fixes
=> Examples RTAudio fixes

examples/sound/audioOutputExample/src/ofApp.cpp, libs/openFrameworks/sound/ofRtAudioSoundStream.cpp, libs/openFrameworks/sound/ofSoundBaseTypes.cpp, libs/openFrameworks/sound/ofSoundStream.cpp, libs/openFrameworks/utils/ofConstants.h
Fixes: https://github.com/openframeworks/openFrameworks/issues/8224 for issues with Windows and deeper issues 
- ofRtAudioSoundStream - Fix for device api not being set in setup causing reinit or warning / errors
- ofSoundBaseTypes -Fix for ofSoundBaseTypes for printing device list (now apis by platform) and spelling of unknown
- ofSoundStream - api setting explicit 
- ofConstants.h - Missing constants for RTAudio platforms
```
#define __WINDOWS_DS__
#define __WINDOWS_MM__
#define __WINDOWS_WASAPI__
#define __WINDOWS_ASIO__
```  
```
#define __LINUX_PULSE__
#define __LINUX_ALSA__
#define __LINUX_OSS__
```` 
- with RTAudio cmake fixes applied - Build 3
https://github.com/openframeworks/apothecary/pull/464
=> RtAudio / ofRtAudioSoundStream / ofSoundBaseTypes 

.github/workflows/of.yml, libs/openFrameworks/events/ofEvents.cpp, libs/openFrameworks/events/ofEvents.h, libs/openFrameworks/utils/ofConstants.h, libs/openFrameworks/utils/ofFpsCounter.cpp, libs/openFrameworks/utils/ofFpsCounter.h, libs/openFrameworks/utils/ofTimerFps.cpp, libs/openFrameworks/utils/ofTimerFps.h, scripts/ci/emscripten/build.sh, scripts/ci/emscripten/build_addons.sh, scripts/ci/linux64/build.sh, scripts/ci/linux64/run_tests.sh
Fixes: https://github.com/openframeworks/openFrameworks/issues/8238
- fixed default values
- fixed ofGetLastFrameTimeSecs() to return double duration as to spec 
- fixed ofGetLastFrameFilteredTimeSecs()  to return double duration as to spec 
- fixed timestamp calculation for < 2
- fixed filteredTime calculation with clamps for anomalies 
- fixed filteredTime calculation to only occur with timeMode FilteredTime
- passing timeMode as int in ctor / setter added
- queue to deque (for size optimisation)
- allowed for FPS change with functions added
- fixed setting of ofFPSCounter and timeMode 
- fixed changing of FPS not changing fps counter
=> Fix: ofGetLastFrameTime() always returns 0 (Filtered/System timeMode) Bug

addons/ofxiOS/src/video/AVFoundationVideoGrabber.mm, libs/openFrameworks/video/ofAVFoundationGrabber.mm
Fixes reported: https://github.com/openframeworks/openFrameworks/issues/8230
Where system OS macOS 13 having issues with SDK types not defined in macOS 13.
```#if __MAC_OS_X_VERSION_MAX_ALLOWED >= 140000```
- Also fixed prior to 10.15 where AVCaptureDeviceDiscoverySession not defined use old api with deprecations pragma'd.
- Simplified code using device target list
- Did test @gllmAR the ifdef solution and didn't work for macOS 14+ so definitely test this out 
- Fixed with same logic. Added iOS 17+ BuiltInLiDARDepthCamera, ContinuityCamera, TrueDepthCamera and External 
- Fixed issue with CGBitmapInfo cast
- Simplified code using device target list
=> Fix: [macOS] OF nightly minimum system requirement >13

.github/workflows/clean-up-cache-cron.yml, .github/workflows/of.yml
- Action for Auto clearing of caches after merging is not currently functional - more debugging added
- Action On Cron 3 AM UTC Daily to clear caches with - more permissions on Main repo rather than on a Fork / Merge close action like the former.
- Fix of YML from last merge
=> Github Actions - Cache Fix 

.gitmodules, scripts/ci/package_builds.sh, scripts/ci/simulate_nightly.sh, scripts/dev/create_package.sh
- Fixed action 
- Fixed up simulate fix also
=> Nightly Build Fix

libs/openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj/project.pbxproj, of, scripts/dev/download_libs.sh, scripts/dev/downloader.sh, scripts/dev/upgrade.sh, scripts/of.sh, scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
- Removes libraries check
- Fixes Clean issues for Xcode projects due to permissions (added script) 
- downloader [4.4.0 ~ 4.5.0] - fix close connection for zero urls.
- emscripten fix download 32 bit
- of commands
=> Template fix for scripts - Fixes Clean

libs/openFrameworks/types/ofParameter.h
fixes some edges cases and prevents misinterpreting a std::string in the context of constructing an ofParameter<std::string> (follows #8235 and #8218 triggered by the tightening in #8132)
=> fix(ofParameter): ctor refinements for std::string

libs/openFrameworks/3d/of3dPrimitives.cpp, libs/openFrameworks/3d/ofMesh.inl, libs/openFrameworks/3d/ofNode.cpp, libs/openFrameworks/gl/ofVbo.cpp, libs/openFrameworks/graphics/ofPolyline.inl, libs/openFrameworks/types/ofRectangle.cpp
with some small changes here we can avoid including ofVectorMath.h with all templates and other includes
=> ofRectangle changes to avoid including ofVectorMath.h

addons/ofxAssimp/src/Source/ofxAssimpSrcScene.cpp, addons/ofxAssimp/src/Source/ofxAssimpSrcScene.h
Fixes load times mentioned in #8267 by caching the bone list instead of searching through all the meshes and all the bones for every isBone() function call.
=> create a map of the bones instead of searching for all the meshes 

libs/openFrameworksCompiled/project/ios/CoreOF.xcconfig, libs/openFrameworksCompiled/project/macos/config.macos.default.mk, libs/openFrameworksCompiled/project/osx/config.osx.default.mk
from iOS CoreOF.xcconfig and config.*.default.mk for macOS and osx.
=> Remove boost references 

addons/ofxGui/src/ofxInputField.cpp, addons/ofxGui/src/ofxSlider.cpp
ofParameter / ofxSlider linking error
Fixes https://github.com/openframeworks/openFrameworks/issues/7458
Found when using ofxGui - ofxAssimpExample 
~~removed conditional define and using template class define as fix for all platforms~~
edited define for apple targets
=> ofxGui fix for symbols on iOS

libs/openFrameworksCompiled/project/ios/CoreOF.xcconfig, libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj, libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/xcshareddata/xcschemes/openFrameworks.xcscheme, libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig, libs/openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj/project.pbxproj, scripts/ci/ios/build.sh, scripts/templates/ios/emptyExample.xcodeproj/project.pbxproj, scripts/templates/ios/emptyExample.xcodeproj/xcshareddata/xcschemes/emptyExample.xcscheme, scripts/templates/ios/ofxiOS-Info.plist, scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
- iOS Template Project Fixes for Target Configuration (Debug/Release)
- Also Target Device Simulator or Real -> **no more linking errors**
- core ios Project - targetname to just simple openFrameworks
- LIB_OF -> LIB_OF_RELEASE / LIB_OF_DEBUG
- Object-C enabled by default
- Fixes: https://github.com/openframeworks/openFrameworks/issues/8308
- plist add location permission https://github.com/openframeworks/openFrameworks/issues/8310
- Fix for ios ci script - add device target for later too 
- iOS Subproject removed and just using standard reference files of core code = clean
- fix for release
- added fmt Fixes https://github.com/openframeworks/openFrameworks/issues/8300
=> Xcode iOS Target Project Fixes

scripts/templates/ios/emptyExample.xcodeproj/project.pbxproj
Fixes:  https://github.com/openframeworks/openFrameworks/issues/8312#issuecomment-2693439746
- for ofxIOS is absent from sidebar
- Fixes editing source within an app's project tree iOS+OFLib does not trigger recompile the lib 
- Fixes  - add ofxiOS group folder ref
=> iOS template 

scripts/of.sh
Since this is Developer useful in this Release window this will aide 
- oF script 0.1.0 -> 0.2.0 - fixed subcommands
- update now supports pg/projectgenerator / libs
-  fixed passing values to subscripts when not needed
- added version query for library and pg
- added variable for HOST_URL -u --url - default to github/openframeworks/apothecary 
```
one@One4Sevens-MBP openFrameworksiOSTIPS % ./of help     
Wed  5 Mar 2025 13:15:17 AEDT: [openFrameworks: help]
Usage: ./of <command> [subcommand] [options]
Commands:
update [subcommand]    Update openFrameworks components
libs                 Download openFrameworks libraries (default)
pg | projectgenerator  Download Project Generator
version [subcommand]   Show version information
of                   Show openFrameworks version (default)
pg …
```
=> of script updates

scripts/osx/xcode_project.sh, scripts/templates/osx/Project.xcconfig, scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj
Narrowly scoped just for osx/ template. 
Might be needed for macOS/ template too, but that is not currently being used by PG. 
I believe iOS and tvOS is not needed as they deploy to the device. 
Move the setting to Project.xcconfig with a comment, to give people the option to easily override it if they want. 
Closes #8321
=> Restore target build dir behavior for Xcode. Closes #8321

libs/openFrameworks/video/ofGstUtils.cpp, libs/openFrameworks/video/ofGstUtils.h
2 speed calls within a video frame tends to freeze the video player (confirmed on multiple setups with GST >= 1.20). behavior seems related to changes between GST 1.12 and 1.20. this implements a simple guard that gets reset at the beginning of update().
=> fix(GSTPlayer): prevent multiple speed change requests within a frame

libs/openFrameworks/gl/ofVboMesh.cpp, libs/openFrameworks/gl/ofVboMesh.h
- Fixes changing of verts / colors not reflected in vboMesh in some cases
- Adds remove functions for Vertices and Colours at Indices  - Add removeVertex() - removeColor()
- public -> updateVbo();
Changes apart of Android just splitting each core change as seperate PR. 
I'll keep the Android PR to strictly ofxAndroid and Templates
=> ofVboMesh - Fix Updating Indices / Color

libs/openFrameworks/utils/ofURLFileLoader.cpp
- Windows - fixes if ssl and https called
=> ofURLFileLoader Windows

.github/workflows/nightly.yml, scripts/ci/package_builds.sh, scripts/dev/create_package.sh, scripts/dev/download_libs.sh
Changes to nightly create package 
- Add Android Release - Windows / macOS 
- Linux create package to use built project generator rather than build 
- non verbose on extraction libs from download_libs
- disabled build android examples PG until fixed
- Allowed for nightly failure on one target to not break others.
- export build summary now found on action (click it) with table of success
=> Nightly - Android - Linux

libs/openFrameworks/app/ofAppEGLWindow.cpp
This PR fixes #8374.
Description of the fix:
The function previously returned `str.c_str()`, which pointed to a local std::string that got destroyed upon function exit, leading to a dangling pointer issue.
To fix this, I changed the return type to `std::string`, ensuring that a copy of the string is returned instead of a pointer to temporary memory.
=> Fix for returnDanglingLifeTime

addons/ofxAssimp/src/Source/ofxAssimpSrcBone.cpp, addons/ofxAssimp/src/Source/ofxAssimpSrcScene.cpp, addons/ofxAssimp/src/Source/ofxAssimpSrcScene.h, addons/ofxAssimp/src/ofxAssimpScene.cpp, addons/ofxAssimp/src/ofxAssimpTexture.cpp, addons/ofxAssimp/src/ofxAssimpTexture.h
Material set metalness, roughness and clear coat values. Somewhat related: #8267
Clean up of commented code.
Recalculate scene bounds per request, instead of cache and requiring calling recalculate bounds per mesh.
=> ofxAssimp: Fix for incorrectly over writing textures.

libs/openFrameworks/video/ofAVFoundationGrabber.mm
=> Sort devices by name, ensure FaceTime camera is listed first. 

addons/ofxAssimp/src/ofxAssimpAnimationMixer.cpp, addons/ofxAssimp/src/ofxAssimpAnimationMixer.h, addons/ofxAssimp/src/ofxAssimpNode.cpp, addons/ofxAssimp/src/ofxAssimpScene.cpp, addons/ofxAssimp/src/ofxAssimpScene.h
updating from scene will take effect on changing animation parameters.
Before this PR, the following would have no effect, and calling `setAnimation(0)` to try and update the animation mixer would fail since it was the same index.
```
model.getAnimation(0).setLoopType(OF_LOOP_NORMAL);
model.getAnimation(0).play();
```
Now both the above works in addition to 
```
model.getCurrentAnimation().setLoopType(OF_LOOP_NORMAL);
model.getCurrentAnimation().play();
```
As mentioned in this issue:
https://github.com/openframeworks/openFrameworks/issues/8387
=> ofxAssimp: Convert animation mixer animation clip references to weak_ptrs

libs/openFrameworks/graphics/ofImage.cpp, libs/openFrameworks/utils/ofURLFileLoader.cpp, libs/openFrameworks/utils/ofURLFileLoader.h
- fix missing POST (broken by else statement)
- Fix issue for Async threads  throwing exceptions (and randomly failing to complete directive)
- minor update api of deprecated ```PUT``` changed to ```UPLOAD```
```
C/C++: /home/runner/work/openFrameworks/openFrameworks/libs/openFrameworks/utils/ofURLFileLoader.cpp:341:32: 
warning: 'CURLOPT_PUT' is deprecated: since 7.12.1. Use CURLOPT_UPLOAD [-Wdeprecated-declarations]
C/C++:   341 |                 curl_easy_setopt(curl.get(), CURLOPT_PUT, 0);
C/C++:       |                                              ^
C/C++: /home/runner/work/openFrameworks/openFrameworks/libs/openFrameworksCompiled/project/android/openframeworksAndroid/../../../../../libs/curl/include/curl/curl.h:1294:3: note:
'CURLOPT_PUT' has been explicitly marked deprecated here …
```
=> cURL / OpenSSL core api fixes

libs/openFrameworks/gl/ofCubeMap.cpp, libs/openFrameworks/gl/ofCubeMap.h, libs/openFrameworks/gl/ofCubeMapShaders.h
spelling correction for irradianceCubeMap()
#8395 and #8396
=> ofCubeMap: Android define around regenerateAllTextures()

addons/ofxAssimp/src/Source/ofxAssimpSrcBone.cpp, addons/ofxAssimp/src/Source/ofxAssimpSrcBone.h, addons/ofxAssimp/src/Source/ofxAssimpSrcMesh.cpp, addons/ofxAssimp/src/Source/ofxAssimpSrcMesh.h, addons/ofxAssimp/src/Source/ofxAssimpSrcNode.cpp, addons/ofxAssimp/src/Source/ofxAssimpSrcNode.h, addons/ofxAssimp/src/Source/ofxAssimpSrcScene.cpp, addons/ofxAssimp/src/ofxAssimpNode.cpp, addons/ofxAssimp/src/ofxAssimpScene.cpp
The important change here is getAsString
the base class has a different parameter type of the derived class (int / unsigned int), so it complains about shadowing.
I've changed the parameter types and added override
removed virtual from derived classes
and some small changes to avoid int64 -> int32 implicit conversion warnings
=> ofxAssimp small suggestions

examples/3d/ofxAssimpExample/src/ofApp.cpp, examples/gl/materialPBRAdvancedExample/src/ofApp.cpp, examples/gl/shadowsExample/src/ofApp.cpp, examples/gl/textureBufferInstancedExample/src/ofApp.cpp, libs/openFrameworks/gl/ofCubeMap.cpp, libs/openFrameworks/gl/ofCubeMap.h, libs/openFrameworks/gl/ofMaterial.cpp, libs/openFrameworks/gl/ofShader.cpp, libs/openFrameworks/gl/ofShadow.cpp, libs/openFrameworks/gl/ofShadow.h
ofShadow
Rename isGlCullingEnabled() & setGlCullingEnabled() to isCullingEnabled() && setCullingEnabled(): #8411
ofCubeMap and ofShadow, make private by wrapping in of::priv. 
Added more comments and made a few more functions private to reduce confusion.
#8409
=> Cleanup ofShadow and ofCubemap

libs/openFrameworks/utils/ofURLFileLoader.cpp
So I am a little lazy and decided to use ofURLFileLoader for *basic* REST stuff to a local ollama server instead of bothering with ofxHTTP. It's just a thin wrapper for HTTP and it's built into the core anyway...
I noticed that GETs work fine however trying to POST a body with stringified JSON resulted in a 405 METHOD NOT ALLOWED error. Enabling verbose in the request showed that, in my case, the actual request type being made was a GET even though I set the request method to POST.
I was able to fix this by making sure the libcurl method opts are set *before* dealing with the request body / POST data handling. This broke GET so only setting the POST handling stuff if not doing a GET was the fix. If the request is a GET, the request body should be ignored anyway, I believe. I think libcurl …
=> ofURLFileLoader bugfix for sending POST

libs/openFrameworks/utils/ofURLFileLoader.cpp
=> Enable all supported encoding compressions in curl.

examples/math/randomExample/src/ofApp.cpp, libs/openFrameworks/utils/ofRandomDistributions.h
exponential distribution requires a real value for lambda; enforce it at the OF interface.
=> fix(random_distributions): enforce real for expon lambda

addons/ofxGui/src/ofxBaseGui.cpp
Prevent this error when a new JSON settings is saved:
```
[ error ] ofLoadJson: Error loading json from "/Users/steve/Documents/MarkSynth/settings/synth1/settings-4.json": file doesn't exist
```
I'm also suspicious of L235-237 for the same reason, but there's no error message when loading a non-existent XML so not sure.
=> Don't load non-existent JSON settings file when saving a new file

addons/ofxAssimp/src/Source/ofxAssimpSrcScene.h, addons/ofxAssimp/src/ofxAssimpMesh.cpp, addons/ofxAssimp/src/ofxAssimpMesh.h, addons/ofxAssimp/src/ofxAssimpScene.cpp
Add setting to apply transforms to meshes to address: https://github.com/openframeworks/openFrameworks/issues/8460
=> Load setting for applying mesh transform.

libs/openFrameworks/communication/ofArduino.cpp, libs/openFrameworks/communication/ofArduino.h
This PR fixes a typo in the ofArduino event name:
- Renamed EI2CDataRecieved to the correct spelling EI2CDataReceived.
- Updated log messages to use “received” instead of “recieved”.
- Added a deprecated alias for EI2CDataRecieved to maintain backward compatibility with existing code.
Fixes #6499
=> fix typo in ofArduino
